### ISSUE TITLE
Styling Example

### ISSUE THREAD

**Issue by flywire** [Python-Markdown/markdown#1000]
I'm confused about how to use CSS styling with Admonition. I note Attribute Lists and CodeHilite also rely on CSS styling to be effective, and there are minimal notes with CodeHilite. I think a simple example would be worthwhile.

Specifically, with Admonition, how can I:
1.  Render the HTML to display admonition type (eg note when there is a title)? The default output is fairly meaningless without the admonition type and much less meaningful than the markdown.
1. Use the CSS when [Using Python-Markdown on the Command Line](https://python-markdown.github.io/reference/)?

This CSS from https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/css/base.css is much more complicated than needed for a simple example but it still doesn't render the admonition type.

**stylesheet.css**
```
.admonition {
    padding: 15px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    border-radius: 4px;
    text-align: left;
}

.admonition.note { /* csslint allow: adjoining-classes */
    color: #3a87ad;
    background-color: #d9edf7;
    border-color: #bce8f1;
}

.admonition-title {
    font-weight: bold;
    text-align: left;
}
```

**Comment by waylan** [comment]
In my projects I have simply copied the CSS from a Sphinx theme I liked. In fact, the Python-Markdown documentation uses a MKDocs theme in which all of the CSS/images/JS is from a Sphinx theme. I try to avoid working with CSS as I am not very good at it. And providing CSS is out-of-scope for a Markdown parser.

**Comment by flywire** [comment]
I don't want to write CSS either and the process you explained is a reasonable way of managing it. When [Using Python-Markdown on the Command Line](https://python-markdown.github.io/reference/) how do you get it to use that CSS given the HTML is generated?

---

Admonitions are parsed very differently to other elements. John Gruber’s Markdown implementation parses documents to display in a browser but I suppose the rST-style is to display via another processor. The result is the admonition type is very clear in the markdown but completely hidden in the browser after it is parsed and needs to be processed by something else to be displayed.

I probably should have been implemented with `<admonition-type>` like:
```html
<div class="admonition note">
<p class="admonition-title"><admonition-type>Note: </admonition-type>optional explicit title within double quotes</p>
<p>Any number of other indented markdown elements.</p>
<p>This is the second paragraph.</p>
</div>
```

Admittedly, that still wouldn't separate paragraphs from other blocks like say blockquotes.

**Comment by waylan** [comment]
> When Using Python-Markdown on the Command Line how do you get it to use that CSS given the HTML is generated?

Python-Markdown only every generates a HTML fragment (the part which goes within the `<body>` tag of a fill HTML document. Everything else is the responsibility of the user to provide, including anything in the `<head>` of the document, CSS and/or JavaScript. From the command line, you might pipe the output to a template, write a shell script or something else.

Of course, Python-Markdown is a Python library first. The command line script is only provided as a convenience and not the primary use-case. Either way, if you are looking for a full-featured solution, then I would suggest looking at a static site generator. You previously linked to MkDocs, which is one such tool which happens to use Python-Markdown.

**Comment by facelessuser** [comment]
As @waylan said, you'd have to provide a template containing necessary HTML headers and such. You would inject your HTML fragment into that template.

```py
'''
<html>
<head>
<!-- CSS style tags and such would go here -->
</head>
<body>{}</body>
</html>
'''.format(my_html_fragment)
```

**Comment by flywire** [comment]
@facelessuser that's a nice example that would fit well in https://python-markdown.github.io/extensions/code_hilite/#step-2-add-css-classes with output to really demonstrate how it works.

---

Back to the specific admonition example which I'm struggling with. I have a solution but it's ugly, especially for a dozen admonitions. (It would have been trivial with an admonition type in the admonition title.)

![image](https://user-images.githubusercontent.com/11288701/87294358-fd85ac00-c546-11ea-818c-ebc661d22374.png)

```html
<link rel="stylesheet" href="extra.css">

<p>A normal sentence.</p>

<div class="admonition note">
<p class="admonition-title">this is the title</p>
<p>This is a description.</p>
</div>
<p>A normal sentence.</p>

<div class="admonition tip">
<p class="admonition-title">this is the title</p>
<p>This is a description.</p>
</div>
<p>A normal sentence.</p>
```

**extra.css**

```css
.admonition {
  padding: 10px;
}

.admonition-title::before { 
  font-style: normal;
  font-weight: bold;
}

.admonition-title {
  font-style: italic;
}


.admonition.note {
  background-color: lightblue;
}

.admonition.note .admonition-title::before { 
  content: "Note: ";
}

.admonition.note .admonition-title {
  color: blue;  
}


.admonition.tip {
  background-color: lightgreen;
}

.admonition.tip .admonition-title::before { 
  content: "Tip: ";
}

.admonition.tip .admonition-title {
  color: green;  
}

```

---

Once you have the css files a reference can be generated in Windows like:
- `echo ^<link rel="stylesheet" href="docs/css/styles.css"^> > css.html & echo ^<link rel="stylesheet" href="docs/css/extra.css"^> >> css.html`

And a quick and dirty prepend like:
- `(>nul copy /y css.html index.*) & python -m markdown -x admonition index.md >> index.html`
