### ISSUE TITLE
How to add div before table

### ISSUE THREAD

**Issue by woile** [Python-Markdown/markdown#1002]
Hello! 

I'm trying to create a responsive table, this means the output should look, in a very raw way, like this:

```html
<div>
<table>
    <thead>
        <tr>
            <th colspan="2">The table header</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>The table body</td>
            <td>with two columns</td>
        </tr>
    </tbody>
</table>
</div>
```

Then I could style the div with the responsive attribute:

```css
div {
  overflow-x: auto;
}
```

I've been reading the docs, and I cannot find a way to add that `div` to the table generation. Ideally I'd like to add a div with a class: `<div class="table-responsive">`.
I took a look at the table extension, but it says it doesn't accept any parameters, maybe there's a different way to add extra attributes.

---

I know there's a hacky way in markdown:

```md
<div class="table-responsive">
| Title | Title 2 |
| ----- | --------- |
| A    | B        |
</div>
```

But I'd expect something more elegant to avoid modifying each file containing a table.

---

Can someone help me with this? Or point somewhere? 

Thanks! :smiley:

**Comment by waylan** [comment]
> I know there's a hacky way in markdown

That is not a "hacky way." That is the way. As the rules [explain][1]:

> Markdown is not a replacement for HTML, or even close to it. Its syntax is very small, corresponding only to a very small subset of HTML tags. The idea is not to create a syntax that makes it easier to insert HTML tags. In my opinion, HTML tags are already easy to insert. The idea for Markdown is to make it easy to read, write, and edit prose. HTML is a *publishing* format; Markdown is a *writing* format. Thus, Markdown’s formatting syntax only addresses issues that can be conveyed in plain text.
> 
> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself.

In fact, as tables are not prose, some have argued that we shouldn't even have a table syntax for Markdown, but should require raw HTML for tables. Regardless, the correct way to address this is with raw HTML.

Of course, there is that pesky issue that Markdown is not parsed within raw HTML. However, the [md_in_html][2] extension should address that for you. In the end, you should have:

```text
<div class="table-responsive" markdown="1">

| Title | Title 2 |
| ----- | --------- |
| A    | B        |

</div>
```

[1]: https://daringfireball.net/projects/markdown/syntax#html
[2]: https://python-markdown.github.io/extensions/md_in_html/

**Comment by woile** [comment]
Oh okay, I thought I could customize how it is rendered.

Thanks a lot! :+1: 

It made me wonder how is github actually doing it haha, I don't know why I didn't think of it before, I found that they apply this `css` in case someone has the same issue:

```css
table {
  display: block;
  width: 100%;
  overflow: auto;
}
```
