### ISSUE TITLE
HTML comment in markdown="1" block causes conversion stoppage

### ISSUE THREAD

**Issue by git1sal** [Python-Markdown/markdown#1012]
```python
from markdown import markdown as md

t1 = """<div markdown="1">

***This is markdownized***

<!---foobar-->

***This is not markdownized***

</div>"""

 md(t1,extensions=["extra"])
```

Yields:

```
'<div>\n<p><strong><em>This is markdownized</em></strong></p>\n<!---foobar-->\n\n***This is not markdownized***\n\n</div>'
```

Anything within the `<div>` after the HTML comment is not processed.

Bug, or just unexpected behavior for me?

Relevant fact: PHP Extra does not have this behavior; it does continue processing as markdown after the comment.

**Comment by waylan** [comment]
This will be addressed by #803 which is completely replacing the existing raw HTML parser.
