### ISSUE TITLE
Upgrade PyYAML disutils

### ISSUE THREAD

**Issue by FrancescaDB** [Python-Markdown/markdown#1017]
Dear all,

I am sorry for this question that may be trivial, but I have been struggling a lot to solve it.
 
I am trying to run some code on a cluster with polyaxon. However, I get this error:

**‘PyYAML’. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

I tried:
- conda update PyYAML
- pip install --ignore-installed PyYAML
- pip install --upgrade --force-reinstall pip==9.0.3, then pip install PyYAML --disable-pip-version-check
and finally pip install --upgrade pip

but neither of these approaches solved my problem.

I am working on a MacBookPro. The version of my PyYAML is 5.3.1 and it is stored in /anaconda3/lib/python3.6/site-packages.

Do you have any suggestion?

Thanks a lot!

**Comment by waylan** [comment]
Are you sure `pip`, `PyYAML` and `markdown` are all associated with the same Python install? Running `pip --version` will tell you which Python it is associated with. You have indicated that `PyYAML` is associated with `conda`, but if `markdown` is not, then that won't matter. How are you calling Markdown?

**Comment by waylan** [comment]
Due to the lack of response and inadequate information to assist, I am closing this. It can be reopened if/when the information requested is provided.
