### ISSUE TITLE
[id]: reference type is suppressed

### ISSUE THREAD

**Issue by ljgww** [Python-Markdown/markdown#102]
'[example.com][id]' renders correct html code but

'[id]:' http://example.com "Title" 

is suppressed (ignored, so not rendered to html)

(py 2.6.1 macosx 10.6.8)
even here on github

**Comment by waylan** [comment]
I can't reproduce this. 

``` python
>>> markdown.markdown('[foo][id]\n\n[id]: http://example.com "Title"')
u'<p><a href="http://example.com" title="Title">foo</a></p>'
```

Although I did notice that you have some extra quotes in your example (around the `[id]:`. Remove those and it should work fine. If not, please provide a more specific example? Perhaps the source of the simplest document that fails. For example, the following document works fine. What will make it fail?

```
[foo][id]

[id]: http://example.com "Title"
```

**Comment by ljgww** [comment]
I have put quotes around in order that this system renders it visible (otherwise text gets swallowed as this system obviously uses same markup) 

'[id](http://example.com): http://example.com' <- below this line there is exactly same one without quotes

**Comment by ljgww** [comment]
I have put quotes around in order that this system renders it visible (otherwise text gets swallowed as this system obviously uses same markup) 

`[id]: http://example.com` <- below this line there is exactly same one without quotes

also I noticed here that '[' and ']' gets swallowed too

**Comment by waylan** [comment]
I'm sorry but I don't understand the problem you are reporting. As far as I can tell, everything is working exactly as it should.  If you want to display markdown markup in a markdown document, place it in a code block or code span (like I did above). I suggest providing three code blocks: One with the input text, a second with the actual output and a third with the output you expected. Be sure to use the "preview" option before submitting your comment.

**Comment by ljgww** [comment]
```
import markdown
print markdown.markdown('[foo][id]\n\n[id]: http://example.com "Title"')
```

i get this test correct ... maybe it is some side effect (will test more) its hard to get text correct here as github uses variant of markdown. 

i also got result

```
$ python markdown_test.py 
<p><a href="http://example.com" title="Title">foo</a></p>
```

Try to answer to my message by putting (follwing at the beginning of the line)

```
[foo][id]
[id]: http://example.com "Title"
```

**Comment by waylan** [comment]
I just edited your last comment so that you have proper code blocks. Please note the changes I made for any future reports. It may also help to familiarize yourself with [GitHub's additions](http://github.github.com/github-flavored-markdown/) to the [Markdown syntax](http://daringfireball.net/projects/markdown/syntax).

**Comment by ljgww** [comment]
I think I got it... (it means that [id]: ) never gets rendered visible but it is used to render foo part visible. Need to understand markdown better then.

I expected wikipedia kind of reference eg.[1]

then there is [1] reference ... my bad of not understanding the idea of the reference.

**Comment by waylan** [comment]
Ah, yes, that is the correct behavior. There is no bug here. I am closing this.

**Comment by ljgww** [comment]
thank you!
