### ISSUE TITLE
Block quotes next to each other are rendered in a single `<blockquote>` tag

### ISSUE THREAD

**Issue by surfer190** [Python-Markdown/markdown#1024]
With the following markdown with block quotes one after another:

```
The quotes:

> Somewhere, something incredible is waiting to be known

> Extraordinary claims require extraordinary evidence

have been ascribed to Carl Sagan.
```

The default python markdown renders the quotes in a single blockquote (with mkdocs):

```
<p>The quotes:</p>
<blockquote>
<p>Somewhere, something incredible is waiting to be known</p>
<p>Extraordinary claims require extraordinary evidence</p>
</blockquote>
<p>have been ascribed to Carl Sagan.</p>
```

However [commonmark](https://commonmark.org/help/tutorial/05-blockquotes.html) renders it as seperate blockquotes:

```
<p>The quotes:</p>
<blockquote>
<p>Somewhere, something incredible is waiting to be known</p>
</blockquote>
<blockquote>
<p>Extraordinary claims require extraordinary evidence</p>
</blockquote>
<p>have been ascribed to Carl Sagan.</p>
```
 
For stying reasons I would like to achieve the later. Is this possible?

**Comment by waylan** [comment]
As Babelmark [demonstrates][1], implementations are divided on this with all Commonmark implementations behaving one way and all old-school Markdown implementations behaving the other. We are proud to be in the latter camp. Python-Markdown is **not** a Commonmark implementation. We follow the [original rules][2] and the reference implementation (`markdown.pl`).

As an aside, this is a perfect demonstration of why we are not interested in adopting Commonmark. The original rules clearly indicate what the behavior should be in this case. However, Commonmark still changed the behavior. If all they really were doing was standardizing unclear or inconsistent behavior (like they claim), they would have left this alone. Therefore, Commonmark is not Markdown and will not influence our behavior.

That said, anyone is free to create their own extension which alters the behavior in any way. All known extensions are listed on the [wiki][3]. If you don't see anything there, then you can always [create your own][4].

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=The+quotes%3A%0A%0A%3E+Somewhere%2C+something+incredible+is+waiting+to+be+known%0A%0A%3E+Extraordinary+claims+require+extraordinary+evidence%0A%0Ahave+been+ascribed+to+Carl+Sagan.
[2]: https://daringfireball.net/projects/markdown/syntax#blockquote
[3]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
[4]: https://python-markdown.github.io/extensions/api/

**Comment by Phuker** [comment]
FYI, if you want separated block quotes, add a HTML comment like this:

```python
import markdown

s = '''
> a
>
> b

<!-- Force separate Markdown block quotes -->

> c
'''

print(markdown.markdown(s))
```

Results:

```html
<blockquote>
<p>a</p>
<p>b</p>
</blockquote>
<!-- Force separate Markdown block quotes -->

<blockquote>
<p>c</p>
</blockquote>
```

See: https://meta.stackexchange.com/questions/298962/how-can-i-separate-multiple-quote-blocks

**Comment by everdrone** [comment]
@surfer190 had your same problem, made a quick patch to the original `BlockQuoteProcessor` if you need.

```py
import re

import xml.etree.ElementTree as etree

from markdown import util
from markdown.extensions import Extension
from markdown.blockprocessors import BlockProcessor


class BlockQuoteProcessor(BlockProcessor):
    """
    replaces: https://github.com/Python-Markdown/markdown/blob/f6ca75429562cfa7df333b3529838679e4bfd443/markdown/blockprocessors.py#L277
    """

    RE = re.compile(r'(^|\n)[ ]{0,3}>[ ]?(.*)')

    def test(self, parent, block):
        return bool(self.RE.search(block)
                   ) and not util.nearing_recursion_limit()

    def run(self, parent, blocks):
        block = blocks.pop(0)
        m = self.RE.search(block)
        if m:
            before = block[:m.start()]  # Lines before blockquote
            # Pass lines before blockquote in recursively for parsing first.
            self.parser.parseBlocks(parent, [before])
            # Remove ``> `` from beginning of each line.
            block = '\n'.join(
                [self.clean(line) for line in block[m.start():].split('\n')]
            )
            
        # This is a new blockquote. Create a new parent element.
        quote = etree.SubElement(parent, 'blockquote')
        # Recursively parse block with blockquote as parent.
        # change parser state so blockquotes embedded in lists use p tags
        self.parser.state.set('blockquote')
        self.parser.parseChunk(quote, block)
        self.parser.state.reset()

    def clean(self, line):
        """ Remove ``>`` from beginning of a line. """
        m = self.RE.match(line)
        if line.strip() == '>':
            return ''
        elif m:
            return m.group(2)
        else:
            return line


class BlockQuoteExtension(Extension):
    def extendMarkdown(self, md):
        """Extend the inline and block processor objects."""

        md.parser.blockprocessors.register(
            BlockQuoteProcessor(md.parser), 'quote', 70
        )
        md.registerExtension(self)


def makeExtension(*args, **kwargs):
    """Return extension."""

    return BlockQuoteExtension(*args, **kwargs)
```
