### ISSUE TITLE
Docs deployment error

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#1028]
The github action which deploys a release appears to have a auth problem when deploying the documentation. See the output for the [3.3 release][1]. 

[1]: https://github.com/Python-Markdown/markdown/runs/1216611346?check_suite_focus=true

**Comment by facelessuser** [comment]
I've never used an action for this. I use this: https://github.com/facelessuser/pymdown-extensions/blob/master/.github/workflows/deploy.yml#L30. Seems to work still as I released 10 days ago.

**Comment by waylan** [comment]
I didn't use that because we are using an org setup, where the built site is deployed to the `master` branch of a different repo rather than the `gh-pages` branch of the same repo. I'm assuming the auth issue is related to crossing the two repos. I thought I had done everything correctly, but apparently not. For the record, this was the first test if it all, so it has never worked.

**Comment by waylan** [comment]
When I did this I followed [these instructions][1] and set up the deploy key [as instructed here][2] with the private key saved to this repo (as a `secret` named `PAGES_DEPLOY_KEY`) and the public key saved to the `Python-Markdown/Python-Markdown.github.io` repo (as a `deploy_key`). I'm assuming I messed something up with that.

[1]: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository
[2]: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key

**Comment by waylan** [comment]
Maybe I need to save the `secret` to the organization rather than the repo? That way the other repo would also have access. I'm guessing here.

**Comment by waylan** [comment]
See [Manually running a workflow][1], which could be handy for testing purposes.

> When a workflow is configured to run on the `workflow_dispatch` event, you can run the workflow using the REST API or from the Actions tab on GitHub.

See also [workflow_dispatch][2].

[1]: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
[2]: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch

**Comment by facelessuser** [comment]
Ah, I forgot that you are running in an org.

**Comment by waylan** [comment]
As a reminder to myself, when I released 3.3.1 yesterday, I had done nothing to address this issue and the same error occurred. I expected as much, but didn't want to delay getting that fix out so went forward and manually deployed the docs.

**Comment by waylan** [comment]
This may be resolved with [github-action-push-to-another-repository](https://github.com/cpina/github-action-push-to-another-repository), which has comprehensive [documentation](https://cpina.github.io/push-to-another-repository-docs/index.html) (including all sorts of troubleshooting tips). Also [copy_file_to_another_repo_action](https://github.com/dmnemec/copy_file_to_another_repo_action) is a simpler action. Both are implemented as shell scripts, which could be helpful in developing our own solution around  `mkdocs gh-deploy`. Or we could use one of them directly.

**Comment by waylan** [comment]
Hmm, I just discovered that `Python-Markdown/Python-Markdown.github.io` did not have any deploy keys. Anyway, I just generated a new public/private pair and saved them to the correct locations. We'll see if that resolves it with the next release.

**Comment by waylan** [comment]
Still failing. As seen [here](https://github.com/Python-Markdown/markdown/actions/runs/6711805985/job/18240001281#step:6:47) I'm getting:

```
 Error loading key "/home/runner/.ssh/github": error in libcrypto
 Error: Action failed with "The process '/usr/bin/ssh-add' failed with exit code 1"
```
