### ISSUE TITLE
Tests fail with pygments-2.7.0+

### ISSUE THREAD

**Issue by mgorny** [Python-Markdown/markdown#1030]
Pygments 2.5.2 (as used in tox.ini) are pretty old. After upgrading to 2.7.0 or 2.7.1, I get the following test failures.

I can make a pull request updating the tests if you wish. Please just tell me if you prefer updating them purely for new pygments version, or if I should try to fit some regexps in to support both.

```
======================================================================
FAIL: test_codehilite_linenos_hl_lines (test_syntax.extensions.test_code_hilite.TestCodeHiliteClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 289, in test_codehilite_linenos_hl_lines
    self.assertOutputEquals('line 1\nline 2\nline 3', expected, lang='text', linenos='inline', hl_lines=[1, 3])
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 43, in assertOutputEquals
    self.assertMultiLineEqual(output.strip(), expected)
AssertionError: '<div[58 chars]inenos">1</span><span class="hll">line 1\n</sp[119 chars]div>' != '<div[58 chars]ineno">1 </span><span class="hll">line 1\n</sp[119 chars]div>'
- <div class="codehilite"><pre><span></span><code><span class="linenos">1</span><span class="hll">line 1
?                                                                    -
+ <div class="codehilite"><pre><span></span><code><span class="lineno">1 </span><span class="hll">line 1
?                                                                       +
- </span><span class="linenos">2</span>line 2
?                           -
+ </span><span class="lineno">2 </span>line 2
?                              +
- <span class="linenos">3</span><span class="hll">line 3
?                    -
+ <span class="lineno">3 </span><span class="hll">line 3
?                       +
  </span></code></pre></div>

======================================================================
FAIL: test_codehilite_linenos_inline (test_syntax.extensions.test_code_hilite.TestCodeHiliteClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 216, in test_codehilite_linenos_inline
    self.assertOutputEquals('plain text', expected, lang='text', linenos='inline')
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 43, in assertOutputEquals
    self.assertMultiLineEqual(output.strip(), expected)
AssertionError: '<div[43 chars]><span class="linenos">1</span>plain text\n</code></pre></div>' != '<div[43 chars]><span class="lineno">1 </span>plain text\n</code></pre></div>'
- <div class="codehilite"><pre><span></span><code><span class="linenos">1</span>plain text
?                                                                    -
+ <div class="codehilite"><pre><span></span><code><span class="lineno">1 </span>plain text
?                                                                       +
  </code></pre></div>

======================================================================
FAIL: test_codehilite_linenos_linenospecial (test_syntax.extensions.test_code_hilite.TestCodeHiliteClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 323, in test_codehilite_linenos_linenospecial
    self.assertOutputEquals('line 1\nline 2\nline 3', expected, lang='text', linenos='inline', linenospecial=2)
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 43, in assertOutputEquals
    self.assertMultiLineEqual(output.strip(), expected)
AssertionError: '<div[58 chars]inenos">1</span>line 1\n<span class="linenos s[77 chars]div>' != '<div[58 chars]ineno">1 </span>line 1\n<span class="lineno sp[77 chars]div>'
- <div class="codehilite"><pre><span></span><code><span class="linenos">1</span>line 1
?                                                                    -
+ <div class="codehilite"><pre><span></span><code><span class="lineno">1 </span>line 1
?                                                                       +
- <span class="linenos special">2</span>line 2
?                    -
+ <span class="lineno special">2 </span>line 2
?                               +
- <span class="linenos">3</span>line 3
?                    -
+ <span class="lineno">3 </span>line 3
?                       +
  </code></pre></div>

======================================================================
FAIL: test_codehilite_linenos_linenostep (test_syntax.extensions.test_code_hilite.TestCodeHiliteClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 306, in test_codehilite_linenos_linenostep
    self.assertOutputEquals('line 1\nline 2\nline 3', expected, lang='text', linenos='inline', linenostep=2)
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 43, in assertOutputEquals
    self.assertMultiLineEqual(output.strip(), expected)
AssertionError: '<div[58 chars]inenos"> </span>line 1\n<span class="linenos">[69 chars]div>' != '<div[58 chars]ineno">  </span>line 1\n<span class="lineno">2[69 chars]div>'
- <div class="codehilite"><pre><span></span><code><span class="linenos"> </span>line 1
?                                                                    -
+ <div class="codehilite"><pre><span></span><code><span class="lineno">  </span>line 1
?                                                                      +
- <span class="linenos">2</span>line 2
?                    -
+ <span class="lineno">2 </span>line 2
?                       +
- <span class="linenos"> </span>line 3
?                    -
+ <span class="lineno">  </span>line 3
?                      +
  </code></pre></div>

======================================================================
FAIL: test_codehilite_linenostart (test_syntax.extensions.test_code_hilite.TestCodeHiliteClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 271, in test_codehilite_linenostart
    self.assertOutputEquals('plain text', expected, lang='text', linenos='inline', linenostart=42)
  File "/tmp/markdown/tests/test_syntax/extensions/test_code_hilite.py", line 43, in assertOutputEquals
    self.assertMultiLineEqual(output.strip(), expected)
AssertionError: '<div[44 chars]<span class="linenos">42</span>plain text\n</code></pre></div>' != '<div[44 chars]<span class="lineno">42 </span>plain text\n</code></pre></div>'
- <div class="codehilite"><pre><span></span><code><span class="linenos">42</span>plain text
?                                                                    -
+ <div class="codehilite"><pre><span></span><code><span class="lineno">42 </span>plain text
?                                                                        +
  </code></pre></div>

======================================================================
FAIL: testFencedLanguageAttrNoclasses (test_syntax.extensions.test_fenced_code.TestFencedCode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/markdown/tests/test_syntax/extensions/test_fenced_code.py", line 641, in testFencedLanguageAttrNoclasses
    self.assertMarkdownRenders(
  File "/tmp/markdown/markdown/test_tools.py", line 65, in assertMarkdownRenders
    self.assertMultiLineEqual(output, expected)
AssertionError: '<div[79 chars] 125%; margin: 0;"><span></span><code><span st[83 chars]div>' != '<div[79 chars] 125%"><span></span><code><span style="color: [71 chars]div>'
- <div class="python codehilite" style="background: #f8f8f8"><pre style="line-height: 125%; margin: 0;"><span></span><code><span style="color: #408080; font-style: italic"># Some python code</span>
?                                                                                         ------------
+ <div class="python codehilite" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span><code><span style="color: #408080; font-style: italic"># Some python code</span>
  </code></pre></div>

----------------------------------------------------------------------
Ran 877 tests in 3.770s

FAILED (failures=6, skipped=21)
```

**Comment by waylan** [comment]
Hmm, looks like they simply changed the whitespace around line numbers. Pygments has been making these sorts of small changes to their output for years, which is why we lock in a version. We only need to test against one Pygments version. If you want to update to the most recent version and update the relevant tests, you are welcome to.

**Comment by mgorny** [comment]
@waylan, thanks. Could you tell me if you're planning a new release soonish, or if it's better that I backport the patch for us?

**Comment by waylan** [comment]
We released 3.3 yesterday. No plans are in place for any future work at this point. And this only changes tests which we run in a tox env. Therefore, there is no reason to do a release for this change. I see no reason to backport anything.

As an aside, it occurs to me you may have missed the point of these tests. They are not testing whether Pygments returns the correct HTML, but rather they test the following:

1. That we don't raise any errors when calling Pygments' APIs.
2. That whatever HTML returned by Pygments is properly inserted into Markdown's output.

However, we don't really care what is between the wrapping `<div>` tags. Testing that is the responsibility of the Pygments project.  It just happens to be easier to include the content in the test and then lock Pygments to a specific version than to leave the content out of the test. In an ideal world our expected output might look like this:

```
<p>Some Markdown content</p>
<div class='codehilite'>
...
</div>
<p>More Markdown content</p>
```

And then the assertion method would just ignore whatever is located between the opening and closing `div` tags. Presumably, for that to work, we would need to create a new assertion method which would handle `...` specially. It's just not a high priority for me as I never run the tests outside of the tox env where the pygments version is locked.

**Comment by mgorny** [comment]
Well, it is a high priority for us since we want to test the package before installing it. I suppose I could skip these tests but I'd really prefer not to lose the opportunity of verifying it. If you indeed wish to ignore `...`, I'm all for it. I could do it via `assertRegex` but it sucks a little bit as it doesn't show nice diff of everything else if test fails.

**Comment by waylan** [comment]
> If you indeed wish to ignore `...`, I'm all for it. I could do it via `assertRegex` but it sucks a little bit as it doesn't show nice diff of everything else if test fails.

That is why we haven't done it yet. Presumably we could borrow some ideas from [doctest.ELLIPSIS][1]. Although, even that includes some warnings about being imprecise. As per this [comment][2], doctest does output "fancy diffs" for ellipses containing test cases, but their usefulness is questionable. Now if someone wanted to implement the `_ellipsis_match()` function proposed there, then that would be useful.

Another option might be to use an HTML aware diffing lib (such as [htmltreediff][3] or [htmldiff][4]). If there is a way to tell it to ignore everything within `div.codehilite`, that would be extremely useful. I haven't looked to closely at the libs and don't know if that is even possible. As I understand it, [lxml.html.diff][5] only diffs the text content, not the HTML tags, so it's not useful here.

[1]: https://docs.python.org/3.8/library/doctest.html#doctest.ELLIPSIS
[2]: https://github.com/python/cpython/blob/3.8/Lib/doctest.py#L1652-L1658
[3]: https://github.com/christian-oudard/htmltreediff
[4]: https://github.com/mitsuhiko/htmldiff
[5]: http://lxml.de/lxmlhtml.html#html-diff

**Comment by waylan** [comment]
> Well, it is a high priority for us since we want to test the package before installing it.

So you have a version of Pygments installed which doesn't match the version used in the tox env and the tests fail when you run them in your own env. Now we update to the new Pygments version. Later Pygments releases a new version and you update, but Markdown doesn't. Now the problem exists all over again. That's not a problem I am interested in dealing with. 

Actually, after looking at 10058fae (where we added the tox env)  I am reminded that this change only became effective with the new release yesterday. In previous releases, the tests all assumed Pygments was not installed. I have to wonder if having Pygments installed would have resulted in some tests failing. In other words, we have never guaranteed that all tests will pass in any env where Pygments is installed--that is until version 3.3, but then only within the tox env.

I see three possible solutions:

1. Do nothing. You would need to run the tests in an env where the Pygments version matches what the tests expect.
2. We could include a version check when determining if Pygments is installed and skip the relevant tests if there is a version mismatch.
3. Create a solution which avoids the tests from failing due to differences in Pygments output as discussed above (by adding support for an ellipsis).

While option 3 is probably the most desirable, option 2 seems like a reasonable compromise until someone can find the time to do the work to implement option 3.

**Comment by mgorny** [comment]
I would actually prefer 1 over 2. Failed tests are less of a concern than stuff broken in production. Not saying the latter is likely to happen but tests are the best way to check early. Plus, it gives the incentive to update them from time to time.

**Comment by waylan** [comment]
FYI, version 3.3.1 was released yesterday,

**Comment by mgorny** [comment]
I've just learned of https://github.com/asottile/re-assert project that might be close to what we want — that is, apparently it reports where regex failed to match.
