### ISSUE TITLE
Inline elements getting parsed as text when doubly nested

### ISSUE THREAD

**Issue by greenape** [Python-Markdown/markdown#1045]
```python
import markdown
md = markdown.Markdown(extensions=["markdown.extensions.md_in_html"])
test = """
<div markdown="1">
<div>
<img src="" />
<code>Test</code>
<p>Test 2</p>
</div>
</div>
"""
md.convert(test)
```

Which gives:
```'<div>\n<div>\n&lt;img src="" /&gt;\n&lt;code&gt;Test&lt;/code&gt;\n<p>Test 2</p>\n</div>\n</div>'```

When I'd expect to get ```'<div>\n<div>\n<img src="" />\n<code>Test</code>\n<p>Test 2</p>\n</div>\n</div>'```.

Happens with 3.3, 3.3.1.

**Comment by facelessuser** [comment]
Hmm, it seems the new HTML parser is escaping inline tags for some reason.

**Comment by facelessuser** [comment]
Seems like `md_in_html` subclasses from the new HTML parser, but overrides start tag handling. What it forgets to do is flag whether the content is "raw HTML" as that logic is in the overridden base element's start tag logic.

Doing a quick and dirty patch to add this flagging of "raw HTML" logic to `md_in_html`, we get the expected results:

```
<div markdown="1">
<div>
<img src=""/>
<code>Test</code>
<p>Test 2</p>
</div>
</div>
```

Now, I haven't done much testing on this, but I think I should be able to get this fix in with a couple of other HTML related parse issues.

**Comment by facelessuser** [comment]
The cause isn't quite right, but there is some inline handling logic missing. I'll spend some time narrowing it down.

**Comment by facelessuser** [comment]
This case has a solution in https://github.com/Python-Markdown/markdown/pull/1044.
