### ISSUE TITLE
HTML error with video elements (after version 3.2.2)

### ISSUE THREAD

**Issue by jorgesumle** [Python-Markdown/markdown#1047]
I was using version 3.2.2, but after the upgrade I get HTML validation errors with video elements:
```
'"file:/var/www/html/deponejo/Freak-Spot/output/locutus-de-gnu/index.html":321.4-321.120: error: Unclosed element "video".', '"file:/var/www/html/deponejo/Freak-Spot/output/locutus-de-gnu/index.html":325.45-325.48: error: No "p" element in scope but a "p" end tag seen.', '"file:/var/www/html/deponejo/Freak-Spot/output/locutus-de-gnu/index.html":326.1-326.8: error: Stray end tag "video".'
```

## Input

```
<video controls poster="https://freakspot.net/wp-content/uploads/2017/01/Bildschirmfoto-vom-2017-02-01-00-58-04.png">
  <source src="https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12965/A0001-4030.medium.webm" type="video/webm">
  <p>Lo siento, tu navegador no soporta HTML 5. Por
  favor, cambia o actualiza tu navegador</p>
</video>
```

## Output

```
<p><video controls poster="https://freakspot.net/wp-content/uploads/2017/01/Bildschirmfoto-vom-2017-02-01-00-58-04.png">
  <source src="https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12965/A0001-4030.medium.webm" type="video/webm">
<br>
<p>Lo siento, tu navegador no soporta HTML 5. Por
  favor, cambia o actualiza tu navegador</p></p>
</video>
```

**Comment by facelessuser** [comment]
I imagine this may be an issue caused by the fact that it is treated as an inline element but you are embedding block elements within it.

**Comment by waylan** [comment]
I'm not able to replicate this behavior.

```python
>>> import markdown
>>> markdown.version
'3.3.2'
>>> t = """
... <video controls poster="https://freakspot.net/wp-content/uploads/2017/01/Bildschirmfoto-vom-2017-02-01-00-58-04.png">
...   <source src="https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12965/A0001-4030.medium.webm" type="video/webm">
...   <p>Lo siento, tu navegador no soporta HTML 5. Por
...   favor, cambia o actualiza tu navegador</p>
... </video>
... """
>>> print(markdown.markdown(t))
<video controls poster="https://freakspot.net/wp-content/uploads/2017/01/Bildschirmfoto-vom-2017-02-01-00-58-04.png">
  <source src="https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12965/A0001-4030.medium.webm" type="video/webm">
  <p>Lo siento, tu navegador no soporta HTML 5. Por
  favor, cambia o actualiza tu navegador</p>
</video>
```

**Comment by waylan** [comment]
Oh, it requires the `md_in_html` extension, which wasn't mentioned:

``` python
>>> print(markdown.markdown(t, extensions=['md_in_html']))
<p><video controls poster="https://freakspot.net/wp-content/uploads/2017/01/Bildschirmfoto-vom-2017-02-01-00-58-04.png">
  <source src="https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12965/A0001-4030.medium.webm" type="video/webm">
<br />
<p>Lo siento, tu navegador no soporta HTML 5. Por
  favor, cambia o actualiza tu navegador</p></p>
</video>
```

By the way, I just noticed that some block level elements in the core are not included in the extension. Presumably we simply need to expand the list to ensure nothing is missing. Unfortunately, we can't just reuse the list in the core as we need them broken up into subcategories. Regardless, that should be an easy fix.

**Comment by facelessuser** [comment]
Is there a problem with block tags? As far as I'm aware, video are inline in the HTML spec.

**Comment by facelessuser** [comment]
I guess, at the very least, the inconsistent handling between `md_in_html` and normal parsing is a bug.

**Comment by waylan** [comment]
Comparing the tags listed in `markdown.util.BLOCK_LEVEL_ELEMENTS` with `markdown.extensions.md_in_html.block_level_tags` we have the following differences:

```
   'address',    
+  'address',    
   'article',    
   'aside',      
   'blockquote', 
+  'body',       
   'canvas',     
+  'colgroup',   
   'dd',         
   'details',    
   'div',        
   'dl',         
   'dt',         
   'fieldset',   
   'figcaption', 
   'figure',     
   'footer',     
   'form',       
-  'group',      
   'h1',         
   'h2',         
   'h3',         
   'h4',         
   'h5',         
   'h6',         
   'header',     
   'hr',         
   'iframe',     
+  'legend',     
   'li',         
   'main',       
+  'map',        
   'math',       
   'menu',       
   'nav',        
   'noscript',   
+  'object',     
   'ol',         
-  'output',     
+  'option',     
   'p',          
   'pre',        
-  'progress',   
   'script',     
   'section',    
   'style',      
   'table',      
   'tbody',      
   'td',         
+  'textarea',   
+  'tfoot',      
   'th',         
   'thead',      
   'tr',         
   'ul',         
-  'video'
```

1. The `address` tag is included twice in `md_in_html`; once in `span_tags` and once in `block_tags`. Opps. But which one should it be?
2. The following tags are missing completely from `md_in_html`: `'group', 'output', 'video'`. They need to be added, but where?
3. The following tags are listed in `md_in_html` but not in the core: `'body', 'colgroup', 'legend', 'map', 'object', 'option', 'testarea', 'tfoot'`. Should they be added to the core? Perhaps some of them should be removed from `md_in_html`?

**Comment by facelessuser** [comment]
@waylan, I'm confused, as a plugin can add new items to the block tag list, shouldn't this list be shared?

**Comment by facelessuser** [comment]
Personally, I'd have the `md_in_html` parser just use the common one via something like `self.md.block_level_tags`.

**Comment by facelessuser** [comment]
Oh, there are 3 lists of block level tags now. One in `util`, one in `core`, and one in `md_in_html`. I would use the one in `core` as it has been available for some time for people to use to adjust block level tags.

EDIT: corrected, I would use the one in `core`.

**Comment by waylan** [comment]
> @waylan, I'm confused, as a plugin can add new items to the block tag list, shouldn't this list be shared?

Normally, yes. However, `block_level_tags` is defined as `span_tags + block_tags + raw_tags`. The extension needs the tags to be defined in those three groups to work correctly.

https://github.com/Python-Markdown/markdown/blob/2766698ac88ae9218d41b3ca1d9fbd4b4bd105e5/markdown/extensions/md_in_html.py#L26-L39

For a full explanation of why that matters, the see the [documentation][1] for the differences between `markdown="1"`, `markdown="block"` and `markdown="span"`.

[1]: https://python-markdown.github.io/extensions/md_in_html/#syntax

**Comment by facelessuser** [comment]
Then where does the `core` list fit into things?

**Comment by facelessuser** [comment]
https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L75-L85

I'd hate to lose the ability to adjust this list.

**Comment by waylan** [comment]
The extension completely ignores the core's list. 

I suppose `block_level_tags` could be a copy of the list from core. `span_tags` and `raw_tags` could still be defined in the extension, and then `block_tags` could be generated as a list of all tags which are in `block_level_tags` but not in `span_tags` or `raw_tags`.

Oh and thanks for reminding me we moved the list to the core and deprecated the one in `util`. I forgot about that.

**Comment by facelessuser** [comment]
Is `span_tags` really necessary? If it isn't in `raw_tags` or `block_tags`, I would assume it is a `span_tags`. Does `md_in_html` have to ensure every tag is in the predefined list of all elements? I would think just ensuring we handle `block_tags` and `raw_tags` different would be enough. If `tag not in block_tags + raw_tags` you could treat it as a span.

**Comment by waylan** [comment]
Yes, `span_tags` is necessary. It does not designate the tags as "span-level". Rather, it designates them as "block-level" tags which only get `span` parsing of their contents (they can't contain other "block-level" content). See the documentation. And note that this behavior is not new. It existed in the old implementation and it was what made the old extension impossible to debug.

**Comment by facelessuser** [comment]
Cool, then yeah, I think we could join this with the `core` list.

**Comment by waylan** [comment]
Btw, I just confirmed that adding `video` to the list in the extension solves the reported bug. I could do a quick patch for that, but I suppose we should just do it correctly.

**Comment by facelessuser** [comment]
If I get a chance, I can maybe look into a pull this evening, that is if someone doesn't get to it first.
