### ISSUE TITLE
Some elements turning into None in html output with md_in_html

### ISSUE THREAD

**Issue by greenape** [Python-Markdown/markdown#1049]
```python
import markdown
md = markdown.Markdown(extensions=["markdown.extensions.md_in_html"])
test = """
<div class="output_area" markdown="1">
<table>
<thead><tr>
<th style="text-align:right"></th>
<th style="text-align:right">time</th>
<th style="text-align:right">amplitude</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right">0</td>
<td style="text-align:right">0</td>
<td style="text-align:right">0</td>
</tr>
</tbody>
</table>
</div>
"""
print(md.convert(test))
```

Which gives me -

```html
<div class="output_area">
<table>
<thead>None<tr>
<th style="text-align:right">None</th>
<th style="text-align:right">time</th>
<th style="text-align:right">amplitude</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right">0</td>
<td style="text-align:right">0</td>
<td style="text-align:right">0</td>
</tr>
</tbody>
</table>
</div>
```

Rather than

```html
<div class="output_area">
<table>
<thead><tr>
<th style="text-align:right"></th>
<th style="text-align:right">time</th>
<th style="text-align:right">amplitude</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right">0</td>
<td style="text-align:right">0</td>
<td style="text-align:right">0</td>
</tr>
</tbody>
</table>
</div>
```

Which is what I'm expecting - note the extra `None` before the `<tr>` in `<thead>` and in the first header.

**Comment by facelessuser** [comment]
Yup, looks like another bug in the new HTML parser, unfortunately. Looks like we need a `None` check somewhere before inserting some text content.

**Comment by facelessuser** [comment]
I think I may have a fix.

**Comment by waylan** [comment]
Here is a simpler case:

```
<div markdown="1">
<div></div>
</div>
```

Note that the text content of the second `<div>` is empty. Presumably, `Element.text` is `None` rather than an empty string as it should be. We should probably just address this in the serializer to avoid `None` in any output.

**Comment by waylan** [comment]
@facelessuser if you have a fix, go for it. Although we should probably do something with the serializer as well.

**Comment by facelessuser** [comment]
@waylan I'm not sure what you mean in regards to the serializer.

**Comment by facelessuser** [comment]
I've created pull #1050. We can discuss additional changes there if more than what I'm doing needs to be addressed.

**Comment by waylan** [comment]
> @waylan I'm not sure what you mean in regards to the serializer.

My thinking was that there could be any number of other situations in which the `text` of an `Element` is `None`. We should never render that as `None`. However, I have since looked at the serializer and see that every call to `write(text)` is nested within a `if text` check, so the serializer already accounts for this.

It would seem that the issue is isolated to parsing the content of an Element as Markdown, which your fix addresses. So nevermind.
