### ISSUE TITLE
webpage is not available with www.

### ISSUE THREAD

**Issue by sullerandras** [Python-Markdown/markdown#106]
I copied [this](http://www.freewisdom.org/projects/python-markdown/) url from the source code, but it is not working, it says:

Not Found

The requested URL /projects/python-markdown/ was not found on this server.

It is working fine [without www](http://freewisdom.org/projects/python-markdown/). Either please update the links in the source, or make it work with www as well.

**Comment by waylan** [comment]
I thought I changed the links in the source. Perhaps I missed some or are you not using the most recent code here on Github? The links should all point to http://packages.python.org/Markdown/. Please point out any I may have missed.

**Comment by yuri** [comment]
I fixed the issue on freewisdom.org. However, Waylan, if you want to host the website on python.org, I can replace the current site with a link to the new site.

**Comment by sullerandras** [comment]
I downloaded 2.1.1 from [here](http://pypi.python.org/pypi/Markdown), and saw the links with www inside that tarball.
Would you upload the new version to pypi? 2.1.1 is quite old as I see.

**Comment by waylan** [comment]
@yuri that seems like the sensible thing to do. It is much easier keeping the code and docs in sync when they are maintained together. Since the python.org docs are generated from the docs in the repo (and actually use our implementation), updating the wiki has become a nuisance.

**Comment by yuri** [comment]
Ok, I'll put this on my todo list.
