### ISSUE TITLE
 Proper way to test python code in docstrings?

### ISSUE THREAD

**Issue by arogozhnikov** [Python-Markdown/markdown#1060]
I use python built-in `doctest` module, which works with the following format
```python
>>> 1 + 2
3
```

To make this work with mkdocs, I need to coonvert this example into

````
```python
>>> 1 + 2
3

```
````

note that besides triple quotes I need to add an empty line.

**Comment by waylan** [comment]
So long as the `fenced_code` extension is enabled, I don't see any problems here, with or without the blank line. 

```` python
>>> import markdown
>>> src = '''
... ```python
... >>> 1  + 2
... 3
... ```
... '''
>>> print(markdown.markdown(src, extensions=['fenced_code']))
<pre><code class="language-python">&gt;&gt;&gt; 1  + 2
3
</code></pre>
````

Could you please provide the HTML you are getting and the HTML you are expecting?

**Comment by arogozhnikov** [comment]
Here is an example:

mod.py
````python
def f():
       '''
       This is a test function. In python you use doctests to test fragments of code in strings.
       This example works and checked:
       >>> 1 + 2
       3
   

       We use mkdocs to generate documentation (so we use fences for code). Maybe that's not the right way,
       but I didn't find a better way
   
       We will also use doctests to test code in the documentation. 
       All examples below fails because ``` is considered a part of output
   
       ```python
       >>> 1 + 2
       ```
   
       ```python
       >>> 1 + 2
       3
       ```
   
       ```python
       >>> x = "this code outputs nothing, just an example"
       ```
   
       '''
       pass
````

test.py
````python
import doctest

import mod
doctest.testmod(mod)
````

After `python test.py` you will see
```
python test.py
**********************************************************************
File "/Users/axelr/Downloads/example_doctest/mod.py", line 16, in mod.f
Failed example:
    1 + 2
Expected:
    ```
Got:
    3
**********************************************************************
File "/Users/axelr/Downloads/example_doctest/mod.py", line 20, in mod.f
Failed example:
    1 + 2
Expected:
    3
    ```
Got:
    3
**********************************************************************
File "/Users/axelr/Downloads/example_doctest/mod.py", line 25, in mod.f
Failed example:
    x = "this code outputs nothing, just an example"
Expected:
    ```
Got nothing
**********************************************************************
1 items had failures:
   3 of   4 in mod.f
***Test Failed*** 3 failures.
```


While rendering is correct, I don't see a way to use it (as a part of mkdocs) with testing. Ideas?

**Comment by waylan** [comment]
I'm sorry, but I thought you were reporting a rendering error by Markdown. Testing your own code is out-of-scope for discussion here. I would suggest asking on a general purpose forum.
