### ISSUE TITLE
Header wrapping

### ISSUE THREAD

**Issue by georgthegreat** [Python-Markdown/markdown#1063]
At the time, the following markup:

```
# OPERA
BELLISSIMA
```

Renders into `<h1>OPERA</h1>` followed by `<p>BELLISSIMA</p>`. It does not look to be possible to wrap headers in any way.

I am using markdown as a book transcription format, hence I would like to make line wrap match the original book being transcribed (in order to simplify proofreading), yet I would like to render all the text without any additional wrapping — just as with the normal paragraphs.

Is it possible to achieve these using python-markdown?

**Comment by georgthegreat** [comment]
I did a brief research on the subject — it looks like there is no implementation which supports word wrapping in headers.

As [original John Gruber's description](https://daringfireball.net/projects/markdown/syntax) does not say anything, this seems like a bug: as there is no blank line before the next line, it should not be considered as a new paragraph.

**Comment by waylan** [comment]
You are correct that the original rules do not specifically state that headers cannot wrap. However, that is how the reference implementation behaves. And when the rules aren't clear, the behavior of the reference implementation controls.

Additionally, as this has been consistent behavior for many years now, there are many thousands of documents which do not have blank lines between headers and the content that follows them. Makes such a change would break all of those documents.

For the above reasons we will not be making any such change. Of course, you are welcome to alter the behavior in an extension if you want.

**Comment by georgthegreat** [comment]
Can this be done via configuration option of the Markdown class (at the time Markdown parser itself does not seem to be configurable — only extension do).

Of course I could copy-paste HashHeaderParser and alter it, but this does not seem the right thing to do.

**Comment by waylan** [comment]
This would need to be done via an extension which provides a new `BlockProcessor` which replaces the `HashHeaderProcessor`.

**Comment by mitya57** [comment]
You can also always insert raw `<br>` into your header:
```python
>>> markdown.markdown('## OPERA<br>BELLISSIMA')
'<h2>OPERA<br>BELLISSIMA</h2>'
```

**Comment by georgthegreat** [comment]
> You can also always insert raw `<br>` into your header:
> 
> ```python
> >>> markdown.markdown('## OPERA<br>BELLISSIMA')
> '<h2>OPERA<br>BELLISSIMA</h2>'
> ```

This solves the reversed problem: I want the source to have the same layout at the original book.

I. e. compare the layout of this transcription:
https://raw.githubusercontent.com/hda-technical/dancebooks/master/transcriptions/%5B1589%2C%20it%5D%20Prospero%20Lutij%20-%20Opera%20bellissima.md

with the layout of the original book:
https://gallica.bnf.fr/ark:/12148/bpt6k3215756/f9.item

**Comment by mitya57** [comment]
Ah, sorry. I think raw HTML may still help you, though?

```python
>>> print(markdown.markdown('<h2>OPERA\nBELLISSIMA</h2>'))
<h2>OPERA
BELLISSIMA</h2>
```

**Comment by waylan** [comment]
I will point you to [this part][1] of the rules (emphasis in original):

> The idea for Markdown is to make it easy to read, write, and edit prose. HTML is a *publishing* format; Markdown is a *writing* format. Thus, Markdown’s formatting syntax only addresses issues that can be conveyed in plain text.

What you are trying to do is more of a *publishing* thing that a *writing* thing in that you are concerned with the layout of the text. That is not something Markdown is very good at. However, as the next sentence states:

> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself.

Therefore, @mitya57's suggestions are probably the best way to address your needs. Use raw HTML to get the rendered document to display as you desire.

If, on the other hand, you are attempting to get the Markdown text itself to match a specific layout, then I expect you will constantly be running into limitations of the syntax. That is not Markdown's goal or purpose.

[1]: https://daringfireball.net/projects/markdown/syntax#html

**Comment by georgthegreat** [comment]
Again, you are confusing the input with the output.

I want input (that is raw text, typed in somewhat flavoured Markdown) to look like the source book. Therefor raw HTML is completely undesired.

The rendered text must not look as the original, but rather should be convenient for reading.

I got your point already and copy-pasted hash header processor in [868e5e9957b0b0fca4b9e027d16a1a90ffecfcc4](https://github.com/hda-technical/dancebooks/commit/868e5e9957b0b0fca4b9e027d16a1a90ffecfcc4).

It is just strange fact while extensions are configurable, the core itself is not.
