### ISSUE TITLE
Does python-markdown support inline code highlighting?

### ISSUE THREAD

**Issue by champignoom** [Python-Markdown/markdown#1064]
Hi,

Can one write something like `` `code`{.ruby}`` to highlight inline code?

See https://stackoverflow.com/questions/23226224/inline-code-syntax-highlighting-in-github-markdown

**Comment by facelessuser** [comment]
If you are using a JavaScript highlighter, it is possible you could just add a class. I imagine you may additionally need a custom loader to target inline code, but it is probably possible.

There is also: https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/.

**Comment by champignoom** [comment]
Thanks, that's what I was searching for.

Nice work btw
