### ISSUE TITLE
Multiline comments adds code-block.

### ISSUE THREAD

**Issue by blue-hexagon** [Python-Markdown/markdown#1076]
**Triple quotes (multiline comment) in Python adds a \<pre\>\<code\>\</code\>\</pre\> wrapping to the content in Markdown 3.3.3**

```
markdown.markdown(
'''# Heading One
## Subheading One
- List item 1
- List item 2
- List item 3

## Subheading Two
Text''')
```

Results in:
```<h1>Heading One</h1>
<pre><code> ## Subheading One - List item 1 - List item 2 - List item 3 ## Subheading Two Text </code></pre>
```

**Comment by waylan** [comment]
I'm not seeing that behavior.

```python
>>> markdown.markdown(
... '''# Heading One
... ## Subheading One
... - List item 1
... - List item 2
... - List item 3
...
... ## Subheading Two
... Text''')
'<h1>Heading One</h1>\n<h2>Subheading One</h2>\n<ul>\n<li>List item 1</li>\n<li>List item 2</li>\n<li>List item 3</li>\n</ul>\n<h2>Subheading Two</h2>\n<p>Text</p>'
>>>
```

However, if your code is nested in a indented section of your python code, then this is normal Python behavior. For example like this:

```python
def myfunc():
    return markdown.markdown(
    '''# Heading One
    ## Subheading One
    - List item 1
    - List item 2
    - List item 3

    ## Subheading Two
    Text''')
```

Notice that every line except the first one includes one level of indent. Python retains that indent, which is then passed on to Markdown. And, of course, Markdown correctly wraps the indented content in a code block. If you don't want that indent to result in in a code block, you need to not include it in your string that you pass to Markdown.

Fortunately, Python provides the [textwrap.dedent][1] function for this very purpose. Use it like this:

```python
from text wrap import dedent
src = dedent('''
    # Heading One
    ## Subheading One
    - List item 1
    - List item 2
    - List item 3

    ## Subheading Two
    Text
''')
markdown.markdown(src)
```

[1]: https://docs.python.org/3.8/library/textwrap.html#textwrap.dedent

**Comment by blue-hexagon** [comment]
Thank you for the through clarification.
