### ISSUE TITLE
Internal link. 

### ISSUE THREAD

**Issue by dpawson** [Python-Markdown/markdown#1077]
https://daringfireball.net/projects/markdown/syntax#link shows internal links as

[hot text][marker]  

then

[marker]:   

This seems not to work? the hot text shows as a link to the document, the marker shows up as per source.

Is this a bug please?

**Comment by waylan** [comment]
If you don't include a URL with the reference, [as seen here][1], then it is not recognized as a reference.

However, if you include the URL, it [works fine][2].

```
[hot text][marker]

[marker]: http://example.com
```

If you are experiencing different behavior, then please provide a specific example as well as which version of Python-Markdown you are using and any extensions which you may be using.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bhot+text%5D%5Bmarker%5D%0A%0A%5Bmarker%5D%3A
[2]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bhot+text%5D%5Bmarker%5D%0A%0A%5Bmarker%5D%3A+http%3A%2F%2Fexample.com

**Comment by dpawson** [comment]
On Mon, 30 Nov 2020 at 23:50, Waylan Limberg <notifications@github.com>
wrote:

> If you don't include a URL with the reference, as seen here
> <https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bhot+text%5D%5Bmarker%5D%0A%0A%5Bmarker%5D%3A>,
> then it is not recognized as a reference.
>
> However, if you include the URL, it works fine
> <https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bhot+text%5D%5Bmarker%5D%0A%0A%5Bmarker%5D%3A+http%3A%2F%2Fexample.com>
> .
>
> [hot text][marker]
>
> [marker]: http://example.com
>
> If you are experiencing different behavior, then please provide a specific
> example as well as which version of Python-Markdown you are using and any
> extensions which you may be using.
>
>
> An internal link was my use case

[hot text][marker]

[marker]:  non link text.

From your response I assume it's only viable for 'indirect' links.

Apologies, I'll  insert html.

regards



-- 
Dave Pawson
XSLT XSL-FO FAQ.
Docbook FAQ.

**Comment by waylan** [comment]
```
[marker]:  non link text.
```

Yes, that is not a valid link reference and it not recognized as one, which is the correct behavior. The best approach is to use raw HTML.
