### ISSUE TITLE
Don't put <p> around summary tag inside details with markdown flag set?

### ISSUE THREAD

**Issue by fiendish** [Python-Markdown/markdown#1079]
The summary tag is a special tag inside details that I think should be ignored when processing internal markdown.

```Python
from markdown import markdown
from pprint import pprint

a = """
<details markdown="1">
<summary><b>Click to expand table</b></summary>

| Entity                              |   Count |
|:------------------------------------|--------:|
| Thing 1                      |      16 |
| Thing 2                      |       9 |

</details>
"""

pprint(markdown(a, extensions=["extra"]))
```

```html
' <details>\n'
 '<p><summary><b>Click to expand table</b></summary></p>\n'
 '<table>\n'
 '<thead>\n'
 '<tr>\n'
 '<th align="left">Entity</th>\n'
 '<th align="right">Count</th>\n'
 '</tr>\n'
 '</thead>\n'
 '<tbody>\n'
 '<tr>\n'
 '<td align="left">Thing 1</td>\n'
 '<td align="right">16</td>\n'
 '</tr>\n'
 '<tr>\n'
 '<td align="left">Thing 2</td>\n'
 '<td align="right">9</td>\n'
 '</tr>\n'
 '</tbody>\n'
 '</table>\n'
 '</details>'
```

Note here that there are `<p></p>` around the summary, but IMO there should not be.

**Comment by waylan** [comment]
Can you point to support for this in the HTML5 spec?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fiendish** [comment]
I don't understand the request. Support for what, the summary tag? 
See: https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element
Also: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

> A \<summary\> element may only be used as the first child of a \<details\> element.

**Comment by facelessuser** [comment]
`summary` is being treated as inline from what I can tell. You can modify the elements treated as block in a plugin though, or you can modify the block elements of the `Markdown` instance directly: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L75. Now, could we treat `summary` as a block element by default? That is up to @waylan, but this can be worked around.

Alternatively, you could consider using a plugin for details: https://facelessuser.github.io/pymdown-extensions/extensions/details/.

**Comment by waylan** [comment]
Looking at the spec it seems that the `summary` tag is only valid as the first child of a `detail` tag and can only contain elements which a `p` tag can contain. Any other use would be invalid. Therefore...

1. We don't need to consider uses outside of `detail`. If a document author uses it in that way that is on them. In other words we don't need to be concerned with using a different parsing behavior outside of the very limited valid use-case.
2. Wrapping it in `p` would cause it to not be the first child of `detail` and therefore it would always be invalid to wrap it in a `p` tag.
3. As it can not contain any block level elements, we should only parse its content as span-level content.

Given the above, yes, `summary` should be added to the [default list of block-level elements][0]. It should also be added to the list of [span_tags][1] of the `md_in_html` extension to control the default behavior when it is given a `markdown="1"` attribute.

[0]: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L75
[1]: https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/md_in_html.py#L34-L37
