### ISSUE TITLE
Python Version Error on importing markdown module for Apache-Flask Application

### ISSUE THREAD

**Issue by denizdxyz** [Python-Markdown/markdown#1081]
Hello all,

I am trying to deploy my flask based web app on Apache server but on importing markdown module, I am getting the following error even though I am using Python version 3.7 (I also tried version 3.8 and 3.9):

My pip version is : 20.2.4

I also tried uninstalling and reinstalling eveything on my conda environment but the problem didn't get resolved. 

It runs perfectly on my localhost but when I try to run on Apache server I am getting the following error:

```
[Tue Dec 01 02:52:35.801307 2020] [wsgi:error] [pid 53137:tid 140083771930368] [remote 127.0.0.1:39018]     import markdown
[Tue Dec 01 02:52:35.801317 2020] [wsgi:error] [pid 53137:tid 140083771930368] [remote 127.0.0.1:39018]   File "/home/deniz/miniconda3/envs/flask_env/lib/python3.7/site-packages/markdown/__init__.py", line 27, in <module>
[Tue Dec 01 02:52:35.801355 2020] [wsgi:error] [pid 53137:tid 140083771930368] [remote 127.0.0.1:39018]     raise ImportError('A recent version of Python 3 is required.')
[Tue Dec 01 02:52:35.801373 2020] [wsgi:error] [pid 53137:tid 140083771930368] [remote 127.0.0.1:39018] ImportError: A recent version of Python 3 is required.
```

Thank you
Best Regards
Deniz

**Comment by waylan** [comment]
We fully support Python version 3.6 through 3.9. I am not aware of any reason this shouldn't work. Based on the traceback, the error is being raised here:

https://github.com/Python-Markdown/markdown/blob/b77c207d53c5d4d87039dd57e77b9d22d6c4c60a/markdown/__init__.py#L26-L27

... which suggests to me that you are using Python 2 with your server. Is there any situation in which a version 3+ of Python would evaluate `True` for `sys.version_info[0] < 3`?

**Comment by denizdxyz** [comment]
Okay I understood. In Apache, I was actually using the python version 2.x not the one in my conda environment (python 3.x).

I am closing the issue.

Thank you
Deniz
