### ISSUE TITLE
Wikilinks Fails GitHub wiki Images

### ISSUE THREAD

**Issue by flywire** [Python-Markdown/markdown#1082]
Fails to link GitHub wiki Images.

Wikis can display PNG, JPEG, [JPG,] and GIF images.

[Linking to images in a repository](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/editing-wiki-content#linking-to-images-in-a-repository)
> You can link to an image in a repository on GitHub by copying the URL in your browser and using that as the path to the image. For example, embedding an image in your wiki using Markdown might look like this:
>
>`[[https://github.com/USERNAME/REPOSITORY/blob/main/img/octocat.png|alt=octocat]]`

eg: `!['Example Image'](https://raw.githubusercontent.com/wiki/schroef/extra-image-list/images/extra-image-list.jpg)`

**Comment by waylan** [comment]
While this extension may be similar to GitHub’s wiki syntax, it is not intended to be a clone.

In fact, this extension’s primary purpose is to serve as an example of how an extension could be implemented. I’m not inclined to add any new features. However, if someone wanted to fork it, they are certainly welcome to, so long as they do so within the constraints of the license.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flywire** [comment]
Generally works in markdown, just doesn't always render properly eg preview: https://github.community/t/bug-wiki-and-help-markdown-image-parser/146735

**Comment by waylan** [comment]
If you can provide a minimal example that fails which one would expect to work after reading our documentation, then we will reconsider.

**Comment by flywire** [comment]
> this extension’s primary purpose is to serve as an example of how an extension could be implemented

Noted. Moved to https://github.com/neurobin/mdx_wikilink_plus/issues/6

**Comment by flywire** [comment]
[Merge pull request #7 from flywire/patch-1
Render Images](https://github.com/neurobin/mdx_wikilink_plus/commit/7c2ff537f5b027d3e70dc2c5c7a675e2292eea68)
