### ISSUE TITLE
I would like to split a markdown file along  h2 headers

### ISSUE THREAD

**Issue by joegyoung** [Python-Markdown/markdown#1089]
I have markdown files that has multiple sub topics separated by h2 headers. I want to be able to split the file by topics into an array of strings. I would like to use the markdown library before import something new into my script.  Can you help show me? Thank you.

**Comment by facelessuser** [comment]
TBH, Python Markdown provides a Markdown parser and an API to write extensions, I'm not sure that any of us that contribute and help support this project have the time to help design custom solutions.

You could maybe do something with an extension, but you'd have to put in the work to figure out how that would go. Do you come up with a way to split it before it goes through the Markdown parser? Do you parse the whole file and then split the HTML output afterward? Are there edge cases you need to consider? Is there a different approach that could be taken? That is really something you'd have to explore. Or maybe someone has already done something similar to what you are looking for, it doesn't hurt to search around.

If this is important to you, and you can't find an existing solution, I would look into the API and see if you can create an extension that does what you want, or maybe you can just come up with an independent way to split it before or after using the Python Markdown library.

**Comment by joegyoung** [comment]
I am from the ruby realm and this is the first foray into python. This is my current attempt. I pulled it from stackoverflow. 

```
file = open('index.md','r')
data = file.read()
file.close()


contents = []
for i in xrange(len(data)-1-3,-1,-1):
	if data[i:i+2] == '\n#' and data[i:i+3] != '\n##':
		contents.append(data[i+1:])#append the section
		data = data[:i]#remove from data
contents.reverse()

print(len(contents))
```
This will work for my needs then once I figure out how to get it to look for /n## instead of /n#

**Comment by joegyoung** [comment]
I will close this ticket. I used:
```
splitData = data.split("\n##")
for i in xrange(len(splitData)-1,-1,-1):#going backwards
    if splitData[i][0] == '##':#subsection
        splitData[i-1] += splitData.pop(i)#being sure to add back what we remove from the .split
    else:#section
        splitData[i] = splitData[i]#adding back the wanted part removed with the .split
```

**Comment by facelessuser** [comment]
Glad you figured out something that works for you. Sorry I couldn't be of more help.
