### ISSUE TITLE
Add support for Non breaking space character

### ISSUE THREAD

**Issue by xgouchet** [Python-Markdown/markdown#1098]
Right now, the UTF-8 [`NO-BREAK SPACE` character](https://www.fileformat.info/info/unicode/char/00a0/index.htm) (0xC2 0xA0) seems to be left as is, which is not handled properly by  some navigators. Instead it would be better to convert it into the HTML version of a non breaking space : `&nbsp;`

**Comment by waylan** [comment]
Markdown does not convert characters to HTML entities in general. Why should it be different for this character?

Yes, I understand that HTML entities are generally preferred in HTML, but that is not reason enough to convert any other characters either. The fact is, raw HTML, including HTML entities, can be included directly in Markdown. There is no reason to not use `&nbsp;` directly. In fact, it is easier to type that the gymnastics to get the actual Unicode character.

I'm going to defer to the reference implementation on this and leave the behavior as-is. That said, you (or anyone) is free to create an extension which alters the default behavior.

**Comment by xgouchet** [comment]
Hey @waylan 
Thanks for taking the time to respond. I understand your point of view, and I'll probably make an extension then. FYI for me it's actually easier to type a non-breaking space (it's a two keys shortcut on my system), and has the advantage of looking like a space when reading the raw markdown.
Thanks again
