### ISSUE TITLE
Highlight fenced code with pygments

### ISSUE THREAD

**Issue by andreikop** [Python-Markdown/markdown#110]
Github fenced code blocks contain programming language name. 
It would be nice, if you support code highlighting with pygments.

You could check https://github.com/trentm/python-markdown2/blob/master/lib/markdown2.py. It declares pygmetns support for fenced code blocks (but, don't work for me)

**Comment by waylan** [comment]
The  [fenced_code](http://packages.python.org/Markdown/extensions/fenced_code_blocks.html) extension is aware of and calls the [codehilite](http://packages.python.org/Markdown/extensions/code_hilite.html) extension if it is loaded and passes the language in.  You just need to include both of them: 

``` python
markdown.markdown(text, extensions=['codehilite', 'fenced_code'])
```

Although I see this is not documented anywhere, so I guess I need to fix that. Thanks.

**Comment by andreikop** [comment]
I just found, that there are one more extension for being similar to github flavored markdown output - nl2br.
Maybe you should add more user friendly API, something like 

```
markdown.markdown(text, dialect='github')
```

instead of 

```
markdown.markdown(text, extensions=['codehilite', 'fenced_code', 'nl2br'])
```

**Comment by waylan** [comment]
As I've stated elsewhere previously, I'm not opposed to something like this. However, I have no need for it and have no interest in spending the time to implement it myself. However, if someone else did that would be fine (no volunteers yet). Oh, and I would suggest the pattern used by the "extra" extension. It wraps various other extensions (check the source). No need to add a new keyword. Just do `extensions=['github']`. In fact, that way, it can live as a [third party extension](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions) - no need to wait for me to maintain something I don't care about.
