### ISSUE TITLE
Feature request: abbreviations extension - support for multi-word and case insensitive (or a glossary extension?)

### ISSUE THREAD

**Issue by StarfallProjects** [Python-Markdown/markdown#1101]
At present, the abbreviations extension appears to be case sensitive and only support single-word abbreviations (basing this off how it works in its integration with Material for MkDocs - original discussion [here](https://github.com/squidfunk/mkdocs-material/issues/2258))

It would be really useful if it could support multi-word terms and be case insensitive. I'm primarily thinking of its use-case as a glossary tool, where it is necessary to add definitions for more than just strict abbreviations (you might want to define industry or company specific terminology, for instance). Alternatively, if it felt more logical to keep abbreviations just to abbreviations, a "glossary" extension that behaves the same but supports multi-word and any case would be helpful.

**An example of what I mean:**

I want to be able to do something like:

`*[Alternate site testing]: Fingerprick blood tests, using a site other than the fingers or palm of hand.`

And have it provide the definition for both:

_Alternate site testing can be complicated.
If you want to do alternate site testing, follow these steps._

**Comment by waylan** [comment]
I'm sorry, but a glossary (which defined terms) is a different feature from abbreviations. Given the text you provide, the use-case this extension is intended for would be this:

```
AST can be complicated.
If you want to do AST, follow these steps.

*[AST]: Alternate site testing
```

Note that abbreviations are generated by using HTML's [abbr][1] element which is specifically intended for abbreviations or acronyms. A glossary which defined terms would be a different feature which would use different HTML.

Of course, you are free to develop your own extension which offers the features you want. However, I do not have the time available to do so for you.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

**Comment by waylan** [comment]
By the way, if you want to use an existing extension, you may find more success with footnotes. You can point to the same footnote from multiple locations. Like this:

```
Alternate site testing[^1] can be complicated.
If you want to do alternate site testing[^1], follow these steps.

[^1]: Fingerprick blood tests, using a site other than the fingers or palm of hand.
```

Then you could use some JavaScript to display the text of the footnote inline on hover. A quick search turned up [this example][1], among [others][2].

[1]: https://www.jqueryscript.net/text/Inline-Footnotes-On-Hover.html
[2]: https://duckduckgo.com/?q=inline+footnotes+javascript&atb=v101-1__&ia=web

**Comment by StarfallProjects** [comment]
Ah sorry I though this was an issue tracker for the whole repo, so proposing a new extension might be possible. Thanks for responding so quickly.

**Comment by waylan** [comment]
Yes, this is for the whole repo. However, we are not adding new extensions. Instead, we expect new extensions to be developed separately by third parties.
