### ISSUE TITLE
Footnote problem

### ISSUE THREAD

**Issue by fourchette** [Python-Markdown/markdown#111]
When I create a document with some footnote, the next document I create have the same footnote.

**Comment by waylan** [comment]
I'm assuming you're using a single instance of the class to process multiple documents. If so, then you should call the `reset()` method on the class between each document (as [documented](http://packages.python.org/Markdown/reference.html#Markdown)).

If you are experiencing a different issue, please provide more information.

**Comment by fourchette** [comment]
OK I just need to open my eyes, sorry for that.
