### ISSUE TITLE
How to run multiple Extensions of Python Markdown Library

### ISSUE THREAD

**Issue by Ew02726** [Python-Markdown/markdown#1110]
I am using the Python Markdown Library (https://python-markdown.github.io/) with the Table of contents extension & the Tables extension, however both of these extensions are called differently.

For the Table of Contents extension:

md = markdown.Markdown(extensions=['toc'])

output = md.convert(someFile)

For the Tables extension:

md = markdown.markdown(someFile, extensions=['tables'])

The same file needs to be parsed by both extensions. Is there a way to do this in one execution of the script, or would I have to run the first extension, save that file, and run the second extension after?

python

**Comment by waylan** [comment]
The `extensions` argument accepts a list. You can include multiple items in a list. 

```python
markdown.Markdown(extensions=['toc', 'tables'])
```

This is fully [documented](https://python-markdown.github.io/reference/#extensions).
