### ISSUE TITLE
Blockquotes should not be parsed inside code blocks

### ISSUE THREAD

**Issue by danielzgtg** [Python-Markdown/markdown#1113]
python-markdown is not rendering backtick code blocks properly when they include a greater than sign (">").

# Input

`'```\n>\n```'`

# Expected Output

`'<p><code>></code></p>'`

According to https://daringfireball.net/projects/markdown/syntax , "Regular Markdown syntax is not processed within code blocks. E.g., asterisks are just literal asterisks within a code block. This means it’s also easy to use Markdown to write about Markdown’s own syntax."

Most parsers parse this properly: https://johnmacfarlane.net/babelmark2/?text=%60%60%60%0A%3E%0A%60%60%60

For example, GitHub Markdown:

```
>
```

# Actual Output

`'<p>```</p>\n<blockquote>\n<p>```</p>\n</blockquote>'`

This is making it hard to render content that contains ">" signs, such as many types of command line interfaces

**Comment by waylan** [comment]
You appear to be using fenced code blocks, which are not part of the original Markdown rules and therefore not enabled by default. Have you enabled the [fenced code block][1] extension?

If there is any bug here, it is that we differ from markdown.pl in that we do not require a space after the `>` and markdown.pl does to recognize it as a blockquote. See [Babelmark][2], where I added the space, which causes markdown.pl to match Python-Markdown output with or without the space.

[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/
[2]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60%0A%3E+%0A%60%60%60

**Comment by danielzgtg** [comment]
> Have you enabled the fenced code block extension?

I didn't.

After enabling it, my Markdown renders properly now.

Sorry, I didn't realize I needed to enable that extension
