### ISSUE TITLE
option to renumber footnotes in correct page order

### ISSUE THREAD

**Issue by gabriel-v** [Python-Markdown/markdown#1117]
When editing a single document numerous times, you add footnotes all over the place:

```markdown
Last minute but very important thing here[^3].
FIrst lorem ipsum [^1].
Second paragraph somewhere [^2].

[^1]: added this link first
[^2]: added this one second
[^3]: and this one third
```

Footnotes are rendered with numbering as above (`[^3]`, then `[^1]`, then `[^2]`) and showing the footnote list in the original order too.

For numbered footnotes, sometimes the numbers themselves are not important; just their order in the page. Here, the correct link numbering and ordering seems to be the responsibility of the writer.

I would like some kind of parameter on the footnote extension to enable renumbering of the numbered footnotes, and sorting their entries in the footnote section. With such an option set, the document writers will only need to use the same number in both places to get a correct link.

**Comment by waylan** [comment]
I'm not sure I follow. When you say you want the ability to renumber, what do you mean? Renumber in the order that the references (`[^1]`) appear in the document? Or renumber in the order that the footnotes appear in the document?

If the former, then how do we feel with a single footnote being referenced from multiple location in the same document?

This could be difficult to implement. We don't really keep track of which footnote references occur where in the document. To determine their oder, we would need to scan the entire document first, and then reorder. An added complication is that the footnotes are stored in a Python `dict` by key. How do we reassign item `1` to item `2` without overdoing the existing item `2`? 

I have two points:

1. The correct behavior is non-obvious.
2. We get little gain for a lot of work.

I suppose that if someone did the work I would consider it. But I'm more inclined to suggest that you could fork the extension and develop this as a third party alternative.

**Comment by waylan** [comment]
I'm closing this as something which should be implemented as a third-party extension.

**Comment by J3ronimo** [comment]
Hey waylan,

"renumber in the order that references appear" that is. This is the default behavior in VS Code's markdown preview (with [this](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes)), in Github and also in Gitlab, so I second OP that it would be nice to see `python-markdown`'s footnotes extension play along nicely here, where it currently produces different output to all of these.
