### ISSUE TITLE
[Footnotes] Can you alter the hr-position within MkDocs?

### ISSUE THREAD

**Issue by Andre601** [Python-Markdown/markdown#1122]
I utilize the Footnotes extension in MkDocs to have footnotes displayed at the bottom of my pages.
Now is my goal to further customize it, which I partially achieved using the `///Footnotes Go Here///` text.

The thing I struggle with right now is that the footnotes always have a horizontal ruler above themself, which is something I don't want (or at the very least want to replace)

Can this be achieved with the available configuration settings?
If this is something MkDocs has to change, let me know and I file an issue on their issue tracker.

**Comment by waylan** [comment]
No, there is no configuration option to exclude the `hr`. If you really don't want it, you could use MkDocs' `extra_css` config option to include some CSS which sets the `hr` to `display:hidden`.

**Comment by Andre601** [comment]
Wouldn't that alter the hr globally? I don't really want every hr to be hidden. At most should it only be the one for the footnotes.

**Comment by waylan** [comment]
The footnotes (including the `hr`) are always wrapped in a `<div class="footnote">`. So just do:

```css
div.footnote>hr {
    display:hidden;
}
```

And then the rule will only ever apply to `hr`s which are immediate children of the footnote `div`s. By using `>` you can ensure that a `hr` included an the body of a footnote will not be hidden as it is not an immediate child. However, if you want all `hr`s within footnotes to be hidden replace `>` with a space.

**Comment by Andre601** [comment]
That seems to work. Although a small difference: It's `display: none` ;)
