### ISSUE TITLE
Unordered list indentation

### ISSUE THREAD

**Issue by liushilive** [Python-Markdown/markdown#1125]
Code:

```python
import markdown

text = """
* List item
  * Nested list item indented by 2 spaces
* List item
  * Nested list item indented by 2 spaces
  * List item
    * Nested list item indented by 2 spaces"""

markdown.markdown(text)
```

Out:

```html
<ul>\n<li>List item</li>\n<li>Nested list item indented by 2 spaces</li>\n<li>List item</li>\n<li>Nested list item indented by 2 spaces</li>\n<li>List item<ul>\n<li>Nested list item indented by 2 spaces</li>\n</ul>\n</li>\n</ul>
```

Out preview:

<ul>
<li>List item</li>
<li>Nested list item indented by 2 spaces</li>
<li>List item</li>
<li>Nested list item indented by 2 spaces</li>
<li>List item<ul>
<li>Nested list item indented by 2 spaces</li>
</ul>
</li>
</ul>

---

Expectation corrected output:

```html
<ul>\n<li>List item<ul>\n<li>Nested list item indented by 2 spaces</li>\n</ul>\n</li>\n<li>List item<ul>\n<li>Nested list item indented by 2 spaces</li>\n<li>List item<ul>\n<li>Nested list item indented by 2 spaces</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>
```

Expectation corrected preview:

<ul>
<li>List item<ul>
<li>Nested list item indented by 2 spaces</li>
</ul>
</li>
<li>List item<ul>
<li>Nested list item indented by 2 spaces</li>
<li>List item<ul>
<li>Nested list item indented by 2 spaces</li>
</ul>
</li>
</ul>
</li>
</ul>

Github Markdown editor：

![image](https://user-images.githubusercontent.com/13434707/114829164-526b9100-9dfd-11eb-8f5b-15fd4b4b56d4.png) ![image](https://user-images.githubusercontent.com/13434707/114829151-4c75b000-9dfd-11eb-8dc2-aaa4e59f13bc.png)

Rule: <https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md007>

**Comment by mitya57** [comment]
Python-Markdown requires 4 spaces indentation for list items content by default.

This is documented in the [“Differences” section](https://python-markdown.github.io/#differences) of our docs. Quoting from there:

> The [syntax rules](https://daringfireball.net/projects/markdown/syntax#list) clearly state that when a list item consists of multiple paragraphs, "each subsequent paragraph in a list item **must** be indented by either 4 spaces or one tab" (emphasis added). However, many implementations do not enforce this rule and allow less than 4 spaces of indentation. The implementers of Python-Markdown consider it a bug to not enforce this rule.
>
> This applies to any block level elements nested in a list, including paragraphs, sub-lists, blockquotes, code blocks, etc. They **must** always be indented by at least four spaces (or one tab) for each level of nesting.
>
> In the event that one would prefer different behavior, [tab_length](https://python-markdown.github.io/reference/#tab_length) can be set to whatever length is desired. Be warned however, as this will affect indentation for all aspects of the syntax (including root level code blocks).
