### ISSUE TITLE
Create graphics on pages with Python-Markdown

### ISSUE THREAD

**Issue by laurianops** [Python-Markdown/markdown#1126]
I'm using the pelican as a CMS, and I want to create graphics on the pages using Python-markdown, does anyone have any idea how I do this?

**Comment by facelessuser** [comment]
I'm not sure what you mean "create graphics", but I'm pretty sure an extension is what you'd want. I'm not sure if there is one already that does what you want as I'm not sure what you are trying to do, but you may have to look around for an existing plugin or write your own.

**Comment by laurianops** [comment]
Thanks @facelessuser  I believe this must be the right path.
