### ISSUE TITLE
-x tables not working for command-line interface

### ISSUE THREAD

**Issue by lars-bd** [Python-Markdown/markdown#1134]
Using the example from the documentation (the > are for preventing GitHub from translating the table)

    > First Header  | Second Header
    > ------------- | -------------
    > Content Cell  | Content Cell
    > Content Cell  | Content Cell

invoking markdown with

    python -m markdown -x tables sample.md > sample.html

doesn't translate the table from text to HTML, but generates a [pre][code] wrapper.

**Comment by waylan** [comment]
> the > are for preventing GitHub from translating the table

Actually, the are for blockquotes, which is working just fine:

```bash
$ cat sample.md
> First Header  | Second Header
> ------------- | -------------
> Content Cell  | Content Cell
> Content Cell  | Content Cell
$ python -m markdown -x tables sample.md
<blockquote>
<table>
<thead>
<tr>
<th>First Header</th>
<th>Second Header</th>
</tr>
</thead>
<tbody>
<tr>
<td>Content Cell</td>
<td>Content Cell</td>
</tr>
<tr>
<td>Content Cell</td>
<td>Content Cell</td>
</tr>
</tbody>
</table>
</blockquote>
```

> Using the example from the documentation

What documentation? Also, what version of Python-Markdown are you using?

**Comment by lars-bd** [comment]
I meant to say that I used the `>` merely to prevent GitHub from converting the ASCII into a real table, like markdown.py is supposed to do.  Please ignore the `>`s, as they are not in the example I try to convert.

As for your second question, I took this example from your project's documentation: https://python-markdown.github.io/extensions/tables/

**Comment by waylan** [comment]
Again, this is working fine for me. What version of Python-Markdown are you using?

**Comment by lars-bd** [comment]
I've just installed the latest version with pip a couple of days ago.

    cassiopeia:~# pip list | grep -i markdown
    Markdown                3.3.4

**Comment by lars-bd** [comment]
To rule out any subtle misunderstandings, I attached my sample markdown file.  With this file, I do:

    cassiopeia ~ > markdown_py -x tables table.md
    <p>hello</p>
    <pre><code>First Header  | Second Header
    ------------- | -------------
    Content Cell  | Content Cell
    Content Cell  | Content Cell
    </code></pre>

[table.md](https://github.com/Python-Markdown/markdown/files/6541238/table.md)

**Comment by waylan** [comment]
The issue is that your table is indented. Of course, any indented content is considered a code block. Remove the indent and it will work as expected

**Comment by lars-bd** [comment]
Oh, I see.  Thanks for clarifying this!
