### ISSUE TITLE
No way to disable escaping on code blocks / inline code

### ISSUE THREAD

**Issue by gmjosack** [Python-Markdown/markdown#1135]
I have a site that allows users to input markdown for posts/comments. I need to sanitize that input for display so they can't input html. This works fine except that and `<`, `>`, `&` get double escaped when inside code blocks or inline code.

I've seen recommendations to sanitize the html after running it through markdown with an allow list of tags but this doesn't work for me as it allows users to post html. This is problematic because i have markdown extensions that all for example that output img tags but I wouldn't want users to be able to post arbitrary images.

I've spent some time looking through the code and search around and I don't see any guidance or good ways to solve this issue. I've filed this issue to see if there's something I'm missing or if the project would be open to an enhancement that supports disabling escaping. I'd be open to doing a pull request but want to make sure I'm not wasting me time first.

**Comment by facelessuser** [comment]
I'm not sure I understand. If the code is not getting double escaped passing through Python Markdown normally, which I don't think it is, then the problem lies somewhere in your Markdown handling.

If it is getting double escaped due to sanitization, then the problem is with sanitization. 

If the source is already escaped from the input, then you need to figure out how to unescape content before passing it through Python markdown.

You'll need to do some investigative work to discover where the unintended escaping is originating from. Once you do that, I'm sure it will be more clear what you should do.

**Comment by gmjosack** [comment]
Here's a more concrete example

#### Setup
```python
In [1]: import markdown
In [2]: import bleach
In [3]: text = """
   ...: <>&
   ...: 
   ...: `<>&`
   ...: 
   ...: ```
   ...: <>&
   ...: ```
   ...: """
In [4]: md = markdown.Markdown(extensions=["codehilite", "fenced_code"])
```

#### Output from sanitizing
~~~
In [5]: print(bleach.clean(text, tags=[]))

&lt;&gt;&amp;
`&lt;&gt;&amp;`

```
&lt;&gt;&amp;
```
~~~

#### Output from converting sanitized text
~~~html
In [6]: print(md.convert(bleach.clean(text, tags=[])))
<p>&lt;&gt;&amp;</p>
<p><code>&amp;lt;&amp;gt;&amp;amp;</code></p>
<div class="codehilite"><pre><span></span><code>&amp;lt;&amp;gt;&amp;amp;
</code></pre></div>
~~~

#### Desired output
~~~html
<p>&lt;&gt;&amp;</p>
<p><code>&lt;&gt;&amp;</code></p>
<div class="codehilite"><pre><span></span><code>&lt;&gt;&amp;
</code></pre></div>
~~~

If I were to sanitize with approved tags after converting with markdown the user gets to post html which is not desired.

~~~python
In [7]: text = """
   ...: <b>hi</b>
   ...: **hi**
   ...: ```
   ...: <b>hi</b>
   ...: ```
   ...: """
~~~

you can see the user input is passed through

~~~html
In [19]: print(bleach.clean(md.convert(text), tags=["p", "b", "strong", "div", "pre", "code", "span"]))
<p><b>hi</b>
<strong>hi</strong></p>
<div><pre><span></span><code><span>&lt;b&gt;</span>hi<span>&lt;/b&gt;</span>
</code></pre></div>
~~~

I'd like to disallow any html input, rendering it as typed always limiting input only to markdown. It works fine in all cases currently other than inline code and code blocks doing additional escaping.

**Comment by facelessuser** [comment]
Right now, I'm seeing the intended behavior. You are trying to sanitize Markdown, not HTML with bleach. So you are escaping code content that you do not intend to. So when it passes through the Markdown parser, it gets escaped again as it thinks you want that exact content to display in the code blocks.

You should sanitize the final HTML when it comes out of Python Markdown.

Python Markdown doesn't disallow all HTML, if you need to do that, you can try writing an extension that disables that in the Markdown parser, but that is something that is not currently supported out of the box.

**Comment by gmjosack** [comment]
Yea, I understand i'm sanitizing markdown and not html, I've just not found a better way to accomplish this currently which I'm bit surprised by as I didn't expect it to be a niche use case.

I don't particularly care if people use `<b>` tags but i'm using the `pymdownx.emoji` extension which outputs an img tag. I want to offer emoji without offering users the ability to post arbitrary images.

Would you say that is not a use case this library supports without adding a custom html sanitizer extension? If disabling this escaping isn't desired I can look at an alternative method to handle this and close this issue.

**Comment by facelessuser** [comment]
> Yea, I understand i'm sanitizing markdown and not html, I've just not found a better way to accomplish this currently which I'm bit surprised by as I didn't expect it to be a niche use case.

Disabling all HTML? Or some interface to configure specific tags to be disabled?

You might find some parers out there that maybe disable all HTML tags, but probably few allow that. Even less likely is some specialized interface to disable specific tags. At most some may disable things like `<script>` tags and such, but we defer that to things like bleach post Markdown processing.

> I don't particularly care if people use `<b>` tags but i'm using the `pymdownx.emoji` extension which outputs an img tag. I want to offer emoji without offering users the ability to post arbitrary images.

So, you specifically want to only allow emoji images? I guess you could parse the HTML afterwards and remove any images that have images from unknown locations 🤷🏻.

I mean, people can specify images currently using Markdown as well, not just HTML, so blocking HTML isn't going to stop people from linking an image. I mean, I guess you could disable the image processor in Python Markdown as well with your own plugin, so I guess that is an option.

**Comment by gmjosack** [comment]
I appreciate all the insight here. Seems it's probably best to just let people use the approved html tags and switch to sanitizing post markdown conversion. I like the idea of limiting input to no html but seems that's not really supported and it's be a lot of work to do right.

Thanks for your time here.

**Comment by CyberFox001** [comment]
I get the exact same problem.

If I escape the html generated from Markdown, it will escape the legit html tags.

@gmjosack Have you found a working solution ?
