### ISSUE TITLE
inserting newlines

### ISSUE THREAD

**Issue by modernNeo** [Python-Markdown/markdown#1137]
I am somewhat confused by how to insert newlines in places like codeblocks and such.

If I understand correctly, doing 2 trailing white spaces should insert a newline, right?

cause if I do
```
line 1  
  
line 2
```

I get

```
<p>line 1  </p>
<p>line 2</p>
```
instead of
```
<p>Line 1</p><br>
<p>Line 2</p>
```

and then if I do

```
Here is an example of AppleScript:  
  
    tell application "Foo"
        beep
    end tell
```

the code block is properly indented but there is no new line after `AppleScript`, I instead get
```
<p>Here is an example of AppleScript:  </p>
<pre><code>tell application "Foo"
    beep
end tell
</code></pre>
```

the way I am using the markdown module is like so

```
markdown.markdown(
            request.POST['message'], extensions=[
                'sane_lists', 'markdown_link_attr_modifier'
            ],
            extension_configs={
                'markdown_link_attr_modifier': {
                    'new_tab': 'on',
                },
            }
        )
```

**Comment by facelessuser** [comment]
Per the Markdown spec, the following defines two paragraphs. And that is exactly what happens. Spacing between paragraphs is controlled by the browser's styling and can be increased or decreased by fiddling with margins, etc.

```
line 1  
  
line 2
```

You can use two spaces at the end of a line to force `<br>` between lines, but that is just for lines within a specific block.

So if you did:

```
line 1  
line 2
```

It would work, but not when you have an empty new line.

If you want to force a `<br>` for an empty line (and yes white space on a line is still considered empty), you can manually use `<br>`.

```
line 1<br>
<br>
line 2
```

https://johnmacfarlane.net/babelmark2/?text=line+1%3Cbr%3E%0A%3Cbr%3E%0Aline+2

This will not work for your second example as Markdown won't embed other blocks inside the paragraph. A code block must be its own seperate block.

If you want to see more spacing between the code block and the paragraph, you need to style the blocks with CSS to increase the margin etc.

**Comment by modernNeo** [comment]
I am not entirely sure if I understand what you said here
>This will not work for your second example as Markdown won't embed other blocks inside the paragraph. A code block must be its own separate block.

Since I do not want the `pre` block to be embedded in the paragraph, I just want a newline inserted like this
```
<p>Here is an example of AppleScript:</p><br>
<pre><code>tell application "Foo"
    beep
end tell
</code></pre>
```

**Comment by facelessuser** [comment]
What I'm saying is that this won't work

```
Here is an example of AppleScript:<br>
<br>
    tell application "Foo"
        beep
    end tell
```

It'll treat the entire block as one paragraph and the code will not get treated as code. You'd have to do something like this (with a newline separating the paragraph from the code block.

```
Here is an example of AppleScript:<br>
<br>

    tell application "Foo"
        beep
    end tell
```

**Comment by modernNeo** [comment]
that does not work either. running

```
Here is an example of AppleScript:<br>
<br>

    tell application "Foo"
        beep
    end tell
```

through 
```
markdown.markdown(
            request.POST['message'], extensions=[
                'sane_lists', 'markdown_link_attr_modifier'
            ],
            extension_configs={
                'markdown_link_attr_modifier': {
                    'new_tab': 'on',
                },
            }
        )
```

gives me
```
<p>Here is an example of AppleScript:<br>
<br></p>
<pre><code>tell application "Foo"
    beep
end tell
</code></pre>
```

**Comment by modernNeo** [comment]
nope, that worked. I identified the issue as being one of my CSS rules that was messing with the `<br>` tags. thanks
