### ISSUE TITLE
Markdown fails to convert a paragraph + sane list if there is only a single line between them

### ISSUE THREAD

**Issue by devfox-se** [Python-Markdown/markdown#1138]
Markdown fails to convert a paragraph + sane list if there is only a single line between them.
`txt_ok` contains 2 new line characters and the output html is a valid list where markdown fails to generate a proper list from `txt_fail` because there is only 1 `\n` between List name and List content

```
>>> txt_ok = "My List:\n\n1. First Item\n2. Second Item"
>>> txt_fail = "My List:\n1. First Item\n2. Second Item"

>>> markdown.markdown(txt_ok)
'<p>My List:</p>\n<ol>\n<li>First Item</li>\n<li>Second Item</li>\n</ol>'

>>> markdown.markdown(txt_fail)
'<p>My List:\n1. First Item\n2. Second Item</p>'
```

**Comment by waylan** [comment]
This is the correct (expected) behavior (see [Babelmark][1]). As a reminder, Python-Markdown is not a Commonmark implementation, but an implementation of the original rules. As Babelmark, demonstrates, we follow the behavior of the reference implementation (`markdown.pl`). You must include a blank line between a paragraph and a list. Seems like a reasonable rule to me. It is beyond me why Commonmark felt the need to change it.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=My+List%3A%0A1.+First+Item%0A2.+Second+Item
