### ISSUE TITLE
Line breaks not being handled correctly?

### ISSUE THREAD

**Issue by Dave-ts** [Python-Markdown/markdown#1140]
I found this issue while working on another project heavily dependent on python-markdown. The issue existed in 3.2.1 so I pulled in tag 3.3.4 and found the issue still shows up there. I did a little research and it seems that python-markdown isn't matching spec in the fourth issue, but html is causing issues in the rest, so I thought I'd leave it here for ya'll to decide if it's worth changing.

Markdown to test
```
line
no trailing space

line 
one trailing space

line  
two trailing spaces

line   
three trailing spaces

line	
trailing tab
```

Output
```
<p>line
no trailing space</p>
<p>line 
one trailing space</p>
<p>line<br />
two trailing spaces</p>
<p>line <br />
three trailing spaces</p>
<p>line  <br />
trailing tab</p>
```

**First**: A line with no space at the end has a space entered in the html as it is rendered. This seems like an issue with HTML5 render engines where a line break is treated as a space rather than actually ignored. When converting from markdown to html I wonder if we shouldn't be stripping these single line breaks out in order to produce the expected result (A simple concatenation of the two or more lines).

HTML Example:
```
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>
<p>
my first line
my second line.
</p>

</body>
</html>
```

HTML output:
```
My First Heading
My first paragraph.

my first line my second line.
```

**Second**: The single space at the end of the line seems to be stripped by the render engine or ignored by the html engine. One space following a line does result in the desired space being seen in the browser, but it's happening as a result of accident rather than intent. If the engine stripped the line break out we'd still get only one space (as we should), but if we instead entered `&nbsp` at render time we'd likely end up with two blank spaces, once again because of HTML render brokenness in regards to \n characters.

example with `&nbsp` and line break left in, note the duel spaces:

```
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>
<p>
my first line&nbsp	
my second line
</p>

</body>
</html>

OUTPUT

My First Heading
My first paragraph.

my first line  my second line

```
**Third**: Three or more spaces add a line break and leave the rest of the spaces behind. While I think this behavior is sort of as expected, a problem that occurs is that the space that is left is ignored by html once again because it's not converted to `&nbsp` The actual statement from Gruber's website says: "When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return."

In this case I think the entire `{2,}` spaces should be stripped and the `<br />` should replace it.

**Fourth**: Tab produces a line break. This is just weird and I suspect would be best to just get rid of.

I found these issues doing some pretty edge case document production, but in doing some searching for this issue report I'm finding a great deal of posts out there with folks having issues with the way HTML is dealing with line breaks. IMHO the engine would be improved by handling these line break issues by stripping the line break and using them as a single concatenated line. Filling in with `&nbsp` might be bad just because it could result in making much messier output. I'll let you great folks debate if this is worth looking into or not.

Sorry for the wall of text, tried to do and share as much research as I could on the issue.

**Comment by facelessuser** [comment]
> First: A line with no space at the end has a space entered in the html as it is rendered. This seems like an issue with HTML5 render engines where a line break is treated as a space rather than actually ignored. When converting from markdown to html I wonder if we shouldn't be stripping these single line breaks out in order to produce the expected result (A simple concatenation of the two or more lines).

HTML5 is correct in this case. If you line break with no space to a new line, there should be a space between the last word on the first line and the first word on the second line. That is not a bug, and Python Markdown should not alter the result the make these words concatenated.

> Second: The single space at the end of the line seems to be stripped by the render engine or ignored by the html engine. One space following a line does result in the desired space being seen in the browser, but it's happening as a result of accident rather than intent. If the engine stripped the line break out we'd still get only one space (as we should), but if we instead entered &nbsp at render time we'd likely end up with two blank spaces, once again because of HTML render brokenness in regards to \n characters.

HTML collapses white space (unless you have specific CSS options that prevent such -- think code blocks). We don't do anything special with white space in this scenario. The white space is left as it is insignificant, and the HTML browser does the right thing. If you do not want that white space, I would suggest you do not enter it.

> Third: Three or more spaces add a line break and leave the rest of the spaces behind. While I think this behavior is sort of as expected, a problem that occurs is that the space that is left is ignored by html once again because it's not converted to &nbsp The actual statement from Gruber's website says: "When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return."

Again, this behavior is fine. We do not police white space, the browser will do the right thing and collapse it as needed. If you are enabling CSS that does not collapse white space, then you should enter exactly what you prefer.

> Fourth: Tab produces a line break. This is just weird and I suspect would be best to just get rid of.

Python markdown converts tabs to 4 spaces. This is documented and is why you get the behavior you describe. Whether Python Markdown "should" do this is debatable, but this is currently a known and accepted behavior in Python Markdown.

**Comment by Dave-ts** [comment]
Sounds good, close it up then I just wanted to put it out there in case it was something that should be addressed.
