### ISSUE TITLE
Heading ID does not work

### ISSUE THREAD

**Issue by muhanpixie** [Python-Markdown/markdown#1141]
Try to give a heading ID as doc:  ### My Great Heading {#custom-id}
 But it puts `<h3> My Great Heading {#custom_id} </h3>` instead of `<h3 id="customer_id">My Great Heading </h3>`

**Comment by waylan** [comment]
Have you enabled the [attr_list][1] extension?

[1]: https://python-markdown.github.io/extensions/attr_list/
