### ISSUE TITLE
codeblock inside list will be render incorrectly

### ISSUE THREAD

**Issue by dantezhu** [Python-Markdown/markdown#1144]
markdown text like this:

````
1. A
    subA1
    ```
    subcode1
    subcode2
    ```
    subA2

2. B
    subB1
    subB2
````
cmd:
```
$ markdown_py  -x fenced_code -x nl2br x.md > 1.html
```

It will be render like this:
![image](https://user-images.githubusercontent.com/1105212/121998683-d54d9f80-cdde-11eb-97c9-573118595a61.png)

this is not right.

**Comment by waylan** [comment]
As stated in the [docs][0]:

> Warning: Fenced Code Blocks are only supported at the document root level. Therefore, they cannot be nested inside lists or blockquotes. If you need to nest fenced code blocks, you may want to try the third party extension [SuperFences][1] instead. 

[0]: https://python-markdown.github.io/extensions/fenced_code_blocks/
[1]: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/

**Comment by dantezhu** [comment]
thanks, but why not support it?
superfences is too invasive...

**Comment by facelessuser** [comment]
Too invasive? In what way?

**Comment by dantezhu** [comment]
For example, the rendered result will have a lot of classes, instead of just inserting a class="lang-python" at the top level

**Comment by dantezhu** [comment]
For example, markdown code like this:
````
1. A
    a
    ```python
    1
    2
    3
    ```
    b

2. B
    a
    b
````

will be render like this:
```
<ol>
<li>
<p>A<br />
    a<br />
    <div class="highlight"><pre><span></span><code><span class="mi">1</span>
<span class="mi">2</span>
<span class="mi">3</span>
</code></pre></div><br />
    b</p>
</li>
<li>
<p>B<br />
    a<br />
    b</p>
</li>
</ol>
```

there has a lot of code like this:
```
 class="mi"
```

of course, if I uninstall pygments, I will be ok:
```
<ol>
<li>
<p>A<br />
    a<br />
    <pre class="highlight"><code class="language-python">1
2
3</code></pre><br />
    b</p>
</li>
<li>
<p>B<br />
    a<br />
    b</p>
</li>
</ol>
```
but other package may need pygments too.

Or is there any other method here that can be kept as above?

**Comment by facelessuser** [comment]
Turn off Pygments. And if you don't like the `highlight` class, turn it off.

```py
>>> markdown.markdown('```python\nimport test\n```', extensions=["pymdownx.superfences", "pymdownx.highlight"], extension_configs={'pymdownx.highlight': {'use_pygments': False, 'css_class': ''}})
'<pre><code class="language-python">import test</code></pre>'
```

**Comment by dantezhu** [comment]
@facelessuser thanks a lot!
