### ISSUE TITLE
Can you customize footnotes section display?

### ISSUE THREAD

**Issue by Andre601** [Python-Markdown/markdown#1145]
For context: I use the footnotes markdown extension within [mkdocs](https://github.com/mkdocs/mkdocs) and together with the [Material for MkDocs theme](https://github.com/squidfunk/mkdocs-material)

My question now is, if I can customize the footnotes section in such a way that it always is formatted like this:
```html
<hr>
<h2 id="__footnotes">Footnotes</h2>

<ol>
  <li>Footnote 1</li>
  <li>Footnote 2</li>
  <li>Footnote 3</li>
</ol>
```

I essentially want to move the horizontal ruler a bit up and add a level 2 header to the entire thing.

Right now do I achieve this by setting the current `<hr>` inside the footnote div to `display: none;` using CSS and manually insert a separate `<hr>` and `<h2>` section into the page, followed by the `<!-- footnotes -->` comment to change the position of the footnote list. The issue there is, that I have to do this manually on each page where I want to use the footnotes, which can be tedious to do.

So now I ask if you can customize the footnote extension in some way to do this by itself.

Thank you in advance for your response.

**Comment by waylan** [comment]
There is currently no way to customize the HTML output by the footnotes extension and there are no plans to change that. Of course, anyone is free to create their own extensions (or fork the existing extensions) which behave in whatever way they desire.
