### ISSUE TITLE
nested, unordered list fails linter

### ISSUE THREAD

**Issue by leggewie** [Python-Markdown/markdown#1147]
As found out in getpelican/pelican#2895, the generated code for nested, unordered lists fails the [html-linter](https://pypi.org/project/html-linter/): "48:76: Error: General Formatting: Use a new line for every block, list, or table element, and indent every such child element: Move the opening "ul" to its own line."  
  
  The offending generated HTML code is
  ```
  $ grep -n remote.*ul public/pages/experience.html -A1
  48:<li>highly proficient in Linux administration including headless and remote<ul>
  49-<li>desktop, server and embedded</li>
  ```
The fact that python-markdown opens the second-level of the unordered list at the end of the preceding line is what triggers the linter. The error message is pretty clear.  The generating markup code is
  ```
  $ grep remote$ content/pages/experience.md -A1
  - highly proficient in Linux administration including headless and remote
      - desktop, server and embedded
  ```

I [verified](https://waylan.pythonanywhere.com/dingus) the continued existence of this issue until release 3.3.2 of python-markdown.

**Comment by facelessuser** [comment]
> "48:76: Error: General Formatting: Use a new line for every block, list, or table element, and indent every such child element: Move the opening "ul" to its own line."

This is a suggestion. Linters are not authorities on format. They are suggestions that like-minded people opt into. Yes, some linting rules can actually also highlight invalid things as well, but not always.

Linters are also best used on something like handwritten documents to help users format things better, not on auto-generated code. I definitely wouldn't run an HTML linter on compressed HTML for instance which minimizes white spaces and strips out unnecessary new lines and such to provide the smallest HTML possible to make HTML requests faster.

My question would be, does Python Markdown generate anything that is invalid HTML5? If not, I don't see a reason to change what Python Markdown is doing. That is my personal opinion though and I'll let @waylan comment with a final verdict.

**Comment by waylan** [comment]
I agree with @facelessuser. Couldn't have said it better myself.
