### ISSUE TITLE
Support \\n as linebreak (via extension)

### ISSUE THREAD

**Issue by MGChecker** [Python-Markdown/markdown#1157]
For example in GitHub or Gitea,\
a single backslash at the end of the line leads to a line break. It would be nice if it would be possible to make Python-Markdown behave like this as well, since it declutters syntax in comparison to `<br />` (and is more visible than `  `).

**Comment by waylan** [comment]
Have you tried the [nl2br] extension?

If you need different behavior, then you are free to create your own third-party extension. We will not be adding any new (builtin) extensions.

[nl2br]: https://python-markdown.github.io/extensions/nl2br/

**Comment by facelessuser** [comment]
[EscapeAll](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/) Is an extension that enables escaping any character (within reason of what is allowed by the parser). It has an option to allow escaping newlines and have them insert `<br>`. If you only need `<br>`, I'm sure you could write an extension that just does that.
