### ISSUE TITLE
Can attribute lists be added to markdown reference links?

### ISSUE THREAD

**Issue by norman-abramovitz** [Python-Markdown/markdown#1158]
Can the attribute list extension support an attribute list on the reference portion of a reference-style link?  

The inline syntax works like this, but the readability factor is low.

    Open [http://127.0.0.1:8080/][1]{:target="_blank"}  in your browser:
    [1]: http://127.0.0.1:8080/ "Local Concourse"

Could the attribute extension process input like this as well?

    Open [http://127.0.0.1:8080/][1] in your browser:
    [1]: http://127.0.0.1:8080/ {:target="_blank"} "Local Concourse"
    
Advantages of this additional syntax. 
1. Improve readability of the base text
2. Allows all URL-related processing to be located in one place.

**Comment by waylan** [comment]
No, that is not supported.

Note that the attribute list feature was created as a subset of the feature first created by Maruku (see [web archive][1]). The requested behavior was not supported there, so it is not supported here either.

Given the above, we will not be added the requested feature to our extension.

Of course, you are free to create your own extension and/or fork the existing extension (within the confines of the license) which adopts whatever behavior you desire.

[1]: https://web.archive.org/web/20170324172643/http://maruku.rubyforge.org/proposal.html
