### ISSUE TITLE
Asterisk incorrectly converted to <em> in html block

### ISSUE THREAD

**Issue by daredevildave** [Python-Markdown/markdown#116]
I believe the following python code generates an incorrect output. The asterisks should remain, but instead are replaced by em tags.

``` python
import markdown as md
input = '<span class="nx">x</span> <span class="o">*</span> <span class="mi">5</span><span class="p">,</span> <span class="nx">y</span> <span class="o">*</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">0</span><span class="p">);'
m = md.Markdown()
print(m.convert(input))
```

Printed output

``` html
<p><span class="nx">x</span> <span class="o"><em></span> <span class="mi">5</span><span class="p">,</span> <span class="nx">y</span> <span class="o"></em></span> <span class="mi">5</span><span class="p">,</span> <span class="mi">0</span><span class="p">);</p>
```

Expected output

``` html
<p><span class="nx">x</span> <span class="o">*</span> <span class="mi">5</span><span class="p">,</span> <span class="nx">y</span> <span class="o">*</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">0</span><span class="p">);</p>
```

**Comment by waylan** [comment]
While I understand your point of view, this is not inline with the original implementation (check on the [Dingus](http://daringfireball.net/projects/markdown/dingus)). As the syntax [rules](http://daringfireball.net/projects/markdown/syntax#html) state: "Unlike block-level HTML tags, Markdown syntax is processed within span-level tags."

Of course, you, as a human reader, recognize that each asterisk is in a different span, however, markdown doesn't have a sophisticated enough understanding of html to recognize that.  All that happens is anything between `<` and `>` gets escaped before processing markdown text and then unescaped afterward. To the parser, the asterisks looks like opening and closing `<em>` tags in a single paragraph and parses them accordingly.

If you want the markdown parser to ignore characters with special meaning in markdown then you need to [backslash escape](http://daringfireball.net/projects/markdown/syntax#backslash) them.
