### ISSUE TITLE
Incorrect Download url in https://pypi.org/pypi/Markdown/json

### ISSUE THREAD

**Issue by loot-whore** [Python-Markdown/markdown#1163]
"project_urls": {
            "Documentation": "https://Python-Markdown.github.io/",
            "Download": "http://pypi.python.org/packages/source/M/Markdown/Markdown-3.3.4-py2.py3-none-any.whl",
            "GitHub Project": "https://github.com/Python-Markdown/markdown",
            "Homepage": "https://Python-Markdown.github.io/",
            "Issue Tracker": "https://github.com/Python-Markdown/markdown/issues"
        },
HTTP on pypi.python.org was turned off like years ago, so this url is unreachable
`    "releases": {
        "1.6": [],
`
Could you remove this empty release?

**Comment by waylan** [comment]
Thanks for bring this to our attention. We have a few options here.

1. We could just remove the "Download" URL altogether. After all, PyPI includes a "Download Files" link in the "Navigation" section of the sidebar right above the "Project Links".
2. We could simply replicate the "Download Files" URL: `https://pypi.org/project/Markdown/#files`. However, as that is provided right above, I don't see the value in repeating it here.
3.  We could try to replicate the old behavior of generating an actual link to the `.whl` file directly. However, note that the current file URL is `https://files.pythonhosted.org/packages/6e/33/1ae0f71395e618d6140fbbc9587cc3156591f748226075e0f7d6f9176522/Markdown-3.3.4-py3-none-any.whl`. We would need to replicate the hash. And we can't update it after uploading, we need to have it before pushing a release.

As a reminder, this is one of the links in [project_urls][1], so it is freeform. We can include whatever links we want. There is no requirements for specific things being listed here. Of course, we want to include links which will be helpful to our users. In the end, I think probably option 1 above makes the most sense.

[1]: https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls

**Comment by loot-whore** [comment]
Yes, removing the link works as well. At least there will be no confusing info :)
What's about removing release 1.6 which is empty?

**Comment by facelessuser** [comment]
Agree with removing it. I see no real value in it and the PyPI "download" seems sufficient.

**Comment by waylan** [comment]
> What's about removing release 1.6 which is empty?

I was just looking into that. As it happens, the first tagged release in the git repo is 1.7 so it would appear that the 1.6 release files have been lost to history. Therefore, I have deleted the 1.6 release from PyPI. It should not longer be included in the list of releases.

**Comment by loot-whore** [comment]
Thanks :)
