### ISSUE TITLE
Colons in URLs are not allowed in safe mode

### ISSUE THREAD

**Issue by gandaro** [Python-Markdown/markdown#117]
You cannot use colons in URLs if you are using the safe mode:

``` pycon
>>> MARKDOWN.convert("[Odyssey](https://apollo.open-resource.org/mission:tech:odyssey)")
u'<p><a href="">Odyssey</a></p>'
```

**Comment by waylan** [comment]
As they should not be. Remember, safe_mode is intended for documents (comments, etc) submitted by untrusted users. We don't want to allow those untrusted users to insert code on our sites that could result in a XSS attach. See the [comments](https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L318) in the code for details.

If a web site is using that format for its urls, that's a problem for that site. I wouldn't recommend it. If that means untrusted users can't post links to that site, I'm ok with that if it means no XSS attaches.

**Comment by gandaro** [comment]
So, because of your laziness not to blacklist the evil formats and because _you_ “wouldn’t recommend it,” people are forbidden to link to sites using colons in their URLs?

Did you know Wikipedia is using that format too? https://en.wikipedia.org/wiki/File:Hello.png

Really, there is no harm in such links, isn’t it?

**Comment by cwebber** [comment]
What XSS attack is being prevented by links with a colon in them?  If there is such a thing I'm genuinely curious what it is, but I don't know of anything at the moment.

**Comment by waylan** [comment]
First, a blacklist is never as secure as a whitelist. A blacklist only blocks specific known vulnerabilities while a whitelist blocks everything except known safe urls. If even one vulnerability is missed in a blacklist, then the purpose of the blacklist is negated. Whereas an overzealous whitelist is still safe. There is plenty of more info on this issue elsewhere on the web if you're curious. But that is why we take the current approach.

The idea is that we close it up to let nothing through, then poke holes where there are known safe urls. Currently, one of the ways this is done is to block all urls which contain a colon (to avoid `javascript:alert('XSS')`, etc.). If, however, you can provide with certainty, specific uses of urls that contain colons which will **definitely** not ever be confused with JavaScript calls, then we can poke a hole for that use-case only. And I should mention that saying site X uses that url format is not a good reason. However, pointing to official specifications and/or authorities on XSS which suggest that it is a safe url would be needed.

If you don't like the approach taken by Python-Markdown, then I would suggest using a third party library (I suggest [bleach](https://github.com/jsocol/bleach), which is probably more secure anyway. Just do `bleach.clean(markdown.markdown(sometext))`. In fact, personally I would like to remove Python-Markdown's 'safe_mode' altogether and recommend this approach instead. The only reasons I haven't are for backward comparability and the desire to avoid the need for dependencies.

**Comment by cwebber** [comment]
Okay, that's a very useful response.  We were currently cleaning out output via lxml.html.clean anyway but I thought if python-markdown had a reason to strip out URLs with colons like this maybe we should know why.

I'll look at bleach though.  Thanks for the response!

**Comment by gandaro** [comment]
If you say that you are keeping it mainly because of backward compatibility and additional dependency reasons I would just stop using it. ;-)  So you don’t spend time on it if we could just use a better software.  I’m sorry if I expressed myself unkindly, I was just annoyed of something else…
