### ISSUE TITLE
Is there an extension that formats the output html?

### ISSUE THREAD

**Issue by writeblankspace** [Python-Markdown/markdown#1170]
Are there any extensions that will format the output html (indents, newlines, etc)?

**Comment by mitya57** [comment]
Most of the existing third-party extensions are listed in the wiki: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions. I couldn’t find one that suits your needs so there is probably none.

I think there is no need to use an extension at all for this purpose. You can just take HTML from Python-Markdown and format it in your Python code. You can use something like BeautifulSoup’s [prettify()](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#pretty-printing) method for that.
