### ISSUE TITLE
Add pre-commit hook

### ISSUE THREAD

**Issue by voronind** [Python-Markdown/markdown#1176]
Can we add [pre-commit](https://pre-commit.com/index.html#new-hooks) hook? There is no Python markdown linter.

**Comment by facelessuser** [comment]
I'm confused about what this is asking. Are you asking that git commit hooks are added to the Python Markdown project to lint its own resources? Or are you asking for a separate project that uses Python Markdown and can be installed as a git hook to lint other Markdown content in other projects?

If it is the latter, you are free to create any project you need using Python Markdown as a dependency, I don't imagine we will be taking on an additional project to provide such functionality. If it is the former, I'm pretty sure we have everything we need to ensure proper project health and don't really need to add pre-commit hooks at this time.

Feel free to clarify if I am still a bit confused as to what is being asked.

**Comment by voronind** [comment]
I mean checking other projects on Markdown file correctness.

**Comment by waylan** [comment]
> I mean checking other projects on Markdown file correctness.

That it out-of-scope for a Markdown parser. Note that a linter enforces best practices which is much more strict than a parser. Therefore, the linter does not need to make use of the same parser as you are using to parse your document. 

Personally, I use and recommend [DavidAnson/markdownlint][1] as a Markdown linter.

[1]: https://github.com/DavidAnson/markdownlint
