### ISSUE TITLE
Bug:  Should remove trailing whitespace in HTML tags.

### ISSUE THREAD

**Issue by kim5566** [Python-Markdown/markdown#1180]
# Bug

For example, the following:
```
<div markdown = "1">

This is a *Markdown* Paragraph.

</div>
```
...is rendered as:
```
<div>
<p>= "1"&gt;</p>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```
# Expected behavior: 

Should be rendered as:
```
<div>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```

# Context:
Python 3.8.11
mkdocs, version 1.2.2

**Comment by waylan** [comment]
I'm assuming this was closed because you realized you needed to enable the `md_in_html` extension for this to work.
