### ISSUE TITLE
Add possibility to inject own serializer

### ISSUE THREAD

**Issue by fgrie** [Python-Markdown/markdown#1181]
As I want to convert markdown input to a output format different than (X)HTML, it would be very handy to provide my own serializer method, similar to `to_html_string(element)`.
It could be injected in a similar way as extension are (either as class or string). Either a  dedicated parameter would be used to inject the custom serializer (`output_format` would then be ignored if the custom serializer is provided), or `output_format ` could be extended to held either the name of the build-in format or a python method for a custom serializer.

```
def my_serializer(element):
    return 'Hello world!'

my_output = markdown.markdown('', serializer=my_serializer)
```

**Comment by facelessuser** [comment]
I imagine you could use a post-processor. Position it as the last step and output it to anything. Or you could just parse in the HTML after Python Markdown is done and serialize it any way you want. You definitely wouldn't want to serialize it mid-processing as almost no other plugin would be ready for your serialization.

**Comment by fgrie** [comment]
Parsing the HTML output would be a possibility too, but as I would parse it into a ElementTree again, just taking the internal one would be fine.
Post processing could just be skipped in case of a custom serializer, or even passed as a custom method list like the custom serializer itself.

**Comment by facelessuser** [comment]
I guess I'm not understanding yet how you plan on using it, but a custom serializer passed around internally throughout the processing steps is just not going to be feasible. A plugin can serialize content to anything they want as long as it serializes back to how Python Markdown accepts it. Also, after Python Markdown is done with processing and returns the HTML, you are also free to do whatever you want with it.

**Comment by waylan** [comment]
This is already possible, although, as it is not documented, it is subject to change. First, you need to add your "output_format" to the dict at `markdown.Markdown.output_formats`. The key should be a string name you assign and the value should be a pointer to your serializer function. Then, from an instance of the class, simply set the output_format to the name you assigned. Whether you add your output format through a subclass of `markdown.Markdown` or to an instance (perhaps through an extension) is up to you. If you use a subclass, then you can specify the `output_format` when you create an instance of the class. If you add it to an instance, then be sure to call the `set_output_format` method on the instance to tell it to use your serializer.

```
def my_serializer(element):
    # implement your serializer here

# instance
md = markdown.Markdown()
md.output_formats['myformat'] = my_serializer
md.set_output_format('myformat')
output = md.convert(input)

# subclass
class MyMarkdown(markdown.Markdown)
    output_formats =  {
        'html':   markdown.to_html_string,
        'xhtml':  markdown.to_xhtml_string,
        'myformat': my_serializer
    }
md = MyMarkdown(output_format='myformat')
output = md.convert(input)
```

That said, it would be more complicated than that, as the postprocessors (which all run after the serializer) all expect HTML and therefore they will all need to be replaced with ones which understand your non-HTML format.

**Comment by fgrie** [comment]
@facelessuser 
My application is to generate downloadable PDF from markdown, instead of HTML. Re-parsing the HTML back to an ElementTree would be possible, but if can skip the stop of generating HTML to immediately parse it again, why not? 
In [core.py:set_output_format](https://github.com/Python-Markdown/markdown/blob/7cff3bd5af4a3ebea608b9fc7c48327d67147db0/markdown/core.py#L203) I would just set up my custom serializer, passed to the application, and add the information that a custom one is used.
In [core.py:272](https://github.com/Python-Markdown/markdown/blob/7cff3bd5af4a3ebea608b9fc7c48327d67147db0/markdown/core.py#L272) I would just skip post processing if a custom serializer is used.

@waylan 
Exact this was the first solution I was thinking about, but as for me the effort is pretty much the same I could also contribute a standardized way to do this if wanted. For me it has the advantage of not relying on possible changing internals whilst possibly helping somebody with the same requirement in future.

**Comment by waylan** [comment]
This is the standardized way. There is no need to add another.

Regardless, I expect you will never get a complete working solution as the work to replace the postprocessors will not be worth the effort. The easiest and most efficient solution will be to parse the HTML output, not implement a custom serializer.
