### ISSUE TITLE
Text in codeblock beginning with '#' is still rendered in <h1> tags

### ISSUE THREAD

**Issue by Zeebrow** [Python-Markdown/markdown#1183]
## pip show markdown

Name: Markdown
Version: 3.3.4

# code: 
```
import markdown
import os

mdf = 'example.md'
htmlout = "md.html"

with open(mdf, 'r') as md:
    f = md.read()

try:
    os.remove(htmlout)
except FileNotFoundError:
    pass

with open(htmlout,'w+') as h:
    h.write(markdown.markdown(f))
```

# example.md input
````
# heading outside code block

```
# heading inside code block
#!/bin/bash
```
````
# md.html output
```
<h1>heading outside code block</h1>
<p>```</p>
<h1>heading inside code block</h1>
<h1>!/bin/bash</h1>
<p>```</p>
```

**Comment by facelessuser** [comment]
If you don't enable the [`fenced_code`](https://python-markdown.github.io/extensions/fenced_code_blocks/) extension or use something like [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/), then your fences aren't going to get turned into code blocks properly.

**Comment by Zeebrow** [comment]
Thank you! I should have read everything in `/docs`.
