### ISSUE TITLE
como fazer a implantação do markdown dentro do meu código?

### ISSUE THREAD

**Issue by verasdan** [Python-Markdown/markdown#1185]
como fazer a implantação do markdown dentro do meu código?

alguém sabe informar como faz pra utilizar?

se tiver algum tutorial já serve

**Comment by facelessuser** [comment]
Translated with google:

```
How to do markdown implantation within my code?

Does anyone know how to inform how to use it?

se tiver algum tutorial já serve
```

I would take a look at the documentation: https://python-markdown.github.io/reference/.
