### ISSUE TITLE
Show images alt using figures

### ISSUE THREAD

**Issue by marie-bnl** [Python-Markdown/markdown#1186]
Hi! It would be awesome to be able to have an extensions in the extras to show the images' alt as captions. 

I'd like

```md
![A very very cute cat](cat.jpg)
```

to be rendered as 

```html
<figure>
    <img src="cat.jpg" alt="A very very cute cat">
    <figcaption>A very very cute cat</figcaption>
</figure>
```

**Comment by facelessuser** [comment]
Python Markdown doesn't aim to provide every extension that people may want. It mainly provides core Markdown functionality, and yes, a few extra. Generally it is expected users will use the plugin system to extend it in ways that they want.

**Comment by marie-bnl** [comment]
Thanks for your answer!
