### ISSUE TITLE
pytest DeprecationWarning

### ISSUE THREAD

**Issue by gunlinux** [Python-Markdown/markdown#1191]
Got DeprecationWarning  on pytest  / Python 3.8.10 

```
tests/test_basics.py::test_empty_db
venv/lib/python3.8/site-packages/markdown/inlinepatterns.py:209: DeprecationWarning: Flags not at the start of the expression '^(.*?)(?i)\\b((?:(?:f' (truncated)
    self.compiled_re = re.compile(r"^(.*?)%s(.*)$" % pattern,

tests/test_basics.py::test_empty_db
venv/lib/python3.8/site-packages/markdown/inlinepatterns.py:209: DeprecationWarning: Flags not at the start of the expression '^(.*?)\\b(?i)([a-z0-9' (truncated)
    self.compiled_re = re.compile(r"^(.*?)%s(.*)$" % pattern,
```

**Comment by facelessuser** [comment]
This is generally a Python deprecation being exposed by pytest, but yeah, it should probably be addressed. Keeping the flags in the middle of the pattern doesn't enable insensitivity only after that point, so there is absolutely no benefit to keeping them where they are. In later versions, you can sort of scope groups with certain flags, but that is not what Python Markdown is doing here.

**Comment by facelessuser** [comment]
Since Python 3.6 is the lowest supported Python version, we can probably get around this by changing our patterns to scope these flags via `(?aiLmsux-imsx:...)` as this support was added in Py 3.6. We'd have to modify any inline patterns using flags, but that should future-proof us. External libs can update this on their own at any time.

I may experiment with this soon.

**Comment by facelessuser** [comment]
@gunlinux is this test running on an external lib? I'm not sure I'm finding such flags being used within Python Markdown. If so, this would be an error with external libs, and not us.

**Comment by gunlinux** [comment]
> @gunlinux is this test running on an external lib? I'm not sure I'm finding such flags being used within Python Markdown. If so, this would be an error with external libs, and not us.

Yeah, i disable one by one all related to Markdown extension and libs, seems it triggered by call from  
"from mdx_partial_gfm import PartialGithubFlavoredMarkdownExtension" whic

Sorry for wasted time
Gonna readdress issue to them
https://github.com/zopieux/py-gfm
