### ISSUE TITLE
Feature request: Use of image title as figure caption

### ISSUE THREAD

**Issue by NSchwirz** [Python-Markdown/markdown#1192]
Markdown is very useful for documentation. It is both structured enough to be rendered as styled document and simple enough to be human readable.

I would like to use the image titles as image captions. Due to security-reasons I do not want to include HTML myself.

There are some work-arounds like:
  * picture and caption in an table (disadvantage: no semantic meaning)
  * a single paragraph consisting only the picture and its emphased caption using css-magick (disadvantage: not interoperable and restricted to html-output)
  * including (potential harmful) HTML snippets (disadvantage: potential security problem)

Currently `![alt-text](image.png "title")` will be translated to something like `<img alt="alt-text" src="image.png" title="title">` and similar in other export formats.
I would like to suggest something like
```
<figure>
<img alt="alt-text" src="image.png"
<figcaption>title</figcaption>
</figure>
```
and similar for other export formats.

**Comment by facelessuser** [comment]
There are extensions to do this: https://github.com/funk1d/markdown-figcap. I'm not sure how well the one I linked works, but it is simply the first one I found when searching.

Should images automatically have `figcaption` defined? I think not. Images can be treated as inline elements. If a user defines it inline to show a small image in a paragraph, they may not want a `figcaption` (which is a block element) and will break up their content. I'd suggest using an extension and use its explicit syntax if desired. Or, if you just want to always have `figcaption` inserted, maybe write a simple extension to walk the HTML tree as a TreeProcessor and add the appropriate fig caption to images that present with a `title`.

**Comment by NSchwirz** [comment]
Thanks for the advice. I will take a look at the extension. Block elements are a point I did not take notice of.
I think I do not understand the sense of the image title yet. My idea was to take the image title as figure-caption if given.

**Comment by facelessuser** [comment]
> My idea was to take the image title as figure-caption if given.

You certainly could do that. I was more stating, from a general image handling perspective, it doesn't make sense to treat all images this way and force them to be figures as it cannot be known how a user wishes the images to be represented. But, for those who always want images to be represented as figures if a title is present (via an additional plugin) it may be fine as they would be knowingly installing the extension/plugin for that purpose.

**Comment by waylan** [comment]
This is the sort of thing that should be implemented as a third party extension. We will not be adding this to Markdown directly. Therefore, I am closing this.
