### ISSUE TITLE
The second comment in a code sections is treated as a heading

### ISSUE THREAD

**Issue by laynr** [Python-Markdown/markdown#1201]
When using two commented lines (#) in a string, the second comment in a code sections is treated as a heading.  For example:

```
import markdown
mark2html = markdown.Markdown()
mark2html.convert('```#first comment\nprint("hello world")\n#second comment```')
```
Results unexpectedly in:
`u'<p>```#first comment\nprint("hello world")</p>\n<h1>second comment```</h1>'`

however the following does work:
`mark2html.convert('```#first comment\nprint("hello world")\nsecond comment```')`

it results in what is expected:
`u'<p><code>#first comment\nprint("hello world")\nsecond comment</code></p>'`

The only difference between the strings in a second "#" character.  

Is there a work around?

**Comment by facelessuser** [comment]
It doesn't appear you've enabled any kind of fenced code extension. You can use the [built-in one](https://python-markdown.github.io/extensions/fenced_code_blocks/) which is limited to document root level, or you can use [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) which can be nested under lists, etc.

In short, the Markdown spec, as originally outlined, does not include fenced code. But yes, they've become pretty ubiquitous these days, and some parsers provide them out of the box, but Python Markdown requires you to enable an extension.

**Comment by laynr** [comment]
Thank you!
mark2html = markdown.Markdown(extensions=['fenced_code']))
Worked for my real strings based on GitHub Flavored Markdown.
