### ISSUE TITLE
Convert mardown to HTML without wrapping it in a <p> tag

### ISSUE THREAD

**Issue by pawamoy** [Python-Markdown/markdown#1207]
Is this possible without manually removing `<p>` and `</p>` at the beginning and end of the converted string?
My use-case is the following: in a Jinja template, I want to render an admonition (details + class + summary).
But when converting the title to HTML (because it could contain `*emphasis*` or `**strong**` Markup), it ends up being wrapped in a paragraph, which breaks the display of the admonition.

```jinja
      <details class="{{ admonition.kind }}">
        <summary>{{ admonition.title|convert_markdown() }}</summary>  {# how to remove <p></p>? #}
        {{ admonition.contents|convert_markdown() }}
      </details>
```

The `convert_markdown` filter basically does this:

```python
return Markup(self._md.convert(text))
```

...where `self._md` is an instance of `Markdown`.

**Comment by facelessuser** [comment]
Running Markdown on a snippet of text without the context of the entire page is going to yield you content wrapped in a paragraph or some other block element.  There isn't a single Markdown parser that does any different: https://johnmacfarlane.net/babelmark2/?text=**strong**+*underline*.

**Comment by waylan** [comment]
This is out-of-scope for the reasons stated by @facelessuser. I suppose you could create an extension which does this, but I suspect an inline-only parser might be a better solution. That said, I have no idea if such a tool already exists. Personally, I would simply retrieve the HTML output and then extract the content of the `<p>` tag and use that.

**Comment by pawamoy** [comment]
Fair enough, I guess I can strip the `p` tag manually since I know there's only one such paragraph :slightly_smiling_face: 
Thanks for your answers!
