### ISSUE TITLE
Can't get admonition to work with mkdocs

### ISSUE THREAD

**Issue by EqualAPriori** [Python-Markdown/markdown#1211]
Hi all, I'm using `Markdown 3.3.6` and for some reason I can't get admonitions to work when I include `-admonition` in the plugins section of my `mkdocs.yml`.

I keep on getting this output: 
> Config value: 'plugins'. Error: The "admonition" plugin is not installed

I'm a bit confused because I thought admonitions ship with Markdown 3.3.6. Thanks in advance, I'm probably missing something obvious.

--- details:
My full mkdocs.yml:
``` md
site_name: mystic
theme:
  name: material
plugins:
  - admonition
nav:
    - "Home": index.md
```

`pip freeze` shows: `Markdown==3.3.6`

**Comment by facelessuser** [comment]
1. This sounds like a Mkdocs question not a Python Markdown question as most likely this is a user error when specifying the extension. As I use both MkDocs and Python Markdown in my own documentation, I am guessing this is likely a user error as I have experienced no issues with Admonitions in Mkdocs.
2. Without posting an actual config, it is difficult to guess what you are doing correctly.

I would take a look at the mkdocs config this project uses to see how we specify admonitions: https://github.com/Python-Markdown/markdown/blob/master/mkdocs.yml#L57.

If you are still having issues, I would ask this over at MkDocs, and when you do, I would post the actual configuration you are using so people can spot any potential user errors.

**Comment by EqualAPriori** [comment]
Ah thanks for the link! I found my user error with your link, closing this thread now.
