### ISSUE TITLE
RTL Text Direction

### ISSUE THREAD

**Issue by liyanboy74** [Python-Markdown/markdown#1214]
How can add RTL (text direction) for generated HTML for languages that must be RTL, such as Arabic and Persian?
For example:
```
<h3 dir="rtl">سلام، حال شما خوب است؟</h3>
```
<h3 dir="rtl">سلام، حال شما خوب است؟</h3>
I can't add style for h<br>
As you can see, github respects this!

**Comment by waylan** [comment]
> As you can see, github respects this!

So do we.

```
>>> markdown.markdown('<h3 dir="rtl">سلام، حال شما خوب است؟</h3>')
'<h3 dir="rtl">سلام، حال شما خوب است؟</h3>'
```

Is there a question or an issue here?

**Comment by liyanboy74** [comment]
It works, but i think this is more like `HTML` than `Markdown`!
I use this tool to prevent writing `HTML` , did I get something wrong?
Is it possible to choose the correct language direction based on the language of the first character of each paragraph that a person enters? (like Github,Instagram & ...)

Another example :
I just write سلام

سلام

**Comment by facelessuser** [comment]
Assuming you have the [`attr_list` extension](https://python-markdown.github.io/extensions/attr_list/) enabled, you can do the following:

```markdown
# سلام، حال شما خوب است؟ { dir='rtl' }
```

**Comment by waylan** [comment]
> Is it possible to choose the correct language direction based on the language of the first character of each paragraph that a person enters?

That is outside the scope of Markdown. As an example, note that Github documents how they process markup at [github/markup][1]. The Markdown is rendered to HTML in step 1. However, identifying and labeling elements as RTL most likely happens in step 4, outside of the Markdown parser.

There may very well be an existing Python library which does this. If not, then that could make for a very useful project for someone to take on. However, it needs to be developed separately from the Markdown parser itself.

[1]: [github/markup](https://github.com/github/markup#github-markup)
