### ISSUE TITLE
Invalid form

### ISSUE THREAD

**Issue by zhenzi0322** [Python-Markdown/markdown#1221]
```
| demo  |  demo |

| ------------ | ------------ |

| 111  |  222 |

| 333  | 555  |
```
to
```
<p>| demo  |  demo |</p>
<p>| ------------ | ------------ |</p>
<p>| 111  |  222 |</p>
<p>| 333  | 555  |</p>
```

**Comment by facelessuser** [comment]
Did you enable the`tables` extension?

**Comment by zhenzi0322** [comment]
> Did you enable the`tables` extension?

Enabled

**Comment by facelessuser** [comment]
Looking closer at your example, are you placing empty lines between all the rows? If so, that is not allowed.

**Comment by zhenzi0322** [comment]
ok

**Comment by facelessuser** [comment]
As this seems to have been due to incorrect use, I'm closing the issue.
