### ISSUE TITLE
Bug: Sublists are not rendered correctly

### ISSUE THREAD

**Issue by Heiko-san** [Python-Markdown/markdown#1229]
Imagine the following list:

```
* a
  * b
  * c
* d
```
Which markdown renders as:

* a
  * b
  * c
* d

However the markdown python module seems to render it as a flat list:

* a
* b
* c
* d

This is no matter if I use the plugin sane_lists or not ...

``` python
#!/usr/bin/env python
import markdown as md

markdown = """
# list

* a
  * b
  * c
* d

"""

_MD_EXTENTIONS = [
    'tables',
    #'sane_lists',
]
html = md.markdown(markdown, extensions=_MD_EXTENTIONS)
print(html)
```

```
<h1>list</h1>
<ul>
<li>a</li>
<li>b</li>
<li>c</li>
<li>d</li>
</ul>
```

I'm using Ubtunu 20.04
```
python --version
Python 3.8.10
```
```
pip freeze
importlib-metadata==4.11.2
Markdown==3.3.6
pkg_resources==0.0.0
zipp==3.7.0
```

**Comment by facelessuser** [comment]
You need to indent sublists four space.

**Comment by Heiko-san** [comment]
Ok, thanks, that helped. :)

I'd still consider this a bug, however.
The "solution" seems more like a workaround to me.

**Comment by facelessuser** [comment]
As far as Python Markdown is concerned, this is not a bug. I'll link you to the maintainer's official response: https://github.com/Python-Markdown/markdown/issues/1204#issuecomment-992499686.

Keep in mind that Python Markdown is an old-school parser, and is not a CommonMark parser. This behavior is unlikely to change.

**Comment by Heiko-san** [comment]
I see.
Thanks again. :)
Well I think I can live with that solution. ;)
