### ISSUE TITLE
`markdown_py` built with python3 doesn't work with Unicode well

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#123]
Hi!

I've cloned the Git repository, ran `sudo python3 setup.py install` and it installed `markdown_py` script into `/usr/local/bin/`.

However, when I run it, type this russian text (`текст по-**русски**`), press `Return` and then `Ctrl+D`, I get this exception:

```
dmitry@eeepc:~/tests/Python-Markdown$ /usr/local/bin/markdown_py
Текст по-**русски**
Traceback (most recent call last):
  File "/usr/local/bin/markdown_py", line 34, in <module>
    run()
  File "/usr/local/lib/python3.2/dist-packages/markdown/__main__.py", line 81, in run
    markdown.markdownFromFile(**options)
  File "/usr/local/lib/python3.2/dist-packages/markdown/__init__.py", line 435, in markdownFromFile
    kwargs.get('encoding', None))
  File "/usr/local/lib/python3.2/dist-packages/markdown/__init__.py", line 353, in convertFile
    text = sys.stdin.read()
  File "/usr/lib/python3.2/codecs.py", line 300, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
```

Note that without emphasis on "русски" word, everything works well.

I use Debian sid and Python 3.2.3.

**Comment by waylan** [comment]
Hmm, I can't seem to reproduce this. Although, there has been some recent changes to that part of the code (since last release). Can you update to the latest code here in Github, try again, and report back?  Thanks.

**Comment by waylan** [comment]
Also, while your testing, I'm just curious it you get different behavior if you pipe the input in - rather than inputting it directly on the command line). For example, add your example text to a text document (foo.txt) and then do this:

```
$ cat foo.txt | /usr/local/bin/markdown_py
```

If that works, but the other doesn't, then I suspect it may be a configuration problem with your command line environment - not a problem with markdown.

**Comment by mitya57** [comment]
I still experience this problem with the latest Git snapshot.

> `$ cat foo.txt | /usr/local/bin/markdown_py`

That works fine, so it seems it's my local problem. Also, when I run `perl` and type that line, I get:

```
Unrecognized character \xD0; marked by <-- HERE after <-- HERE near column 1 at - line 1.
```
