### ISSUE TITLE
[Feature request] Render html body (partial) only?

### ISSUE THREAD

**Issue by rbosch** [Python-Markdown/markdown#1232]
Hi,

Couldn't find an option to render the body content only, basically a partial. Which would be extremely handy to inject in existing page.

**Comment by mitya57** [comment]
Python-Markdown always renders *only* HTML body, i.e. the inner part of `<body>` tag. It is responsibility of the application to add the wrapping part.

**Comment by rbosch** [comment]
Oh, damn. Sorry, i was checking my browser. Assumed it rendered all of it.
Thanks!
