### ISSUE TITLE
Spaces added after markdown tokens and links

### ISSUE THREAD

**Issue by masasin** [Python-Markdown/markdown#1237]
Hello,

If I write something like this:

`_italic_, *bold*, and [a link](https://github.com).`

I get spaces in the final output:

> _italic_ , *bold* , and [a link](https://www.github.com) .

I would expect:

> _italic_, *bold*, and [a link](https://github.com).

It looks like the html tags are on their separate lines whenever we have a markdown token, and I'm wondering if there's a way to change that behaviour.

**Comment by facelessuser** [comment]
I'm not seeing any spaces, maybe it has to do with your HTML styling adding padding or margins:

```py
>>> import markdown
>>> markdown.__version__
'3.3.6'
>>> markdown.markdown('_italic_, *bold*, and [a link](https://github.com).')
'<p><em>italic</em>, <em>bold</em>, and <a href="https://github.com">a link</a>.</p>'
```

**Comment by masasin** [comment]
You were right. It was caused by bs4.prettify(). I'll close this issue.
