### ISSUE TITLE
Unescape characters on markdeep diagrams

### ISSUE THREAD

**Issue by ipocentro87** [Python-Markdown/markdown#1239]
Hi everyone, I am writing a markdeep extension for python-markdown in order to be able to draw diagrams with markdeep support.
However, I had some issues in rendering arrows, since they are escaped. This is the result of an arrow described in markdeep.
```
<markdeep><diagram>
-------&gt;
</diagram></markdeep>
```
Which is not properly handled when the page is loaded. Do you know how I can disable escaping in this scenario?

Thank you very much in advance!

**Comment by ipocentro87** [comment]
I managed to make it work in a dirty way: I include the diagram in a HTML comment, and then I decomment right before printing the html. This prevents the parser to substitute > and other markdown tags (like emphasis, italic, etc.):
```
<markdeep><diagram>
<!-- MARKDEEP_DIAGRAM
--------->
MARKDEEP_DIAGRAM --> 
</diagram></markdeep>
```
Again, it's a bit dirty but makes the job. Is there any better idea?

**Comment by waylan** [comment]
Sorry but I'm not familiar with Markdeep and I'm not sure I understand what you are trying to do. What is the raw Markdown source you are trying to parse? How is it being parsed incorrectly? And what would you like to happen instead?

**Comment by waylan** [comment]
I'm closing this due to the lack of information. If the requested information is provided, we can consider reopening this issue.
