### ISSUE TITLE
Code-block mis-formatted as table

### ISSUE THREAD

**Issue by eworm-de** [Python-Markdown/markdown#1249]
My markdown file contains a block, indented by four spaces:

```
    #!rsc by RouterOS
```

Even Github formats it correctly here in the issue:

    #!rsc by RouterOS

However this markdown implementation in python (used by [cgit](https://git.zx2c4.com/cgit/about/) for markdown formatting) does crazy things and generates a table:

![Screenshot_2022-05-05_09-13-29](https://user-images.githubusercontent.com/970853/166877409-b7a121f4-21fe-47f6-94ff-67190dc2b66f.png)

The original issue can be seen in my repository `routeros-scripts`. First link (cgit) looks strange, second link (Github) is ok.

https://git.eworm.de/cgit/routeros-scripts/about/#installing-custom-scripts-modules
https://github.com/eworm-de/routeros-scripts#installing-custom-scripts--modules=

**Comment by eworm-de** [comment]
Looks like this is caused by `markdown.extensions.codehilite`, which is enabled in cgit's script [md2html](https://git.zx2c4.com/cgit/tree/filters/html-converters/md2html#n298).

**Comment by eworm-de** [comment]
And a minimal reproducer:
```
% echo '    #!rsc by RouterOS' | python -m markdown
<pre><code>#!rsc by RouterOS
</code></pre>
% echo '    #!rsc by RouterOS' | python -m markdown -x codehilite
<div class="codehilite"><table class="codehilitetable"><tr><td class="linenos"><div class="linenodiv"><pre><span class="normal">1</span></pre></div></td><td class="code"><div><pre><span></span><code>
</code></pre></div></td></tr></table></div>
```

**Comment by eworm-de** [comment]
Modified the markdown in my repository to work around the issue...
So do not follow the links but see the reproducer.

Wondering if this can be changed at all... It kind of aligns with the documentation:
https://python-markdown.github.io/extensions/code_hilite/#shebang-no-path

**Comment by waylan** [comment]
> It kind of aligns with the documentation:
> https://python-markdown.github.io/extensions/code_hilite/#shebang-no-path

This is exactly what is causing the issue. So long as you have that feature enabled, a shebang line on the first line of the code block will be interpreted as identifying the language of the block. You have three options:

1. Turn off that feature. As there is no switch within the extension to disable this part only, you will need to not use the extension at all. Probably not the solution you want.
2. Define the language in a line above the first line.

    ```
    :::
    #!rsc by RouterOS
    ```

    In the above example, I used the [colons][0] syntax and left the language name blank. In the output, the colons will be removed and the rest of the block will be preserved.

3. Enable and use the [Fenced Code Blocks extension][1], which defined the language of a block separately from the code itself.

    ````
    ```
    #!rsc by RouterOS
    ```
    ````

Note that shebang lines were chosen as a way to identify the language of a block as they are commonly found on the first line of scripts. Of course, true shebang lines always include a path component (which includes a slash). Therefore, true shebang lines are preserved (not removed). However, it was also recognized that some users might want to define a language for a block which does not have a shebang line. Therefore, we added support for pseudo shebang lines of two varieties (shebang without a path and colons). However, as the shebang line is not part of the code it is removed from the output. In over a decade of supporting this syntax, this is the first time someone has ever reported a conflict with this syntax. Therefore, we will not be making any changes to the behavior of the extension. If it really bothers you, you are free to fork the extension (under the limitations of the license) and modify your fork as you see fit.

[0]: https://python-markdown.github.io/extensions/code_hilite/#colons
[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/

**Comment by eworm-de** [comment]
Thanks a lot for the detailed clarification!
All given solutions have any kind of drawback, so not using these. Now that the rationale is known I will just keep my markup "workaround".
Thanks again and keep up the good work!
