### ISSUE TITLE
Wrong sublist parsing

### ISSUE THREAD

**Issue by Scorpil** [Python-Markdown/markdown#125]
Python-Markdown is not supporting subsists in the way that Mardown.pl does.

For example, if we have this markdown input:

```
 * List
   * Sublist
      * Subsublist
 * List again
 * List once more
```

We have different outputs. Python version:

```
$ markdown_py input 
<ul>
<li>List</li>
<li>Sublist<ul>
<li>Subsublist</li>
</ul>
</li>
<li>List again</li>
<li>List once more</li>
</ul>
```

And Markdown.pl creates this code:

```
$ perl Markdown.pl input 
<ul>
<li>List
<ul>
<li>Sublist
<ul>
<li>Subsublist</li>
</ul></li>
</ul></li>
<li>List again</li>
<li>List once more</li>
</ul>
```

For me this is kind of important issue - i use sublists a lot. I'll try to write some code to change this behavior once i have more spare time.

**Comment by waylan** [comment]
This is a known difference and a request that has been rejected many times in the past. Python-Markdown consistently requires 4 spaces of indent per level or it ignores the indent (markdown.pl does this in some cases not in others) If you want a different amount of indent, then set the the desired amount with the [tab_length](http://packages.python.org/Markdown/reference.html#tab_length) keyword. Of course, this will consistently change the indent for the entire document.

Alternatively, you can always use the [Extension API](http://packages.python.org/Markdown/extensions/api.html) to write your own extension which implements whatever behavior you want.

Personally, I have no interest in implementing what I consider to be a bug and incomprehensible inconsistency in markdown.pl.
