### ISSUE TITLE
[codehilite] Please add support for GitHub-style language definition

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#126]
Forwarded from: http://sourceforge.net/p/retext/tickets/49/

GitHub supports defining source code language after opening backtick block:

``````
```ruby
class Post
  include Mongoid::Document
  field :title
end
```
``````

Please add support for that to `codehilite` or `github-flavored` extension.

**Comment by waylan** [comment]
This is already possible through the fenced_code extension which will work with codehilite if both extensions are loaded.
