### ISSUE TITLE
PrettifyTreeprocessor AttributeError

### ISSUE THREAD

**Issue by fourpoints** [Python-Markdown/markdown#1261]
This code section near the bottom of `markdown.treeprocessors` raises `AttributeError` if `pre[0].text` is `None`.

```py
# Clean up extra empty lines at end of code blocks.
pres = root.iter('pre')
for pre in pres:
    if len(pre) and pre[0].tag == 'code':
        pre[0].text = util.AtomicString(pre[0].text.rstrip() + '\n')
```

The check should be `if len(pre) and pre[0].tag == 'code' and pre[0].text is not None` or `isinstance(pre[0].text, str)`, but that may be too strict.

---

I encountered this with a custom  Block/Inline processor. The band-aid fix was just to ensure these elements had text.

```py
for pre in root.iter("pre"):
    if pre[0].text is None:
        pre[0].text = ""
```

**Comment by waylan** [comment]
Based on the information you provided, I don't understand how that results in an error. All we are doing is resigning `pre[0].text` to a new value, which is exactly the same thing you are doing in your band-aid. Could you please point to where this code is so I can better understand it in context?

**Comment by waylan** [comment]
Oh, I got it. `pre[0].text.rstrip()` raises an error if `pre[0].text` is `None`.

I believe this has not been an issue thus far as internally we always assign a string value to the `text` attribute of an element. The question is: do we want to require all extensions to do the same or not? If not, then we should apply the suggested fix. If so, then we can leave it alone.

Finally, the relevant code is [here](https://github.com/Python-Markdown/markdown/blob/cebe1de23631a300167445bbb152c31615de9faf/markdown/treeprocessors.py#L432-L436) for future reference.

**Comment by fourpoints** [comment]
By default `ET.Element(tag).text` is `None`. But you could add a requirement that it is a string. Thanks for linking to the code.

**Comment by waylan** [comment]
I was curious how the serializer handles a `None` value so I checked the code:

https://github.com/Python-Markdown/markdown/blob/a2e4788f8d1850f59699ce0ab500688031ea1571/markdown/serializers.py#L160-L168

When `text` is `None` , `if text` evaluates to `False ` and the serializer simply skips writing out the text content and moves on to child elements (if any) and the closing tag. It makes sense for an element with `text` of `None` to simply be empty (no different that `text` being an empty string). Therefore, there is no reason to require an element's `text` attribute to be of type `str`.

Finally, the question remains whether the prettifier needs to take any action on an empty code block. In other words, do we want

```html
<pre><code></code></pre>
```

or 

```html
<pre><code>
</code></pre>
```

If the former, then the suggested fix will work fine. If the latter, then we need a slightly more sophisticated fix. Checking Balemark (compare [this][1] with [this][2]) is looks like the first option is acceptable.

Given the above, a PR is welcome adding `and pre[0].text is not None` to the check. 

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60%0A%60%60%60
[2]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60%0A%0A%60%60%60

**Comment by fourpoints** [comment]
Thanks, I'll make a PR later :)

**Comment by fourpoints** [comment]
Thanks for your help! :+1: 

Minor note, this also affects non-empty blocks, i.e. blocks with children but no text, such as `<pre><code><span>x</span></code></pre>`. But I don't think that changes anything here.
