### ISSUE TITLE
Wikilink extension doesn't recognise links with ampersands in them

### ISSUE THREAD

**Issue by tw0shoes** [Python-Markdown/markdown#1268]
If we could change this line:
WIKILINK_RE = r'\[\[([\w0-9_ -]+)\]\]'

to
WIKILINK_RE = r'\[\[([\w0-9_ -&]+)\]\]'

that would fix the issue. 

Thanks for everything.

**Comment by waylan** [comment]
As [previously stated][1]:

> If I make any changes to this extension is would be to remove it from being included with Markdown. It only remains as it is very old. I suspect a better approach for you would be to either fork it or create your own new extension which offers the behavior you desire.

In fact, you may find a third-party extension which already offers a solution.

[1]: https://github.com/Python-Markdown/markdown/issues/875#issuecomment-550041366

**Comment by tw0shoes** [comment]
Sorry, I did look for it, just didn't see that. 
Thanks! Sorry for the time-waster.
