### ISSUE TITLE
Nonexistent extensions pass silently

### ISSUE THREAD

**Issue by nh2** [Python-Markdown/markdown#128]
When you use an extension that doesn't exist for whatever reason (for example, for me `fenced_code` cannot be found), `registerExtensions` just silently ignores that and your output is messed up.

Shouldn't `markdown.markdown(contents, ['adsf'])` throw an error or at least show a warning?

For this, the following code

``` python
        for ext in extensions:
            if isinstance(ext, basestring):
                ext = self.build_extension(ext, configs.get(ext, []))
            if isinstance(ext, Extension):
                # might raise NotImplementedError, but that's the extension author's problem
                ext.extendMarkdown(self, globals())
            elif ext is not None:
                raise ValueError('Extension "%s.%s" must be of type: "markdown.Extension".' \
                    % (ext.__class__.__module__, ext.__class__.__name__))
```

should accomodate for ext being `None`.

**Comment by nh2** [comment]
I just found that `build_extension` internally **does** do a `logger.warn("Failed loading extension ...")`, but that was not printed in my application, as apparently, it does not initialize any logging system. A `logging.basicConfig()` made the problem apparent.

**Comment by nh2** [comment]
So the only question is: Is a logging warning strong enough for a missing extension that the user wanted to use?

**Comment by waylan** [comment]
This is a duplicate of #105 and #112 which have been fixed in the latest source in the repo. The changes will be available in the next release or pull from git if you need them now.

**Comment by nh2** [comment]
Nice!
