### ISSUE TITLE
Can't add spaces at end of text

### ISSUE THREAD

**Issue by TheLostProgrammer** [Python-Markdown/markdown#1283]
I want to add a space at the end of some sentences as I am using this for a website with the specific requirement.

However, I can't due to the markdown removing any trailing spaces by stripping the text. I am wondering if there is a way to prevent this? Is there any extensions of such that can allow this?

**Comment by waylan** [comment]
There is no reason to support this in Markdown as Browsers condense multiple whitespace characters in HTML into a single space anyway. However, in HTML you can work around this by using non-breaking spaces. As Markdown accepts raw HTML, you can do the same within Markdown.

Specifically, use the HTML entity (`&nbsp;`). However, to save on typing, you only need every other space to be non-breaking. Therefore, to add four spaces to the end of a paragraph, try this:

```
A Markdown paragraph. &nbsp; &nbsp;
```
