### ISSUE TITLE
crash under Win64: no attribute 'exec_module'

### ISSUE THREAD

**Issue by Alexey-T** [Python-Markdown/markdown#1286]
CudaText plugin, code is here
https://github.com/CudaText-addons/cuda_markdown_preview

crashes on Win64,
https://github.com/Alexey-T/CudaText/issues/4293

![ccc](https://user-images.githubusercontent.com/4154978/185810840-94448b50-6436-4ef8-95d2-4a72171c9a88.png)

**Comment by Alexey-T** [comment]
on Win64 CudaText ships with Python 3.8 (old was 3.6).

**Comment by veksha** [comment]
1. https://bugs.python.org/issue42131 (i don't know if it is related)

2. also found the following solution:
"downgrade markdown module"
```
pip install markdown==3.2.2
```
(didn't try it)

3. some opened issue on Markdown bug-tracker https://github.com/Python-Markdown/markdown/issues/1132

**Comment by Alexey-T** [comment]
I don't like 'downgrade' way, better I wait until it's fixed.

**Comment by waylan** [comment]
This is a duplicate of #1132.

**Comment by waylan** [comment]
As I note in #1132, this has been fixed in Python 3.10. Upgrading should fix the issue.

**Comment by Alexey-T** [comment]
users of CudaText have Python 3.8 preinstalled.

**Comment by waylan** [comment]
Unfortunately, I am not aware of any workarounds. The issue is in Python's zipimport library, not with our code. If CudaText is using zipimport then they need to support Python 3.10 (or backport zipimport from Python 3.10) to have a properly working implementation.

**Comment by Alexey-T** [comment]
after user upgraded to Python 3.10 DLLs, he sees new error:

![er](https://user-images.githubusercontent.com/4154978/187045939-a3a1e90b-b0ed-4748-8ef7-64b907fc0c4f.png)

@veksha 

>    also found the following solution:     "downgrade markdown module" pip install markdown==3.2.2

do you know where do get 3.2.2 version? I cannot find it on https://pypi.org/project/Markdown/#files

**Comment by facelessuser** [comment]
Yup the trace explains that the `gfm` extension (which is not our code) is trying to access `markdown.util.etree` which is no longer provided. So `gfm` will have to update its code to not access `markdown.util.etree` and instead use:

```python
import xml.etree.ElementTree as etree
```
