### ISSUE TITLE
Lightweight enough for a microcontroller running MicroPython?

### ISSUE THREAD

**Issue by sgbaird** [Python-Markdown/markdown#1287]
I am looking for a solution to use markdown files with [microdot](https://github.com/gigya/microdot) and an RPi Pico W running MicroPython. I also came across [udownmark](https://github.com/pfalcon/udownmark).

**Comment by facelessuser** [comment]
I don't know if Python Markdown will work in MicroPython. Micro Python is so stripped down that many of the built-in libraries that are required may not be available.

We do not actively test MicroPython either, so you'd have to experiment to see, though I would be surprised if you _didn't_ run into issues.

**Comment by sgbaird** [comment]
@facelessuser thanks! I may have misunderstood `upip` (thinking I could do `import upip; upip.install("markdown")`. Will probably try out udownmark for now and come back to this if it doesn't meet the needs. Thanks for the quick reply!

**Comment by facelessuser** [comment]
Yeah, I have limited experience with micropython. I've dealt with it occasionally on embedded devices here and there, but in every case, I found it very stripped down to the basic syntax with most standard lib stuff not present. I don't know if that is true in all cases though.
