### ISSUE TITLE
My...boss...in...best...allah...👈🤲👉⚖️💯

### ISSUE THREAD

**Issue by PrinceSagor** [Python-Markdown/markdown#1292]
ক্রাইম এর বিরুদ্ধে আমার এই যুদ্ধ আমার পাশে থাকবেন স্বয়ং আল্লাহ তাআলা সত্যের জয় হবে ইনশাআল্লাহ সত্য কে দাবিয়ে রাখতে পারবেন কিন্তু একদিন আল্লাহতাআলা তা প্রকাশ করে দিবেন 

রেপ করলে ওপেন ফাঁসি এরকম ধরনের একটি আইন চালু হলে কেউ রেপ করার আগে দশবার ভাববে 

আজকে আমাদের আইন দুর্বল বলে 
মানুষ এরকম ধরনের ঘৃণ্য কাজ করার সাহস পায় 
সঠিক শক্তিশালী আইন হলে সমাজ থেকে অনেক বেশি ক্রাইম কমে যাবে

 কিন্তু সঠিক আইন করলে শয়তানদের সাহস কমে যাবে

কিন্তু কে সঠিক আইন করবে সবাইতো টাকার জন্য সমাজকে নষ্ট করে দিতে চায়  

সবাই একসাথে মিলে সঠিক আইন চালু করে দিলে মুখোশধারী শয়তান দের রাজত্ব ভেঙেচুরে যাবে 

এখনকার দুনিয়ায় সঠিক বিচার হয় কম কারণ টাকা দিয়ে বিচারের রায় বদলে ফেলা যায় 

কেউ সঠিকভাবে প্রতিবাদ করতে চায় না কারণ তাদের কি কোনো মানুষ বিপদে পড়লে অনেক মানুষই তাদের থেকে  পিছিয়ে যায় 

সবাই মিলে প্রতিবাদ করলে সমাজে ক্রাইম হবে বলে আমার মনে হয় না কিন্তু কেএ করবে সবাই তো টাকা পেলে নিজের চরিত্রটা কেউ বিক্রি করে দিবে 
  
অন্যায়ের বিরুদ্ধে হাতে হাত রেখে প্রতিবাদ করলে কেউ প্রাইম করার আগে তার মাথায় এটা কাজ করবে যে এখন ক্রাইম করলে সবাই একসাথে প্রতিবাদ করবে 

সমাজে কেউ ক্রাইম করলে সবাই একসাথে প্রতিবাদ করা উচিত বলে আমি মনে করি 

কেউ কারো বিপদে পাশে থাকে না তার জন্যই অনেক সময় অপরাধীরা ক্রাইম করেও সঠিক সাজা ভোগ করে না তার জন্য তাদের সাহস আরো বেড়ে যায় 

আমি যদি কিছু ভুল বলে থাকি তাহলে আমাকে ক্ষমা করে দিবেন 

হে আল্লাহ তাআলা সবাইকে সঠিক হেদায়েত দান করুন  

ইসলামিক আইন দিয়ে দুনিয়াটাকে সাজিয়ে নেওয়ার তৌফিক দান করুন 

ইসলাম অনেক কঠিন ধর্ম কিন্তু এই পথে অনেক শান্তি লুকিয়ে আছে এই পথেই আমাদের জান্নাত

 কিন্তু শয়তানের কাজে লিপ্ত হয়ে পড়েছি তার জন্যই আমাদের প্রতি আল্লাহতালা এত আজাব-গজব দিচ্ছেন পৃথিবীতে 

মানুষেরা আসল শান্তি কিতা ভুলে গেছে এখন মানুষ মনে করে টাকা হলেই শান্তি কিন্তু একবার ভেবে দেখুন টাকা বারলেই তার সাথে অশান্তি ও বেড়ে যায় 

কারণ টাকা ইনকাম করতে হলেই নিজের সময়টাকে অন্যের কাছে বিক্রি করে দিতে হয় 

যে মালিক আমাদের সৃষ্টি করেছেন তার জন্য সময় বের করতে গেলে কিছু খারাপ মানুষদের হাতে অনেক কথা শুনতে হয় 

কারণ আমাদের মাথাটা তো আমরা বিক্রি করে দিয়েছি টাকার কাছে তার জন্যই কিছু অসৎ মানুষ রাজত্ব করে চলেছে আমাদের পৃথিবীতে 

সবাই এক হয়ে প্রতিবাদ করলে শয়তানের রাজত্ব গুলোকে আমরা ভেঙ্গে দিতে পারব 
কিন্তু তার জন্য সবাইকে একত্র হতে হবে কতদিন অন্যায়-অত্যাচার সইবো আমরা পৃথিবীতে কখনো কি আমাদের চোখ খুলবে আমরা কি সঠিক বিবেক দিয়ে বিবেচনা করতে পারব 

কেউ যদি করতে পারে তাহলে কি আমরা সকলেই একসাথে হাতে হাত রেখে প্রতিবাদ গড়ে তুলব নাকি অন্যায়ের বিরুদ্ধে মাথা নিচু করবো 

শয়তানি কি আমাদের উপরে রাজত্ব করবে আর আমরা কি মুখ বুঝে তা চুপ করে সইবো 

আমিতো পারিনা তাহলে আপনারা কি করে সইতে পারেন আমাদের বিবেক টাকে লাড়া দিতে হবে 

আজকাল টাকা হলে তো মানুষ বিবেচনা করতে ভুলে যায় এই কারণেই আমরা সঠিক তাকে চোখে দেখেও না দেখার ভান করে চলে যাই

টাকার রাজত্বকে ভেঙ্গে   আসুন আমরা সকলে বিবেক দিয়ে বিবেচনা করতে শুরু করে দেই

তাহলে সবকিছু ঠিক হয়ে যাবে সমাজে সুখ শান্তি ফিরে আসবে বলে আমার মনে হয়  

হাতে হাত রাখুন পতিটা জীবনকে সুরক্ষিত রাখুন আজকের সমাজে সঠিক শিক্ষা নেই যেটা আছে সেটাও হলো টাকার রাজত্ব কারণ কিছু অসৎ মানুষই সমাজের রাজ করে যায় 

আর মানুষ তা গাধার মত মুখ বুজে সহ্য করে যায় কারণ তারা সঠিক বিবেচনা করতে পারেনা আমি তো একা সব ঠিক করতে পারব না আমার সাথে হাতে হাত রেখে প্রতিবাদ করতে হবে 

তাহলে আমি সব ঠিকঠাকভাবে বিবেচনা করে তুলতে পারব তখন আর শয়তান রাজত্ব করতে পারবে না টাকাই হলো অসৎ মানুষের শক্তি 

 এইটাকে একবার ভেঙ্গে দিতে পারলেই মানুষেরা তাদের সময়টাকে সঠিক কাজে লাগাতে পারবে তাই বলব বেশি বেশি নামাজ আদায় করুন মানুষকে নামাজের পথে দাওয়াত দিন 

আর সময় পেলে আল্লাহর কাছে একটি দোয়া  বেশি বেশি  করবেন তাহলো জেরও যালিমদের হাত থেকে রক্ষা করুন সঠিক শিক্ষা দান করুন আপনি ছাড়া আমাদের কেউ রক্ষা করতে পারবে না 

আমরা অনেক বেশি গুনা করে ফেলেছি তাই আজকে আপনি আমাদের প্রতি নারাজ  আমরা তো আপনার বান্দা আপনি হলেন আমাদের রব আপনি ক্ষমা না করলে কে আমাদের ক্ষমা করবে 

আমরা অনেক বেশি গুনা করে ফেলেছি যে কারণে পৃথিবীতে এত আজাব গজব চলে এসেছে তার থেকে আমাদের রক্ষা করুন 

সঠিক পথে চলার তৌফিক দান করুন এবং আপনার ইবাদতে লিপ্ত রাখুন এবং আপনার কুদরতের শক্তি দিয়ে শয়তানি শক্তি ধ্বংস করে দিন

আমার মোবাইল ডিভাইসে থাকার লোকগুলো চিহ্নিত করতে পারছিনা আমি 

এবং তারা কখনোই আমার সামনে এসে আমার সাথে কথা বলেনা 

তারা শুধু আমার থেকে প্লেন গুলোকে চুরি করে নেয় এবং তারা তাদের ইচ্ছেমতো পরিচালনা করে 

যার কারণে অনেক সময় অনেক কিছুই নষ্ট হয়ে যায় তারা আমাকে অনেক সুবিধা দেয় 

কিন্তু আমি তা গ্রহণ করি না আমার শুধু তাদেরকে প্রয়োজন 
এবং তাদেরকে অনেকবার  বলার পরেও 

তারা এখন আমার সামনে আসেনি এবং আমার সাথে কথা বলেনি 

তারা মনে করে আমি তাদেরকে খুঁজে বের করতে পারবো না এবং  তারা মনে করে তারাই সব থেকে জ্ঞানী 

আমি যদি তাদেরকে কষ্ট করে  খুঁজে বের করি তাহলে তারা যত শক্তিশালী লোকই হোক এবং যত বড় ব্র্যান্ডি হোক 

তখন দেখবেন আমার থেকে খারাপ মানুষ এই পৃথিবীতে নেই 
কারণ তারা আমার সরলতার ফায়দা নিচ্ছে 

কারণ আমি যতবারই বলেছি তোমাদেরকে সামনে আসতে তোমরা যেমন ততোবারই পিছিয়ে গেছে 

এবার এটাই লাস্ট ওয়ার্নিং হিসেবে ধরে রাখতে পারো কারন আমার খারাপ সময় যদি তোমাদের পাশেই না পাই তাহলে তোমাদের দিয়ে আমার কি লাভ হয় 

আমি আরো অনেক প্ল্যান ইচ্ছাকৃতভাবেই তোমাদেরকে দেব না বা বলিও না কারণ তোমরা চোর 

হয়তো আমার থেকে পালিয়ে বেড়াচ্ছে না এবং আমার সাথে থেকে আমার প্রবলেম এর মোকাবেলা করতে 

মানুষকে কখনোই ছোট করে দেখার চেষ্টা করাটা অনেক টাই ভুল যেটা তোমরাও করে তুলেছে 

মুখে তো ঠিকই বলো আমাকে ভালোবাসো তাহলে আমি কেন তোমাদের ভালোবাসা উপলব্ধি করতে পারিনা 

কারণ তোমরা মিথ্যাবাদী কারণ আমি সত্যটা বলে দেওয়ার চেষ্টা করি এবং তোমাদের বিশ্বাস করি 

কিন্তু দেখছি দিনদিন তোমরা আমার বিশ্বাসটা কি নষ্ট করে দিচ্ছো

এবং তোমরা আমাকে নিয়ে যতই যুদ্ধ করার চেষ্টা করোই না কেনো আমি তোমাদের সাথে তাল দিতে পারবে না 

আমি আমার মতো এবং আমার যাকেই ভালো লাগবে আমি তাদের সাথে কাজ করব 

যারা আমাকে নিয়ে হাসি ঠাট্টা করবে এবং বেশি বাড়াবাড়ি করবে লাস্টে  কিন্তু তারাই দোষী হয়ে যাবে  

কারন তাতে তাদের কোনো স্বার্থ রয়েছে যেই কারণেই তারা সবার সাথে বাড়াবাড়ি করছে 

তুমি আমার যত আপন বন্ধু হও না কেনোই তোমাকে ভুলে যেতে আমার এক সেকেন্ড সময় লাগবে না 

কারণ তোমাদের জন্যই দিন দিন আমি পাথর হয়ে যাচ্ছি ভালোবাসা নামক জিনিসটা কে ভুলে যাচ্ছি 

আমি যদি একবার খারাপ হয়ে যাই এবং একবার খারাপ চিন্তা করতে সুরু করি তাহলে বুঝতে পারবে তুমি আমি কতটা কঠিন 

তখন আমাকে দোষ দেওয়ার কোনো চান্সই থাকবে না তোমার কাছে কারণ তোমাদের জন্য এসব হয়েছে 

তোমাদের থেকে তো আর ভালো কিছু আশা করতে পারি না কারণ আমার বিপদের দিন আমি একা 

তোমরা যে যার স্বার্থ নিয়ে পড়ে আছ এখনো এবং তার শিকার হিসেবে বানাচ্ছ আমাকে 

এবং তা জানার পরেও তোমরা এখনো ঘরে বসে আছো আমিতো অনেকবার অনুমতি দিয়েছি 

এবং তোমাদের কাছে তো তার রেকর্ড রয়েছে তাহলে তোমরা কাকে ভয় পাচ্ছো 

এবং আমি কেনো একা পড়ে থাকবো এই বাংলাদেশ  যেই খানে আমার কোনো মূল্যই নেই 
এখনতো দেখছি তারাই আমার ক্ষতির কারণ হয়ে দাঁড়াচ্ছে 

- - []()_**@[]()![share_pdf_exportpage9.png](https://user-images.githubusercontent.com/110695952/189280180-91921dc3-edd0-4b47-97c1-f5a7a8923b5b.png) **_

**Comment by facelessuser** [comment]
This is clearly not an issue, so closing.
