### ISSUE TITLE
Code blocks wrapped in p tag instead of pre tag

### ISSUE THREAD

**Issue by harlankoehn** [Python-Markdown/markdown#1296]
Is there any specific reason that code blocks are wrapped in p tags instead of pre tags? I'm currently using Stackedit and it wraps code blocks in a `<pre>` tag which is nice because then I can style those differently than inline code. Gitlab and Github do this as well.

Just to clarify, python-markdown will output:

```
<p>
  <code>
     someCodeGoesHere() {}
  </code>
</p>
```

Others will output:

```
<pre>
  <code>
     someCodeGoesHere() {}
  </code>
</pre>
```

**Comment by facelessuser** [comment]
This makes me think you are misusing the feature. Are you using fences or indented code blocks? If you are using fences did you enable the fenced code extension?

Please provide examples and configuration so we can understand exactly what you are doing and how we can advise you.

**Comment by facelessuser** [comment]
This answer is related to this question as well: https://github.com/Python-Markdown/markdown/issues/1297#issuecomment-1290965774

**Comment by waylan** [comment]
#1297 confirms that the user has failed to enable the fenced code block extension. Therefore, I am closing this as user error.
