### ISSUE TITLE
Code lines that start with a # being treated as a heading by the TOC extension

### ISSUE THREAD

**Issue by harlankoehn** [Python-Markdown/markdown#1297]
Markdown code blocks can potentially contain text that looks exactly like a heading, but should not be treated as such. For example, comments in python code start with a `#`. The TOC extension currently adds an entry for code lines that start with a hashtag, which seems like a bug to me.

I didn't test every possible scenario to see if it only happens when the comment is the first line of code or only has a single hashtag, etc. I was going to post example code here but it's pretty much impossible to do so because github issues uses markdown and converts my example code to HTML. The problem seems fairly straight forward though.

**Comment by facelessuser** [comment]
Can you provide a minimal example?

**Comment by harlankoehn** [comment]
Here's a screenshot with minimal code to demonstrate:

<img width="1152" alt="Screen Shot 2022-10-25 at 1 44 14 PM" src="https://user-images.githubusercontent.com/6472924/197845710-3945fd71-38e0-420e-ae0a-c099bf99acda.png">

**Comment by facelessuser** [comment]
Please post a copy/pastable example and provide your Markdown configuration extensions and options. Right now I can only guess what is wrong. Most likely, this is a user error, but without more details, I cannot answer.

**Comment by harlankoehn** [comment]
My markdown which I'm passing in to the python function down below:

<pre>
# This is a test

[TOC]

## Section 1 - Script Usage

### Section 1.1 - Cron Configuration

Use `crontab -l -u root` to view the currently configured crontab, or `crontab -e -u root` to edit it.

```
# m h d Mo dow
  5 4 * *  6 /opt
```
</pre>

My python code. I don't have any configuration beyond the default. This is in a Python 3.8.1 environment on MacOS.
```
def get_html_for_markdown(content: str):
    return markdown.markdown(content, extensions=['toc'])
```

**Comment by facelessuser** [comment]
You need to enable a fenced code extension. Fenced code is not part of the original Markdown spec, so you must enable one. 

- One that ships with Python Markdown: https://python-markdown.github.io/extensions/fenced_code_blocks/.
- For an implementation that handles nesting under lists and such, I would recommend https://facelessuser.github.io/pymdown-extensions/extensions/superfences/.

**Comment by waylan** [comment]
I am closing this as user error.
