### ISSUE TITLE
Add Nlbr extension

### ISSUE THREAD

**Issue by david-a-wheeler** [Python-Markdown/markdown#13]
This is a small feature request.

I recommend including the "Nlbr" extension as part of the Python-Markdown package, as described here:
http://deathofagremmie.com/2011/05/09/a-newline-to-break-python-markdown-extension/

Do **not** turn it on by default, because obviously this changes the semantics of markdown substantially.  Still, it's a common change to markdown (used by Github, for example), and it's easy to implement.  Making it easy to invoke, when desired, would be very nice.

Thanks!

**Comment by waylan** [comment]
I'm not opposed to this, but would need the permission of the extension author. And yes, it would not be on by default, but would simply be an included extension which the user would need to opt into.

**Comment by waylan** [comment]
For the record, we've received permission from the extension author to add the Nl2Br extension. Discussion is archived on the [mailing list](http://sourceforge.net/mailarchive/forum.php?thread_name=BANLkTim0vovGVhArbw5YEd--Qst6fQ_U_g%40mail.gmail.com&forum_name=python-markdown-discuss)

**Comment by david-a-wheeler** [comment]
Thanks for letting me know!  I think that's great news.

All the best...!

--- David A. Wheeler

----- Start Original Message -----
Sent: Tue, 21 Jun 2011 08:17:14 -0700
