### ISSUE TITLE
strange convertion of EOLs near URL

### ISSUE THREAD

**Issue by Alexey-T** [Python-Markdown/markdown#1302]
from markdown module:
```
__version_info__ = (3, 4, 1, 'final', 0)
```
I see that EOLs near URL is converted to EOL in HTML - see source MD on the right, result on the left.

![md-er](https://user-images.githubusercontent.com/4154978/200076914-315f20f8-07f7-4357-ad49-42c0f9cca9cb.png)

which is wrong IMO, I must get URL in HTML on the same line. no?

@veksha may be interested.

Code of CudaText plugin:
https://github.com/CudaText-addons/cuda_markdown_preview

I use Ubuntu 20.

**Comment by veksha** [comment]
@Alexey-T , please provide this file. maybe two spaces are there.

**Comment by Alexey-T** [comment]
File 
[index.zip](https://github.com/Python-Markdown/markdown/files/9942135/index.zip)

**Comment by veksha** [comment]
even without urls `<br>` is added:

![image](https://user-images.githubusercontent.com/275333/200081834-cc4bef65-73ee-4260-980c-0f820989508c.png)

**Comment by Alexey-T** [comment]
if it is by design, close the issue.

**Comment by veksha** [comment]
could be a bug of CudaText plugin.

**Comment by veksha** [comment]
works ok if I remove `GithubFlavoredMarkdownExtension`!  (or use `PartialGithubFlavoredMarkdownExtension`)

**Comment by facelessuser** [comment]
GFM appears to be the extension adding that behavior, which isn't a surprise as GFM has the feature of turning new lines to breaks.
