### ISSUE TITLE
Issue with codehilite extension

### ISSUE THREAD

**Issue by TheLostProgrammer** [Python-Markdown/markdown#1310]
My current version for Markdown is 3.4.1 with the other requirements all at their current versions.

On my local version of my website, I get the following output:
```html
<div class="codehilite">
  <pre><span></span><code><span class="nb">print</span><span class="p">(</span><span class="mi">5</span> <span class="o">+</span> <span class="mi">2</span><span class="p">)</span>
</code></pre>
</div>
```
This is exactly how it was working until I deployed this to my VPS and from there, it all went downhill.

With this code on my VPS (same as local version):
```python
markdown.markdown(response.get('description'), extensions=['fenced_code', 'codehilite', 'tables'])
```

I get the following output:
```html
<pre class="codehilite">
    <code class="language-py">print(5 + 2)</code>
</pre>
```
This is not what is wanted as it is not at all capable of being worked with. No styling can be added to this at all.

Based on what I have been trying to work out, the issue seems to be caused by the extension `codehilite`. When removing it from the `extensions` list on my local version, it looks the exact same as the output on my VPS. 

Not entirely sure how this can be fix or why the extension is causing such an issue.

**Comment by TheLostProgrammer** [comment]
Sorry, issue appears to be that `Pygments` was not installed on the VPS which caused Codehilite to not work. My mistake.

**Comment by Enough7** [comment]
> Sorry, issue appears to be that Pygments was not installed on the VPS which caused Codehilite to not work. My mistake.

How did you @TheLostProgrammer set pygments up?

**Comment by TheLostProgrammer** [comment]
> How did you @TheLostProgrammer set pygments up?

@Enough7, to setup pygments, I installed the Python library using the following:
```bash
pip install Pygments
```

Here is the link to the library: https://pypi.org/project/Pygments/

**Comment by Enough7** [comment]
Okay, thats odd.
I did the same but with a virtual Environment but it does not work.

**Comment by waylan** [comment]
@Enough7, What do you mean by "it does not work"? Did the installation fail? Did Markdown raise an error? Did the code block not get highlighted? Or some other issue I haven't thought of?

Note that setup for the extension is documented [here](https://python-markdown.github.io/extensions/code_hilite/#setup). If you have gone through the steps documented there and are still having an issue, please feel free to come back, open a new issue, and provide more details as outlined in our [guide](https://python-markdown.github.io/contributing/#issues).

**Comment by Enough7** [comment]
Hey @waylan,
thank you for helping me out.
I was confused is was using this guide [Codehilite - MkDocs Docmark](https://yakworks.github.io/docmark/extensions/codehilite/).
I used the config found here [Code blocks - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/) and syntaxhighlighting works now.

**Comment by facelessuser** [comment]
Material is generally geared towards using SuperFences which does not use Codehilte, mainly to facilitate some custom things.
