### ISSUE TITLE
Can't parse html tag correctly

### ISSUE THREAD

**Issue by luzhixing12345** [Python-Markdown/markdown#1311]
![image](https://user-images.githubusercontent.com/56221493/205994193-6a30d730-b7d1-40e2-844b-2dd32b2e2b00.png)

result:

```
<p>```html</p>
<div align="right"><image src="abc"></image></div>
<p>```</p>
```

It looks like the html code parsing failed, because it should be `<p><code>`

```
<p><code>html
&lt;div align="right"&gt;&lt;image src="abc"&gt;&lt;/image&gt;&lt;!--div--&gt;</code></p>
```

I noticed that HtmlBlockPreprocessor match and catch `<div align="right"><image src="abc"></image></div>`, and I guess maybe we should not remove it immediately and solve this in BlockParser ?

**Comment by mitya57** [comment]
Fenced code blocks (` ```…``` `) are not part of standard Markdown syntax. You need to enable `fenced_code` extension to use them.

See https://python-markdown.github.io/extensions/fenced_code_blocks/.
