### ISSUE TITLE
How do you add a custom PreProcessor?

### ISSUE THREAD

**Issue by fake-name** [Python-Markdown/markdown#1315]
Effectively the title. 

https://python-markdown.github.io/extensions/api/#example describes how to *define* a custom PreProcessor, but I can't figure out how the heck you're supposed to then use it. 

Looking around at some [other issues](https://github.com/Python-Markdown/markdown/issues/1299) it seems that people are defining a custom extension just to inject their preprocessor. That seems a bit janky of a solution. I could I suppose just append my preprocessor to `Markdown.preprocessors` after the main `Markdown()` class has been instantiated, but monkey-patching like that seems fragile. 

What is the proper way to use a custom preprocessor? And would it be possible to get the documentation updated to show the new method?

**Comment by waylan** [comment]
As explained in the [Integrating Your Code Into Markdown][1] section of the documentation, you need to create and register an extension. An extension is the only supported way to alter Python-Markdown's behavior.

[1]: https://python-markdown.github.io/extensions/api/#integrating_into_markdown

**Comment by fake-name** [comment]
So there's zero way to add a preprocessor without a extension?

That seems like a kind of arbitrary and actively unhelpful requirement.

**Comment by facelessuser** [comment]
> That seems like a kind of arbitrary and actively unhelpful requirement.
> 
> That seems like a kind of arbitrary and actively unhelpful requirement.

This is literally how any library that has a workflow like this works. I don't see how this is unhelpful as we provide a supported way in which to run preprocessors. If you have trouble with the API, we offer support to help out in either understanding parts that are not clear or fixing issues that have been overlooked.  With that said, let's rephrase. This is the only way supported in the library. 

Could you subclass the Markdown class and inject your own code to perform some preprocessing, sure, but it isn't supported, and any issues doing this will be yours to figure out.

Could you create your own wrapper script that processes the content and __then__ hands it over to the Markdown class to do its thing, sure, but again, this is an external process completely disconnected from this library, and any issues you have doing this are yours to figure out.
