### ISSUE TITLE
Non-well-formed XHTML due to unescaped brackets

### ISSUE THREAD

**Issue by namedgraph** [Python-Markdown/markdown#1321]
Looks like brackets that are not part of XHTML tags are not being escaped as entities.

Markdown input:
```md
3. For every triple <s p o>, M(<s, p, o>)= <M(s), M(p), M(o)>;
```
becomes non-well-formed XHTML:
```xml
<li>For every triple <s p o>, M(<s, p, o>)= <M(s), M(p), M(o)>;</li>
```
where well-formed XHTML should be using entity-escaping instead:
```xml
<li>For every triple &lt;s p o&gt;, M(&lt;s, p, o&gt;)= &lt;M(s), M(p), M(o)&gt;;</li>
```

**Comment by namedgraph** [comment]
Or should I have the escaped entities already in Markdown input? 🤔

**Comment by facelessuser** [comment]
> Or should I have the escaped entities already in Markdown input? 🤔

That is the correct answer.

Check out what other parsers do, including common mark: https://babelmark.github.io/?text=3.+For+every+triple+%3Cs+p+o%3E%2C+M(%3Cs%2C+p%2C+o%3E)%3D+%3CM(s)%2C+M(p)%2C+M(o)%3E%3B

We'll even enter it here in GitHub and see what it gives us:

3. For every triple <s p o>, M(<s, p, o>)= <M(s), M(p), M(o)>;
