### ISSUE TITLE
Add support for Pygments filters in codehilite

### ISSUE THREAD

**Issue by jvoisin** [Python-Markdown/markdown#1322]
Pygments supports [filters]( https://pygments.org/docs/filters/ ), and some of them like [TokenMergeFilter]( https://pygments.org/docs/filters/#TokenMergeFilter ) could [significantly help]( https://github.com/pygments/pygments/issues/2363 ) with reducing the size of the produced html on some pathological cases.

**Comment by waylan** [comment]
In version 3.3 we made some significant updates to the codehilite extension to allow most any arbitrary option to be set for Pygments. In fact, as the documentation states (at the bottom of the [Usage section](https://python-markdown.github.io/extensions/code_hilite/#usage)):

> All other options are accepted and passed on to Pygments’ lexer and formatter. Therefore, valid options include any options which are accepted by the [html formatter](https://pygments.org/docs/formatters/#HtmlFormatter) or whichever [lexer](https://pygments.org/docs/lexers/) the code’s language uses. Invalid options are ignored without error.

Of course, that requires the filter to be able to be passed to the Lexer on initialization. While Pygments' documentation seems to suggest that you can only add filters by calling the `add_filter` method from an instance of the lexer, you can in fact pass filters in on initialization.

Therefore, you can do this:

```python
markdown.markdown(src, extensions=[CodeHiliteExtension(filters=[TokenMergeFilter()])])
```
