### ISSUE TITLE
Entrypoint executable not being created on version 3.4.2

### ISSUE THREAD

**Issue by ande3577** [Python-Markdown/markdown#1327]
Installation does not report error, but executable is not created. 

Tested using python 3.10.6 and pip 22.0.2 (in Ubuntu docker container)

**Comment by waylan** [comment]
This is related to the changes in #1324. And I just realized I should have used `project.scripts` not `project.entry-points.scripts`. I find it very strange that some entry points don't come under the `entry-point` name while others do. In any event, this should be an easy fix. Thanks for the report.

**Comment by waylan** [comment]
Btw, you can always run the console script with `python -m markdown` which is what I do. I never run `markdown_py`, which is probably why I never noticed the issue.

**Comment by ande3577** [comment]
Thank you for the prompt action.   Endpoint is back to working on my system.
