### ISSUE TITLE
unexpected code block translation

### ISSUE THREAD

**Issue by fn-share** [Python-Markdown/markdown#1331]
In version 3.4.3，this is OK:

`"_markdown.convert('example\n\n``` python\nline1\nline2\n```\n\n')"`

But following is failed:

`"_markdown.convert('example\n\n``` python\nline1\n\nline2\n```\n\n')"`

**Comment by waylan** [comment]
Those two lines are the same. How is one failing? What output do you get and what are you expecting?

More specifically, it appears that you are using fenced code blocks. Did you enable the `fenced_code` extension? What other config options have you set?

**Comment by facelessuser** [comment]
It's failing because one has multiple new lines between code lines, so it's split into two blocks. Inline code only works within a single block. So enabling some kind of fenced code extension will fix the issue.

**Comment by waylan** [comment]
I'm closing this due to the lack of feedback from the original reporter. It appears that they simply need to enable a fenced_code extension.
