### ISSUE TITLE
CodeHilite - custom pygments lexer

### ISSUE THREAD

**Issue by Moraledalx** [Python-Markdown/markdown#1332]
Is it possible to load a custom pygment lexer for the CodeHilite extension ?

**Comment by facelessuser** [comment]
Yup, you have to create a proper Pygments plugin that registers itself properly. Then CodeHilite will just have access to it naturally.

**Comment by Moraledalx** [comment]
Ok, i will have to go the "long" way then, i will try :)
Thank you for your support
