### ISSUE TITLE
Question: Enable md_in_html globally and recursively?

### ISSUE THREAD

**Issue by courtneyaschwartz** [Python-Markdown/markdown#1334]
I have a large documentation project. Pages are either:
- pure Markdown
- Markdown mixed with HTML fragments

Due to limitations in what Markdown can do, we can't eliminate the HTML. Actually HTML is growing because when we can't consistently use Markdown extensions, we wind up replacing it so that output is uniform, and debugging is simpler. This is not ideal, obviously, because then we lose advantages of Markdown extensions. So I'm excited to try md_in_html.

But given the large project size and many contributors, it's not practical to add the attribute `markdown="1"` to every existing tag and potentially most child tags, nor to educate every occasional contributor.

Is there a way to enable Markdown inside HTML globally and recursively, and then only add a tag attribute where we need to _disable_ it?

Thanks.

**Comment by waylan** [comment]
That is not something we support with the existing `md_in_html` extension and I do not anticipate that we will be adding support in the future.

That said, while I was working on the relatively recent refactor of the extension, it occurred to me that there is room for an alternate extension which works differently. However, such an extension is not something I need personally and I don't have the time to build one anyway. But if I did, I would probably build something which works more like Commonmark's raw HTML behavior (see type 7 of the [HTML Blocks in the spec](https://spec.commonmark.org/0.30/#html-blocks)). Specifically, Markdown processing occurs in blocks in which the opening tag is followed by a blank line, but not in blocks which are not.

I should note that such an extension is so different from how our current extension works that it belongs as a separate extension. However, as I cannot take on any additional development or maintenance burden, it would be best if it existed as a third party extension. I just checked and I don't see anything like that listed in the [list of known third party extensions](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions).

By the way, have you looked at the [PyMdown HTML Block](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/html/) extension? It doesn't handle raw HTML, but it is a replacement for it. For that matter, the general [Blocks framework](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/) makes it very easy for anyone to create their own extensions which generate their own custom HTML from a simple syntax. These are experimental as this time, but I'm sure @facelessuser would be happy to receive feedback from more users to make it better.

**Comment by courtneyaschwartz** [comment]
Thanks for the quick reply. 🙂 

PyMdownX block notation isn't exactly "lightweight," so it doesn't scale well. We have tags 4-10 levels deep, for example, and hundreds of topics. That's not unusual in professional docs. Sooo many forward slashes... You can imagine how quickly it becomes intractable.

I'd like to not reinvent the wheel -- better to pool community resources, instead of forking us all to a standstill. I can help with test cases or small contributions. I suspect writing a whole new extension from scratch will take too long, though. So I was hoping to find a nearby roadmap, with efficient syntax like yours.

Companies rarely give full-time devs to docs (or they get poached by main product dev), so the practical answer might be "abandon MkDocs." That's why so many wind up with an older/slower solution like MadCap Flare. Just gives me an "ick" feeling. 😄 

Thanks again.
