### ISSUE TITLE
Support backslash for a forces linebreak

### ISSUE THREAD

**Issue by nolange** [Python-Markdown/markdown#1335]
There is a commonly supported way of creating hard line breaks by adding a `\` as the last character on a line, see [Github Flavored Markdown](https://github.github.com/gfm/#hard-line-breaks) or [pandoc](https://pandoc.org/MANUAL.html#extension-escaped_line_breaks)

I would like this to be supported, the other way of adding two whitespaces is at odds with alot of conventions and editors often silently remove them.

``` bash
printf 'one line\\\nsecond line' |  python -m markdown
```
Should produce:

``` html
<p>one line<br />
second line</p>
```

Does currently produce:
``` html
<p>one line\
second line</p>
```

Bonus Objective: in many implementations the backslash is the only way to add a linebreak in a table cell.

**Comment by waylan** [comment]
The [official rules][1] (which we follow) state:

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

That works in our implementation. If you would like to support any other syntax for line breaks, then that should be implemented as an extension. You may want to check the [list of known extensions][2] to see if one already exists. If not, you are free to create one. However, we will not be adding this to Markdown directly.

[1]: https://daringfireball.net/projects/markdown/syntax#p
[2]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

**Comment by nolange** [comment]
Well, you choice, but this ain't helping the format. there are efforts to standardize common and useful add-ons/changes with https://commonmark.org/ .

That would be better "living" target.

**Comment by facelessuser** [comment]
This extension allows such things: https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/#options. Keep in mind, things you see implemented in GitHub aren't even necessarily part of CommonMark. There is still fragmentation, but Python Markdown is, of course, an old-school Markdown parser.

**Comment by nolange** [comment]
It's in commonmark (i try to limit my files to it)

Thanks for the reference, did not consider this extension to have that functionality.

**Comment by waylan** [comment]
Note that Python-Markdown is not a Commonmark implementation and we have no plans to ever change that. If you want a Commonmark implementation, I would suggest looking elsewhere.
