### ISSUE TITLE
The appearance of an unwanted tag

### ISSUE THREAD

**Issue by ilya-nikolaev** [Python-Markdown/markdown#1337]
![image](https://user-images.githubusercontent.com/65247719/233719806-b617f6ef-f1a9-4698-8317-270885be81a2.png)
![image](https://user-images.githubusercontent.com/65247719/233719838-0a321c2a-22b9-40bc-b6a3-0e78bf34f3d8.png)
![image](https://user-images.githubusercontent.com/65247719/233720039-4bad76dc-aa08-4bec-8a64-55f498bca213.png)

code: https://hastebin.com/share/hanufoqeki.py
page.html: https://hastebin.com/share/rekeduxapa.html
page.md: https://hastebin.com/share/ehoforewut.markdown

How does an extra tag appear?

**Comment by ilya-nikolaev** [comment]
All my lists are converted to one numbered, it's weird

**Comment by mitya57** [comment]
> All my lists are converted to one numbered, it's weird

Please see the [documentation]:

> * __Consecutive Lists__
>
>     While the syntax rules are not clear on this, many implementations (including the original) do not end one list and start a second list when the list marker (asterisks, pluses, hyphens, and numbers) changes. For consistency, Python-Markdown maintains the same behavior with no plans to change in the foreseeable future. That said, the [Sane List Extension] is available to provide a less surprising behavior.

Regarding wrapping in the `<p>` tag, let me quote the [Markdown syntax rules]:

> If list items are separated by blank lines, Markdown will wrap the items in `<p>` tags in the HTML output.

[documentation]: https://python-markdown.github.io/#differences
[Sane List Extension]: https://python-markdown.github.io/extensions/sane_lists/
[Markdown syntax rules]: https://daringfireball.net/projects/markdown/syntax#list
