### ISSUE TITLE
Can't parse ```

### ISSUE THREAD

**Issue by ilya-nikolaev** [Python-Markdown/markdown#1338]
I have this code:

Main file: https://hastebin.com/share/safomofese.python
Extension for code: https://hastebin.com/share/yeboxegopu.python
Function for converting: https://hastebin.com/share/hojikotepo.python

Output: 
![image](https://user-images.githubusercontent.com/65247719/233744777-0b6b5b45-7837-474a-8dc4-0bad26401a00.png)

Why is the first block not converted, even though they are identical after the preprocessor?

Output if i turn off my extension and add a comment into first code block:
![image](https://user-images.githubusercontent.com/65247719/233746350-97501b7e-ae5b-4a99-ba77-7864c27a1698.png)

**Comment by waylan** [comment]
Have you enabled the [fenced_code][1] extension?

Also, in the future, please post your code as text in code blocks, not as images.

[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/

**Comment by ilya-nikolaev** [comment]
No, i don't use fenced_code,

**Comment by waylan** [comment]
Note that fenced code blocks are not part of the [original Markdown rules][1]. Therefore, they are not supported by default. You need to enable support by using an extension. As one is provided already with Python-Markdown, there is nothing we need to do here.

[1]: https://daringfireball.net/projects/markdown/syntax
