### ISSUE TITLE
No support for badges / labels

### ISSUE THREAD

**Issue by BitwiseAndrea** [Python-Markdown/markdown#1346]
Badges are very common UI elements in docs. They can be used for many purposes:

Showing relevant tags
<img width="362" alt="image" src="https://github.com/Python-Markdown/markdown/assets/50600470/fcbfe459-dbd2-4a2c-acc9-76295bae1c3d">

Showing version numbers
<img width="230" alt="image" src="https://github.com/Python-Markdown/markdown/assets/50600470/3b8f73b9-96ef-482b-9062-4d5898e30b76">

Showing attributes of something in an easy-to-recognize way
<img width="582" alt="image" src="https://github.com/Python-Markdown/markdown/assets/50600470/57a4f390-2a5c-45ab-9e88-627b9bd4b843">

Showing the status of an element
<img width="199" alt="image" src="https://github.com/Python-Markdown/markdown/assets/50600470/7fea7181-6d6e-4f43-9e9b-fdbdf9d9ffc6">

**Comment by waylan** [comment]
I think this would be a great candidate for a third party extension. There is no need for this to be included with the Markdown library directly. You may want to check the [list](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions) of known extensions to be sure one doesn't already exist.
