### ISSUE TITLE
How to change the line break of generated html files?

### ISSUE THREAD

**Issue by Saigut** [Python-Markdown/markdown#1351]
I use python-markdown (In fact I use [pelican](https://github.com/getpelican/pelican)) to convert markdown document to html files.
The line break of generated html files is LF, but I want CRLF, how to change to CRLF? Thanks.

Refer to [issue](https://github.com/getpelican/pelican/discussions/3143).

**Comment by waylan** [comment]
There is no official mechanism to do this. In fact there is no reason to have one as the HTML will render the same in a browser regardless of which line break character is used.

However, if you need this behavior for some non-typical use case, a post-processor could do a search and replace (in Python a single line would do the trick: `output_string.replace('\n', \r\n')`). Whether that post-processor is provided through some Pelican plugin or a Markdown extension (or something else) depends on your needs. You can check the existing known Markdown extensions [in the wiki][1], or [build your own][2] if one doesn't already exist. Personally, I'm not familiar with Pelican's plugin system so I'm not sure what is available there.

[1]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
[2]: https://python-markdown.github.io/extensions/api/
