### ISSUE TITLE
**text** not rendering as <b>text</b> or <strong>text</strong>

### ISSUE THREAD

**Issue by swehba** [Python-Markdown/markdown#1369]
If I have Markdown that includes bolded text using `**..**`, should markdown.markdown() apply the HTML tags <b> or <strong>? It does not appear to do so. Am I doing something wrong? Do I need to include a particular extension?

**Comment by facelessuser** [comment]
Works here.

```py
>>> import markdown
>>> markdown.__version__
'3.4.4'
>>> markdown.markdown('**text**')
'<p><strong>text</strong></p>'
```

You are going to have to provide a minimal, reproducible example for any further help.

**Comment by swehba** [comment]
I discovered what the issue was. You are correct that, in general, `**` in Markdown will be converted to `<strong>` in HTML. However, my particular Markdown was using HTML table notation (i.e., `<table>...</table>`) to work around some of the limitations of Markdown tables, and in that case, when some of the text in these tables was bolded using `**`, the markdown-to-html converter interpreted the `**` as a literal of two asterisks and did not convert them to `<strong>...</strong>`. This seems like reasonable behavior, although it might be nice to have an option to convert styling inside HTML elements.

**Comment by facelessuser** [comment]
There is always this extension: https://python-markdown.github.io/extensions/md_in_html/#markdown-in-html.

It's important to pay attention to its limitations, so read over the docs.
