### ISSUE TITLE
Distinguish betweet block code and inline code

### ISSUE THREAD

**Issue by dims12** [Python-Markdown/markdown#1376]
Currently I see that both are rendered as just `<code>` which is indistinguisheable and incorrect. Any way to fix?

**Comment by waylan** [comment]
I suspect you have not enabled the [fenced_code](https://python-markdown.github.io/extensions/fenced_code_blocks/) extension.

As a reminder, fenced code blocks are not part of the [original rules](https://daringfireball.net/projects/markdown/syntax) (which we follow). Therefore, they are not enabled by default. I realize that fenced code blocks have become standard in many implementations, including Commonmark, but, as noted in the "note" on our [homepage](https://python-markdown.github.io/#goals), we are not a Commonmark implementation.

**Comment by waylan** [comment]
I am closing this due to the lack of feedback. If the issue persists after enabling the fenced_code extension, please provide an example and we can reopen the issue.
