### ISSUE TITLE
Inconsistancy with reference in lists

### ISSUE THREAD

**Issue by azizmb** [Python-Markdown/markdown#138]
Given the following markdown:

``` markdown
1. First list item

  Text supporting the list item

2. Second list item

3. Reenigne

  Multi line text supporting the second item blah blah 
  blah blah lorem ipsum.
```

Should yield the following HTML:

``` html
<ol>
  <li><p>First list item</p>
    <p>Text supporting the list item</p>
  </li>
  <li><p>Second list item</p>
  </li>
  <li><p>Reenigne</p>
    <p>Multi line text supporting the second item blah blah 
      blah blah lorem ipsum.</p>
  </li>
</ol>
```

This syntax is mentioned in the reference [here](http://daringfireball.net/projects/markdown/syntax#list)

But, generated output by the library is:

``` html
<ol>
  <li>First list item</li>
</ol>
<p>Text supporting the list item</p>
<ol>
  <li>
    <p>Second list item</p>
  </li>
  <li>
    <p>Reenigne</p>
  </li>
</ol>
<p>Multi line text supporting the second item blah blah 
  blah blah lorem ipsum.</p>
```

**Comment by waylan** [comment]
Python-Markdown **requires** 4 spaces of indent for all nested list content. Yes, I know that other implementations do not - I view that as a bug in those implementations, which I will not be adding to Python-Markdown. If you want Python-Markdown to support less than 4 spaces of indent, then set [`tab_length`](http://packages.python.org/Markdown/reference.html#tab_length) to whatever you would like when calling markdown. Just be aware, that the new tab-length will apply to the entire markdown document _consistently_ (as it should).

**Comment by azizmb** [comment]
Ah! Worked!

Thanks for the response. Completely agree with you on the 4 spaces policy, makes absolute sense.
