### ISSUE TITLE
How to integrate arithmatex with python-markdown?

### ISSUE THREAD

**Issue by JTP-123** [Python-Markdown/markdown#1386]
As a new beginner, I decided to make my small tiny flask blog support math formula, so I chose arithmatex under python-markdown. After I have read [offical documentation](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/), i made such configuration as follows, namely I put mathjax cdn link at the bottom of the block script of base.html template, arithmatex is included by markdown function. But it doesn't work. Can anyone give me a favor? thank you.

<code>
# include arithmatex 
def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code', # define allowed html tags for Markdown
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul', 
                        'h1', 'h2', 'h3', 'p', 'img', 'kbd', 'sup', 'sub', 'br', 
                        'table', 'footer', 'thead', 'tbody', 'tr', 'th', 'td', 'small', 'big']
        extensions = ['pymdownx.arithmatex', 'pymdownx.b64', 'pymdownx.emoji']
        target.body_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html', 
                    extensions=extensions,
                    extension_configs={
                        "pymdownx.arithmatex": {
                            "generic": True
                        }
                    }),
            tags=allowed_tags, strip=True))
</code>

part of base.html:
<code>
{% block scripts %}
...    // other script code like moment.js,  self-defined js function
<script>
        window.MathJax = {
            tex: {
                inlineMath: [ ["\\(","\\)"] ],
                displayMath: [ ["\\[","\\]"] ],
                processEscapes: true,
                processEnvironments: true
            },
            options: {
                ignoreHtmlClass: ".*",
                processHtmlClass: "arithmatex"
            }
        };
    </script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async 
            src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
{% endblock %}
</code>

but after my configuration ends, it still produces a plain text, not math formula:
![批注 2023-10-06 131915](https://github.com/Python-Markdown/markdown/assets/68136548/4eefd105-fb8a-4b17-99d0-b36277a5ede1)

**Comment by facelessuser** [comment]
Python Markdown is not the appropriate place to ask questions about 3rd party extensions. You already asked in the appropriate place: https://github.com/facelessuser/pymdown-extensions/discussions/2192, and I've answered as best as can be done.

You need to debug your flask app to find what you are doing wrong. I've already provided you with a working example you can compare against.
