### ISSUE TITLE
Does not handle comments in code snippets

### ISSUE THREAD

**Issue by jrinder42** [Python-Markdown/markdown#1424]
As the title describes, if there are comments in a code snippet, it treats them as headers incorrect when converting to html (markdown.markdown(text))

```python
...
# this is a comment
...
```

It will treat `# this is a comment` as a header as opposed to just a comment

**Comment by waylan** [comment]
Have you enabled the [fenced_code](https://python-markdown.github.io/extensions/fenced_code_blocks/) extension? As a reminder, the original Syntax rules do not include any provision for fenced code blocks. Therefore, they are not enabled by default.

**Comment by jrinder42** [comment]
Thanks, that solves this for me.
