### ISSUE TITLE
rss extension doesn't work

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#143]
I'm trying the example from the [documentation](http://packages.python.org/Markdown/extensions/rss.html):

```
Python 2.7.3 (default, Aug  1 2012, 05:16:07) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>> text = "Some markdown document."
>>> markdown.markdown(text, ['rss'])
u'<rss version="2.0"><channel><title>Markdown in Python</title><link /><description></description></channel></rss>'
```

There is no content at all (which should be in `<description>`)...

I would maybe look at this myself, but I don't have enough time right now, so I just put it here.

**Comment by waylan** [comment]
It works, but only if the document contains headers (h1, h2, ...). Each heading (and any content following it) are inserted as a separate "item" in the document. But you're correct, the documentation doesn't match the actual behavior.

Truth be told, I have been contemplating removing this extension. It was created years ago as a means to demonstrate what could be done with the extension API. But I'm not aware that anyone actually uses it. It would probably be better broken out of the markdown lib and maintained separately - that is if anyone uses it and is interested in maintaining it.

**Comment by mitya57** [comment]
I'm going to use it :)

When will you delete it? Is it still possible to submit a pull request that fixes the documentation?

**Comment by mitya57** [comment]
Please feel free to remove that extension. I'll use my own code for that purposes :)
