### ISSUE TITLE
Installing 2.2.0 using easy_install

### ISSUE THREAD

**Issue by kaba2** [Python-Markdown/markdown#144]
Hi,

I am trying to install Python Markdown 2.2.0 using easy_install. However, it tries to install version 2.0 which I already have. Is there something else to it than just "easy_install markdown"?

Kalle

**Comment by waylan** [comment]
IIRC, you need to tell easy_install that you want to "upgrade". I believe you need the "-u" flag, or maybe " -U". Check easy_install's documentation.  As this is not an issue with markdown I'm closing this.
