### ISSUE TITLE
<table> improperly wrapped by <p> when inside a list

### ISSUE THREAD

**Issue by socram8888** [Python-Markdown/markdown#1445]
When a `<table>` element is specified inside a list, it gets improperly wrapped with a `<p>`:

```python
import markdown
html = markdown.markdown("""
  - List element
    
    <table></table>
""")
print(html)
```
Returns:
```
<ul>
<li>
<p>List element</p>
<p><table></table></p>
</li>
</ul>
```
This is not correct - tables are not allowed inside paragraph elements. What should be generated is:
```
<ul>
<li>
<p>List element</p>
<table></table>
</li>
</ul>
```

**Comment by waylan** [comment]
Please note that the syntax [rules](https://daringfireball.net/projects/markdown/syntax#html) state regarding raw HTML:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. 

Of course, if they cannot be indented, then they cannot be nested inside list items. In fact, this same limitation exists in the reference implementation. We have no plans to change this behavior. However, one is certainly free to develop their own third-party extension which behaves differently.
