### ISSUE TITLE
Html in a definition list

### ISSUE THREAD

**Issue by kaba2** [Python-Markdown/markdown#145]
Hi,

Consider the following Markdown code:

```
Term
:   <pre>
    asdfsa
    -----
    </pre>
```

It results in the following html:

```
<dt>Term</dt>
<dd>
<p><pre>
asdfsa</p>
<hr />
</pre>
</dd>
```

which is clearly wrong. The same html works well for a list-item. Could this be a bug, or am I doing something wrong here?

Kalle

**Comment by waylan** [comment]
The [spec](http://daringfireball.net/projects/markdown/syntax#html) states the following: 

> The only restrictions are that block-level HTML elements -  e.g.`<div>`,`<table>`,`<pre>`,`<p>`, etc. —must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

Of course this means that block level HTML cannot be nested inside list, blockquotes, etc. If you want to do that, then you'll need to use raw html for the list also. This matches with reasoning behind the syntax in the paragraphs immediately preceding the above quoted paragraph. 

As the requested change would be in direct violation of the spec, I'm closing this as wontfix.
