### ISSUE TITLE
add a buildin Mermaid extention

### ISSUE THREAD

**Issue by ouhammmourachid** [Python-Markdown/markdown#1454]
Markdown is a versatile tool for writing and formatting text with simplicity. However, it lacks native support for rendering complex diagrams and flowcharts. While there are existing extensions available for integrating Mermaid, a popular diagramming and charting tool, into Markdown documents, they often fall short in providing seamless integration and proper rendering.

### Lack of Native Support
Markdown lacks built-in support for rendering Mermaid diagrams, requiring users to rely on third-party extensions or tools for integration.

### Inconsistent Rendering
Existing extensions for Mermaid integration may not render diagrams properly or may introduce compatibility issues with different Markdown parsers or rendering engines.

### Complex Setup Process
Users face challenges in setting up and configuring existing Mermaid extensions to work seamlessly with Markdown documents, leading to frustration and inefficiency.

## Proposal
To address these issues and enhance the functionality of the Markdown library, we propose the development of a native Mermaid extension that seamlessly integrates with Markdown documents and provides reliable rendering of Mermaid diagrams.

here is solution that i have worked on by my self and it work very well

```python
"""
Mermaid Extension for Python-Markdown
========================================

Adds mermaid parser (like github-markdown) to standard Python-Markdown code blocks.

Original code Copyright 2018-2020 [Olivier Ruelle].

License: GNU GPLv3

"""

from markdown.extensions import Extension
from markdown.preprocessors import Preprocessor
import mermaid as mmd
from mermaid.graph import Graph

import re
import string

def strip_notprintable(myStr):
    return ''.join(filter(lambda x: x in string.printable, myStr))

MermaidRegex = re.compile(r"^(?P<mermaid_sign>[\~\`]){3}[\ \t]*[Mm]ermaid[\ \t]*$")


# ------------------ The Markdown Extension -------------------------------

class MermaidPreprocessor(Preprocessor):
    def run(self, lines):
        old_line = ""
        new_lines = []
        mermaid_sign = ""
        m_start = None
        m_end = None
        mermaid_lines = []
        in_mermaid_code = False
        is_mermaid = False
        for line in lines:
            # Wait for starting line with MermaidRegex (~~~ or ``` following by [mM]ermaid )
            if not in_mermaid_code:
                m_start = MermaidRegex.match(line)
            else:
                m_end = re.match(r"^["+mermaid_sign+"]{3}[\ \t]*$", line)
                if m_end:
                    in_mermaid_code = False

            if m_start:
                in_mermaid_code = True
                mermaid_sign = m_start.group("mermaid_sign")
                if not re.match(r"^[\ \t]*$", old_line):
                    new_lines.append("")
                if not is_mermaid:
                    is_mermaid = True
                    #new_lines.append('<style type="text/css"> @import url("https://cdn.rawgit.com/knsv/mermaid/0.5.8/dist/mermaid.css"); </style>')
                new_lines.append('<div class="mermaid">')
                m_start = None
            elif m_end:
                graph = Graph('simple','\n'.join(mermaid_lines))
                svg = mmd.Mermaid(graph)
                new_lines.append(svg.svg_response.text)
                new_lines.append('</div>')
                new_lines.append("")
                m_end = None
            elif in_mermaid_code:
                mermaid_lines.append(line)
#                 new_lines.append(strip_notprintable(line).strip())
            else:
                new_lines.append(line)

            old_line = line
        return new_lines


class MermaidExtension(Extension):
    """ Add source code hilighting to markdown codeblocks. """

    def extendMarkdown(self, md):
        """ Add HilitePostprocessor to Markdown instance. """
        # Insert a preprocessor before ReferencePreprocessor
        md.preprocessors.register(MermaidPreprocessor(md), 'mermaid', 35)

        md.registerExtension(self)

def makeExtension(**kwargs):  # pragma: no cover
    return MermaidExtension(**kwargs)
```
and here is the result

```python
markdown_content = """
# Header 1
This is a paragraph with **bold** and *italic* text.

## Header 2
- Item 1
- Item 2
- Item 3
~~~mermaid 
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }
~~~
"""
# we can alsso use ````istead of ~~~
display(HTML(markdown.markdown(markdown_content, extensions=[MermaidExtension()])))
```
![image](https://github.com/Python-Markdown/markdown/assets/93659459/4fcea643-ac6f-40c4-b964-2637ccd6a432)

**Comment by waylan** [comment]
Thank you for your suggestion. However, we are not interested in taking on any additional maintenance burden. Additionally, none of the core developers of this library use Mermaid, therefore we are not familiar with it or the needs of its users and would be not be best suited to maintaining it.

Additionally, I will note that we have been contemplating changing the list of built-in extensions by removing them. In my opinion, it would have been better to not have any built-in, but have all be external. The only reason that has not happened is for backward compatibility. Therefore, we are no longer adding any additional built-in extensions.

**Comment by paulinetheitgirl** [comment]
@ouhammmourachid thank you for sharing this example. I was looking for a way to write a custom preprocessor and neither the documentation in https://python-markdown.github.io/extensions/api/#preprocessors or https://github.com/Python-Markdown/markdown/wiki/Tutorial-1---Writing-Extensions-for-Python-Markdown had what I wanted.
