### ISSUE TITLE
No table support?

### ISSUE THREAD

**Issue by buhtz** [Python-Markdown/markdown#1455]
Is my diagnosis correct that your package do not support markdown tables?

```
`>>> markdown.markdown('| table |\n| me |')
'<p>| table |\n| me |</p>'`
```

**Comment by facelessuser** [comment]
You need to use the table extension: https://python-markdown.github.io/extensions/tables/#usage

**Comment by buhtz** [comment]
Ah thanks. Why is this an extension? Technically what is it? Another module (py-file) imported? Why is it separated.

Is there an in-between format while converting? I don't need HTML but the structure.

**Comment by facelessuser** [comment]
Python Markdown is an old-school Markdown parser (not CommonMark) based on the original spec. Tables were not included in the original spec, probably because they are clunky, even with such an extension (that is my speculation). It was provided as an extension though. It has become pretty ubiquitous in modern Markdown implementations, but originally, it was an extension and remains so in this library.

**Comment by buhtz** [comment]
Do you see away to get the "in-between format" of a table after parsing it? I need to separate the parsing and the conversion into HTML.

**Comment by facelessuser** [comment]
What "in-between format" are you talking about? What format do you _think_ you are trying to get?  I'm not sure what you are doing specifically, but I suspect it extends past the scope of what Python Markdown intends to offer.

**Comment by buhtz** [comment]
> What "in-between format" are you talking about? What format do you _think_ you are trying to get?

For example a two-dimensional array with all cells.

Thanks in advance

**Comment by facelessuser** [comment]
It doesn't have that. If you want that, you'd have to fork the table extension as is and modify it to do what you want it to do. Python Markdown's goal is to convert that syntax to HTML, and that is what it does.

**Comment by buhtz** [comment]
> you'd have to fork the table extension as is and modify it to do what you want it to do.

I will [consider](https://codeberg.org/buhtz/hyperorg/issues/128) this. Of course will all respect to your work and your license.
