### ISSUE TITLE
GFM alerts

### ISSUE THREAD

**Issue by cdbdev** [Python-Markdown/markdown#1456]
Hello,

I recently came across GFM alerts. Apparently it's a recent feature:

https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/

Are there any plans to incorporate this through a new extension? Or are admonitions the way to go?

Thank you for your feedback

**Comment by facelessuser** [comment]
If you have a desire for GitHub style alerts, this might be the closest thing: https://github.com/oprypin/markdown-callouts.

Generally, Python Markdown supports addon behavior through 3rd party extensions. Python Markdown is not meant to be the single repo that implements all the various Markdown variants out there. It supports a few extensions in the base, and the community provides the rest via 3rd party extensions.

**Comment by cdbdev** [comment]
> If you have a desire for GitHub style alerts, this might be the closest thing: https://github.com/oprypin/markdown-callouts.
> 
> Generally, Python Markdown supports addon behavior through 3rd party extensions. Python Markdown is not meant to be the single repo that implements all the various Markdown variants out there. It supports a few extensions in the base, and the community provides the rest via 3rd party extensions.

Ok thank you for your explanation
