### ISSUE TITLE
TOC extension: ignore headers above [TOC] marker

### ISSUE THREAD

**Issue by pozitron57** [Python-Markdown/markdown#1457]
Is it possible to ignore headers that are located above the [TOC] marker?

Example:

``` markdown
# Name of the page (header not shown in TOC)

[TOC]

## Header 1

## Header 2

### Header 2.1

## Header 3
```

**Comment by waylan** [comment]
Not directly, no. However, you may be able to get that result with the `toc_depth` setting. For example, in the example document you provided setting `toc_depth='2-6'` would have that effect. However, if you happened to have any `h1` level heading after the marker, those would also be excluded.

**Comment by pozitron57** [comment]
Thanks, it works for my use cases. Actually I knew about the `toc_depth` option but it didn't come to my mind that it fits my situation.
