### ISSUE TITLE
Fenced code blocks with newlines not parsed into html <code> blocks

### ISSUE THREAD

**Issue by SNeugber** [Python-Markdown/markdown#1458]
I found a behaviour I wasn't expecting: when fenced code blocks contain newlines they are split up into individual `<p>` paragraphs, instead of one big `<code>` block.

Would you be able to clarify if this is a bug or not?

Sample code to reproduce:

```
import markdown

md_text_ok = """
\`\`\` # Having to escape this for github... ignore the back slashes please
foo
\`\`\`
"""

rendered = markdown.markdown(md_text_ok) # -> '<p><code>foo</code></p>'

md_text_broken = """
\`\`\`

foo
\`\`\`
"""

rendered = markdown.markdown(md_text_broken) # -> '<p>```</p>\n<p>foo\n```</p>'

```

**Comment by waylan** [comment]
You need to enable the [fenced_code](https://python-markdown.github.io/extensions/fenced_code_blocks/) extension.

```python
markdown.markdown(some_text, extensions=['fenced_code'])
```

**Comment by SNeugber** [comment]
Oooh, I was not aware, my bad. Thanks for clarifying, it works now :+1:

**Comment by pythoninthegrass** [comment]
Thanks for the solution @waylan! Was able to get my template working like so:

```py
#!/usr/bin/env python

import markdown

msg = """
# Hello, world!

This is a **test email** from [Resend](https://resend.com).

\```bash
python -m venv .venv
source .venv/bin/activate
python -m pip install -r requirements.txt
./send_email.py
\```
""".lstrip()

html = markdown.markdown(msg, extensions=["fenced_code"])

print(html)
```

(Ignore the escaped code block in nested markdown. Probably a better way to do it on GitHub, but don't have the bandwidth to find out)
