### ISSUE TITLE
Please make a PyPI release.

### ISSUE THREAD

**Issue by SimonSapin** [Python-Markdown/markdown#146]
The git version has fixes that are not in the latest PyPI release. (I’m affected by #113.)

**Comment by waylan** [comment]
Yes I am aware of this. As we work on python-markdown as volunteers in our spare time, this will happen when I have the time. In the meantime, you're always free to install from the git repo if you want.

**Comment by SimonSapin** [comment]
Thanks for your response. I ended up installing 2.1.0 which does not have this bug, but git would have worked too. I understand about spare time, thanks for all the work you’ve already done!
