### ISSUE TITLE
A line ending that is preceded by a backslash is not parsed as a hard line break

### ISSUE THREAD

**Issue by AUVESY-Nachwuchskraefte** [Python-Markdown/markdown#1464]
good morning everyone!

when trying to render linebreaks within paragraphs with a backslash at the end of the line as in the [spec](https://spec.commonmark.org/0.31.2/#hard-line-break) the backslash will not be used as a formatting character but stay as is.

```
# linebreaks

asd
asd

das\
das

sad  # 2 spaces
sad

## python-markdown

<h1>linebreaks</h1>
<p>asd
asd</p>
<p>das\
das</p>
<p>sad<br />
sad</p>

## mistletoe

<h1>linebreaks</h1>
<p>asd
asd</p>
<p>das<br />
das</p>
<p>sad<br />
sad</p>
```

**Comment by facelessuser** [comment]
@AUVESY-Nachwuchskraefte Python Markdown is an old-school Markdown parser that predates CommonMark. It is not a CommonMark parser, so any expectations that it _should_ adhere to the CommonMark spec need to be set aside.

With that said, you can get the behavior you are looking for with this extension: https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/.

**Comment by waylan** [comment]
As our [documentation notes](https://python-markdown.github.io/#goals): 

> *This is not a CommonMark implementation*; nor is it trying to be! Python-Markdown was developed long before the CommonMark specification was released and has always (mostly) followed the [syntax rules](https://daringfireball.net/projects/markdown/syntax) and behavior of the original reference implementation. No accommodations have been made to address the changes which CommonMark has suggested. It is recommended that you look elsewhere if you want an implementation which follows the CommonMark specification.

Note that backslash escapes are only applied to a subset of characters as defined in the rules and a newline is not one of them (see [BACKSLASH ESCAPES](https://daringfireball.net/projects/markdown/syntax#backslash)). Therefore, there should be no expectation that a backslash escape would have any effect on a newline character. Instead, the rules provide for a hard break by preceding a newline with two or more spaces (see [PARAGRAPHS AND LINE BREAKS](https://daringfireball.net/projects/markdown/syntax#p)).

Given the above, this is being closed as wontfix.

**Comment by AUVESY-Nachwuchskraefte** [comment]
Thank you for your response, I overlooked the "note" in your documentation.

@facelessuser thanks for your provided solution, I will try it.
