### ISSUE TITLE
'markdown_extras' is not a registered tag library. Must be one of:

### ISSUE THREAD

**Issue by bhekidaweti** [Python-Markdown/markdown#1466]
Markdown works well in local development but not in deployment. I get the ff error  in deployment:

> 

markdown_extras' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz

> 

My django app is deployed on aws and im using nginx .Your help is much appriciated

**Comment by facelessuser** [comment]
This is most certainly a user error, but unfortunately, you have not provided enough information for anyone to help.

> markdown_extras' is not a registered tag library.

This makes me think you've somehow configured something wrong in your app, which may not even be Python Markdown related.

In order for someone to be able to help, please provide a minimal, reproducible example so that we can get some idea of what the real question really is.

**Comment by bhekidaweti** [comment]
This is my code both in local server and deployment server i have installed markdown using pip install and it appears under pip list in in both development and deployment. 

html file :
```html

{% extends "quiz/layout.html" %}

{% load markdown_extras %}

{% block body %}
<h1>{{ post.title }}</h1>
<p>By {{ post.author.username }} on {{ post.created_at }}</p>
{% if post.image %}
<img src="{{ post.image.url }}" alt="{{ post.title }}">
{% endif %}
<div>{{ post.content|convert_markdown|safe }}</div> 
<a href="{% url 'post_list' %}">Back to Blog</a>
{% endblock %}
```

markdown_extras.py file in the templatestags folder( I have also created en empty __init__.py file in this folder . )

import markdown
```python
from django import template
from django.template.defaultfilters import stringfilter
from django.utils.safestring import mark_safe

register = template.Library()

@register.filter
@stringfilter
def convert_markdown(value):
    return markdown.markdown(value, extensions=['markdown.extensions.fenced_code'])
```
This the error I get (I have set the debug mode to true just to show this error)

> <html>
<body>
<html lang="en"><body style="padding: 0px; margin: 0px; font: small sans-serif; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);"><div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204);"><h1 style="padding: 0px; margin: 0px; font-weight: normal;">TemplateSyntaxError at /1/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87);">'markdown_extras' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz</pre>
Request Method: | GET
-- | --

5.0.3
TemplateSyntaxError
'markdown_extras' is not a registered tag library. Must be one of: admin_list admin_modify admin_urls cache i18n l10n log static tz
/home/ubuntu/env/lib/python3.10/site-packages/django/template/defaulttags.py, line 1036, in find_library
blog.views.post_detail
/home/ubuntu/env/bin/python3
3.10.12
['/home/ubuntu/capstone',  '/home/ubuntu/env/bin',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/home/ubuntu/env/lib/python3.10/site-packages']
Sun, 02 Jun 2024 10:11:49 +0000

</div><div id="explanation" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(238, 238, 238);"><p style="padding: 0px; margin: 0px;">You’re seeing this error because you have<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap; word-break: break-word;">DEBUG = True</code><span> </span>in your Django settings file. Change that to<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap; word-break: break-word;">False</code>, and Django will display a standard page generated by the handler for this status code.</p></div></body></html>
</body>
</html>TemplateSyntaxError at /1/
'markdown_extras' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
Request Method:	GET

Django Version:	5.0.3
Exception Type:	TemplateSyntaxError
Exception Value:	
'markdown_extras' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
Exception Location:	/home/ubuntu/env/lib/python3.10/site-packages/django/template/defaulttags.py, line 1036, in find_library
Raised during:	blog.views.post_detail
Python Executable:	/home/ubuntu/env/bin/python3
Python Version:	3.10.12
Python Path:	
['/home/ubuntu/capstone',
 '/home/ubuntu/env/bin',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/home/ubuntu/env/lib/python3.10/site-packages']
Server time:	Sun, 02 Jun 2024 10:11:49 +0000
Error during template rendering
In template /home/ubuntu/capstone/blog/templates/blog/post_detail.html, error at line 3

'markdown_extras' is not a registered tag library. Must be one of: admin_list admin_modify admin_urls cache i18n l10n log static tz
1	{% extends "quiz/layout.html" %}
2	
3	{% load markdown_extras %}
4	
5	{% block body %}
6	<h1>{{ post.title }}</h1>
7	<p>By {{ post.author.username }} on {{ post.created_at }}</p>
8	{% if post.image %}
9	<img src="{{ post.image.url }}" alt="{{ post.title }}">
10	{% endif %}
11	<div>{{ post.content|convert_markdown|safe }}</div>
12	<a href="{% url 'post_list' %}">Back to Blog</a>
13	{% endblock %}
Traceback [Switch to copy-and-paste view](https://funwithworldflags.com/1/#)
/home/ubuntu/env/lib/python3.10/site-packages/django/template/defaulttags.py, line 1034, in find_library
        return parser.libraries[name] …
Local vars
During handling of the above exception ('markdown_extras'), another exception occurred:
/home/ubuntu/env/lib/python3.10/site-packages/django/core/handlers/exception.py, line 55, in inner
                response = get_response(request) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/core/handlers/base.py, line 197, in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) …
Local vars
/home/ubuntu/capstone/blog/views.py, line 12, in post_detail
    return render(request, 'blog/post_detail.html', {'post': post}) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/shortcuts.py, line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/loader.py, line 61, in render_to_string
        template = get_template(template_name, using=using) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/loader.py, line 15, in get_template
            return engine.get_template(template_name) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/backends/django.py, line 33, in get_template
            return Template(self.engine.get_template(template_name), self) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/engine.py, line 177, in get_template
        template, origin = self.find_template(template_name) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/engine.py, line 159, in find_template
                template = loader.get_template(name, skip=skip) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/loaders/cached.py, line 57, in get_template
            template = super().get_template(template_name, skip) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/loaders/base.py, line 28, in get_template
                return Template( …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/base.py, line 154, in __init__
        self.nodelist = self.compile_nodelist() …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/base.py, line 196, in compile_nodelist
            return parser.parse() …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/base.py, line 510, in parse
                    raise self.error(token, e) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/base.py, line 508, in parse
                    compiled_result = compile_func(self, token) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/loader_tags.py, line 295, in do_extends
    nodelist = parser.parse() …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/base.py, line 510, in parse
                    raise self.error(token, e) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/base.py, line 508, in parse
                    compiled_result = compile_func(self, token) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/defaulttags.py, line 1096, in load
            lib = find_library(parser, name) …
Local vars
/home/ubuntu/env/lib/python3.10/site-packages/django/template/defaulttags.py, line 1036, in find_library
        raise TemplateSyntaxError( …
Local vars

**Comment by facelessuser** [comment]
Okay this is what I was looking for. This seems like a question for Django, not Python Markdown.

I thought this was a question about the Markdown "extras" extension, but what you are asking about is how to properly use Django's templating, which is better asked over at the Django repository, not here.

**Comment by bhekidaweti** [comment]
Ok thanks Isaac

**Comment by mitya57** [comment]
Maybe the problem is that you named the folder `templatestags`, it should be `templatetags` without the `s` in the middle.

**Comment by bhekidaweti** [comment]
> Maybe the problem is that you named the folder `templatestags`, it should be `templatetags` without the `s` in the middle.

Thanks I will try your suggestion and rename the folder

**Comment by bhekidaweti** [comment]
> Maybe the problem is that you named the folder `templatestags`, it should be `templatetags` without the `s` in the middle.

Wow thanks  .  Your suggestion fixed the problem I am so happy :)
