### ISSUE TITLE
linenos does not work as documented/expected

### ISSUE THREAD

**Issue by noah** [Python-Markdown/markdown#147]
Hi, I'm opening this tentatively, as I'm not sure whether this is a bug or whether I'm just stupid.

```
⚡ pip freeze |grep -i markdown
Markdown==2.2.0
```

If I initialize python-markdown with:

```
"codehilite(force_linenos=False)"]
```

Then, given the following comments and code in /usr/lib/python3.2/site-packages/markdown/extensions/codehilite.py,

```
* linenos: (Boolen) Turn line numbering 'on' or 'off' (off by default).
...
>>> code.linenos = True  # True or False; Turns line numbering on or of.  
...
code = CodeHilite(children[0].text,                                                                                                                                                          
linenos=self.config['force_linenos'],      
...
self.config = {                                                                                                                                                                                      
    'force_linenos' : [False, "Force line numbers - Default: False"], 
```

I would expect `codehilite(force_linenos=False` to have the effect of disabling linenos globally, irrespective of whether there is a shebang line or not.  Another way to say this, is that I can't find a way to globally disable line numbering by the `codelite(` call.

What makes me think that this could be a bug is that there is a check in the `hilite()` function in `codehilite.py` as follows:

```
if self.lang is None:
    self._getLang()
```

And if this gets called, and there is a shebang, `self.linenos=True` in all cases.

```
if m.group('shebang'):                                                                                                                                                                           
    # shebang exists - use line numbers                                                                                                                                                          
    self.linenos = True  
```

If I comment out this check, I get syntax highlighting and no line numbers in all cases, which is what I want.  Please let me know what you think, I hope I'm not being dumb.

**Comment by waylan** [comment]
Sorry, perhaps this is not well documented. `force_linenos=True` forces all highlighted code to contain line numbers. Setting it to `False` turns off that feature. With _force__linenos turned off, it is left up to the first line of each individual code block (whether is starts with a # or not) to determine whether that block should be numbered. There is no way to globally _force_ all line numbering to be off.

If your codeblock starts with a shebang and you do not want line numbering then I would suggest the following:

```
::: python
#!/usr/bin/python
...
```

The first line will tell codehilite that the block is python code and to not number the line. However, that line will not be included in the output. The second line will become the first line in the output and your readers will be non-the-wiser.

I realize this is not ideal, but the `force_linenos` keyword is a Boolean value which result means we only get 2 possible values. To add a way to globally turn linenos off, we need a third value. We could use `None`, but that it not exactly intuitive.

**Comment by noah** [comment]
From and API standpoint, this is--as you pointed out--less than ideal.  The current scheme requires someone with an existing document base to change _n_ documents to conform, whereas a global switch would require one change.

One-change scenarios include:
- Make `force_linenos` a ternary switch (perhaps using `None`)
- Change the existing function signature to more precisely capture the possible states for line-numbering of code blocks:
  - Line numbers always on
  - Line numbers always off
  - Line numbers iff first line is shebang
- Add a negative keyword argument to existing function signature: `disable_linenos=True`

I think the second one makes the most sense.  If you're in favor of a change, please let me know which you like best and I'll code it.

**Comment by waylan** [comment]
I certainly like your second proposal the best and that's how I'd do it if I was starting fresh. However, there are backward compatibility considerations as well. I don't want to break existing code when people upgrade to the next version. Options one and three seem address that concern better.

Perhaps we should implement option 2 (using a new keyword like, say, "linenos" or "linenums" or ...) and leave `force_linenos` behavior alone (perhaps with a depreciation warning). Then document and pragmatically enforce the policy that only one or the other keyword can be used.

Merge requests are certainly welcome.

**Comment by noah** [comment]
Closing with reference to pull request:

https://github.com/waylan/Python-Markdown/pull/148
