### ISSUE TITLE
Build failure?

### ISSUE THREAD

**Issue by dpawson** [Python-Markdown/markdown#1489]
Long time (happy) user of pymarkdown. New PC, have to build my extension
Following previous updates, now shows error as below:
Advice please. 

running develop
/usr/lib/python3.13/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/usr/lib/python3.13/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.13'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.13/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

**Comment by facelessuser** [comment]
I'm not really sure what you are doing. This package isn't called `pymarkdown` , did you mean `markdown` or are you talking about a different package? 

I don't know what command you ran as all you posted was an error that does not seem to reference this package. Can you be more explicit about what you are doing? I'm not even sure right now if your question is even directly related to this package.

**Comment by dpawson** [comment]
Trying to build an extension to pymarkdown... Is that different / same as markdown_py please..
If different my apologies and please delete this issue.

**Comment by facelessuser** [comment]
You are not providing enough information. Please provide all the steps that you are doing as I am very confused about what steps you are doing and what package are applying them to.

This is our package: https://pypi.org/project/Markdown/.

It is not `pymarkdown`: https://pypi.org/project/pymarkdown/

Please provide a step-by-step of what you are doing and please explicitly state where you got the code you are trying to build.

**Comment by dpawson** [comment]
I am (was) using pymarkdown. Quite confusing naming. Issue closed.
