### ISSUE TITLE
items list not rendered correctly  to HTML

### ISSUE THREAD

**Issue by abdilahsamari100** [Python-Markdown/markdown#1491]
When converting `Markdown` to `HTML`, lists are not properly rendered the sub-items under each main item 

The nested sub-items should appear inside the respective parent `<ul>` tags, maintaining the correct list hierarchy.

```py
import markdown

markdown_text = """
- **Visual Narration**: Description here
- **Story Arcs and Pacing**:
  - Sub-item 1
  - Sub-item 2"""

# Convert Markdown to HTML
html_output = markdown.markdown(markdown_text, extensions=['extra'], output_format="html")

# Print the HTML result
print(html_output)
```

**Expected :**

![image1](https://github.com/user-attachments/assets/bcefe7ac-90aa-4ec4-85a5-644536a3ae37)

**Actual :**

![image2](https://github.com/user-attachments/assets/f62c2ebe-f6b0-451d-84f3-1b5149efc6ed)

How i can solve this problem please?

**Comment by facelessuser** [comment]
If you want to have nested lists, they need to be indented 4 spaces (or 1 tab). You can read further about this here and how to change if you feel so inclined: https://python-markdown.github.io/#differences.

```py
import markdown

print(f'Markdown Version: {markdown.__version__}')
print('-----')

MD = """
-   **Visual Narration**: Description here
-   **Story Arcs and Pacing**:
    -   Sub-item 1
    -   Sub-item 2
"""

extensions = ["extra"]
extension_configs = {}

print(markdown.markdown(MD, extensions=extensions, extension_configs=extension_configs))
```
Results

```html
Markdown Version: 3.7
-----
<ul>
<li><strong>Visual Narration</strong>: Description here</li>
<li><strong>Story Arcs and Pacing</strong>:<ul>
<li>Sub-item 1</li>
<li>Sub-item 2</li>
</ul>
</li>
</ul>
```

**Comment by abdilahsamari100** [comment]
@facelessuser **thanks**

**Comment by chrispy-snps** [comment]
The strict requirement for the four-space rule is a significant challenge for people using LLM-generated Markdown (which is a lot of us nowadays). Different LLMs have different list-item indentation behaviors. For example, OpenAI prefers dynamic indents per the list item marker:

```markdown
Human:

Create a two-item ordered list, with a sublist item under each item.

AI:

1. Item 1
   - Subitem 1

2. Item 2
   - Subitem 2

Human:

Create a two-item unordered list, with a sublist item under each item.

AI:

- Item 1
  - Subitem 1

- Item 2
  - Subitem 2
```

The LLM Markdown generation process is not like a piece of software that can be configured for a particular upstream behavior.

**Comment by 17Reset** [comment]
> The LLM Markdown generation process is not like a piece of software that can be configured for a particular upstream behavior.

Agreed, the indentation here in most LLM output is relative, not the mandatory 4 spaces.I hope to be able to support.

**Comment by waylan** [comment]
We have no intention to alter the behavior here. This behavior has been present from the very beginning, Over 2 decades.

**Comment by facelessuser** [comment]
There are extensions that attempt to address this: https://github.com/radude/mdx_truly_sane_lists. I do not use it or have insight into how well it works. If people are interested, they could potentially contribute there or fork if maintenance has died out.
