### ISSUE TITLE
question: inline patterns run before block processors?

### ISSUE THREAD

**Issue by pawamoy** [Python-Markdown/markdown#1492]
From the look of the API, `md.parser.inlinePatterns` and `md.parser.blockprocessors` are two different registries, right? I was trying to have a block processor run *before* an inline pattern by setting its priority as higher than the pattern's, but it doesn't seem to work.

**Comment by facelessuser** [comment]
> From the look of the API, md.parser.inlinePatterns and md.parser.blockprocessors are two different registries, right? 

Yes

> I was trying to have a block processor run before an inline pattern by setting its priority as higher than the pattern's, but it doesn't seem to work.

This is a very unclear statement.

Generally, Blockprocessors do run before inline Blockprocessors, once a block is captured, inline processors could be run on it. A block processors could, once capturing a block, force Blockprocessors to be run on that content further or force inline processors to be run, but generally, a block would have captured the content first.

In short, I would generally say that inlinepatterns are not aware of, nor do they care about what Blockprocessors do and are generally run on blocks that have already been captured by a block.

With all of that said, I have no idea of what you are doing, so I cannot comment further. Most likely, you are not doing what you think you are doing, but I can only speculate with a hard example.

**Comment by waylan** [comment]
Each registry is separate and has no knowledge of any other registry. Therefore, when setting the priority of a block processor, you only need to account for other block processors which have been registered with that that specific registry, There is no need to consider inline processors as they are registered with a separate registry.

**Comment by pawamoy** [comment]
Thanks @facelessuser @waylan!

> This is a very unclear statement.

Guilty of under-stating my problem :sweat_smile:!

> Each registry is separate and has no knowledge of any other registry. Therefore, when setting the priority of a block processor, you only need to account for other block processors which have been registered with that that specific registry, There is no need to consider inline processors as they are registered with a separate registry.

I see, thanks. My main question was whether inline patterns all ran before block processors.

Let me elaborate.

---

Context: https://github.com/pawamoy/markdown-pycon/issues/1.

mkdocs-autorefs registers an inline pattern that handles inline references that weren't already handled by Python-Markdown itself. It transforms them as `autoref` (non-standard) HTML elements as an intermediate step, before fixing them again later in the MkDocs build process.

markdown-pycon registers a block processor that looks for blocks starting with `>>>` (pycon syntax) to transform them using pymdownx.highlight. Basically:

```python
block = blocks.pop(0)
blocks.insert(0, Highlighter(self.parser.md).highlight(block, "pycon"))  # highlight returns Markup
```

The inline pattern has priority 168 while the block processor has priority 30.

I noticed that mkdocs-autorefs logs warnings about false-positive cross-references found in non-fenced pycon blocks:

```md
Some text.

>>> array = [[0, 1, 2], [3, 4, 5]]
>>> i = array[0][1]
```

Here autorefs warns that cross-reference `[1]` cannot be found in the docs. The thing is, markdown-pycon transforms the whole block of pycon syntax into a highlighted block using pymdownx.highlight, and I thought this would prevent autorefs from "seeing" the false-positive cross-ref. But apparently autorefs still sees it, either because it runs before the block is transformed through pymdownx.highlight, or because I'm making wrong assumptions about what pymdownx.highlight is doing (IIUC it stashes HTML, so autorefs should only see a stash ID, not the actual contents). I therefore tried upping the block processor priority to something like 170, but that didn't change anything.

**Comment by facelessuser** [comment]
> transforms the whole block of pycon syntax into a highlighted block using pymdownx.highlight

Let's be clear, because I don't know what you are doing. `pymdownx.highlight` highlights code blocks that have already been processed by Python Markdown in a treeprocessor. It is also used to highlight fenced code during a preprocessor step via `pymdownx.superfences`.

**Comment by pawamoy** [comment]
OK I ran a debugging session. markdown-pycon basically transforms blocks by calling pymdownx.highlight on them and wrapping the result in `Markup`. So instead of `'>>> ...'` they become `Markup('<div ...>')`. I thought autorefs' inline pattern wouldn't run on `Markup` instances, maybe that's my mistake. Its `handleMatch` method does receive a match object, with data being a `Markup` instance. Then all the autorefs machinery kicks in, with a cross-ref identifier equal to `'</span><span class="mi">1</span><span class="p">'`. Maybe it should just return `None` (not handled) if `data` is an instance of `Markup`.

I confirmed by the way that the only time `handleMatch` receives a `Markup` instance is when it comes from markdown-pycon transformed block.

**Comment by pawamoy** [comment]
I got the solution, closing! Thanks again and sorry if it was all unclear, I didn't expect I'd have to go in details.

**Comment by pawamoy** [comment]
For reference, the real solution was to stash the highlighted div instead of reinserting a Markup instance in blocks (which should only be strings).

```python
highlighted = Highlighter(self.parser.md).highlight(block, "pycon")
el = Element("p")
el.text = self.parser.md.htmlStash.store(highlighted)
parent.append(el)
```

This way no changes are needed in autorefs.
