### ISSUE TITLE
Bullet point spacing

### ISSUE THREAD

**Issue by ReinhardKeil** [Python-Markdown/markdown#1497]
In GitHub markdown there is a difference in spacing when blank lines between bullet points are used.

Example (without spacing):

- Item1
- Item2
- Item3

Example (with spacing):

- Item1

- Item2

- Item3

----

Is it possible to enable this feature with Python markdown?  We are actually using https://github.com/mkdocs/mkdocs

**Comment by waylan** [comment]
Yes, that is supported out of the box (view the rendered HTML to see the difference). However, you may also need to ensure your MkDocs theme includes the necessary CSS styles to show the spacing.
