### ISSUE TITLE
Id attribute for Setext-style header not recognized

### ISSUE THREAD

**Issue by jpfleury** [Python-Markdown/markdown#16]
[HeaderId extension](http://www.freewisdom.org/projects/python-markdown/HeaderId) doesn't work with Setext-style headers. The following code:

```
import markdown
text = """
Setext-style header {#id1}
===================
Setext-style header {#id2}
-------------------
### Atx-style header ### {#id3}
"""
print markdown.markdown(text, ['extra'])
```

will output:

```
<h1>Setext-style header {#id1}</h1>
<h2>Setext-style header {#id2}</h2>
<h3 id="id3">Atx-style header</h3>
```

but it should output:

```
<h1 id="id1">Setext-style header</h1>
<h2 id="id2">Setext-style header</h2>
<h3 id="id3">Atx-style header</h3>
```

Version used is 2.0.3.

**Comment by waylan** [comment]
I just started a discussion on the [mailing list](http://sourceforge.net/mailarchive/forum.php?thread_name=BANLkTikoJvo3Y0juCeZsAF5jUDLQ9FvPNQ%40mail.gmail.com&forum_name=python-markdown-discuss) regarding how to approach this issue. See the list for details.
