### ISSUE TITLE
Malformed attr_list attributes produce malformed html

### ISSUE THREAD

**Issue by aleray** [Python-Markdown/markdown#166]
Hi again,

the following document (notice de unmatching quotes)...

``` python
import markdown

doc = """
# Hello {: style='width: 500px;" }

World
"""
md = markdown.Markdown(output_format="html5", extensions=["attr_list"])
print(md.convert(doc))
```

...produces the following malformed html: 

``` html
<h1 500px;"="500px;&quot;" style="'width:">Hello</h1>
<p>World</p>
```

I have no real idea of what the resulting html should look like. Do you think it could be fixed to produce at least valid HTML?

Thanks,

Alex

**Comment by waylan** [comment]
Thanks for the report. Of course, when you pass garbage in, you can expect garbage out. As long as this doesn't crash the parser or the output doesn't crash modern browsers, I can live with this. If a document author wants valid output, then s/he needs to provide valid input. Therefore, this is at the bottom of my priority list. Of course, patches are welcome.
