### ISSUE TITLE
add option to convert html to markdown

### ISSUE THREAD

**Issue by parezcoydigo** [Python-Markdown/markdown#168]
Pandoc has the option to convert html to markdown. It's very useful. As a feature request, I'd love to have that in python-markdown.

**Comment by waylan** [comment]
While it may be nice to have, the way the parser is implemented, there would be no practical way to do this. I do believe there are some html2markdown libs out there (might even be one in python). And, I certainly don't have any time to work on it. I'll say build it yourself. If it becomes popular and can actually be merged, we'll reconsider then.
