### ISSUE TITLE
Markdown Extra support doesn't include modifications to middle-word emphasis

### ISSUE THREAD

**Issue by jpfleury** [Python-Markdown/markdown#17]
PHP Markdown Extra includes [modifications to underscore emphasis](http://michelf.com/projects/php-markdown/extra/#em), but Python Markdown doesn't support them.

According to the Markdown Extra syntax, underscores in the middle of a word don't generate an emphasis. There are 2 cases:
## Strong emphasis

With Markdown Extra, the following:

```
The file name is "my__text__file.txt".
```

will be displayed as the following:

```
<p>The file name is "my__text__file.txt".</p>
```

However, the following Python Markdown code:

```
import markdown
text = "The file name is \"my__text__file.txt\"."
print markdown.markdown(text, ['extra'])
```

will output:

```
<p>The file name is "my<strong>text</strong>file.txt".</p>
```
## Light emphasis

Constant `SMART_EMPHASIS` set to `False` is useful to follow [official Markdown syntax](http://daringfireball.net/projects/markdown/). However, this constant should affect only Markdown standard, but it affects also Markdown Extra. According to the Markdown Extra syntax, the following:

```
The file name is "my_text_file.txt".
```

will be displayed as the following:

```
<p>The file name is "my_text_file.txt".</p>
```

However, the following Python Markdown code (with `SMART_EMPHASIS = False`):

```
import markdown
text = "The file name is \"my_text_file.txt\"."
print markdown.markdown(text, ['extra'])
```

will output:

```
<p>The file name is "my<em>text</em>file.txt".</p>
```

**Comment by waylan** [comment]
First, based on some of your comments I get the sense that you are
reporting based on a 2.0 release. The current code in git no longer
has the global variables. They have all been moved to class attributes
on the Markdown class.

So lets look as a simple example from the current code base:

``` python
>>> markdown.markdown('The file name is "my_text_file.txt".')  # smart_emphasis=True (the default)
<p>The file name is "my_text_file.txt".</p>
>>> markdown.markdown('The file name is "my_text_file.txt".', smart_emphasis=False)
<p>The file name is "my<em>text</em>file.txt".</p>
>>> markdown.markdown('The file name is "my__text__file.txt".')
<p>The file name is "my<strong>text</strong>file.txt".</p>
>>> markdown.markdown('The file name is "my__text__file.txt"., smart_emphasis=False')
<p>The file name is "my<strong>text</strong>file.txt".</p>
```

Now obviously, the "smart_emphasis" attribute only works on "emphasis"
not on "strong". Although, I suppose strong is really stronger
emphasis, so the name would still be appropriate to cover both. I
believe that when that feature was originally added to Python-Markdown
the thought was that double underscores are not likely to occur in
prose, so we only need to be concerned with single underscores.
However, that decision was made before I was involved in the project,
as was the decision to make the "smart" behavior the default (to match
markdown.pl's behavior it should be changed, but I'm not going to go
there).

It could also be argued that a file name should be wrapped in `<code>`
tags, which would alleviate the problem in the given example. That
said, PHP Markdown Extra definitely does support smart double
underscore behavior so Python-Markdown Extra should as well. I don't
think it needs to come under the smart_emphasis attribute though. I
think Extra should probably add the same behavior for double
underscores (triple underscores do not seem to be supported in PHP
Extra). The reason Extra does nothing with this now is that
`smart_emphasis` defaults to `True` so the thinking was that it didn't

## matter. Missed the case for "strong" though.

---

\X/ /-\ `/ |_ /-\ ||
Waylan Limberg

**Comment by jpfleury** [comment]
Hi,

Some explanations to my issue:

Yes, it's based on a 2.0 release (2.0.3).

I'm writing syntax highlighting in gedit for both Markdown and Markdown Extra. I try to follow official syntax as much as possible. It's why I set `SMART_EMPHASIS` to `False`.

Now, with Markdown standard, there's no issue. All is OK:

```
import markdown
text = """The file name is \"my_text_file.txt\".
The file name is \"my__text__file.txt\"."""
print markdown.markdown(text)
```

will output:

```
<p>The file name is "my<em>text</em>file.txt".
The file name is "my<strong>text</strong>file.txt".</p>
```

It follows official syntax.

Now, the problem is with Markdown Extra:
1. First, because, unlike PHP Markdown Extra, strong emphasis (using underscores) in the middle of a word is not displayed literally by Python Markdown:
   
   For `The file name is "my__text__file.txt".`, PHP Markdown Extra outputs:
   
   ```
   <p>The file name is "my__text__file.txt".</p>
   ```
   
   while Python Markdown outputs:
   
   ```
   <p>The file name is "my<strong>text</strong>file.txt".</p>
   ```
2. Second, because Python Markdown follows `SMART_EMPHASIS` set to `False` also for Markdown Extra, whereas it matters only for Markdown Standard, since PHP Markdown Extra doesn't generate emphasis for middle-word underscores.
   
   As consequences, with `SMART_EMPHASIS` set to `False`, we follow Markdown standard, but we no longer follow PHP Markdown Extra.

**Comment by waylan** [comment]
On Fri, Jun 3, 2011 at 9:44 PM, jpfleury
reply@reply.github.com
wrote:
[snip]

> Now, the problem is with Markdown Extra:
> 1. First, because, unlike PHP Markdown Extra, strong emphasis (using underscores) in the middle of a word is not displayed literally by Python Markdown:

Yeah, I acknowledged this as a bug in my previous comment. This is
what I will fix when I find the time. Of course patches/merge requests
are always welcome.

> 1. Second, because Python Markdown follows `SMART_EMPHASIS` set to `False` also for Markdown Extra, whereas it matters only for Markdown Standard, since PHP Markdown Extra doesn't generate emphasis for middle-word underscores.
> 
>    As consequences, with `SMART_EMPHASIS` set to `False`, we follow Markdown standard, but we no longer follow PHP Markdown Extra.

As we are no longer using global variables (with next release), this
is irrelevant. Why would someone do this unless they actually want it?

```
makrdown.markdown('some_text_here', extensions=['extra'], smart_emphasis=False)
```

Btw, as a workaround until the next release, if you have edited the
global variables in the source and want the alternate behavior in one
specific call to markdown, just reset/override the variable:

```
import markdown
markdown.SMART_EMPHASIS = True
markdown.markdown('some_text', ...)
markdown.SMART_EMPHASIS = False
markdown.markdown('other_text', ...)
```

As an aside, one of the reasons I removed the global variables for the
next release is that while the above
has always worked, it was never obvious how to change the behavior.
The new way feels much more intuitive.

## 

---

\X/ /-\ `/ |_ /-\ ||
Waylan Limberg

**Comment by jpfleury** [comment]
> Yeah, I acknowledged this as a bug in my previous comment.

OK, yes, you're right.

Thanks for explanations.
