### ISSUE TITLE
"Command line" instructions on web have wrong script names

### ISSUE THREAD

**Issue by zanedp** [Python-Markdown/markdown#170]
On [command line instructions online](http://freewisdom.org/projects/python-markdown/Command_Line), the instructions say to run "markdown.py", but the version I just installed with the Windows installer .exe is "markdown_py".

**Comment by waylan** [comment]
The documentation was moved some time ago to http://packages.python.org/Markdown/ (the source code, this github repo and PyPI all point here) where it is updated with the current code. Yuri (who owns freewisdom.org) was going to point his pages to the updated docs. Unfortunately, he has not done so. You may want to address that with him.

**Comment by zanedp** [comment]
Thanks, Waylan. I have sent Yuri an email suggesting he point his site to the new documentation location.
