### ISSUE TITLE
Escaping support in Meta-Data extension

### ISSUE THREAD

**Issue by yegle** [Python-Markdown/markdown#173]
The `meta` extension is super useful and this feature was adapted by [pelican](https://github.com/getpelican/pelican) to extract blog post meta data.

One thing missing from this extension is the support for quoting or escaping.

Here's my situation: I'm translating some blog posts into Chinese, and I added a `origin` meta in my posts indicating the original post of the translation.

```
Title: some title that's parsed correctly
Origin: http://example.com/url_that_has_underscore
```

I'm using `vim` so the underscore will be highlighted by `vim` and regarded as italic text. If I'm unlucky that there's odd number of underscores, then the syntax highlight of the rest post would be ruined.

Quoting doesn't help, the highlight is still a mess. So I'm asking for escaping support in this extension.

**Comment by waylan** [comment]
Sorry, but I'm confused by this. The meta-data extension parses and removes the meta data from the document before any other parsing takes place. Therefore the metadata is not parsed as markdown text and doesn't remain in the document. So I'm not sure how you are arriving at  your stated problem. Unless, you have a syntax error which is causing markdown to not recognized your meta-data as such. Meta-data requires that you **not** have any blank lines before the end of your meta-data (even the first line). Is that perhaps the problem?

**Comment by yegle** [comment]
@waylan 

The problem is that most editors like `vim` will consider the whole text as a markdown text, regardless of the meta information at the first lines

Here's a screenshot: http://cl.ly/Lz6p

**Comment by waylan** [comment]
Ah, I see. That is a problem with vim's syntax highlighting - which does not use python-markdown, not a problem with python-markdown. There is no bug here. You'll need to address this with whoever maintains vim's markdown syntax highlighting.

**Comment by yegle** [comment]
I do think this is related to python-markdown since the meta-tag support is an extension to the official Markdown syntax, which actually produces a markdown document with wrong markups for other markdown implementations or editors.

Supporting this extension in vim is easy, but I'm not sure how many editors out there has the same problem.
