### ISSUE TITLE
setup.py: make building docs optional

### ISSUE THREAD

**Issue by mgorny** [Python-Markdown/markdown#176]
The setup.py script overrides 'setup' command with a custom one, forcing documentation build.

We're often building Markdown for multiple Python implementations at the same time, and therefore it is only necessary to build docs once. Therefore, I'd like to request a command-line option to disable the documentation build.

**Comment by waylan** [comment]
This seems like a reasonable request. Patches (pull requests) are certainly
welcome.

**Comment by mgorny** [comment]
I've opened a PR #178 for it. Sorry for two bugs but the common way of converting an issue to PR doesn't seem to work.
