### ISSUE TITLE
Disable parts of Markdown

### ISSUE THREAD

**Issue by daGrevis** [Python-Markdown/markdown#179]
Are there any way to disable, lets say, image adding for Markdown?

I'm using Markdown markup for my blog — for articles and comments. Articles should have full support for Markdown including HTML, but comments should allow only minimal markup w/o images and HTML.

**Comment by waylan** [comment]
You can do this with Python-Markdown's [Extension API](http://packages.python.org/Markdown/extensions/api.html) (see the built-in [safe_mode](http://packages.python.org/Markdown/reference.html#safe_mode) to disallow html). In fact, the Extension API should allow you to change any part of the parser you want to do pretty much anything you want. Of course, you'll need to create your own extension (unless a [third party extension](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions) already meets your needs). 

However, I think a better tool would be to use something like [Bleach](https://github.com/jsocol/Bleach) after running markdown for something like this. In fact, I recommend Bleach over our own so-called 'safe_mode`.

``` python
import bleach
import markdown
bleach.clean(markdown.markdown(some_comment))
```
