### ISSUE TITLE
Link to bug tracker outdated

### ISSUE THREAD

**Issue by jpfleury** [Python-Markdown/markdown#18]
In `docs/README` and `docs/README.html`, the link to the bug tracker is outdated. It's `http://www.freewisdom.org/projects/python-markdown/Tickets` instead of `https://github.com/waylan/Python-Markdown/issues/`.

**Comment by waylan** [comment]
This has already been fixed in the repo on github. If you can, please check the most recent code base before reporting. Thanks.
