### ISSUE TITLE
Release new version (with security fixes) on PyPi

### ISSUE THREAD

**Issue by phihag** [Python-Markdown/markdown#186]
I don't want to toot my own horn, but #185 fixes a major security issue. To allow downstream projects to securely use Python-Markdown (and not custom forks or monkey-patched versions), a new release on PyPi would be great.

**Comment by phihag** [comment]
Forked to [secure-Markdown](http://pypi.python.org/pypi/secure-Markdown/) for now. Sorry for the fork, but we really can't depend on known-insecure libraries.

**Comment by waylan** [comment]
Obviously, this is open source software so you can fork as you see fit, but I would discourage calling it **secure** Markdown (although I see you accurately listed "Development Status :: 2 - Pre-Alpha"). In fact, "safe_mode" is called _safe_ only for historical reasons (before I joined the project). It is an unfortunately named feature. As the developer, I make no guarantees about the security of "safe_mode" (even after applying your patch). If you want "safe" output, my recommendation is to use a third party sanitizer (like [Bleach](https://github.com/jsocol/bleach)) to wrap markdown's output.  

In fact, my long term goal is to drop "safe_mode" altogether (perhaps an extension will be available to escape raw html - but no more) and recommend something like Bleach instead.

Regarding the slow response to do release: I work on Python-Markdown voluntarily in my spare time. I will get to it when I have the time - no sooner.
