### ISSUE TITLE
Crashes Google App Engine

### ISSUE THREAD

**Issue by jwogrady** [Python-Markdown/markdown#188]
So, today I cloned the latest version to use in a Google App Engine project.  For some reason the fenced_code extension completely crashes the GAE dev server. No error messages, no traceback.

The symptoms: My task queue halted and my form would fail to post, except I would never get a failure... my browser churned endlessly. My CPU fan would kick into overdrive every time I tried.

I rolled back to Python-Markdown 2.2.1 and the problem went away.

Here is the commit that resolved my issue... Hopefully the code diff will help isolate the issue better.

https://github.com/jwogrady/bloggart/commit/65dc59d466ce07521480494d6afa4c725c9a5cd7

**Comment by waylan** [comment]
@jwogrady What was the markdown text that caused the problem? Without this, it would be nearly impossible to replicate and find the problem, let alone fix it.

**Comment by waylan** [comment]
@jwpgrady disregard my previous comment. I believe I found and fixed the problem now. Sorry about that. I realize that most users of this lib are running it on web server backends and require a lib that never hangs/crashes. It is very unusual for me to push changes before running the entire test suite. A regex change I pushed yesterday caused the test suite to hang just as you described - and I failed to notice. Everything should be back to normal now. I apologize for the inconvenience.

**Comment by jwogrady** [comment]
@waylan yep!  I updated to the latest release (2.3.0) and everything works perfect now. Here [are the code diffs in my project](https://github.com/jwogrady/bloggart/commit/1dacf05d6a597296d3c3f1b1f45a3a898087b6ba).

PS: Since 2.3.0 is an Alpha version one anticipates that there might be issues. My experience with Markdown, especially the production version on [Pypi](http://pypi.python.org/pypi/Markdown), is that it is very fast and stable. I'm a huge fan of this project, and grateful for all the work you have put into it.
