### ISSUE TITLE
Render "abbr" tag

### ISSUE THREAD

**Issue by mpancorbo** [Python-Markdown/markdown#189]
I'm not a professional programmer and I know very few about Python. Thus, I can't propose a pull on the code. So, this is the reason I make a point in "issue".

I think it is a good idea to render the `abbr` HTML tag using the same syntax as links. If the link field is omitted, then the quoted text roles as "title" in a `abrr` tag. This is an example:

`[Seville](http://en.wikipedia.org/wiki/Seville "Link to wikipedia") is a good place for holydays`

will render normally as:

`<a href="http://en.wikipedia.org/wiki/Seville" title="Link to wikipedia">Seville</a> is a good place for holydays`

But

`[Seville]("Southern city of Spain") is a good place for holydays`

may render as:

`<abbr title="Southern city of Spain">Seville</abbr> is a good place for holydays`

**Comment by waylan** [comment]
This is already possible with the [Abbreviations Extension](http://packages.python.org/Markdown/extensions/abbreviations.html) - which currently appears to be down - a mirror can be found here: http://pythonhosted.org/Markdown/extensions/abbreviations.html

**Comment by mpancorbo** [comment]
Thanks! I'll test it. Looks ok.
