### ISSUE TITLE
LinkPattern text is not atomic

### ISSUE THREAD

**Issue by cdent** [Python-Markdown/markdown#196]
https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L312

```
el.text = m.group(2)
```

As a result it is easy for an extension (for example CamelCase WikiWords) to get active inside the label part of typical labeled markdown link. I reckon the fix is:

```
el.text = util.AtomicString(m.group(2))
```

However I suppose some would moan that disables styling within the label for emphasis. For my own purposes this isn't necessary. Is this a known situation and what I should do is replace `link` in the inlinepatterns with my own implementation or can the above fix be accepted?

**Comment by waylan** [comment]
You are correct in your assumption that this would cripple nested inline markup. For that reason, there is no way such a change would be considered. This clearly falls in the create-your-own-extension camp. Closing wontfix.
