### ISSUE TITLE
Footnote and backtick within code doesn't mix

### ISSUE THREAD

**Issue by isaacto** [Python-Markdown/markdown#204]
With the following markdown document:

```
Footnote[^FOOT].

[^FOOT]: ``There is a literal `backtick` here.``
```

The backtick within double backtick in the footnote become code tag within code tag.  Of course, the expected behavior is that the inner backtick is left as-is.

**Comment by waylan** [comment]
Thanks for the report @isaacto. To clarify, this only happens to inline code when it appears in the last paragraph of a footnote (try a multi-paragraph footnote or a blockquote or list...). My guess is that something is happening when the "back to footnote in the text" (&#8617;) link is appended to the end of the last paragraph (with a blockquote or a list, a new paragraph is appended after the blockquote or list - so no problem). However, that all happens before any inline patterns are run, so it's not clear to me what difference that should make. You've found a very unusual edge case. In the meantime, you can always [backslash escape](http://daringfireball.net/projects/markdown/syntax#backslash) your literal backticks.
