### ISSUE TITLE
Drop-in replacement for misaka

### ISSUE THREAD

**Issue by techtonik** [Python-Markdown/markdown#206]
Misaka is hard to install on Windows. It would be awesome if python-markdown was its dropin replacement.

**Comment by waylan** [comment]
Its not perfectly clear from the original poster, but I think this is asking that Python-Markdown adopt Misaka's API (there are no questions asked - only statements made). According to Misaka's [repo](https://github.com/FSX/misaka/commit/9accee68b3234c6fc9c6ea7f3998a365d7d2e245), it first appeared two years ago while Python-Markdown has been around one month short of nine years (see the old [change log](https://github.com/waylan/Python-Markdown/blob/master/docs/change_log.txt)). Additionally, last I checked, Python-Markdown was in the top 50 most downloaded packages from PyPI. If anything, it would seem to me that Misaka might want to consider being a drop-in replacement for Python-Markdown. My point is, if Python-Markdown changes its API, that would break a **lot** of existing code. There are many many projects depending on our API as it is - presumably a lot more that Misaka.

For that matter, its not that hard to do anyway (untested - I'm basing this on Misaka's readme):

``` python
try:
    from misaka import html as markdown
except ImportError:
    from markdown import markdown

html = markdown('some text')
```

If there is demand for more, then feel free to create a wrapper around Python-Markdown's Markdown class. But that can live as a third party library.

**Comment by techtonik** [comment]
How said about changing the API? If python-markdown is so awesome and mature, it would not be hard to add an alternative API. The reason I ask for this is because misaka is probably 20-100x times faster than python-markdown, and could be a speedup if installed byside. Compatible API means that I have to depend only on python-markdown for developement, and enjoy processing speed when needed by just adding misaka on production.
