### ISSUE TITLE
Empty image alt causes invalid HTML

### ISSUE THREAD

**Issue by yamatt** [Python-Markdown/markdown#208]
So using

```
![](http://i.imgur.com/khr7Z2U.jpg "cat")
```

will create the following img element

```
<img src="http://i.imgur.com/khr7Z2U.jpg" title="cat" alt />
```

Passing that element in to the XHTML validator from the w3c will cause it to give you an error:

```
required attribute "alt" not specified
```

Where as according to WAI specs an empty alt attirbute is valid and sometimes required.

```
<img src="http://i.imgur.com/khr7Z2U.jpg" title="cat" alt="" />
```

**Comment by waylan** [comment]
I can't seem to replicate this. Which version of markdown are you using?

``` python
>>> import markdown
>>> markdown.version
'2.3.1'
>>> markdown.markdown('![](http://i.imgur.com/khr7Z2U.jpg "cat")')
u'<p><img alt="" src="http://i.imgur.com/khr7Z2U.jpg" title="cat" /></p>'
```

**Comment by yamatt** [comment]
Same version and that is the output for me too. I still get the output on my blog. Perhaps it's to do with the Jinja filter I'm using. I shall investigate. Cheers for the concise example.

**Comment by waylan** [comment]
I'm closing this as it appears to be an issue with a third party tool.
