### ISSUE TITLE
Source code with repeated empty lines is not detected properly

### ISSUE THREAD

**Issue by ZlobnyiSerg** [Python-Markdown/markdown#210]
Example:

<pre>
```
        a

        b
```
</pre>

Results to

`````` html
<p>```
        a</p>
<pre><code>    b
</code></pre>
<p>```</p>
``````

When space between _a_ and _b_ removed, everything become ok:

``` html
<p><code>a
        b</code></p>
```

**Comment by waylan** [comment]
I can't seem to replicate this. Which version are you using.

``` python
>>> import markdown
>>> markdown.version
'2.3.1'
>>> markdown.markdown('\ta\n\n\tb\n')
u'<pre><code>a\n\nb\n</code></pre>'
```

Or, are you trying to use [fenced code blocks](http://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html)? If so, you need to tell markdown to use that extension:

`````` python
>>> markdown.markdown("```\n\t\ta\n\n\t\tb\n```", extensions=['fenced_code'])
u'<pre><code>        a\n\n        b\n</code></pre>'
``````

**Comment by ZlobnyiSerg** [comment]
Ah, all right, everything works ok after adding fenced_code extension. Not very obvious... Closing the issue
