### ISSUE TITLE
Unable to use attr_list on hr tags

### ISSUE THREAD

**Issue by aleray** [Python-Markdown/markdown#213]
Hi,

is it possible to use attr_list on hr tags? I've been trying the following without any success:

``` python
txt = """
hello

* * *
{: class='foo' }
world
"""
# u"<p>hello</p>\n<hr />\n<p>{: class='foo' }\nworld</p>"

txt = """                                       
hello
* * * {: class='foo' }
world           
"""
markdown.markdown(txt, extensions=['attr_list'])
# u"<p>hello\n<em> * </em> {: class='foo' }\nworld</p>"
```

Thanks,

Alex

**Comment by waylan** [comment]
Hmm, interesting. Like h1-6, Hrs are only contained on one line. However, the hr **must** be the only thing on the line so including a attr list causes the line to not be identified as a hr. In most block level elements, the attr list would go on the last line of the content. However, hrs are self-closing tags (meaning they have no content). Predictably, putting the attr list on the line after the hr results in the attr list being in a separate paragraph. Given the syntax and how the parser is implemented, I see no easy way to work around this without a major refactor.

Curious, how do other implementations of attr lists work with hrs? If they don't, then I suspect we shouldn't either.

The fact is, it is easy enough to use raw html for hrs anyway.

```
hello

<hr class='foo' />

world
```
