### ISSUE TITLE
Problem with attr_list

### ISSUE THREAD

**Issue by jpzimmer** [Python-Markdown/markdown#218]
Good morning,
I spotted a problem with the attribute list extension version > Feb 06, 2013  
From this version attributes are no more integrated properly in some element lists.
This is caused by the argument prettify that replaced inline line 136
Is it possible either to return to the argument inline or to set an option that allows to use the argument inline ?
I give you below, a demonstration code of the problem

---
# Test for python markdown attr_list
## python -m markdown -x attr_list test.md > test.html
# Good
- one
- two
  - subtwoone
  - subtwotwo
    - subtwotwoone
- three
  - subthree
# Demonstration of the problem
## Bad with version after Feb 06, 2013
- line 136
- md.treeprocessors.add('attr_list', AttrListTreeprocessor(md), '>prettify')
  ## Good with version Dec 13, 2012 and before
- md.treeprocessors.add('attr_list', AttrListTreeprocessor(md), '>inline')
- one good
  {: .myclass}
- two bad
  {: .myclass}
  - subtwoone good
    {: .myclass}
  - subtwotwo bad
    {: .myclass}
    - subtwotwoone good
      {: .myclass}
- three bad
  {: .myclass}
  - subthree good
    {: .myclass}

---

Great thanks for your work.
Best regards
JP Zimmer

**Comment by waylan** [comment]
Took me a while to figure this report out (github uses markdown - your report might have used code blocks to keep things clear). In any event, after commit 4ff74e3, in any **list item which has child lists**, attr_lists are not recognized. It would appear that some change in insignificant whitespace by the prettify processor has tripped up the attrt_list extension.

I'll have to explore whether I should patch the attrt_list extension to parse the new/different whitespace properly, or switch the order of the processors again - but without breaking the issue resolved by commit 4ff74e3.

Thanks for the report.

**Comment by jpzimmer** [comment]
Good morning,
Sorry for this mistake. I had to do comment on the source.
I have no idea for the moment to help you.
Sorry.
Thank you for your attention

Jean-Philippe Zimmer

Le 2013-05-30 01:24, Waylan Limberg a écrit :

**Comment by waylan** [comment]
Reopening this as the patch does pass tests on Python 3. See [this comment](https://github.com/waylan/Python-Markdown/commit/ea4af0db29a86466e4b8b9e694299054565a29ca#commitcomment-3730909).
