### ISSUE TITLE
Escaping with Bleach

### ISSUE THREAD

**Issue by akhayyat** [Python-Markdown/markdown#225]
When escaping Markdown markup with Bleach, `>` are always escaped and replaced with `&gt;`, making blockquotes impossible.

My first thought was to "teach" Bleach to handle `>` correctly, but I don't think that is appropriate, as Bleach is not Markdown-specific, and cannot be bothered to learn about every markup that can include HTML.

My next thought is to "teach" the Markdown parser about escaped `>`'s that would otherwise result in a blockquote.

Using a regex similar to the one used to transform `>` into a blockquote, but that looks for `&gt;` instead of `>`, and possibly packaging it into a Markdown extension: unescape_blockquotes.
- Does this make sense?
- Is there a better way to solve this problem?

**Comment by akhayyat** [comment]
Admittedly, things will be easier if Markdown is run before Bleach.
This discussion, however, assumes that Bleach must be run first.
Example: if I want to store safe Markdown text, and render it later.

**Comment by waylan** [comment]
I would not try running bleach on markdown text. Bleach uses html5lib under the hood, and I would expect the output to be mangled by bleach. Yes, we recommend Bleach as a way to sanitize markdown - but only after rendering the markdown text as html.

**Comment by Zequez** [comment]
There are multiple reasons using Bleach to sanitize Markdown is VERY lacking and has a lot of issues:
- You can't disallow the user from writing HTML tags themselves
- You have to specify all the tags and attributes that you want to allow, is there a list somewhere of all the tags and attributes that can be generated by markdown?
- If you use a plugin that outputs an special tag with classes or something (for example to embed a YouTube video), you don't want to user to be able to be able to put arbitrary iframes in markdown, and now you have to write an special callable filter for bleach to allow this.
- If you process something like `<script></script>Hi!` with markdown it outputs `'<script></script>\n\n<p>Hi</p>'`, if you now process that with bleach allowing `<p>` and disallowing `<script>`, the script tags end up outside a paragraph.

**Comment by waylan** [comment]
As you demonstrate in your examples, sanitizing HTML is complicated and unique to each use case. There is no one-size-fits-all solution. Each situation needs to be custom built for that situation. The half-backed solution we offered gave people a false sense of security and so its being deprecated. There is no way we could build a system that was actually safe for everyone. Yes, that means that if you use Bleach, it could be a lot of work and you should probably have a security expert to do the work (and/or audit the work), but that it the only way you will get anywhere near true security anyway. And I am certainly not that expert.

May I suggest reading this for an explanation of why excluding raw HTML from Markdown is not in itself safe: https://michelf.ca/blog/2010/markdown-and-xss/

To get you started with Bleach, I would suggest [yourcelf/bleach-whitelist](/yourcelf/bleach-whitelist) as a starting point. A list of all tags output by standard Markdown are included along with various other helpful lists.
