### ISSUE TITLE
Define List title with  Attribute Lists support.

### ISSUE THREAD

**Issue by xpol** [Python-Markdown/markdown#236]
It is common we need to link to a define of some item.
So we need the title of a define list (`dt` tag) have an ID so we can link to it.

But current Attribute Lists title does not handle the attribute list.

``` markdown
Title{: #title}
:   The descriptions ....
```

Would render as some thing like:

**Title{: #title}**
    The descriptions ....

**Comment by waylan** [comment]
This was just implemented in commit a9ca97325e903 last week. It will be available in the  next release.
