### ISSUE TITLE
disable guessing in codehilite

### ISSUE THREAD

**Issue by skurfer** [Python-Markdown/markdown#24]
I’d like the option to disable syntax guessing. Something like `codehilite(guess_syntax=False)`.

I feel like I’m starting 80% (a completely made up number) of my blocks with “:::text” to avoid weird colors here and there. So I’m adding markup to make it _not_ do something, where I’d prefer to just add it where I want something to happen.

I could attempt this myself and submit a pull request if you prefer. Thanks.

**Comment by waylan** [comment]
A pull request would be welcome.
