### ISSUE TITLE
Abbreviations in links are rendered twice

### ISSUE THREAD

**Issue by astorije** [Python-Markdown/markdown#240]
Hi,

I am using standard Python (3.3.0 but also appeared on 2.7.x) and Markdown 2.3.1, which has been installed _via_ `pip install Markdown`.

If you consider this file `test.md`:

```
Good: W3C

Bad: [W3C](http://www.w3.org)

*[W3C]: World Wide Web Consortium
```

Then run the following command:

```
$ python -m markdown -x abbr test.md > output.html
```

`output.html` will be generated as:

```
<p>Good: <abbr title="World Wide Web Consortium">W3C</abbr></p>
<p>Bad: <a href="http://www.w3.org"><abbr title="World Wide Web Consortium"><abbr title="World Wide Web Consortium">W3C</abbr></abbr></a></p>
```

So as we can see, the `<abbr />` tag has been generated twice where only one instance was expected.

Just to be sure, is it a bug or am I wrong in the syntax?

**Comment by waylan** [comment]
This is a duplicate of #224 which has already been fixed and will be available in the next release.

**Comment by astorije** [comment]
Outch, sorry about that, I will look closer next time...
