### ISSUE TITLE
slugify should strip HTML tags

### ISSUE THREAD

**Issue by gollmar** [Python-Markdown/markdown#241]
The headerid and toc extensions produce odd IDs when the header contains HTML tags.

For example, 

```
## This header has an <i>italic</i> word
```

produces

```
<h2 id="this-header-has-an-wzxhzdk2italicwzxhzdk3-word">This header has an <i>italic</i> word</h2>
```

**Comment by waylan** [comment]
This is a duplicate of #232 which has already been fixed and will be available in the next release.
