### ISSUE TITLE
What's your opinion about porting Sphinx html_add_permalinks feature to markdown?

### ISSUE THREAD

**Issue by talha131** [Python-Markdown/markdown#245]
Documentation generated via Sphinx shows a permalink to the every heading when you hover on it.
![screen shot 2013-08-29 at 5 08 53 pm](https://f.cloud.github.com/assets/1094724/1049382/e5eedc9c-10a3-11e3-85e4-67843b11c6b7.png)

Sphinx names [this features `html_add_permalinks`](http://sphinx-doc.org/config.html?highlight=permalink#confval-html_add_permalinks).

To the best of my knowledge, [headerid extension](http://pythonhosted.org/Markdown/extensions/header_id.html) does define id attribute of every heading. But it is not visible in the rendered output.

So 

``` text
#header 
```

will appear as

``` html
<h1 id="header">Header</h1>
```

rather than

``` html
<h1 id="header">Header <a href="#header" title="Permalink to header" class="permalink">¶</a></h1>
```

The [only way](http://stackoverflow.com/q/5636191/177116) I could find  to make it work with markdown is

``` markdown
# A header [¶](#a-header) {#a-header}
```

But this is not automatic.

I am curious has there been any attempt to port this feature to markdown? Was it shot down? Or is there an obvious way that I have missed? Basically I want to know the community's opinion about this feature.

Thanks for your time.

**Comment by waylan** [comment]
I seem to recall this discussion taking place back when the [TOC](http://pythonhosted.org/Markdown/extensions/toc.html) extension was added (which imports much some of its functionality from the HeaderId extension). The TOC extension currently has an option (anchorlink) which converts the entire header into a link. IIRC, that behavior was preferred to displaying a pilcrow as the link. I would suggest searching the [list archive](http://sourceforge.net/mailarchive/forum.php?forum_name=python-markdown-discuss) for details.

Regardless of how the link gets added, I suppose it would make sense to break that functionality out into the HeaderId extension like the other functionality shared by both extensions. Pull requests are certainly welcome. :-)

**Comment by talha131** [comment]
Thanks for your response. I sure do want to work on this feature plus "breaking down functionality" that you mentioned.

**Comment by talha131** [comment]
Thanks to @mitya57, this feature has been implemented.
