### ISSUE TITLE
Package not showing up in pip freeze

### ISSUE THREAD

**Issue by chrisspen** [Python-Markdown/markdown#248]
I have markdown==2.3.1 installed in a virtual environment, which is perfectly importable:

```
./.env/bin/python
Python 2.7.3 (default, Aug  1 2012, 05:14:39) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import markdown
>>> markdown.version
'2.3.1'
```

However, when I run `./.env/bin/pip freeze | grep markdown`, nothing shows up. Why is this? This is making it difficult to track server installations using the markdown package, because I don't have the standard way of telling if it's installed, and if so, which version.

**Comment by waylan** [comment]
Hmm, freeze is not a feature of pip I know much about. Is there some specific requirements that pip has for freeze to work with a package? Markdown is just a standard python package using distutils. Nothing fancy going on.

**Comment by chrisspen** [comment]
Sorry, I just double checked, and it seems the fault it mine. It seems the name is case-sensitive, and pip reports it as "Markdown", not "markdown".
