### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by cjrd** [Python-Markdown/markdown#250]
Throughout http://pythonhosted.org/Markdown/extensions/wikilinks.html the wikilinks extension is used as `wikilink` rather than `wikilinks` e.g.

```
>>> html = markdown.markdown(text, 
...     ['wikilink(base_url=/wiki/,end_url=.html)']
... )
```

which doesn't work with python-markdown v.2.3.1, adding the `s` to the end of `wikilink` seems to fix the problem:

```
>>> html = markdown.markdown(text, 
...     ['wikilinks(base_url=/wiki/,end_url=.html)']
... )
```

**Comment by waylan** [comment]
Yes, some years back the extension was renamed to "wikilinks". Apparently, the documentation was not updated properly. A pull request is certainly welcome.
