### ISSUE TITLE
Deprecation warnings on Python 3

### ISSUE THREAD

**Issue by lvella** [Python-Markdown/markdown#254]
I get these warnings when using Python-Markdown together with my Django application on Python 3:

/home/vella/projetos/chroni9/venv/site-packages/markdown/blockprocessors.py:322: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if sibling and sibling.tag in self.SIBLING_TAGS:

/home/vella/projetos/chroni9/venv/site-packages/markdown/blockprocessors.py:518: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if sibling and sibling.tag == 'pre' and len(sibling) and sibling[0].tag == 'code':

/home/vella/projetos/chroni9/venv/site-packages/markdown/treeprocessors.py:279: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for child in currElement.getchildren():

/home/vella/projetos/chroni9/venv/site-packages/markdown/treeprocessors.py:299: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  if child.getchildren():

/home/vella/projetos/chroni9/venv/site-packages/markdown/treeprocessors.py:240: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for child in [node] + node.getchildren():

/home/vella/projetos/chroni9/venv/site-packages/markdown/treeprocessors.py:182: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for child in [node] + node.getchildren():

/home/vella/projetos/chroni9/venv/site-packages/markdown/**init**.py:296: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if newRoot:

**Comment by waylan** [comment]
I wondered when the changes to ElementTree's API would catch up to us. No that we don't support the older versions, its time to update. Thanks for the report.

**Comment by jkempinger-dv** [comment]
@waylan I'm seeing these same deprecation warnings on lines 275 and 276 of markdown/treeprocessors.py in version 2.6.10.

**Comment by waylan** [comment]
@jkempinger-dv this issue was fixed and closed over three years ago. Could you please open a new issue with a full report. Thanks.
