### ISSUE TITLE
Markdown extra is not exposed as parsing tree

### ISSUE THREAD

**Issue by lu-zero** [Python-Markdown/markdown#259]
Noticed in MoinMoin2 since it walks the parsing tree to convert to its internal representation. 

extra syntax such as 

```
code blocks using ~~~
```

Is stored in the tree as element.text `<pre><code>` instead appending the parsing tree to that node.

**Comment by waylan** [comment]
While is may not look like it at first, this is a duplicate of #53. This issue is part of the fix for #53. Of course, patches (pull requests) are welcome.
