### ISSUE TITLE
codehilite should allow setting default language preference

### ISSUE THREAD

**Issue by mgorny** [Python-Markdown/markdown#26]
If I run markdown on a single set of docs where all code examples are in the same language, I don't see a reason to repeat `...python` over and over again. It would be nice if codehilite allowed specifying the common language once.

**Comment by waylan** [comment]
This feels a little to much like feature creep to me. I'm going to say
you have two options. (1) don't define any language and let pygments
guess the language (it does pretty good on all but the shortest of
code snippets) or (2) write your own extension which implements your
feature (we created the API for just this sort of stuff). And, if your
extension gets lots of attention, we'll think about adding it then.

On Wed, Jun 22, 2011 at 2:15 AM, mgorny
reply@reply.github.com
wrote:

> If I run markdown on a single set of docs where all code examples are in the same language, I don't see a reason to repeat `...python` over and over again. It would be nice if codehilite allowed specifying the common language once.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/waylan/Python-Markdown/issues/26

## 

---

\X/ /-\ `/ |_ /-\ ||
Waylan Limberg

**Comment by laurentalacoque** [comment]
I too would dream of such a feature.
I guess it wouldn't be too much hastle to implement too.
a simple 
```.py
extension_configs = { 'codehilite': { 'lang':'python'}}
```
would do the trick.

I have some lisp snippets that aren't recognized by codehighlite in automatic mode.
