### ISSUE TITLE
HTML is escaped inside backticks even with safe_mode=False

### ISSUE THREAD

**Issue by pomel** [Python-Markdown/markdown#263]
It looks inconsistent:

```
In [1]: import markdown
In [2]: markdown.markdown("*<p>qqq</p>*")
Out[2]: u'<p><em><p>qqq</p></em></p>'
In [3]: markdown.markdown("`<p>qqq</p>`")
Out[3]: u'<p><code>&lt;p&gt;qqq&lt;/p&gt;</code></p>'
In [4]: markdown.markdown("_&amp;_")
Out[4]: u'<p><em>&amp;</em></p>'
In [5]: markdown.markdown("`&amp;`")
Out[5]: u'<p><code>&amp;amp;</code></p>'
```

If there is a way to keep HTML entities unchanged inside code block, please tell me.

**Comment by waylan** [comment]
No of course not. Code blocks are for displaying code. Therefore, html must be escaped to be displayed as raw html. I cannot think of any reason why you would want any different behavior. If you want to use html inside pre and/or code tags, then I would suggest using raw html for the pre/code tag as well. You're already writing raw html. How hard is it to  wrap that html in an extra pre/code tag?

**Comment by pomel** [comment]
Yes, I got it. As a matter of act, I indeed don't need to write HTML inside code tag, but I need to preserve some HTML entities (like &nbsp;). I finished with custom extension. Sorry for disturbing you!
