### ISSUE TITLE
A bug in odict.py

### ISSUE THREAD

**Issue by socratescli** [Python-Markdown/markdown#265]
In  "markdown/odict.py", line 10, in iteritems_compat,

```
return iter(getattr(d, _iteritems)())
```

should be

```
return iter(getattr(d, '_iteritems')())
```

**Comment by waylan** [comment]
Are you sure you have the latest version of Python-Markdown? For starters, line 10 contains comments, not code. Secondly, the line you cite does not exist in the file. Could you link to the offending line in the file here on github or better yet, provide a pull request with your proposed fix?

**Comment by waylan** [comment]
Lacking any useful information, I'm closing this issue.
