### ISSUE TITLE
Skipping ./test.md: could not find information about 'title'

### ISSUE THREAD

**Issue by sunxianchao** [Python-Markdown/markdown#268]
alter installed pelican  Markdown, I put a test.md in content and then  make html 
bug console show this error "ERROR: Skipping ./test.md: could not find information about 'title'"

**Comment by sunxianchao** [comment]
in window 7 and i installed it in cgywin

**Comment by waylan** [comment]
What is pelican markdown? Perhaps some python library that uses
Python-Markdown under the hood? More importantly, what it the contents of
test.md? Although, your error message complains about a "title". Markdown
doesn't know anything about "titles" so I'm assuming that your error is
related to pelican not markdown. But without more informatIon I can't be
sure. Could you provide a complete example of the most basic set of
circumstances that replicates the problem?

## 

Waylan Limberg

**Comment by waylan** [comment]
This issue is closed due to a lack of information. I believe this is an issue for Pelican -- whatever that is.

**Comment by Abyetc** [comment]
do you have a solution?

**Comment by rndmh3ro** [comment]
@Abyetc
You need the following line in your markdown-file:
`Title: $YOUR_POST_TITLE`

As described here: http://docs.getpelican.com/en/3.3.0/getting_started.html#file-metadata

**Comment by orzel** [comment]
This can happen if Title is not on the first line of your file. The error message is especially useless, shame on pelican.

**Comment by MartinThoma** [comment]
I suddenly get the same message. Most of my files begin with `---` which worked fine for quite a while.

edit: `sudo pip install markdown --upgrade` (from 2.6.6 to 2.6.8) seems to fix it.

**Comment by perkfly** [comment]
This issue still exists in 2019. The official quick start tutorial does not work without `---`. 

see: http://docs.getpelican.com/en/stable/quickstart.html#create-an-article

**Comment by waylan** [comment]
This is a Pelican issue, not a Markdown issue. I am locking this issue to prevent further discussion here. Any discussion of this issue should be taken to the Pelican project.
