### ISSUE TITLE
ImportError : No module named 'markdown.extensions.*'

### ISSUE THREAD

**Issue by Jubijub** [Python-Markdown/markdown#269]
This is a new install on my computer, using PyCharm 3.0.1, **Python 3.3.2 x64**, with Markdown 2.3.1 freshly installed using pip 1.4.1, the whole thing running on **Windows 8.1 64 bits** with latest patches. I'm using a virtualenv
Note : 
- I have the same error while running the snippet below directly from Command line.
- I reproduce the issue with a virtualenv with no space in the path (c:\Temp\venvmd)
- I reproduce the issue with an older version (2.2.1)
- I **don't** reproduce this issue with Python 2.7.6 x64, with the same parameters otherwise

This happens when running very basic code : 

```
__author__ = 'Jubi'
import markdown

class Converter():
    def toHTML(self, markdown_text):
        print(markdown.Markdown(markdown_text))


if __name__ == "__main__":
    conv = Converter()
    print(conv.toHTML("**dddd**"))
```

Here is the full error message : 

```
C:\Python33\python.exe "C:/Users/Jubi/Documents/My      Documents/Dev/Projects/Blog/Blog/Converter.py"
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\markdown\__init__.py", line 198, in   build_extension
    module = __import__(module_name, {}, {}, [module_name.rpartition('.')[0]])
ImportError: No module named 'markdown.extensions.*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Jubi/Documents/My Documents/Dev/Projects/Blog/Blog/Converter.py", line 11, in <module>
    print(conv.toHTML("**dddd**"))
  File "C:/Users/Jubi/Documents/My Documents/Dev/Projects/Blog/Blog/Converter.py", line 6, in toHTML
    print(markdown.Markdown(markdown_text))
  File "C:\Python33\lib\site-packages\markdown\__init__.py", line 139, in __init__
configs=kwargs.get('extension_configs', {}))
  File "C:\Python33\lib\site-packages\markdown\__init__.py", line 164, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, []))
  File "C:\Python33\lib\site-packages\markdown\__init__.py", line 202, in build_extension
    module = __import__(module_name_old_style)
ImportError: No module named 'mdx_*'

Process finished with exit code 1
```

**Comment by Jubijub** [comment]
issue closed as using markdown.markdown works :)

I would still believe that a better error message (if the function hangs if no parameter is passed forcing the argument or making the error more explict would help. Also avoiding using case sensitive method names would avoid this kind of stuff)

**Comment by waylan** [comment]
Case sensitive method names? You didn't even call any methods. `markdown` is the module. `markdown.Markdown` is the class, and `markdown.markdown` is a wrapper function. Pretty conventional python.

If you want to use the class you need to create an instance first:

```
md_instance = markdown.Markdown()
html =  md_instance.convert(some_text)
```

The [docs](http://pythonhosted.org/Markdown/reference.html#Markdown) should explain the details.
