### ISSUE TITLE
Justification in table rendering does not work in HTML5

### ISSUE THREAD

**Issue by mkasa** [Python-Markdown/markdown#271]
Justification in tables (using the table extension) does not work in HTML5.

Let's consider an example below.

```
|testtest1|testtest2|testtest3|
|--------:|:--------|:-------:|
|right    |     left|   center|
```

This should be rendered like this (in ASCII art):

```
|testtest1|testtest2|testtest3|
|---------|---------|---------|
|    right|left     | center  |
```

and works fine without CSS, but does not work at least in some cases.
After a couple of minutes of struggling, I found it was the same problem with [this](http://stackoverflow.com/questions/2546857/why-align-center-not-overriding-on-text-alignright).

A column in the last row is always rendered using `<td align="...">` in markdown/extensions/tables.py, although `align` property is deprecated (at least) in HTML5 (I don't know when it was deprecated) so it will not override the text justification specified in CSS properly (I confirmed it with Chrome 31.0.1650.57m on Windows). It should use `<td style="text-align: ...">` instead when the output format is compatible with CSS.

**Comment by waylan** [comment]
Thanks for the report.

It looks like the align attribute was "deprecated" in [HTML4](http://www.w3.org/TR/html401/present/graphics.html#h-15.1.2) and is now "obsolete" in [HTML5](http://www.w3.org/TR/html-markup/table.html).

**Comment by waylan** [comment]
The table extension exists so that Python-Markdown maintains feature parity with PHP Markdown Extra. Therefore, the table extension is an exact clone of PHP's and nothing more. That being the case, I'm following PHP's [policy](https://github.com/michelf/php-markdown/issues/58#issuecomment-16021096) on this issue and closing this wontfix.

**Comment by mthuurne** [comment]
Would it be acceptable to have an option to have the extension put the alignment in a `style` attribute? I'd be willing to submit a pull request if it has any chance of getting accepted.

I validate all my generated HTML using the validator.nu checker and this is causing a lot of red lines in the test report.

**Comment by waylan** [comment]
@mthuurne you are free to build your own table extension which has whatever behavior you want. Whether you start from scratch or fork the existing extension (within the confines of the license), doesn't matter to me. For that matter, perhaps one of the existing [third party extensions][1] already meets your needs.

[1]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

**Comment by mthuurne** [comment]
I already implemented a workaround by having a `Treeprocessor` change the `align` attribute to `style`. But I was hoping for a solution that would lead to less code to maintain, while forking the extension would increase the maintenance burden instead (it's only ~200 lines, but that's still a lot more than the workaround).
