### ISSUE TITLE
can't create footnote definition lists

### ISSUE THREAD

**Issue by lusitania** [Python-Markdown/markdown#273]
Hi

I was writing this:

```
Establish a good signature[^!good signature] ...
[^!good signature]: A perfect signature ...
```

I expected to get something like this (according to your documentation):

> Establish a good signature<sup>1</sup> ... (or even better <a href="#good_signature">good signature</a>)
> ...
> 
> <dl>
> <dt id="good_signature">good signature</dt>
> <dd>A perfect signature ...</dd>
> </dl>

But instead I get a regular footnote. No definition list.

This is my markdown invocation:

```
mdobj = markdown.Markdown(['abbr', 'def_list', 'footnotes'])
self.html_content = mdobj.reset().convert(self.md_content)
```

**Comment by waylan** [comment]
I'm not sure why you think that should work. The reference to a footnote is never part of the footnote. So `[^!good signature]:` only identifies the text that follows as a footnote, but is is not part of the footnote itself. If you want that text as a term, then you need to add it as a term. Try this instead:

```
Establish a good signature[^!good signature] ...

[^!good signature]: good signature
    : A perfect signature ...
```

Remember that everything except the first line of a footnote must be indented one level. Perhaps it would be more clear if we add some more items to the list:

```
Establish a good signature[^!good signature] ...

[^!good signature]: 
    good signature
    : A perfect signature ...

    term 2
    : definition two

    term 3
    : definition three
```

In that example I've also left the first line blank and moved the first line of text down with the indented text. Now you can see the entire body as a unit. This is a handy little (undocumented) feature of footnotes which really helps work out block level issues. When my footnotes contain anything other than a paragraph, I always leave the first line blank for this very reason.

I'm closing this as there is no bug here.

**Comment by lusitania** [comment]
I see. To answer your question as to why I think my snipped should have worked, please allow me to [quote](http://pythonhosted.org/Markdown/extensions/footnotes.html):

```
Footnotes[^1] have a label[^label] and a definition[^!DEF].

[^1]: This is a footnote
[^label]: A footnote on "label"
[^!DEF]: The definition of a footnote.
```

From what I understand (thanks to your detailed enhancement to my snipped) the intended functionality could have been achieved with `[^label]` or `[^good signature]`, already. Yes? There was no (obvious) need for a `[^!DEF]` unless DEF(inition) means "definition list".

So yes, I did some reading between the lines. It would be great if you could clarify the intended use of `[^!` in the documentation.

Thank you

**Comment by waylan** [comment]
@lusitania the use of the `!` was simply to demonstrate that any text can be used in a label. It has no special meaning. I suppose as that same character has special meaning for images, it is not too unreasonable to assume it had special meaning here, especially as it was used specifically in conjunction with the word "definition". An unfortunate coincidence to be sure. I just made some changes to the docs that should make things clearer.
