### ISSUE TITLE
Nested ULs have bad syntax.

### ISSUE THREAD

**Issue by bearbin** [Python-Markdown/markdown#277]
Nested ULs, i.e.

```
 * an item
  * another item inside
  * and another
```

don't work properly. They proudce the deeper elements inside a list inside their own li element, like this:

```
<ui>
  <li>An item</li>
  <li><ul><li>Another item inside</li></ul></li>
  <li><ul><li>and another</li></ul></li>
</ul>
```

Rather than having the second-level list being part of the first list item.

**Comment by waylan** [comment]
Hmm, I'm not getting that at all:

``` python
>>> t = ''' * an item
...   * another item inside
...   * and another'''
>>> print markdown.markdown(t)
<ul>
    <li>an item</li>
    <li>another item inside</li>
    <li>and another</li>
</ul>
```

Of course, as Python-Markdown [requires](http://pythonhosted.org/Markdown/index.html#differences) four spaces of indent, let's fix that input up:

``` python
>>> t = '''* an item
...     * another item inside
...     * and another'''
>>> print markdown.markdown(t)
<ul>
    <li>an item
        <ul>
            <li>another item inside</li>
            <li>and another</li>
        </ul>
    </li>
</ul>
```

While I have fixed up the (insignificant) whitespace in the output to make it easier to reed, the output is exactly what we should be getting. Can you provide an example that fails?

**Comment by bearbin** [comment]
I think the underlying issue is just not enough whitespace (why 4, btw, everything else accepts 2?) but I'm sure it did it. Anyway, closing.
