### ISSUE TITLE
Friendly end-user documentation

### ISSUE THREAD

**Issue by nicktimko** [Python-Markdown/markdown#281]
Putting it lightly, the "canonical" link for describing Markdown syntax (http://daringfireball.net/projects/markdown/syntax) is a rather dated-looking, ponderous tome that, while espousing how "easy-to-read and easy-to-write" it is, is anything but, droning on and on for a couple screens until it gets to something about how to use it.

In looking for a somewhat friendly guide to link users to (because I'm lazy), I was curious if adding an end-user cheat-sheet to the Python-Markdown documentation would be a well-received idea.  It would be extremely clean and lack a "Philosophy" section, looking either what's on the [Wikipedia page](http://en.wikipedia.org/wiki/Markdown) or [StackExchange pages](http://stackoverflow.com/markdown), tuned to accommodate the specifics of PyMD (what few there are).

Granted, it's not so straightforward: in configuring how MD is used in whatever app, there can't be a unified guide to cover everything.  Is there some happy medium between nothing and rolling-your-own?

**Comment by waylan** [comment]
I have to disagree with your assessment of the Philosophy section of the syntax documentation. That section has been the determining factor in Python-Markdown's behavior more often that you would think. If a user doesn't understand that section, then they will be frustrated and annoyed by many of markdown's edge cases. I regularly get bug reports and feature requests that are clearly not bugs and/or outside the scope of markdown only when taking the Philosophy section into consideration. IMO, every user of markdown **_should**_ read that section.

That said, a "quick-start" or "cheat-sheet" certainly makes sense. In fact, one already exists to the right of Gruber's [Dingus](http://daringfireball.net/projects/markdown/dingus).

Aside from copying either of those documents verbatim (which would require appropriate permission from the copyright holder) I have no desire or interest in producing any alternate documentation of Markdown's syntax. There is already too much [divergence](http://johnmacfarlane.net/babelmark2/faq.html#what-are-some-examples-of-interesting-divergences-between-implementations) between implementations. [Ideally](http://johnmacfarlane.net/babelmark2/faq.html#why-does-it-matter-whether-implementations-agree), there would be no divergence. Of course, as noted in our documentation, Python-Markdown [differs](http://pythonhosted.org/Markdown/index.html#differences) where there are bugs in the reference implementation. Aside from those bugs however, our primary [goal](http://pythonhosted.org/Markdown/index.html#goals) is to follow "the syntax rules and the behavior of the original (markdown.pl) implementation as reasonably as possible." That being the case, why would we need our own set of syntax rules (aside from a verbatim copy of the existing rules)? Wouldn't that just open up the possibility for more divergence?

I will not be adding any additional syntax documentation for the reasons cited above. This is being closed wontfix.
