### ISSUE TITLE
Fenced code blocks with indentation on lists

### ISSUE THREAD

**Issue by marcinkuzminski** [Python-Markdown/markdown#283]
Not sure if this is a bug. But python-markdown has support for fenced code blocks with syntaxt highlight eg:

![screen shot 2014-02-07 at 17 50 04](https://f.cloud.github.com/assets/163648/2111963/faaf11a8-9017-11e3-93e0-1b0e22981045.png)

That renders to:

``` ruby
 def index
 puts "hello world"
 end
```

However when this is used with lists, with identation the rendered code is wrong
![screen shot 2014-02-07 at 17 51 40](https://f.cloud.github.com/assets/163648/2111978/2b0310de-9018-11e3-81b1-ccc0ba78fe95.png)
- item
- item2
  
  ``` ruby
   def index
   puts "hello world"
   end
  ```
  
  This is how github rendered it, this is what i see on my end:

![screen shot 2014-02-07 at 17 52 31](https://f.cloud.github.com/assets/163648/2111985/4568ded6-9018-11e3-8c25-5efd32128960.png)

**Comment by waylan** [comment]
This is a duplicate of #53. Currently, fenced code blocks only work at the root level.
