### ISSUE TITLE
Add support for tables converting to HTML

### ISSUE THREAD

**Issue by Alexey-T** [Python-Markdown/markdown#290]
I see that tables in MD code not ok previewed in HTML page. Example file from SF.net page with tables:

```
Possible values of lexer id:

Id | Meaning
---|-----------
`LEXER_FOR_FILE` | Returns name of lexer for entire file.
`LEXER_FOR_CARET` | Returns name of lexer at caret position.
```

**Comment by waylan** [comment]
Are you aware of the existing [tables extension](https://pythonhosted.org/Markdown/extensions/tables.html) or are you requesting support for a different table implementation?

If the former, just enable the extension as per the [documentation](https://pythonhosted.org/Markdown/extensions/index.html).

If the later, I suggest you read my explanation to #74.

In the event that I've misunderstood your request and you have encountered a bug in the existing table extension, please provide more specific information.

**Comment by Alexey-T** [comment]
I didn;t know it. New notes: a) ur URL https://pythonhosted.org/Markdown/extensions/index.html shows help with wrong cased id: `markdown.markdown(....)`. must be `markdown.Markdown`. b) How to enable borders for HTML tables? i see no table borders for my MD file shown above

**Comment by waylan** [comment]
@Alexey-T in response to your comments:

A) Both are valid, depending on what you are trying to do. The docs demonstrate usage in the simple case. See the [library reference](https://pythonhosted.org/Markdown/reference.html#the-details) for a full explanation.

B) styling HTML is beyond the scope of Markdown. I would suggest searching for information on how to style HTML tables (hint, use CSS).

As there is no bug here, I am closing this issue.

**Comment by MKrabs** [comment]
If anyone is having this issue, and the site isn't loading as well for you:

from: https://python-markdown.github.io/extensions/tables/
`markdown.markdown(some_text, extensions=['tables'])`
