### ISSUE TITLE
Test error with Python 3.1 and 3.2

### ISSUE THREAD

**Issue by Arfrever** [Python-Markdown/markdown#295]
Markdown test suite has 1 error with Python 3.1 and 3.2. This error does not occur with other versions of Python.

```
$ PYTHONPATH=build/lib nosetests-3.2
.............................................................................................S.......E.................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................................................................................................
======================================================================
ERROR: TestSyntax: "extensions/smarty"
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/Python-Markdown/tests/__init__.py", line 109, in __call__
    'output.\n\n%s' % (input_file, ''.join(diff)))
tests.util.MarkdownSyntaxError: Output from "/tmp/Python-Markdown/tests/extensions/smarty.txt" failed to match expected output.

--- /tmp/Python-Markdown/tests/extensions/smarty.html
+++ actual_output.html
@@ -1,21 +1,21 @@
-<p>1440&ndash;80&rsquo;s<br />
+<p>1440&ndash;80&lsquo;s<br />
 1440&ndash;&lsquo;80s<br />
 1440&mdash;&lsquo;80s<br />
 1960s<br />
-1960&rsquo;s<br />
+1960&lsquo;s<br />
 one two &lsquo;60s<br />
 &lsquo;60s</p>
 <p>It&rsquo;s fun. What&rsquo;s fun?<br />
-&ldquo;Isn&rsquo;t this fun&rdquo;? &mdash; she said&hellip;<br />
+&rdquo;Isn&rsquo;t this fun&rdquo;? &mdash; she said&hellip;<br />
 &ldquo;&lsquo;Quoted&rsquo; words in a larger quote.&rdquo;<br />
-&lsquo;Quoted &ldquo;words&rdquo; in a larger quote.&rsquo;<br />
-&ldquo;quoted&rdquo; text and <strong>bold &ldquo;quoted&rdquo; text</strong><br />
-&lsquo;quoted&rsquo; text and <strong>bold &lsquo;quoted&rsquo; text</strong><br />
+&rsquo;Quoted &ldquo;words&rdquo; in a larger quote.&rsquo;<br />
+&rdquo;quoted&rdquo; text and <strong>bold &ldquo;quoted&rdquo; text</strong><br />
+&rsquo;quoted&rsquo; text and <strong>bold &lsquo;quoted&rsquo; text</strong><br />
 em-dashes (&mdash;) and ellipes (&hellip;)<br />
-&ldquo;<a href="http://example.com">Link</a>&rdquo; &mdash; she said.</p>
+&rdquo;<a href="http://example.com">Link</a>&rdquo; &mdash; she said.</p>
 <hr />
 <p>Escaped -- ndash<br />
 'Escaped' "quotes"<br />
 Escaped ellipsis...</p>
 <p>&lsquo;Escaped "quotes" in real ones&rsquo;<br />
-'&ldquo;Real&rdquo; quotes in escaped ones'</p>+'&rdquo;Real&rdquo; quotes in escaped ones'</p>

----------------------------------------------------------------------
Ran 298 tests in 3.564s

FAILED (SKIP=76, errors=1)
```

**Comment by waylan** [comment]
I'm assuming the changes in Pull #287 broke this but I don't have the time to look at it right now. Perhaps @mitya57 would know more about it.

**Comment by mitya57** [comment]
Thanks for reporting the bug.

First, that was not caused by #287, this bug was here from the beginning of smarty extension.
Then, it looks like an issue in Python (< 3.3) to me. This example produces a match with Python 3.3, but not with 3.2:

``` python3
>>> import re
>>> r = "(?<=[^\\u0002])'"
>>> re.search(r, "80's")
```

Also, @waylan, is there any way I can avoid passing strings with junk to the inline pattern? Currently, my `SubstituteTagPattern` consumes strings like:

```
1440\x02klzzwxh:0007\x0380\x02klzzwxh:0010\x03\x02klzzwxh:0000\x031440\x02klzzwxh:0008\x03
```

… and so on, and has to apply the regex to such strings. I would prefer if it acted only on "clean" parts instead.

**Comment by Arfrever** [comment]
However `re.search("(?<=[^\u0002])'", "80's")` works in Python 3.1 and 3.2.

**Comment by waylan** [comment]
> Also, @waylan, is there any way I can avoid passing strings with junk to the inline pattern? Currently, my `SubstituteTagPattern` consumes strings like:
> 
>    1440\x02klzzwxh:0007\x0380\x02klzzwxh:0010\x03\x02klzzwxh:0000\x031440\x02klzzwxh:0008\x03
> 
> ... and so on, and has to apply the regex to such strings. I would prefer if it acted only on "clean" parts instead.

@mitya57, Unfortunately, no, not within an inline pattern. Those placeholders are what allow nesting of inline elements. So, for example, both of the following work:

```
[**foo**](/bar)

**[foo](/bar)**
```

As it stands now, the link pattern runs first, which in the first instance would work fine without placeholders, however it would fail for the second. And if we change the order of the patterns, then the first would fail while the second would work. Why?

Let's take the second example above. To start with, the entire line is inserted in a paragraph. For simplcities sake, I'll represent that ElementTree Element's attributes as JSON. It would look this this:

```
{
    tag = 'p',
    text = '**[foo](\bar)**',
    children = [],
    tail = ''
}
```

Then after we run the first inline pattern, namely the link pattern, we now have:

```
{
    tag = 'p',
    text = '**',
    children = [
        {
            tag = 'a',
            text = 'foo',
            attrs = {
                href = '/bar'
            },
            children = [],
            tail = '**'
        }
    ],
    tail = ''
}
```

Now, how do you propose we run a regex to test for that link being wrapping in strong syntax? It still is, but the opening token is in the text attr of the p element and the closing token is in the tail attr of the child a element. The solution we employ is to use a placeholder. Therefore, instead, our ElementTree looks like this:

```
{
    tag = 'p',
    text = '**\x02klzzwxh:001\x03**',
    children = [],
    tail = ''
}
```

And that gives us something (the p element's text attr) we can run the regex on. Once all inline patterns have run, we then swap all those placeholders out for the actual elements.

To be honest, I'm not crazy about that solution myself, but it works ...mostly (see #253 & #161). The solution came out of a GSoC project and was better than anything we had, so we adopted it. However, I would be open to other solutions as long as our current extension API continues to work as is.
