### ISSUE TITLE
TypeError with third party extensions 

### ISSUE THREAD

**Issue by chewnoill** [Python-Markdown/markdown#300]
trying to import a third party extension 

``` python
import unittest
import markdown
import pyembed.markdown


class Test(unittest.TestCase):


    def testName(self):

        ext = {"pyembed.markdown":[]}
        markdown.markdownFromFile("thisisatest.md","out.html",extensions=ext)
        pass
```

```
Traceback (most recent call last):
  File "...\test.py", line 17, in testName
    markdown.markdownFromFile("thisisatest.md","out.html",extensions=ext)
  File "...\markdown\__init__.py", line 448, in markdownFromFile
    md = Markdown(**kwargs)
  File "...\markdown\__init__.py", line 137, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "...\markdown\__init__.py", line 163, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, []))
  File "...\markdown\__init__.py", line 200, in build_extension
    [module_name.rpartition('.')[0]])
TypeError: Item in ``from list'' not a string
```

force convert to string fixed error:

``` python
module = __import__(module_name, {}, {}, [str(module_name.rpartition('.')[0])])
```

**Comment by waylan** [comment]
You appear to be passing the extension keyword a dict, but it only accepts a list. See the [docs](https://pythonhosted.org/Markdown/reference.html#markdown) for the extensions keyword. Try `ext = ["pyembed.markdown"]` and I think you'll find it works fine.

**Comment by chewnoill** [comment]
its still fails

```
Traceback (most recent call last):
  File "...\test.py", line 16, in testName
    markdown.markdownFromFile("thisisatest.md","out.html",extensions=["pyembed.markdown"])
  File "...\markdown\__init__.py", line 446, in markdownFromFile
    md = Markdown(**kwargs)
  File "...\markdown\__init__.py", line 137, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "...\markdown\__init__.py", line 163, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, []))
  File "...\markdown\__init__.py", line 200, in build_extension
    [module_name.rpartition('.')[0]])
TypeError: Item in ``from list'' not a string
```

**Comment by waylan** [comment]
What happens when you import the module yourself?

```
from pyembed import markdown
```

By the way, you probably want to rename that module as it would clash with the markdown module.

**Comment by chewnoill** [comment]
it imports just fine, its not my extension I pulled it from here:

https://github.com/pyembed/pyembed-markdown

it looks like the problem is that rpartition is converting the string to unicode, and import doesn't like it:

``` python
...
print module_name,module_name.rpartition('.')[0]
print type(module_name),type(module_name.rpartition('.')[0])
...
```

```
...
pyembed.markdown pyembed
<type 'str'> <type 'unicode'>
...
```

looks like the issue has been reported in other projects as well

https://github.com/toastdriven/django-tastypie/issues/1005

removing 

``` python
from __future__ import unicode_literals
```

fixed it there.

**Comment by waylan** [comment]
Ok, that could be the issue. I'll have to look into it. Although, to be both PY2 and PY3 comparable, I don't think we can remove the import of unicode_literals.

In the meantime, my suggestion would be to import the extension and pass an instance in, which is the recommended way anyway.

```
from pyembed.markdown import PyEmbedMarkdown
markdown.Markdown(extensions=[PyEmbedMarkdown()])
```

That is the recommended way both in the Pyhon-Markdown docs and in the PyEmbed-Markdown docs.

**Comment by waylan** [comment]
Hmm, I can't seem to replicate this.

``` pycon
>>> import markdown
>>> md = markdown.Markdown(['markdown.extensions.footnotes'])
>>> md.registeredExtensions
[<markdown.extensions.footnotes.FootnoteExtension object at 0x00000000022960F0>]
>>> extra = __import__('markdown.extensions.extra', {}, {}, [u'markdown.extensions'])
>>> extra
<module 'markdown.extensions.extra' from 'markdown/extensions/extra.py'>
```

If the issue was that rpartition was returning unicode, then both of the above should have failed. But they do not on both Linux and Windows machines in both Python 2.7 & 3.3.

I'm inclined to close this unless someone can provide me with a very basic example that fails.

**Comment by chewnoill** [comment]
try this instead:

``` python
>>> extra = __import__('markdown.extensions',{},{},[u'markdown'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Item in ``from list'' not a string
>>> extra = __import__('markdown.extensions',{},{},['markdown'])
>>> extra
<module 'markdown.extensions' from '/usr/lib/python2.7/dist-packages/markdown/extensions/__init__.pyc'>
```

**Comment by waylan** [comment]
Ok, I got it. Here's the simple example I was looking for to demonstrate the problem. First on the commandline (bash) set up some modules:

``` bash
$ mkdir foo
$ touch foo/__init__.py
$ mkdir foo/bar
$ touch foo/bar/__init__.py
$ touch foo/baz.py
```

And now, from python try to import them using `__import__` where the `from_list` argument is unicode:

``` pycon
>>> baz = __import__('foo.baz', {}, {}, u'foo')
>>> bar = __import__('foo.bar', {}, {}, u'foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Item in ``from list'' not a string
```

When importing a standard `somefile.py` file, no problem exists, but when importing an `__init__.py` file an error is raised. Seems to me like a bug in Python, but we can work around it easily enough. Thanks for the report @chewnoill.
