### ISSUE TITLE
numbering heading support

### ISSUE THREAD

**Issue by fishfly3384** [Python-Markdown/markdown#304]
pandoc supports numbering headings, e.g.,

markdown like:

```
# head1
## head11
## head12
```

will be rendered as:
1 head1
1.1 head11
1.2 head12

I have implemented a extension to do this:
https://github.com/fishfly3384/sublime-evernote/blob/master/markdown/extensions/numbered_heading.py

**Comment by waylan** [comment]
@fishfly3384, if you would like to make others aware of your extension, then I suggest listing it on the [wiki](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions) - which is editable by anyone with a Github account.

If you are proposing that your extension be included with Python-Markdown, I will decline at this time. List it on the wiki, and if it becomes wildly popular, then we will reconsider.
