### ISSUE TITLE
Bad performance when reusing markdown.Markdown instance.

### ISSUE THREAD

**Issue by itsjohncs** [Python-Markdown/markdown#305]
I'm not sure whether this is a bug or ambiguous documentation, but I'm pretty sure it's one of the two.

In the documentation it mentions that if you want to process multiple documents it might make sense to reuse a single `markdown.Markdown` instance ([see here](http://pythonhosted.org//Markdown/reference.html#the-details)). The Flask-Markdown plugin took this to heart and [uses a single instance for the lifespan of the process](https://github.com/dcolish/flask-markdown/blob/master/flaskext/markdown.py#L74).

Unfortunately, this causes performance to degrade (unbounded) as the number of documents processed increases due to (I think) an [ever growing stash of HTML blocks](https://github.com/waylan/Python-Markdown/blob/master/markdown/postprocessors.py#L53).

**Comment by itsjohncs** [comment]
Here's some code to observe the issue:

``` python
import markdown
import time

test_document = """Hello world!

<code>This is some code</code>

Alright, bye world!
"""

USE_ONE_INSTANCE = True
if USE_ONE_INSTANCE:
    the_instance = markdown.Markdown()
    get_instance = lambda: the_instance
else:
    get_instance = lambda: markdown.Markdown()

for i in xrange(10):
    start_time = time.clock()
    for j in xrange(100):
        get_instance().convert(test_document)
    print time.clock() - start_time
```

Outputs

```
0.079565
0.166389
0.254312
0.360932
0.432005
0.520697
0.608689
0.713295
0.777396
0.871599
```

**Comment by waylan** [comment]
Yes, this is why the [documentation](http://pythonhosted.org//Markdown/reference.html#convert) also recommends calling the `reset()` method between each call to `convert()`. Reset clears all that metadata in the class so the next document starts clean. The advantage is that the entire parser doesn't need to be rebuilt. So in your test above, try:

```
get_instance().reset().convert(test_document)
```

So why not call reset within convert? There are some use cases where you may not what to call reset. For example, on the home page of a blog you may have multiple posts in which there are footnotes. You don't what duplicate footnote references on the same page so in that case you would not call reset between calls to convert for each post. However, those types of use cases are rare. Normally a call to reset would be desired. A pull request which clarified the documentation is certainly welcome.

**Comment by itsjohncs** [comment]
Very reasonable, and definitely a documentation issue then. Thank you for the prompt response! I will hopefully make a patch to clarify the documentation then.
