### ISSUE TITLE
safe_mode escape causes URLs with colons to disappear

### ISSUE THREAD

**Issue by sethrosenblum** [Python-Markdown/markdown#307]
When using Markdown with `safe_mode='escape'`, passing in a link with a colon in the query string causes the full link to disappear from the resulting markup.

```
$ python
Python 2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>> markdown.version
'2.4'
>>> md_string = "[My Link](https://www.google.com/?parameter=a:b)"
>>> md = markdown.Markdown()
>>> md.convert(md_string)
u'<p><a href="https://www.google.com/?parameter=a:b">My Link</a></p>'
>>> md = markdown.Markdown(safe_mode='escape')
>>> md.convert(md_string)
u'<p><a href="">My Link</a></p>'
```

It might make sense for the colon to be URL escaped at this point, but certainly not for the link to disappear entirely.

**Comment by waylan** [comment]
As I stated in response to  #301:

> With safe_mode on, we don't allow colons in links to avoid cross site scripting ([XSS](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet)) attacks (the comments in the [code](https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L330) explain more). Sorry we are not going to change this and open a potential security hole (thus I've closed this issue). Of course, you are welcome to create your own extension which works around this. Or better yet, rather than using `safe_mode`, run the output of markdown through an HTML sanitizer like [Bleach](https://github.com/jsocol/bleach). In fact, I recommend Bleach over our own `safe_mode`.
