### ISSUE TITLE
Nested markdown infinite loop

### ISSUE THREAD

**Issue by nordin** [Python-Markdown/markdown#308]
Nested markdown and extra sometimes loops forever in 2.4 (but not in 2.3.1), e.g.:

```
import markdown

print markdown.markdown("""<div markdown="1">

<h1>1</h1>
<h2>2</h2>

</div>""", ['extra'])
```

**Comment by waylan** [comment]
@nordin thanks for the report. I can confirm that this is a problem. It looks like this was introduced in PR #260 and/or #266. @ryneeverett, that was your work -- Any idea what could be causing it? I haven't been able to look too closely yet.

**Comment by ryneeverett** [comment]
Well since the inner headers are being parsed with markdown, they need to follow markdown's rules. We've run into this one before:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines...

Headers are block-level elements, and if you put a blank line between the headers the issue does not occur.

**Comment by nordin** [comment]
Thanks for looking into this. Changing `h1`/`h2` to `span` or putting `<span>1</span><span>2</span>` on one line also hangs. All cases uses 100% CPU until python is killed.

**Comment by ryneeverett** [comment]
Agreed. There is indeed an infinite loop in my code. I'm looking into how to fix it without introducing new bugs.
