### ISSUE TITLE
early list termination with multi-paragrah list items containing a blank line

### ISSUE THREAD

**Issue by minektur** [Python-Markdown/markdown#313]
```
#!/usr/local/bin/python2.7
from markdown import markdown
testinput = """* a b
  c"""
output = markdown(testinput)
print output
```

Yields

```
<ul>
<li>a b</li>
</ul>
<p>c</p>
```

When it should yield

```
<ul>
<li><p>foo</p>

<p>bar</p></li>
</ul>
```

at least according to http://daringfireball.net/projects/markdown/dingus

data may be available at: http://pastebin.com/fiCx80P4

**Comment by minektur** [comment]
hm... seems if I make 4 spaces instead of 2 on the last line after the break, It works.  Is that the spec?  where is the spec? :)

**Comment by waylan** [comment]
I would suggest reading the [Differences](https://pythonhosted.org/Markdown/index.html#differences) section of the docs, specifically the second list item: "Indentation/Tab Length". As stated there, this is not a bug, but the intended behaviour. The bug is in other implementations.
