### ISSUE TITLE
Indented HTML with line breaks

### ISSUE THREAD

**Issue by greggman** [Python-Markdown/markdown#318]
I noticed this don't seem to work

```
1.  This is some stuff

    here's some
    more stuff at the
    same indent

    <p>now for whatever reason

    i need some html</p>

    then I want to continue
    to that I'll get correct numbering
    of the next section

2. the next section
```

Repasted below such that github markdown will format it 
-   A bullet so I don't have to change indentation of the pasted code from above
  1.  This is some stuff
     
     here's some
     more stuff at the
     same indent
     
     <p>now for whatever reason
     
     i need some html</p>
     
     
     then I want to continue
     to that I'll get correct numbering
     of the next section
  2. the next section

With Python-Markdown that inner HTML gets munged into

```
<p><p>now for whatever reason</p>
<p>i need some html</p></p>
```

Those extra `<p>` that were inserted break the HTML.

**Comment by waylan** [comment]
@greggman, may I suggest reading the [syntax rules](http://daringfireball.net/projects/markdown/syntax#html), which state in part (emphasis added):

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, _and the start and end tags of the block should **not** be indented with tabs or spaces_. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

In other words, block-level HTML cannot be nested in a list, blockquote or anything else. It can only be used at the root level of the document. While some markdown implementations do not enforce this rule, Python-Markdown does, with no plans to change in the foreseeable future.

Regarding the output of invalid HTML, I think it is interesting to note that the very next sentence of the rules address the issue of `<p>` tags wrapping block-level HTML — as if to suggest that when you don't follow the rule in the preceding sentence, you should expect this invalid HTML. In fact, this is exactly what the reference implementation does. See [babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+a+list%0A%0A++++%3Cp%3EA+nested+raw+HTML+paragraph%3Cp%3E) for examples of most implementations following the rule.

As this is **not** a bug, I'm closing it as “won't fix”.
