### ISSUE TITLE
Links break if they contain underscores

### ISSUE THREAD

**Issue by Wilfred** [Python-Markdown/markdown#32]
Example:

```
[a b c](/a_b_c)
```

Becomes:

```
<p><a href="/aklzzwxh:0000bklzzwxh:0001c">a b c</a></p> 
```

**Comment by waylan** [comment]
I can't seem to reproduce this. Are you sure you are using the latest code in the repo?

``` python

In [1]: import markdown

In [2]: markdown.markdown('[a b c](/a_b_c)')
Out[2]: u'<p><a href="/a_b_c">a b c</a></p>'

In [3]: markdown.version_info
Out[3]: (2, 1, 0, 'Dev')
```

I suppose it is possible that you are using some extension that is messing with the order of the inline patterns. The text you are getting is a placeholder, which makes me think the patterns are getting run in the wrong order or something. In any event, that would be a bug in your extension, not markdown.

**Comment by Wilfred** [comment]
Sorry, it seems we're using GitHub style markdown where we try to stop inter-word underscores becoming italics. Here's the actual issue we're seeing:

```
>>> import markdown
>>> markdown.version_info
(2, 0, 3, 'Final')
>>> markdown.markdown('[a b c](/a\_b\_c)')
u'<p><a href="/a\x02klzzwxh:0000\x03b\x02klzzwxh:0001\x03c">a b c</a></p>'
```

I think this example is legal markdown, but I'm not sure. Other markdown packages we've used produce `<p><a href="/a_b_c">a b c</a></p>`.

**Comment by waylan** [comment]
Ahh, see you're using markdown version 2.0.3. But the current code in the repo is not exhibiting this behavior (we already fix it) so there is nothing to fix. If you want the fixed code use the current source here on github or wait for the next release.

**Comment by Wilfred** [comment]
Great, thanks for your time.

**Comment by agusmakmun** [comment]
Hello there, i found same problem here...

```python
>>> import markdown
>>> markdown.version
'2.6.7'
>>>
>>> MARKDOWNX_MARKDOWN_EXTENSIONS = [
...     'markdown.extensions.extra',
...     'markdown.extensions.nl2br',
...     'markdown.extensions.smarty',
...     'markdown.extensions.fenced_code',
... 
...     # Custom markdown extensions.
...     'app_forum.utils.extensions.urlize',
...     'app_forum.utils.extensions.mention',
...     'app_forum.utils.extensions.emoji',
... ]
>>> md = markdown.Markdown(extensions=MARKDOWNX_MARKDOWN_EXTENSIONS)
>>> md.convert('![](/media/markdownx/affbbda4-054e-4fd3-b263-eb4982289d01.jpg)@[falcon] ')
'<p>\x02klzzwxh:0000\x03\x02klzzwxh:0001\x03 </p>'
>>>
>>> # but if has `space` between `)` and `@` it work well.
>>> md.convert('![](/media/markdownx/affbbda4-054e-4fd3-b263-eb4982289d01.jpg) @[falcon] ')
'<p><img alt="" src="/media/markdownx/affbbda4-054e-4fd3-b263-eb4982289d01.jpg" /> <a class="direct-mention-link" href="//mysite.com/profile/falcon/">@falcon</a> </p>'
>>> 
```

**My Extention at `app_forum.utils.extensions.mention`**

```python
import markdown
from django.contrib.auth.models import User

BASE_LINK = '//mysite.com/profile/'
MENTION_RE = r'\@\[(?P<username>\S+)\]'
# MENTION_RE = r'(?<!\!)\@\[([^\]]+)\]' -> m.group(2)


class MentionPattern(markdown.inlinepatterns.Pattern):

    def __init__(self, pattern, markdown_instance):
        markdown.inlinepatterns.Pattern.__init__(self, pattern)
        self.markdown_instance = markdown_instance

    def handleMatch(self, m):
        username = m.group('username')

        """Makesure `username` is registered."""
        if username in [u.username for u in User.objects.all() if u.is_active]:
            url = '{0}{1}/'.format(BASE_LINK, username)
            el = markdown.util.etree.Element('a')
            el.set('href', url)
            el.set('class', 'direct-mention-link')
            el.text = markdown.util.AtomicString('@' + username)
            return el


class MentionExtension(markdown.Extension):

    def extendMarkdown(self, md, md_globals):
        """ Setup `mention_link` with MentionPattern """
        md.inlinePatterns['mention_link'] = MentionPattern(MENTION_RE, md)


def makeExtension(*args, **kwargs):
    return MentionExtension(*args, **kwargs)
```

**Comment by waylan** [comment]
@agusmakmun it appears that your issue is completely unrelated to this issue. When I run your input without your extension, the output is completely reasonable:

`<p><img alt="" src="/media/markdownx/affbbda4-054e-4fd3-b263-eb4982289d01.jpg" />@[falcon] </p>`

Which suggests you have a bug in your extension. For an explanation of why you are getting strings like `klzzwxh:0002` in your output, see #354. 

Note that this forum is for reporting bugs in Python-Markdown, not for asking support questions. If you need any assistance building an extension, please ask for assistance on the [mailing list][1]. If you find an actual bug in Python-Markdown (rather than your code), then please [open a new issue][2].

[1]: http://lists.sourceforge.net/lists/listinfo/python-markdown-discuss
[2]: https://github.com/waylan/Python-Markdown/issues/new
