### ISSUE TITLE
'code' element doesn't preserve initial spaces or newlines

### ISSUE THREAD

**Issue by JohnCC330** [Python-Markdown/markdown#321]
`   123456` in the original text doesn't preserve the initial space. I typed 5 or 6 spaces here (before the '1', but the github issue editor seems to remove extra spaces too.

Anyway, the above gets translated into `<code>123456</code>`, without the initial spaces (or new-line characters:
`
123456` doesn't work either).

**Comment by waylan** [comment]
The fact that Github's markdown implementation exhibits the same behavior should be a clue.

As the [syntax rules](http://daringfireball.net/projects/markdown/syntax#code) state:

> The backtick delimiters surrounding a code span may include spaces — one after the opening, one before the closing. This allows you to place literal backtick characters at the beginning or end of a code span:
> 
> ```
> A single backtick in a code span: `` ` ``
> 
> A backtick-delimited string in a code span: `` `foo` ``
> ```
> 
> will produce:
> 
> ```
> <p>A single backtick in a code span: <code>`</code></p>
> 
> <p>A backtick-delimited string in a code span: <code>`foo`</code></p>
> ```

Now, I realize that a strict read of that rule would indicate that no more than one space would be removed from the beginning and end of a code span. However, in practice [most implementations](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%60++++++123456++++++%60) remove all white-space, including the reference implementation (markdown.pl) which most everyone else has copied.

So, my opinion is that this is _not_ a bug. In fact, all of the implementations that don't strip the white-space in your example get the example given in the rule wrong. In other words, those implementations are ignoring that rule. I don't want to be the _only_ implementation with some hybrid behavior (like stripping only one space). And yes, [it matters](http://johnmacfarlane.net/babelmark2/faq.html#why-does-it-matter-whether-implementations-agree) regardless of what the rule actually says.

**Comment by waylan** [comment]
Oh and one more thing. By default, browsers collapse multiple spaces down to one in anything except a `<pre>` tag. So, the inline `<code>` tags will get all white-space collapsed by the browser, regardless of what Markdown outputs, unless the site's CSS contains something like: `code {white-space: pre;}`. That being the case, it doesn't really make sense to preserve white-space in inline code. If you want multiple spaces, then you should be using [non-breaking spaces](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%26nbsp%3B+%26nbsp%3B+%26nbsp%3B+123456+nbsp%3B+%26nbsp%3B+%26nbsp%3B%60) (note that you only need to use a non-breaking space for every other space - just be sure your first and last character in the code snippet is not a plain space).

I'm closing this "won't fix".

**Comment by JohnCC330** [comment]
On Mon, 30 Jun 2014 13:13:09 -0700
Waylan Limberg notifications@github.com wrote:

> > ```
> > <p>A backtick-delimited string in a code span: <code>`foo`</code></p>
> > ```
> 
> Now, I realize that a strict read of that rule would indicate that no more than one space would be removed from the beginning and end of a code span. However, in practice [most implementations][2] remove all white-space, including the reference implementation (markdown.pl) which most everyone else has copied.
> 
> So, my opinion is that this is _not_ a bug. In fact, all of the implementations that don't strip the white-space in your example get the example given in the rule wrong. In other words, those implementations are ignoring that rule. I don't want to be the _only_ implementation with some hybrid behavior (like stripping only one space). And yes, [it matters][3] regardless of what the rule actually says.

Hi Waylan... Thanks for replying!

Yes - you're right of course. For some reason I didn't notice the actual literal code inclusion
mode (using the 4 spaces at the beginning of the line). This is quite unforgiveable, as I've used
it plenty in on-line courses and the like.

Pardon the noise!

John

**Comment by frostybeard** [comment]
I would consider it a bug. I am trying to show the file structure of mp4 files using initial spaces, and GitHub removes all the formatting. Even if I insert it as code, it removes those spaces. Strangely, when I go back to "edit", the spaces are there again, so when you are editing a comment, it shows different formatting than when you post the comment. Bad, in my opinion. The tendency nowadays is to go with wysiwig, and not give people surprises.

**Comment by Simran-B** [comment]
According to the CommonMark spec, only one space character is to be removed from the beginning and end:
https://spec.commonmark.org/0.29/#code-spans

**Comment by facelessuser** [comment]
If desired, one can easily create an extension to override the default inline code handling. While I've never needed leading whitespace to be preserves in these cases (I just use block code if I need that) , but Python Markdown is flexible in that sense.

It is not a Commonmark parser (which is a superset of Markdown), but a Markdown parser.

**Comment by dhyon** [comment]
I would expect my spacing to be preserved in an inline code block to maintain readability 😞

**Comment by waylan** [comment]
As a reminder, we didn't design Markdown. We simply maintain an implementation of the rules defined elsewhere. If you object to the rules, then you need to take that to those who wrote the rules.
