### ISSUE TITLE
Small discrepancy in using '_' vs '*'

### ISSUE THREAD

**Issue by JohnCC330** [Python-Markdown/markdown#322]
This might be documented somewhere, but I didn't find it:

```
print md.markdown("un*frigging*believable")
print md.markdown("un_frigging_believable")
```

produces

```
<p>un<em>frigging</em>believable</p>
<p>un_frigging_believable</p>
```

Though on John Gruber's Dingus they produce:

```
<p>un<em>frigging</em>believable</p>
<p>un<em>frigging</em>believable</p>
```

According to the spec:

> You can use whichever style you prefer; the lone restriction is that the same character must be used to open and close an emphasis span.

The embedded _'s in markdown start working if spaces are added before and after. I.e.:

```
print md.markdown("un _frigging_ believable")
```

but the spaces are then printed too.

**Comment by waylan** [comment]
This is a known and [documented](https://pythonhosted.org/Markdown/index.html#differences) (under "Middle-Word Emphasis”) difference. If you would prefer markdown.pl's behavior ( why would anyone?), you can enable it as [documented](https://pythonhosted.org/Markdown/reference.html#smart_emphasis).

I'm closing this as "won't fix"
