### ISSUE TITLE
Extensions should accept a dict (or **kwargs) for configs on initialization

### ISSUE THREAD

**Issue by mesarvagya** [Python-Markdown/markdown#325]
In the class FootnoteExtension inside footnotes.py, there is error in **init** function.
The code in current version is: 

```
def __init__ (self, configs):
    """ Setup configs. """
      self.config = {'PLACE_MARKER':
                   ["///Footnotes Go Here///",
                    "The text string that marks where the footnotes go"],
                   'UNIQUE_IDS':
                   [False,
                    "Avoid name collisions across "
                    "multiple calls to reset()."],
                   "BACKLINK_TEXT":
                   ["&#8617;",
                    "The text string that links from the footnote to the reader's place."]
                   }

    for key, value in configs:
        self.config[key][0] = value

    # In multiple invocations, emit links that don't get tangled.
    self.unique_prefix = 0

    self.reset()
```

If you check in config parameter, the loop will cause "too many values to unpack" error. The loop should be:

```
for key, value in configs.iteritems():
     self.config[key][0] = value
```

or 

```
for key, value in configs.items():
    self.config[key][0] = value
```

**Comment by waylan** [comment]
Thanks for the report @mesarvagya. That is some old code from earlier versions of Python. I thought we had changed them all. Looks like this one slipped through. I'll get to it when I have the time, ... or ... we do accept pull requests (ideally including a test that fails before the fix is applied but not after).

**Comment by waylan** [comment]
Sorry, it looks like I fired back my response the other day a little to quickly without looking at things more closely. I wondered how we didn't have a test that covered this.

My mistake (or oversight) when responding was that extensions do not accept a dict of config options, but a list of tuples. See the [docs](https://pythonhosted.org/Markdown/reference.html#extension_configs) for an example. Yes, there is a dict there, but the keys are extension names whereas the values (what gets passed to the extension) is a list of tuples.

I realize that the configs are stored in a dict on an instance of the Extension Class (and its subclasses), but when setting configs on initialization, you need to pass a list of tuples. I realize this is probably not the best API (especially now that we [recommend](https://pythonhosted.org/Markdown/reference.html#extensions) that people initialize there own extension instances) but it has been the API for many years (before I joined the project). I think perhaps a refactor (perhaps using _args and *_kwargs for backwards compatibility) is in order. 

I've edited the title to better reflect the actual issue. Thanks for your report.
