### ISSUE TITLE
TOC Ext doesn't ignore `[TOC]` in code blocks/spans

### ISSUE THREAD

**Issue by Wilfred** [Python-Markdown/markdown#33]
It's not possible to get a literal `[TOC]` in the output when use the (excellent) table of contents extension. It would be nice to be able to do

```
`[TOC]`
```

or

```
    [TOC]
```

and just get the literal [TOC] in the output.

**Comment by waylan** [comment]
Not true. As `[` and `]` are escapable characters, you just need to escape them (the same way you would when escaping a link for example). Like this:

```
\[TOC\]
```

Which is returned as:

```
<p>[TOC]</p>
```

Hmm, ahh, what you mean is that `[TOC]` cannot be used in a code block or span. Well, that's different than escaping. I've updated the title to reflect the actual problem. Thanks for the report.

**Comment by Wilfred** [comment]
Perfect, thanks. Sorry I was unclear.
