### ISSUE TITLE
Is there a rel=nofollow extension?

### ISSUE THREAD

**Issue by michaeljones** [Python-Markdown/markdown#330]
I'm using python-markdown for user generated text on a website and I would like to mark all the links as rel="nofollow" which I believe is a good practice in that situation to inhibit spam. Is there an extension for that? Do you think it would be worth adding if there isn't? Or simply maintaining as a third party extension? 

I'm probably going to try to adapt: https://github.com/Undeterminant/markdown-newtab for the purpose unless I find something that handles the issue. I can't see anything from my searches though. A post process filter approach exists as well but it seems like it might be hard to perfect the regex: http://blog.rafaljonca.org/2010/01/simple-nofollow-filter-for-markdown.html

Thanks for the excellent project.
Michael

**Comment by waylan** [comment]
Unless, there is an extension listed on the [wiki](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions), no I'm not aware of any rel="no follow" extensions. I'm not really interested in including one with python-markdown either. However, please do add to the list on the wiki whatever you come up with.

I'm closing this as no "issue" was reported.

**Comment by michaeljones** [comment]
Thanks for the quick response. Sorry if it was an abuse of the issues system. I'm never sure how best to communicate on subjects like this.

**Comment by mitya57** [comment]
We have a mailing list: [python-markdown-discuss@lists.sourceforge.net](https://lists.sourceforge.net/lists/listinfo/python-markdown-discuss).

**Comment by bhch** [comment]
@michaeljones Hi! If you're still looking for a `rel="nofollow"` extension, here's one that I made - [markdown-nofollow](https://github.com/xyres/markdown-nofollow/).
