### ISSUE TITLE
Using meta-data extension from commandline

### ISSUE THREAD

**Issue by plaindocs** [Python-Markdown/markdown#331]
Hi Guys,

Is there no way to use the meta-data extension when using 

```
markdown_py
```

?

**Comment by waylan** [comment]
Yes, you can use the extension the same way you would [use](https://pythonhosted.org/Markdown/cli.html#using-extensions) any extension from the command line, but I suppose you mean: "Is there any way to access the meta data from the command line?"

The answer to that question is no. However, how would you propose the meta data be made available. By default the command line script returns the body on stdout (or writes to a file if given). It's not clear to me how the meta data could also be returned in a useful way.

Note that the [HeaderId](https://pythonhosted.org/Markdown/extensions/header_id.html#using-with-meta-data) and [WikiLinks](https://pythonhosted.org/Markdown/extensions/wikilinks.html#using-with-meta-data-extension) extensions both have support for using some predefined meta-data to effect their behavior within that single document. This is probably the only useful way that meta-data could be used from the command line.

If perhaps you are looking to use the meta data to populate a header around the HTML body, then my suggestion would be to write a Python script which does that and call your script from the command line. Or I suppose you could always write an extension of your own which made the meta-data available in some way (write to stderror or a file??).

Finally, just to be clear, Python-Markdown is primarily a python library. We only provide a command line interface as a convenience with the recognition that its usefulness may be limited. If you want a full featured command line interface to process Markdown, you might want to take a look at [Pandoc](http://johnmacfarlane.net/pandoc/) (which is not a library).

**Comment by plaindocs** [comment]
Hi Waylan,

Thanks for the quick answer.

I did indeed mean using the metadata on the command line, but what you say makes sense. I guess I'll rewrite the script in python at some point.

It might be worth highlighting the fact that the CLI is not intended to be full featured, I missed that when reading the docs.
