### ISSUE TITLE
Should we deprecate "safe_mode"?

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#337]
The [docs](https://pythonhosted.org/Markdown/reference.html#safe_mode) have pointed to [Bleach](https://github.com/jsocol/bleach) as an alternative for same_mode for some time now. And I have been saying for even longer that safe_mode is not really "safe". Therefore, I would like to deprecate it and suggest Bleach be used in its stead. I **might** be inclined to replace it with a simple extension that does raw HTML escaping only -- it would make no claims about being "safe" -- but I don't really see the value when a much safer alternative exists in Bleach.

Any thoughts and/or objections?

Of course, we would issue a PendingDeprecationWarning first, followed by a DeprecationWarning in the next release -- so it won't go away immediately.

Oh, and I know a lot of people use this for comments, etc. As Markdown accepts **kwargs, people setting the `safe_mode` keyword would not get any error if support was simply removed. Suddenly, comments that have had potentially dangerous content will no longer be sanitized when they upgrade to the new Python-Markdown version. Therefore, when the feature is finally removed, I think we need to issue an Error `if 'safe_mode' in kwargs.keys()`.

**Comment by dpawson** [comment]
Your logic seems very sound. I'm supportive.

**Comment by waylan** [comment]
As a reminder to myself, we also need to deprecate support for positional args when we do this as 'safe_mode' was one of the old positional args. See [`markdown/__init__.py L108`](https://github.com/waylan/Python-Markdown/blob/master/markdown/__init__.py#L108). We can't just take it out and keep the later positional args at their same position. Seeing that the current support is really just a hack for backward compatibility we should just deprecate it on the same timeline as safe_mode itself. The end result would be that `markdown.Markdown` and `markdown.markdown` would only accept `**kwargs`, but not `*args`.

Also, we need to deprecate the `html_replacement_text` keyword along with `safe_mode`.
