### ISSUE TITLE
Should be complied with Commonmark

### ISSUE THREAD

**Issue by lipis** [Python-Markdown/markdown#338]
I'm guessing many people already seen this: 

http://standardmarkdown.com/

and the very interesting introduction by Jeff Atwood:  http://blog.codinghorror.com/standard-flavored-markdown/

**Comment by minektur** [comment]
+1  : I think Standard Markdown support would be great.

I wonder how easy it is to run python-markdown through their compliance tests?  hm..

**Comment by minektur** [comment]
and... I guess it would make sense to have both 'traditional' and 'Standard' modes?  I think it would be
unpleasant for projects depending on the current markdown behavior to wake up and find no support?

**Comment by lipis** [comment]
one is more than enough to support.. if you don't want to break things.. stay in the older version.. and just comply with standards..

**Comment by waylan** [comment]
Consider the [goals](https://pythonhosted.org/Markdown/#goals) of Python-Markdown (restated here):

> - Maintain ... an implementation of the markdown parser that follows the syntax rules and the behavior of the original (markdown.pl) implementation as reasonably as possible.
> - Provide an Extension API which makes it possible to change and/or extend the behavior of the parser.

[CommonMark](http://commonmark.org/)  (the (third) name as of this writing) does not meet the first goal, and so the Python-Markdown project has no interest of providing an implementation that meets that spec. However, given our second goal, you should be able to use our parsing engine to create a python implementation of CommonMark. In fact, the parser is built in such a way that the parsing engine could be used to parse some other, not-markdown-inspired text based markup language.

I would imagine that almost the entire set of blockprocessors in Python-Markdown would need to be rewritten, so the way I would do it would be to subclass `markdown.Markdown` and override the [`build_parser`](https://github.com/waylan/Python-Markdown/blob/master/markdown/__init__.py#L158) method. I think reading the source code should be able to guide you from there. Of course, as no one has actually used our parsing engine to built something else, I'm open to general improvements to the underlying engine that might make it easier. But those improvements **must not** alter the current implementation's behavior. And I would expect those who want the changes to do the work. I don't mind reviewing pull requests.

And that is all I have to say on the subject. Please don't ask me to reconsider. Thank you.

**Comment by nhinkle** [comment]
> and so the Python-Markdown project has no interest of providing an implementation that meets that spec

As the creator of the project it's certainly your right to not have an interest in implementing the CommonMark spec and not to allow it, but it's false to say "the project" has no interest since the very existence of this request indicates that at least some people who use the project would like to see it go that direction.

**Comment by lipis** [comment]
@nhinkle And it is kind of nice direction.. but as the _creator_ said.. we are not allowed to ask him to reconsider.. :stuck_out_tongue_winking_eye:

**Comment by nhinkle** [comment]
@lipis you and others may be interested in [commonpark-py](https://github.com/rolandshoemaker/CommonMark-py).
