### ISSUE TITLE
Smarty runs on code blocks

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#340]
... but not code spans. it should not run on either.

See this example:

``` python
>>> t = """
... "Some text \"surrounded\" in 'quotes.'"
...
...     Some "quotes" in a 'code block.'
...
... Some `"quotes" in a 'code span'`.
... """
>>> markdown.markdown(t, extensions=['smarty'])
u'<p>&ldquo;Some text &ldquo;surrounded&rdquo; in &lsquo;quotes.&rsquo;&ldquo;</p>\n
<pre><code>Some &ldquo;quotes&rdquo; in a &lsquo;code block.&rsquo;</code></pre>\n
<p>Some <code>"quotes" in a \'code span\'</code>.</p>'
```

The code blocks should be coming through unaltered (like code spans). I noticed this while editing the docs recently. Only had time to look into it now.

It appears there is no test for this. I think it used to work. Of course, we didn't catch the breakage because of the lack of a test.

**Comment by mitya57** [comment]
Thanks for noticing and fixing this @waylan! Do you plan to do a new release soon? (If not, I will be going to cherry-pick this to my distro packages).

**Comment by waylan** [comment]
Yes, I expect to be doing a release within the next week.
