### ISSUE TITLE
AttributeError: 'module' object has no attribute 'captureWarnings'

### ISSUE THREAD

**Issue by jimi-c** [Python-Markdown/markdown#345]
This occurs during installation on machines running python 2.6.x, as the logging module does not include this function (the docs page at https://docs.python.org/2/library/logging.html#integration-with-the-warnings-module fails to mention this).

**Comment by facelessuser** [comment]
```
Python-Markdown 2.5 Release Notes
=================================

We are pleased to release Python-Markdown 2.5 which adds a few new features
and fixes various bugs. See the list of changes below for details.

Python-Markdown version 2.5 supports Python versions 2.7, 3.2, 3.3, and 3.4.

Backwards-incompatible Changes
------------------------------

* Python-Markdown no longer supports Python version 2.6. You must be using Python 
  versions 2.7, 3.2, 3.3, or 3.4. While Python-Markdown is no longer tested against
  Python 2.6, you may be able to get it working if you install a copy of [importlib] 
  which has been backported for Python 2.6. However, the developers of Python-Markdown 
  offer no guarentees in that situation.
```

**Comment by jimi-c** [comment]
Well that's disappointing, considering python 2.6 is still widespread through CentOS/RHEL 6 (and will remain so until those versions are EOL'd).

**Comment by waylan** [comment]
Yes, as was pointed out int he release notes, support for Python 2.6 is dropped. We are running a single codebase on both Python 2 and 3. The recommended minimum Python version in that scenario is Python 2.7. And as more Python 3 versions get released, it becomes more difficult to continue to support both the new version of Python 3 and Python 2.6. Now that we have added 3.4, it no longer makes sense to also jump through hoops to support Python 2.6.

**Comment by EnTeQuAk** [comment]
@jimi-c you can use my fork for the time being if you really need python 2.6 support - https://github.com/EnTeQuAk/Python-Markdown/tree/feature/py26 - I'll do my best to maintain it at least for some time

**Comment by ghost** [comment]
Wow this is great if you are running RHEL6.  [[inappropriate/offensive comments removed]]
