### ISSUE TITLE
Table of Contents breaks code block 

### ISSUE THREAD

**Issue by tyleha** [Python-Markdown/markdown#346]
Playing around today with adding a Table of Contents in Markdown. However, enabling the Markdown TOC extension and putting the corresponding `[TOC]` in my .md file completely breaks any of my Markdown block code (triple backtick) and converts it into inline (or worse).

It correctly formats inline code like `this example`, but will format the following as inline (with the word python included).

``````
```python
import numpy
def foo():
    pass
```
``````

If I enclose console output with `>` symbols in block code, then the code becomes a block quote

``` bash
>This would be a block quote
>along with this line
```

None of these things happen with the TOC extension disabled. I've tried to poke around as to why but am very unfamiliar with the underpinnings of Markdown. I am running Markdown 2.5.

**Comment by waylan** [comment]
@tylerhartley I edited your post above to better show what you actually are inputting into markdown. Can you very that is correct? And are you using the [Fenced Code Extension](https://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html)? If not, then that would explain your report.

Actually could you show what you are getting as output as well? I want to make sure I am understanding your problem clearly as I can't seem to reproduce you problem:

``````
>>> import markdown
>>> t = """
... [TOC]
...
... # Header
...
... ```python
... import numpy
... def foo():
...     pass
... ```
... """
>>> markdown.markdown(t, extensions=['markdown.extensions.toc', 'markdown.extensions.fenced_code'])
u'<div class="toc">\n<ul>\n<li><a href="#header">Header</a></li>\n</ul>\n</div>\n<h1 id="header">Header</h1>\n<pre><code class="python">import numpy\ndef foo():\n    pass\n</code></pre>'.
``````

**Comment by tyleha** [comment]
Thanks for the edit @waylan - yes, your edit is correct. 

And, yep - you nailed it, I was not using the fenced code extension. Enabling it produces the correct output, as shown below:

```
In [3]: markdown.markdown(t, extensions=['markdown.extensions.toc', 'markdown.extensions.fenced_code
'])
Out[3]: u'<div class="toc">\n<ul>\n<li><a href="#header">Header</a></li>\n</ul>\n</div>\n<h1 id="hea
der">Header</h1>\n<pre><code class="python">import numpy\ndef foo():\n    pass\n</code></pre>'

In [4]: markdown.markdown(t, extensions=['markdown.extensions.toc'])
Out[4]: u'<div class="toc">\n<ul>\n<li><a href="#header">Header</a></li>\n</ul>\n</div>\n<h1 id="hea
der">Header</h1>\n<p><code>python\nimport numpy\ndef foo():\n    pass</code></p>'
```

The issue was that for my implementation, enabling _any_ markdown extensions overwrote the default values, causing fenced_code to be disabled without my knowledge. Now I know. Thanks for the solution - couldn't figure this one out by googling!
