### ISSUE TITLE
Force new line

### ISSUE THREAD

**Issue by Purexo** [Python-Markdown/markdown#348]
Hello, I'd like to force new line in a paragraph but i don't know how to do it.
ex : 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
--->
     <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br />
     Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.<br />
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

**Comment by waylan** [comment]
As the [syntax rules](http://daringfireball.net/projects/markdown/syntax#p) clearly state:

> When you _do_ want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

As this is not actually a bug report, I am closing this.

**Comment by Purexo** [comment]
thanks for your answer. it'll be usefull
