### ISSUE TITLE
anchor link on headers

### ISSUE THREAD

**Issue by erez-o** [Python-Markdown/markdown#351]
Feature request:
Automatic anchor links on all headers. 
It's supported on Github, Readthedocs.
It's implemented in the TOC extension, but not if you don't want a table of contents.

**Comment by erez-o** [comment]
Sorry, the HeaderId extension creates the same effect.
I am not knowledgeable enough to asses if anchor is preferable to ID or not.

If you have any comment, reopen. Thx

**Comment by bjarthur** [comment]
sorry to exhume an old issue, but is there a flag to automatically add anchor links to all headers?  i don't see it in the docs.  as the OP described, github supports this.  specifically:

```
## My Awesome Header ##

a bunch of text...

and then further down i refer the reader to [My Awesome Header](#My-Awesome-Header)
```

in github this works as is.  with this package i have to manually add `<a name="My-Awesome-Header"></a>"` to the header itself, as described [here](https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown).

is there no easier way?  thanks.

**Comment by waylan** [comment]
The HeaderID extension mentioned above has been deprecated. However, the [TOC][1] extension now offers the feature.

[1]: https://python-markdown.github.io/extensions/toc/
