### ISSUE TITLE
Imagage size lands in title:

### ISSUE THREAD

**Issue by maxnoe** [Python-Markdown/markdown#352]
In Markdown i can specify the size of an image like this:

```
![](image.png =300x200)
```

However if i render this with python markdown, the `=300x200` just lands in the title:

```
markdown.markdown("![](test.png =300x200)")
```

results in:
     '<p><img alt="" src="bla.png" title="=30x20" /></p>'

**Comment by omidraha** [comment]
Related https://github.com/Python-Markdown/markdown/issues/353
