### ISSUE TITLE
Imagage size lands in title:

### ISSUE THREAD

**Issue by maxnoe** [Python-Markdown/markdown#353]
In Markdown i can specify the size of an image like this:

```
![](image.png =300x200)
```

However if i render this with python markdown, the `=300x200` just lands in the title:

```
markdown.markdown("![](test.png =300x200)")
```

results in:
    `<p><im g alt="" src="bla.png" title="=30x20" /></p>`

**Comment by waylan** [comment]
@MaxNoe thanks for your report, however, that is not standard markdown syntax. It is not mentioned at all in the [Syntax Rules](http://daringfireball.net/projects/markdown/syntax). And in fact it [appears](http://johnmacfarlane.net/babelmark2/?normalize=1&text=!%5B%5D%28image.png+%3D300x200%29) that it is only supported by one of the many Markdown implementations. 

I recently read an article (i forget where) in which a seasoned Markdown user commented that they never use Markdown's image syntax as the raw HTML `<img>` tag is just as easy to type. As an added benefit to using raw HTML, you have full control over any extra attributes you may want to set on the element. 

If you really don't want to use raw HTML, then I would suggest the [Attribute List](https://pythonhosted.org/Markdown/extensions/attr_list.html) Extension as an alternative. Or you are always free to implement your own extension which replaces the existing image parser (see the [Extension API](https://pythonhosted.org/Markdown/extensions/api.html) docs for more info). Or perhaps someone else [already has](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions).

As there is no bug here, I am closing this "wontfix".

**Comment by omidraha** [comment]
Related https://github.com/Python-Markdown/markdown/pull/88
