### ISSUE TITLE
Nested inline pattern always returns klzzwxh:0002

### ISSUE THREAD

**Issue by T1c0MmRtODFORlpt** [Python-Markdown/markdown#354]
Hello,

I use custom inline patterns to convert my media url and `<audio>` tag, but the media url pattern always returns `klzzwxh:0002` or `klzzwxh:0003`.

Here is the code:

``` python
import markdown

def makeExtension ( configs = None ) :
    return my_exstension()


class my_exstension ( markdown.Extension ) :

    def __init__ ( self, **kwargs ) :

        super( my_exstension, self ).__init__( **kwargs )

    def extendMarkdown ( self, md, md_globals ):

        md.inlinePatterns.add( 'media_url',
            MediaUrlPattern( r'\{media +(.+?)\}', md ), '_begin' )

        md.inlinePatterns.add( 'audio',
            AudioPattern( r'\{audio +(.+?)\}', md ), '>media_url' )

class MediaUrlPattern ( markdown.inlinepatterns.Pattern ) :

    def handleMatch ( self, m ) :
        return 'http://www.es.com/media/%s' % m.group( 2 )

class AudioPattern ( markdown.inlinepatterns.Pattern ) :

    def handleMatch ( self, m ) :
        el = markdown.util.etree.Element( 'audio' )
        el.set( 'src', m.group( 2 ) )
        el.text = markdown.util.AtomicString( 'Your browser does not support the audio tag.' )
        return el

```

The `.md` file is:

``` markdown
{audio {media music.mp3}}
```

And the HTML output in my thought shoule be:

``` html
<audio src="http://www.es.com/media/music.mp3">Your browser does not support the audio tag.</audio>
```

But it rendered:

``` html
<audio src="klzzwxh:0002">Your browser does not support the audio tag.</audio>
```

Could you give me some advice or should I go another way?

Thanks.

**Comment by waylan** [comment]
@ychongsaytc I see a couple different issues with your code. 

1) InlinePatterns are generally expected to return etree Elements. While this is not a strict rule, the internal code expects that and so you are getting unexpected results as your `MediaUrlPattern` does not return an Element. In the general case this is usually not a problem, but in some edge cases, you can be surprised.

2) The second issue is that your `AudioPattern` is inserting  an already parsed portion of your document into an attribute (src) of an Element rather that as a child element (which is what the internal code expects). 

By way of explanation, the internal code substitutes a placeholder for each returned Element and then after all InlinePatterns are completed, swaps out all the placeholders for the actual elements. However, this only works for Elements (and child Elements), not attributes within an element. Therefore, you need to swap out the placeholder yourself. Fortunately, this is not the first time this issue has come up, so there is an [`unescape`](https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L189) method on the Pattern class you can use to force the placeholder to be swapped out.

Therefore, your `AudioPattern` class would look like this (see the comment highlighting my change):

``` python
class AudioPattern ( markdown.inlinepatterns.Pattern ) :

    def handleMatch ( self, m ) :
        el = markdown.util.etree.Element( 'audio' )
        el.set( 'src', self.unescape(m.group( 2 )))  # <<< Note the call to self.unescape added here
        el.text = markdown.util.AtomicString( 'Your browser does not support the audio tag.' )
        return el
```

I haven't tested that, but I expect that will address this immediate problem (note that a different implementation of [`unescape`](https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L293) exists on the `HtmlPattern` so the one method may not work in all situations).

However, I wonder why you need two Pattern classes. Why not just have one class that handles the entire thing (avoiding the first issue mentioned above)? Then you can build and return an element all at once and won't have to work around the second issue which is dependent on the undocumented internal implementation and subject to change without notice.

As there is no actual bug in Python-Markdown I am closing this issue.

**Comment by T1c0MmRtODFORlpt** [comment]
Thank you for you explanation, and the `self.unescape` method works and solve this issue, perfectly.

Yes, two patterns are extremely unnecessary, I thinks it's just what perfectionists do :-P

Anyway, **Python-Markdown** is a fresh, high-efficiency tool for me. Thanks for your contribution, too.
