### ISSUE TITLE
Deployment of 3rd party extensions

### ISSUE THREAD

**Issue by lusitania** [Python-Markdown/markdown#355]
I couldn't find a recommended way to deploy extensions. One [particular](https://github.com/smartboyathome/Markdown-GridTables/) doesn't even have a setup.py so I could integrate it into my required packages.

So, how is it done?

**Comment by waylan** [comment]
If you are asking how to install a third party extension, that is a question you would need to ask the author of that extension. I have no control over how third party extension authors arrange their packages.  As long as the package is importable, then Markdown can use it provided you give Markdown the correct path as explained in the [docs](https://pythonhosted.org/Markdown/reference.html#extensions). If you are unsure of the correct path, that depends on how you installed it and/or how the extension author arranged their package. I would suggest asking the authors of the specific packages you want to use. I don't offer support for third party extensions.

As an aside, there have been some [recent changes](https://pythonhosted.org/Markdown/release-2.5.html) to the extension API. It is possible that some older extensions need to be updated.  Again, that is something you need to contact the author of that extension about.

You may also find some help on the [mailing list](http://lists.sourceforge.net/lists/listinfo/python-markdown-discuss). GitHub Issues is for reporting bugs, not support questions.

As there is no issue here with Python-Markdown, I am closing this.
