### ISSUE TITLE
List + paragraph strange behavior

### ISSUE THREAD

**Issue by jespino** [Python-Markdown/markdown#362]
With this markdown code:

```
- list item 1

- list item 2
- list item 3
- list item 4
```

The result is:

```
<ul>
<li><p>list item 1</p></li>
<li><p>list item 2</p></li>
<li>list item 3</li>
<li>list item 4</li>
</ul>
```

I think must be:

```
<ul>
<li><p>list item 1</p></li>
<li>list item 2</li>
<li>list item 3</li>
<li>list item 4</li>
</ul>
```

or

```
<ul>
<li>list item 1</li>
<li><p>list item 2</p></li>
<li>list item 3</li>
<li>list item 4</li>
</ul>
```

But with the current result you can create 2 list splited in 2 blocks :disappointed:

**Comment by me-and** [comment]
This matches the reference Markdown.pl implementation. I agree that it's odd, but I don't think it's a bug.

You can compare the [Babelmark results](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+list+item+1%0A%0A-+list+item+2%0A-+list+item+3%0A-+list+item+4) to check for yourself.

**Comment by jespino** [comment]
IMHO this is a bug, maybe a bug on the reference implementation, but a bug.

**Comment by me-and** [comment]
That's something you'll need to take up with John Gruber, or find some fork of the Markdown syntax/implementation that changes the behaviour to what you want. Or alternatively, write an extension or patch yourself to provide this behaviour using Python Markdown.

This project is trying to emulate the reference implementation as closely as possible, in the name of minimizing the differences between people switching from the reference implementation to this one. This has been the long-standing precedent; see for example #64 and #309 for similar cases.

**Comment by jespino** [comment]
Sure, I've sent a email to John Gruber, and I understand and share the opinion of follow the reference implementation. I close the issue, and try to talk with John Gruber to change the reference implementation. Thanks :smiley:

**Comment by waylan** [comment]
For the record, this is definitely not a bug. Python-Markdown didn't always work this way (it did its own strange thing--I forget what--it was years ago), and I painstakingly worked through it until all the edge cases matched the reference implementation.

While I agree that that is not an immediately obvious output (I would have come up with something different myself), we are not changing it now (nor do I expect any other implementations to) as the thousands (millions?) of existing documents out there would all break. As long as that is the case, I expect that Markdown never will (or should) change.
