### ISSUE TITLE
Ordered list in unordered list doesn't work

### ISSUE THREAD

**Issue by vbkaisetsu** [Python-Markdown/markdown#364]
When unordered lists are nested in ordered lists, the output of Python Markdown is not correct.

Input:

```
1. aaaaa
2. bbbbb
  * ccccc
  * ddddd
3. eeeee
```

Output of John Gruber's Markdown:

```
<ol>
<li>aaaaa</li>
<li>bbbbb
<ul>
<li>ccccc</li>
<li>ddddd</li>
</ul></li>
<li>eeeee</li>
</ol>
```

Python markdown:

```
<ol>
<li>aaaaa</li>
<li>bbbbb</li>
<li>ccccc</li>
<li>ddddd</li>
<li>eeeee</li>
</ol>
```

**Comment by me-and** [comment]
This is intentional behaviour, and isn't considered a bug in Python Markdown; see, for example, #172 and #125 (the latter covers this exact behaviour, the former has a bit more information on the reason this isn't considered a bug).

You need to use four spaces in your indents, so the below should work as expected:

```
1.  aaaaa
2.  bbbbb
    *   ccccc
    *   ddddd
3.  eeee
```

**Comment by vbkaisetsu** [comment]
I'm sorry. I couldn't find previous bug reports.
Okay, your example works good.

**Comment by RyperHUN** [comment]
I have the same problem. Tried your example with 4 spaces and got wrong results:
Input:
```
Test2:
1.  aaaaa
2.  bbbbb
    *   ccccc
    *   ddddd
3.  eeee
```
`python -m markdown file.md`
Output:
```
<p>Test2:
1.  aaaaa
2.  bbbbb
    *   ccccc
    *   ddddd
3.  eeee</p>/
```

**Comment by mitya57** [comment]
@RyperHUN You need an empty line before the lists, both the outer and the inner. This input:
```markdown
Test2:

1.  aaaaa
2.  bbbbb

    *   ccccc
    *   ddddd
3.  eeee
```
Gives expected result:
```html
<p>Test2:</p>
<ol>
<li>aaaaa</li>
<li>
<p>bbbbb</p>
<ul>
<li>ccccc</li>
<li>ddddd</li>
<li>eeee</li>
</ul>
</li>
</ol>
```
