### ISSUE TITLE
Recursion error in TOC Ext with long documents

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#366]
It appears that the TOC extension reaches recursion depth in the [`order_toc_list`](https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/toc.py#L25) function (which defines and calls the `build_correct` function). This was reported on the [mailing list](http://sourceforge.net/p/python-markdown/mailman/message/33044462/):

> A quick look at the source indicates that that method recursively calls itself to turn a flat list of headers (h1-6) taken from the document and rearranges them into a properly nested list to use as the Table of Contents.

Ideally a refactor would eliminate any recursion, although that may be a little too high to aim. We certainly don't want a situation where a longer document guarantees greater recursion depth because that will always put an artificial limit on the length of the document the parser can handle. In this case, the returned list should never be more than 6 levels deep (`h1-6`), so ideally, the code would never go more than six levels of recursion deep -- which is perfectly acceptable.

**Comment by facelessuser** [comment]
> Ideally a refactor would eliminate any recursion, although that may be a little too high to aim.

I think handling it in one pass is quite reasonable.  There are really only three cases: level < last, level > last, level == last.  If the current depth and parents are tracked well, one pass is easily achievable.  Looking at the code, it is currently more complicated than I think it needs to be.  If I get an hour today, I will code up a fix for a pull request.

**Comment by facelessuser** [comment]
I'll run some tests tonight or tomorrow and put together a pull.

``` python
def order_toc_list(toc_list):
    """Given an unsorted list with errors and skips, return a nested one.
    [{'level': 1}, {'level': 2}]
    =>
    [{'level': 1, 'children': [{'level': 2, 'children': []}]}]

    A wrong list is also converted:
    [{'level': 2}, {'level': 1}]
    =>
    [{'level': 2, 'children': []}, {'level': 1, 'children': []}]
    """

    ordered_list = []
    if len(toc_list):
        # Initialize everything by processing the first entry
        last = toc_list.pop(0)
        last['children'] = []
        levels = [last['level']]
        ordered_list.append(last)
        parents = []

        # Walk the rest nesting the entries properly
        while toc_list:
            t = toc_list.pop(0)
            current_level = t['level']
            t['children'] = []

            # Reduce depth if current level < last item's level
            if current_level < levels[-1]:
                # Pop last level since we know we are less than it
                levels.pop()

                # Pop parents and levels we are less than or equal to
                to_pop = 0
                for p in reversed(parents):
                    if current_level <= p['level']:
                        to_pop += 1
                    else:
                        break
                if to_pop:
                    levels = levels[:-to_pop]
                    parents = parents[:-to_pop]

                # Note current level as last
                levels.append(current_level)

            # Level is the same, so append to the current parent (if available)
            if current_level == levels[-1]:
                (parents[-1]['children'] if parents else ordered_list).append(t)

            # Current level is > last item's level,
            # So make last item a parent and append current as child
            else:
                last['children'].append(t)
                parents.append(last)
                levels.append(current_level)
            last = t

    return ordered_list
```

**Comment by waylan** [comment]
Wow, that is a big improvement. Glad to see no recursion is needed. I hoped that was the case, but hadn't thought through the problem all the way. I've been removing reclusive code like this since shortly after I took the project over. This was one of the few pieces I hadn't got to yet. Looking forward to the seeing the PR with tests.

**Comment by facelessuser** [comment]
Yeah, avoiding recursion is usually the better way to go (if possible).

I thought about refactoring the current code, but it was much easier to just throw away the code and start from scratch instead of trying to massage the recursion into a non-recursion.
