### ISSUE TITLE
Add markdown-urlize to included extensions 

### ISSUE THREAD

**Issue by Wilfred** [Python-Markdown/markdown#37]
It would be great to see markdown-urlize as part of the included extensions, since it's very common functionality to add to markdown. Would this be possible? [The author seems up for it](https://github.com/r0wb0t/markdown-urlize/issues/2).

**Comment by waylan** [comment]
Seeing I just released an alpha release last night, I'm not going to be adding any new extensions. However, after 2.1 final is out it _may_ be a possibility. Although, I'm not sure why it can't just stay a third party extension. Is there much precedence of other implementations offering this functionality out of the box?

**Comment by Wilfred** [comment]
The sites I use markdown on (GitHub, StackOverflow, CodebaseHQ and I believe Posterous) all use markdown with this additional functionality. But sure, I agree it's not critical to have.

**Comment by bkeating** [comment]
You have my vote to implement this extension. It's clean, concise and as @Wilfred mentions, many services with such functionality.

**Comment by ThiefMaster** [comment]
Urlize would be a great extension, but there are some things that should be changed:
- Do not urlize something.com/net/org as long as it doesn't start with http:// or www. - too many false positives
- Do not urlize inside a link. Actially, this is a major issue as it results in bad/invalid HTML (nested `<a>` tags)
  An example for a case where this problem occurs is `[www.foobar.com][1]` with `[1]: http://foobar.com` later. This results in invalid html; here's a full doctest showing the problem: https://paste.aeum.net/show/50/ - issue ticket: https://github.com/r0wb0t/markdown-urlize/issues/5

**Comment by waylan** [comment]
If @ThiefMaster is correct, then I'm not adding the urlize extension until those issues are dealt with externally. I've never used the extension, have no need for the extension, and don't really care if it is included, so someone else will need to provide a working extension (with decent tests) before I'm willing to consider including it. Just an FYI.

**Comment by ThiefMaster** [comment]
The developer of the extensions seems to be MIA for quite some time or just not interested in it anymore.
Would be great if @waylan or anyone else familiar with python-markdown could take it over or at least fix it as having it included would indeed be great.

Something else which might be worth considering would be adding a "github-flavored" mode which would enable all the things from [GitHub Flavored Markdown](http://github.github.com/github-flavored-markdown/) (except the github.com-specific things of course)

**Comment by waylan** [comment]
If no one is willing to set up and provide a working extension, then that tells me that there is not much desire to have this extension included. As I've stated, I have no use for this extension myself - and therefore no motivation to bother with it. I certainly don't want to commit to maintaining it if no one else cares enough to get it working. I'm closing this for now. Perhaps if the status of the extension changes we can revisit then.

As an aside, a "Github Flavored Extension" sounds like an excellent idea - as a third party extension. I'd recommend something like how the "Extra" extension wraps up various different extensions to provide all the different PHP Markdown Extra additions in one place. Sounds like a project for someone who cares about that. And that person is not me. I have enough to do and I prefer non-github flavored markdown anyway.
