### ISSUE TITLE
text followed immediately by an unordered list

### ISSUE THREAD

**Issue by macterra** [Python-Markdown/markdown#370]
I would expect this markdown to generate a 3-item list:

```
this should be a list:
* one
* two 
* three
```

but it generates this HTML:

```
<p>this should be a list:
<em> one
</em> two 
* three</p>
```

Am I missing something?

**Comment by waylan** [comment]
Yes you are missing a blank line. I was going to point you to the syntax rules, but having just reread the list section, the rules don't explicitly say the blank line is required. However, the reference implementation requires the blank line as does [most implementations](http://johnmacfarlane.net/babelmark2/?normalize=1&text=this+should+be+a+list%3A%0A*+one%0A*+two+%0A*+three). That being the case, we have no intention of changing this implementation.

Many have argued that not requiring a blank line between every block level construct in Markdown was an error int he design (I tend to agree). In fact, in this particular case, requiring the blank line  saves us from unintentional lists. Consider the following paragraph from the syntax rules:

> If you do use lazy list numbering, however, you should still start the list with the number 
> 1. At some point in the future, Markdown may support starting ordered lists at an 
> arbitrary number.

Notice how the second line of that paragraph starts with `1.`. If a blank line was not required between a paragraph and a list, that paragraph would render incorrectly. Therefore, I always put blank lines between all block level constructs in my Markdown documents - even when Markdown does not require it. It is just good practice, and it makes it easier when I come back later to edit it.
