### ISSUE TITLE
Name of the syntax highlighted language

### ISSUE THREAD

**Issue by bjourne** [Python-Markdown/markdown#373]
If you use the codehilite extension, you can have markdown like this:

```
:::python
def simbets(count, bet_size, win_prob, capital):
```

Which emits:

```
<div class="codehilite"><pre><span class="k">def</span> <span class="nf">simbets</span><span class="p">(</span><span class="n">count</span><span class="p">,</span> <span class="n">bet_size</span><span class="p">,</span> <span class="n">win_prob</span><span class="p">,</span> <span class="n">capital</span><span class="p">):</span>
```

All good, and you get reasonable colorization if you use `pygmentize -S default -f html > codehilite.css` as your stylesheet. But I would suggest that you emit `class="codehilite python"` as the html code because Python is the name of the highlighted language. Then I could in my css write:

```
.python .nf { color: red; }
```

And my override would only affect Python code.

**Comment by waylan** [comment]
In all the years, I've never seen anyone make this request before. And of all the different tools that wrap Pygments, I've never seen one that does this either. In fact, I don't think Pygments even has support for it. That being the case, I have no interest in doing it. Maybe, and only maybe, if Pygments offered support for it, would i coms der offering a config setting to pass to Pygments.

That said, if you really want this, you are free to write your own extension.

**Comment by bjourne** [comment]
When you wrap pygments manually, you have full control of what `div` surrounds the highlights, so in those scenarios this feature is irrelevant. My use case is that I want a purple rectangle arround Python code, a red one around Ruby and green around C#. The code changes needed to make that happen was tiny:

``` diff
                     lexer = get_lexer_by_name('text')
+            cssclass = self.css_class + (' ' + self.lang if self.lang else '')
             formatter = get_formatter_by_name('html',
                                               linenos=self.linenums,
-                                              cssclass=self.css_class,
+                                              cssclass=cssclass,
                                               style=self.style,
```
