### ISSUE TITLE
HeaderId Extention Doesn't ID Underlined Headers

### ISSUE THREAD

**Issue by kevincox** [Python-Markdown/markdown#38]
The Header Id extension doesn't work properly on _"underlined"_ headers

Example:

```
Header 1 {#header1}
========

Header 2 {#header2}
--------
```

Becomes:

```
<h1>Header 1 {#header1}</h1>
<h2>Header 2 {#header2}</h2>
```

Expected:

```
<h1 id="header1">Header 1</h1>
<h2 id="header2">Header 2</h2>
```

**Comment by waylan** [comment]
Closing as a duplicate of Issue #16. The short answer is use the new [attr_list](https://github.com/waylan/Python-Markdown/blob/master/docs/extensions/attr_list.txt) extension.
