### ISSUE TITLE
Meta-Data extension fails when document contains dashes

### ISSUE THREAD

**Issue by kennell** [Python-Markdown/markdown#387]
The Meta-Data extension fails to extract metadata when the metadata is wrapped by three dashes. Example:

```

---
title: why python is great
author: guide von rossum
date: 2014-05-25

---

some **markdown** content
```

The dashes have become the de-facto standard for enclosing metadata in Markdown, the Markdown2 module already suports this, see: https://github.com/trentm/python-markdown2/wiki/metadata

**Comment by waylan** [comment]
@kevvvvv, thanks for your suggestion. However, this was recently added in ef6eb03 and will be available in the [next release](https://github.com/waylan/Python-Markdown/blob/master/docs/release-2.6.txt#L168). As such I am closing this as a duplicate.
