### ISSUE TITLE
Don't convert links without scheme

### ISSUE THREAD

**Issue by musiKk** [Python-Markdown/markdown#388]
I converted `[Google](www.google.com)` and was surprised to find that this creates a relative link. I find this rather counter-intuitive given that I was writing a component that allows users to create content formatted with markdown. There may be use cases where relative links are better (documentation?) so I think there should be some options:
- just slap `http://` in front of it
- ignore it and just print the link text without formatting (StackOverflow does it like this)
- generate the relative link as it is currently the case ([GitHub](www.github.com) does it like this, and from my POV this doesn't make sense); for all I care this may stay the default

Does this or something along those lines sound reasonable?

**Comment by waylan** [comment]
As every implementation [behaves](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%28www.example.com%29) the same way, I see no reason to change anything here. The link is copied into the HTML exactly as you typed it. To do anything else would be an error. For example, what if I wanted to create a relative link to the file `www.html`? If `http://` was automatically pretended, then I would be unable to do so. Never mind that there is a tremendous number of domains that do not start with `www.` and/or end with something other than `.com`. Whatever solution one may come up with is likely to have some errors. I'm closing this wontfix.

**Comment by musiKk** [comment]
That's why I think it should be configurable. If you use markdown for users writing comments, relative links don't make any sense since you can never be sure if the site's structure changes. As I said, StackOverflow [gets it right and at least doesn't show links without scheme](http://meta.stackexchange.com/a/248583/157045). I guess its implementation is not featured in babelmark2.

I also didn't want to assume that links have to start with www or end with com. `localhost` should become `http://localhost` as well if the corresponding option is enabled.

I'm not too familiar with Python-Markdown's architecture. Is it difficult to add options to patterns? From what I can see, all that has to be done is change `LinkPattern`'s `sanitize_url` to evaluate some option.

**Comment by waylan** [comment]
We have an extensive [extension API](https://pythonhosted.org/Markdown/extensions/api.html) (the [tutorial](https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown) might be a good place to start). You are free to do whatever you want. However, in all of the years, this is the first that I have seen anyone ever mention this. And for the record, I do not consider SO's implementation a true Markdown. What they have is more like 'Markdown inspired '. I **_will not**_ be making any changes.
