### ISSUE TITLE
Backslashes disappear during python markdown processing

### ISSUE THREAD

**Issue by jordanjambazov** [Python-Markdown/markdown#39]
Any backslashes \ get removed during the markdown processing. Backslashes that are in code blocks get displayed properly, but ones in the markdown body -- not.

For example, if you parse "C:\Program Files\" the markdown processor will return "C:Program Files".

**Comment by mikkeloscar** [comment]
`\` backslash is an escape character and has to be escaped with `\\`. 
See http://daringfireball.net/projects/markdown/syntax#backslash

**Comment by jordanjambazov** [comment]
Hmm... but if we escape all backslashes they appear doubled in the code block. Take a look at this markdown preview: http://github.github.com/github-flavored-markdown/preview.html Backslashes are can be escaped, but escaping shouldn't be compulsory. Currently backslashes are completely removed by Python Markdown if they're not escaped.

**Comment by mikkeloscar** [comment]
I'm sorry, you are right. They shouldn't be removed if they aren't escaped.
