### ISSUE TITLE
toc permalinks icon - option to add a different icon

### ISSUE THREAD

**Issue by erez-o** [Python-Markdown/markdown#398]
Looking at different internet sites like Wikipedia, Readthedocs, Github, etc.. the paragraph icon is no longer the standard for permalinks.

Either the "§" sign is used (wikipedia), or a link icon is used (Readthedocs & Github).

1) Is it possible to have a configuration option to change the paragraph icon to a different icon?
2) Is it possible to have configuration option to put the permalink in the beginning of the header, and not in the end? Again, the standard in both Github and Wikipedia.

Thanks.

**Comment by facelessuser** [comment]
I don't think the current extension allows that.  But the truth is, there is no standard for permalinks.  Some things catch on with certain groups and other things catch on with other groups.  I think this extension's implementation follows Python's documentation convention https://docs.python.org/3/whatsnew/3.4.html. I think it served the author's purpose as that was it's intent.

I think allowing the configuration of the link icon would be a good addition, but I don't know if the author is going to want to implement a whole new variation putting the link in front, but maybe.

I say, if you want something radically different, you can implement your own.  I have done so myself here: https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/headeranchor.py.  This extension puts anchor links before headers like Github does (using the method that they used at the time of creating the extension; Github can't seem to stop tweaking their CSS, so it may not be exactly the same now, but it works the same).  Anyways, so it just generally formats the link header, and everything is aligned and styled via CSS. Documentation for the extension is here and the documentation is  generated with the extension mentioned: http://facelessuser.github.io/PyMdown/Extensions/HeaderAnchor.html.  This is currently compliant with changes made in 2.6.0 of Python Markdown.

EDIT: I should mention that the above extension does rely on the toc extension to ensure it uses the same slugify method etc. So the toc extension needs to be available to import, but not necessarily turned on.

**Comment by waylan** [comment]
As the [documentation](https://pythonhosted.org/Markdown/extensions/toc.html#usage) states regarding the 'permalink' option:

> When set to `True` the paragraph symbol (¶ or `“&para;”`) is used as the link text. When set to a string, the provided string is used as the link text.

Pay special attention to the second sentence. You can pass in whatever string you want and it will be used as the label. Therefore, you could pass in `'&sect;'` if you wanted "§". Or if you wanted an icon [like GitHub](https://github.com/blog/1106-say-hello-to-octicons), pass in the appropriate character from your [icon font](https://css-tricks.com/flat-icons-icon-fonts/) of choice.

As far as the ability to place the link before the header, I'd prefer to avoid feature creep. As other third-party extensions exist that offer that feature, I see no need to add it here.

**Comment by erez-o** [comment]
Thx, 

I think that for future references, the documentation would be better if you give the examples you gave me: 
you could pass in '&sect;' if you wanted "§". Or if you wanted an icon like GitHub, pass in the appropriate character from your icon font of choice.
