### ISSUE TITLE
Apostrophes at the beginning of words rendered incorrectly with Smarty

### ISSUE THREAD

**Issue by gandaro** [Python-Markdown/markdown#399]
Examples:
- ‘90s instead of ’90s
- ‘tis instead of ’tis
- ‘twas instead of ’twas
- etc.

**Comment by mitya57** [comment]
I will follow the original SmartyPants approach — it handles '90s, but not 'tis or 'twas.

**Comment by gandaro** [comment]
So you do not care if your SmartyPants implementation actually works?

**Comment by mitya57** [comment]
@gandaro The other examples you provided ('tis and 'twas) are rarely used and hard to detect. That's why I think we should not bother supporting them.

@waylan Do you agree with me?

**Comment by waylan** [comment]
I say we should follow the original SmartyPants implementation (the Perl one). People have been using that for many years and I see no reason to do anything different. It is simply to difficult to effectively determine when an apostrophe is intended and when a single quote is intended. If it really matters to a document author, the author can insert the html entity into the document manually in those rare edge cases.

Alternatively, if someone thinks that all of the edge cases can be handled, they are free to build their implementation. I would be happy to be proven wrong. However, I'm not interested in maintaining it myself.

**Comment by mitya57** [comment]
The current version should match the original smartypants.
