### ISSUE TITLE
TOC: Problem with "Link-Headers"

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#4]
This issue has been copied from [Ticket 84](http://www.freewisdom.org/projects/python-markdown/Tickets/000084) of our old bug tracker and was reported by "Eugen" (no contact info provided). It has been copied as-is:

> Suppose you have got this markdown structure:
> 
> <pre>
> [TOC]
> ...
> # [Wikipedia](http://en.wikipedia.org/)
> ...
> </pre>
> 
> 
> I.e., one of the headers is a link to a website.
> 
> Then, the generated TOC link to the Section "Wikipedia" does not link to the section inside the document but also to "http://en.wikipedia.org/". I don't know if this is intended behaviour but I think it is irritating.

**Comment by eugenkiss** [comment]
Thanks a bunch ;)
