### ISSUE TITLE
Surprising compilation of double-spaced asterisks

### ISSUE THREAD

**Issue by davidchambers** [Python-Markdown/markdown#40]
This may in fact be what the "spec" (Markdown.pl) tells us is correct behaviour, but it strikes me as odd:

```
>>> import markdown
>>> markdown.version
'2.0.3'
>>> print markdown.markdown('*  *  *')
<ul>
<li>
<ul>
<li>*</li>
</ul>
</li>
</ul>
```

Perhaps a more sensible translation would involve a single list item (containing two asterisks) inside a single unordered list.

I'm of the opinion that defining correct translations for "invalid" input is just as important as defining correct translations for valid Markdown.

**Comment by waylan** [comment]
Hey David, this **was** a bug which we **already** fixed so I'm closing this.

``` python
>>> import markdown
>>> markdown.version
'2.1.0.alpha'
>>> markdown.markdown('* * *')
u'<hr />'
```

Which, btw is the correct behavior. See [babelmark](http://babelmark.bobtfish.net/?markdown=*++*++*).

Oh, and if you could give [2.1.0.alpha](https://github.com/waylan/Python-Markdown/downloads) a spin, I'd appreciate it.

**Comment by davidchambers** [comment]
Thanks, Waylan. You're one step ahead as always. I should have pulled the latest source and/or searched the issue tracker before submitting this but, well, I didn't. ;)

I'm in the midst of an overhaul of Mango's code and syntax at the moment (removing lots of magic from the latter). As a result I'm planning to generate HTML for every one of my existing Markdown documents to verify that my changes have not introduced glaring regressions. While I'm at it, I'll do the before and after with 2.1.0.alpha and let you know if anything shows up in the diff. :)
