### ISSUE TITLE
Link-definitions inside blocks

### ISSUE THREAD

**Issue by kaba2** [Python-Markdown/markdown#406]
Link-definitions inside a block are ignored. For example, using the admonition extension:

```
!!! type "optional explicit title within double quotes"
    Any number of other indented markdown elements.

    This is the second paragraph. Lets try [this][].

    [this]: www.google.com
```

The same happens with list items. 

I would expect this to work. Is this by design or a bug?

**Comment by waylan** [comment]
This is definitely not a bug. Most legacy parsers follow this same behavior (see [babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+++This+is+a+list.+Lets+try+%5Bthis%5D%5B%5D.%0A%0A++++%5Bthis%5D%3A+www.google.com)). Interestingly, I was going to point to where the rules say a link must be at the document root (not nested), but to my surprise (I've known that it works in practice this way for many years) it doesn't say that. In fact, the rules simply state that they can be placed "anywhere in the document... on a line by itself." While it is not expressly stated, one interpretation of "on a line by itself" could be that nothing, including indentation, is permitted on the line. Obviously, not all implementation authors agree with that interpretation.

Perhaps it would help to consider that the same reference would be used for multiple links within the document. Consider this [example](http://johnmacfarlane.net/babelmark2/?normalize=1&text=This+is+a+paragraph+with+a+%5Blink%5D%5B%5D%3B%0A%0A*+This+is+a+list+item+with+a+%5Blink%5D%5B%5D+and+a+nested+reference.%0A%0A++++%5Blink%5D%3A+http%3A%2F%2Fexample.com):

``` markdown
This is a paragraph with a [link][];

* This is a list item with a [link][] and a nested reference.

    [link]: http://example.com
```

Even though that link reference is nested in the list, it would still apply to both links. That might be surprising to some. Therefore, by forcing all link references to be at the document root, it is not  a surprise that they are global and do not only apply to the item they are nested in.

For that reason, I think that the implementations which allow the references to be nested have it wrong.

**Comment by kaba2** [comment]
Dear Waylan,

I propose two principles to guide choices in this matter.

## Embedding principle

Suppose A and B are valid texts of Markdown, and A contains a sub-element I (e.g. a list item). Then the text formed by copying B into A under I is valid Markdown. In addition, the content of B is faithfully embedded into I; it contains the same information as B does.

## Encapsulation principle

Suppose A is a valid text of Markdown, and A contains a sub-element I (e.g a list item). Then changes to the content of I only affect I and its sub-elements. 

## Embedding example

Here is an example of embedding B into A under I.

### Text A

```
Things to buy

* apples
* milk

Also, look up foobar from [Google][].

[Google]: https://www.google.fi
```

### Text B

```
Foo-Milk. Contains 100 calories, according to [Google][].

[Google]: https://www.google.com
```

### Text B embedded into a sub-element I of A

```
Things to buy

* apples
* Foo-Milk. Contains 100 calories, according to [Google][].

    [Google]: https://www.google.com

Also, look up foobar from [Google][].

[Google]: https://www.google.fi
```

## Where should link-definitions be allowed in Markdown?

We can now evaluate the different design-choices in terms of the two principles.

### Link-definitions only at the top level

In this case, a link-definition is only parsed at the top level. This is how things currently are. 

The embedding principle does _not_ hold, because a nested link-definition is not handled.

The encapsulation principle holds, because a nested  link-definitions is not handled at all; there is no leakage of information upwards.

### Link-definitions at any element, without scoping

In this case, a link-definition is parsed at every element, but every link-definition refers to the same global name. That is, all the link-definitions reside in the same scope. This is how you interpreted the change.

The embedding principle holds.

The encapsulation principle does _not_ hold. This is because link-definitions in the sub-elements can collide with link-definitions at upper-levels, or indeed with link-definitions in arbitrary elements. As I understand it, the failure of the encapsulation covers the problems you mentioned.

### Link-definitions at any element, with scoping

In this case, a link-definition is parsed at every element. Each element (e.g. a list item) creates a local link-definition-scope. If a link is not defined locally, then it is looked up recursively at the parent scope. This is analogous to how variables are scoped in programming languages. This is how I think this should work.

The embedding principle holds.

The encapsulation principle holds.

## Real-life example

I have implemented a Markdown-extension, which allows you to wrap blocks into html-elements, like this:

```
!!! <div class="note">

    Things to buy

    * apples
    * milk

    There is also the Finnish [Google][].

    [Google]: https://www.google.fi
```

To make the content work exactly as without the wrapping, the embedding principle must hold. As discussed, the current implementation fails the embedding principle.

To demonstrate the encapsulation principle, and the importance of scoping, consider:

```
There is the international [Google][].

[Google]: https://www.google.com

!!! <div class="note">

    There is also the Finnish [Google][].

    [Google]: https://www.google.fi
```

Under my proposed design, the link-definition inside the div-region will not leak to the upper levels due to the scoping rules; the encapsulation principle holds.

## Conclusion

I propose the link-definitions to be allowed to be defined everywhere, with each sub-element creating a local link-definition-scope. This fulfills the embedding principle, and the encapsulation principle.

As you note, this proposal is not in contradiction with the (vague) specification. In the long term, the specification itself should be updated and improved to make it more useful and less ambiguous. This is one of such proposals to do so.

If you are against it, I wonder if I could make Markdown behave like this as an extension?

Best regards,
Kalle

**Comment by waylan** [comment]
@Kaba2 I have no interest in implementing this myself. You appear to have created an entire new spec which it not implemented in any Markdown (or CommonMark) parser. Of course, you are free to create any extension that you want. The extension API gives you fill access to all parts of the parser, so, if it is possible at all, then it is possible through an extension.
