### ISSUE TITLE
Smarty and abbr issue

### ISSUE THREAD

**Issue by facelessuser** [Python-Markdown/markdown#408]
Not sure how hard this is to fix, or if this is a case that is worth the effort, but `abbr` extension coupled with `smarty` can sometimes render the wrong type of quote.

``` python
import markdown


src = '''
GFM's syntax is different than the Markdown spec.

*[GFM]: Github Flavored Markdown

'''

print(
    markdown.markdown(
        src,
        extensions=[
            'markdown.extensions.abbr',
            'markdown.extensions.smarty'
        ]
    )
)
```

output

```
GFM‘s syntax is different than the Markdown spec.
```

Obviously a work around is to just insert the quote you want manually:

```
GFM&rsquo;s syntax is different than the Markdown spec.
```

I understand why it is rendering wrong.  `smarty` would have to run before `abbr` to fix this, but I don't know how practical that is.

**Comment by mitya57** [comment]
"GFM" and everything after it are different text blocks from smarty's point of view. I don't think we can do anything about this, except maybe adding a special case for blocks that start with 's.

**Comment by facelessuser** [comment]
> "GFM" and everything after it are different text blocks from smarty's point of view.

Yes, I do understand that.  That is also why I mention I am not sure how realistic a fix might be, I haven't dug too deep, and I realize you are more familiar with how smarty interacts with everything else in Python Markdown.

> I don't think we can do anything about this, except maybe adding a special case for blocks that start with 's.

It may be worth a shot to see if a case for `'s` would help without adding adverse affects.  But yeah, if it adds more issues, then we can live without it.

**Comment by waylan** [comment]
@mitya57, Smarty is your work. I'll leave this to you to do something with. If you decide this is not feasible/worth doing, you are free to close it (I'm not sure if commit access gives to the ability to close issues - let me know if not).

**Comment by mitya57** [comment]
I will try to look at this on the weekend.

**Comment by mitya57** [comment]
I tried adding a special case for `'s`, and it causes some problems. For example, if someone wants to write `‘s’ is a letter`, then that special case makes the left quote a closing one. Of course I can add a special case for that as well, but I don't think it's the right thing to do.

So this issue is “wontfix”.

**Comment by mitya57** [comment]
In case someone wants to play with my special case code, it is in mitya57@82abd25832b6a1f2.

**Comment by waylan** [comment]
Thanks @mitya57. I expected that might be how things worked out.

**Comment by facelessuser** [comment]
Thanks for looking into it.  I realized it may not be worth the effort.  To be honest, I feel something like detecting quotes and apostrophes is something better geared towards programmatic approaches instead of regex.  Regex alone makes it difficult to detect the context of these kinds of things.

It not a big deal though as as manually inserting `&rsquo;` in these types of cases is easy enough.
