### ISSUE TITLE
Footnote extension: validate ids for unicality

### ISSUE THREAD

**Issue by georgthegreat** [Python-Markdown/markdown#409]
Add a config option to throw in case of non-unique footnote id was found.

I can work on this if no objections will be expressed.

**Comment by waylan** [comment]
Throw an error? When parsing a document? Absolutely not! The parser should never throw an error while parsing a document. Not only is this typical Markdown practice, but many/most use Markdown parsers behind web servers, many of which would crash the entire server if an error was thrown during parsing. That puts too much power in the hands of users to bring down a server.

I realize you are suggesting this as a non-default option, but I'm not at all interested. Of course, you are free to fork the extension and do whatever you want, but I don't recommend it..
