### ISSUE TITLE
multiple emphasis not handled correctly.

### ISSUE THREAD

**Issue by inklesspen** [Python-Markdown/markdown#41]
```
because _I_ wouldn't kill him, the _bunshin_ would
```

should come out as

```
<p>because <em>I</em> wouldn't kill him, the <em>bunshin</em> would</p>
```

(according to the official spec and Dingus) but in 2.0.3 it comes out as

```
<p>because <em>I_ wouldn't kill him, the _bunshin</em> would</p>
```

**Comment by waylan** [comment]
This has already been fixed in the current code base and will be available with the next release. Closing this.

**Comment by inklesspen** [comment]
Any idea when that release will be?
