### ISSUE TITLE
Strange behaviour of returning symbol

### ISSUE THREAD

**Issue by georgthegreat** [Python-Markdown/markdown#410]
According to the source, the return-back arrow is only inlined into last `p` element of footnoted text.

This leads to a strange cases when footnote ends with `blockquote` or `header` elements.

![2015-05-17 14-07-03 new tab - mozilla firefox](https://cloud.githubusercontent.com/assets/1121500/7670081/36a9c646-fc9e-11e4-9cab-a1bb127d8cee.png)

This probably could be fixed by some weird CSS like

```
div.footnote p ~ blockquote:last-of-type
{
    display: inline-block;
    width: 90%;
}

div.footnote blockquote + p
{
    display: inline;
}

div.footnote p ~ h3:last-of-type
{
    display: inline;
}

div.footnote h3 + p
{
    display: inline;
}
```

But I suggest just removing the workaround from [here](https://github.com/georgthegreat/Python-Markdown/blob/master/markdown/extensions/footnotes.py#L158)

**Comment by waylan** [comment]
So you are saying we should just append the link to the end of the last item? What if the last item is a list? Then the backlink needs to be appended to the last child (`<li>`) of the last item (`<ul>`). Or if the list item contains paragraphs, then the backlink might need to be appended to the last paragraph in the last list item. Or, if the last item in the footnote is a blockquote, the backlink needs to be appended to the last child paragraph of the blockquote. Or, if the last item in the blockquote is a list... well, you get the idea. The current solution guarantees valid HTML regardless of what is contained within the footnote and does not require that the entire structure of the footnote needs to be taken into consideration when determining where to place the backlink.

I'm not opposed to a different solution, but I prefer something simple like what we have now.

**Comment by georgthegreat** [comment]
What we need is the appending of backlink text to the last text element of out footnote, yes?

Recursion may be helpful there. I'll work on patch and we'll discuss it once it's ready (or when I'll fail, which is also possible). Is it ok?

**Comment by waylan** [comment]
> What we need is the appending of backlink text to the last text element of out footnote, yes?

It is not that simple. What if the last text is bold? Then it needs to be appended after the strong tag (probably in the strong tag's tail). My point is that whatever solution you (or I) may come up with, there will always be another edge case we didn't account for which will be wrong. I would be happy to be proven wrong, but I expect that the current solution is the best solution that will work in all situations.

**Comment by georgthegreat** [comment]
If the last text is bold than I consider the user to be resposible for styling the returning element.
Why not?
