### ISSUE TITLE
A list in a footnote body generates invalid HTML

### ISSUE THREAD

**Issue by georgthegreat** [Python-Markdown/markdown#412]
Assuming the following markdown:

``` markdown
Some text[^1]

[^1]: 
    1.  The top couple half figure, contrary sides and hands across with bottom couple,

        Half figure back on your own sides, and turn partner to places,

        Swing partners with right hands into straight line long-ways, as in a reel, and

        Set,

        Hey and return to places,

        The other three couples do the same.

    2.  Top and bottom couples meet and set,

        Then each gentleman leas the opposite lady to the couple on his left, and set,

        Aach four right and left,

        Swing side couples to places, and turn partners all eight,

        The other two couple o the same.
```

Converting it as follows:

``` python
md = markdown.Markdown(extensions=["footnotes"], output="xhtml5")
md.convert(data)
```

Gives the following HTML (I've added head and body tags, pretty-printed the stuff

``` html
<html>
    <body>
        <p>Some text<sup id="fnref:1">
                <a class="footnote-ref" href="#fn:1" rel="footnote">1</a>
            </sup>
        </p>
        <div class="footnote">
            <hr />
            <ol>
                <li id="fn:1">
                    <ol>
                        <li>The top couple half figure, contrary sides and hands across with bottom couple,</li>
                        <p>Half figure back on your own sides, and turn partner to places,</p>
                        <p>Swing partners with right hands into straight line long-ways, as in a reel, and</p>
                        <p>Set,</p>
                        <p>Hey and return to places,</p>
                        <p>
                            <p>The other three couples do the same.</p>
                        </p>
                        <li>
                            <p>Top and bottom couples meet and set,</p>
                        </li>
                        <p>Then each gentleman leas the opposite lady to the couple on his left, and set,</p>
                        <p>Aach four right and left,</p>
                        <p>Swing side couples to places, and turn partners all eight,</p>
                        <p>The other two couple o the same.</p>
                    </ol>
                    <p>
                        <a class="footnote-backref" href="#fnref:1" rev="footnote" title="Jump back to footnote 1 in the text">&#8617;</a>
                    </p>
                </li>
            </ol>
        </div>
    </body>
</html>
```

Each `<li>` element in footnote is closed after the first line, while it should be closed only before the beginning of the next `<li>`.

**Comment by waylan** [comment]
Thanks for the report. I can verify this is a bug, I'll take a look.

Also there is another peculiarity in the output, The last paragraph of the first list item (or what should be) is wrapped in double paragraph tags:

``` html
<p>
  <p>The other three couples do the same.</p>
</p>
```

Not sure what to make of all this.

**Comment by georgthegreat** [comment]
Please, note that the empty lines between the paragraphs are completely empty, they don't contain any blank symbols at all.

**Comment by waylan** [comment]
> Please, note that the empty lines between the paragraphs are completely empty, they don't contain any blank symbols at all.

Why should that matter? The [syntax rules](http://daringfireball.net/projects/markdown/syntax#p) clearly state

> A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank. 

And in fact, the parser enforces that rule in the very first step when [normalizing white space](https://github.com/waylan/Python-Markdown/blob/master/markdown/preprocessors.py#L55) by removing all white space in blank lines. The rest of the parser will never see that white space and could not possibly be affected by it.

**Comment by georgthegreat** [comment]
Ok, this shoudn't be a problem then.

I wonder, how do I markup a footnote followed by a code block (which starts from the tab/space sequence according to [original grammar](http://daringfireball.net/projects/markdown/syntax#code)).

This isn't the case of this issue, though.

**Comment by waylan** [comment]
> how do I markup a footnote followed by a code block

You don't. Just like you can't have a code block after a list. These are known limitations of Markdown with no workaround. Believe me, people have been trying to suggest solutions for years, but until the official rules are updated to address such issues, most implementations will continue to ignore these issues.

And frankly, you are only reporting the current issue now because most people don't write such extensive footnotes, and may have never tried as they consider footnote bodies to be significantly constrained. That said, it sould work. However, if you plain on continuing to write such complex documents, my suggestion would be to consider a format better suited to the task (perhaps ReST).

**Comment by facelessuser** [comment]
I can fix this.  The key is send the content down not with a parent of `li`.  The parser just can't handle `li` as the parent for complicated things.  At some point, it switches back to the `ol` as the parent.  What you have to do is send it down with a reasonable, surrogate parent.  Then you just pop the elements off the surrogate parent and add them pack to the intended parent.

```py
            self.parser.parseChunk(temp_div, self.footnotes[id])
            for el in list(temp_div):
                li.append(el)
                temp_div.remove(el)
```

Sanity restored

```html
<li id="fn:7">
<ol>
<li>
<p>The top couple half figure, contrary sides and hands across with bottom couple,</p>
<p>Half figure back on your own sides, and turn partner to places,</p>
<p>Swing partners with right hands into straight line long-ways, as in a reel, and</p>
<p>Set,</p>
<p>Hey and return to places,</p>
<p>The other three couples do the same.</p>
</li>
<li>
<p>Top and bottom couples meet and set,</p>
<p>Then each gentleman leas the opposite lady to the couple on his left, and set,</p>
<p>Aach four right and left,</p>
<p>Swing side couples to places, and turn partners all eight,</p>
<p>The other two couple o the same.</p>
</li>
</ol>
<p><a class="footnote-backref" href="#fnref:7" rev="footnote" title="Jump back to footnote 6 in the text">&#8617;</a></p>
</li>
```

**Comment by waylan** [comment]
> The parser just can't handle `li` as the parent for complicated things. At some point, it switches back to the `ol` as the parent.

That actually makes sense. There is a lot of special cases for parsing standard Markdown lists. Therefore the code is checking if the parent is a `li` and doing special things. Of course, for the body of a footnote, none of that applies.

Using a temporary `div` as the parent makes sense. In fact, that is what the Markdown class does for the document root. There isn't any reason why the footnote body couldn't be treated (mostly) as a separate document. We just need a comment in the code explaining why the parent element is a throwaway `div` rather than the actual `li`.

**Comment by facelessuser** [comment]
This will fix #493 as well.  The only thing I could come up with to fix this **and** not break all the tests is to add a new line, and then remove it after parsing.

```py
            # Add a newline to ensure proper parsing at block end.
            self.parser.parseChunk(temp_div, self.footnotes[id] + '\n')
            # Transfer elements from surrogate parent to the intended
            # parent.  li is not a good parent to use as there is special
            # li aware code in list block handlers.  We treat the footnote
            # content as its own document to ensure proper conversion.
            for el in list(temp_div):
                # Strip extra newline now that we are done.
                if el.text and el.text.endswith('\n'):
                    el.text = el.text[:-1]
                li.append(el)
                temp_div.remove(el)
```

I think that will take care of all the bugs that can be reasonably fixed outside of 3.0.  I'll issue a pull a little later today.

**Comment by facelessuser** [comment]
Nevermind it only works in some cases.  I think we need remove the newline in post when we replace the nbsp.

EDIT: I think making the newline part of the nbsp placeholder is the way to go, or do what is done elsewhere and use `STX` etc. That would probably make more sense and keep things consistent.

**Comment by waylan** [comment]
Does it only work "in some cases" for this issue or #493? If the problem is #493 then I'd suggest moving forward with this and addressing #493 separately.
