### ISSUE TITLE
`tab_length` parameter ignored

### ISSUE THREAD

**Issue by karepker** [Python-Markdown/markdown#414]
Input file:

``` markdown
* Test 1
  * Test A
  * Test B
* Test 2
```

run with `markdown.markdownFromFile('input.md', tab_length=2)` produces output file:

``` html
<ul>
<li>Test 1</li>
<li>Test A</li>
<li>Test B</li>
<li>Test 2</li>
</ul>
```

when it should produce a nested list.

I think I've found the issue. In `markdown/blockprocessors.py` line 304: 

``` python
RE = re.compile(r'^[ ]{0,3}\d+\.[ ]+(.*)')
```

`3` should be `self.tab_length - 1`. Similarly for `CHILD_RE` and `INDENT_RE` in `OListProcessor`, `RE` in `UListProcessor`, and `CHILD_RE` in both `SaneOListProcessor` and `SaneUListProcessor`.

When I make these changes locally, I get the expected output for my test case, and all other tests pass as well. See [this commit](https://github.com/karepker/Python-Markdown/commit/6cbc66b4e63de0ddba7413b653591274fc6587cf) in my fork of your repository.

I can send you a pull request with these changes if you'd like.

**Comment by waylan** [comment]
A pull request is welcome.
