### ISSUE TITLE
Replace OrderedDict with prioritized List?

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#418]
I'm looking for feedback on a possible Extension API change which might be introduced in version 3.0.

Currently (version 2.x), all extensions register where they are run within the parser with our homegrown OrderedDict. Each piece of code is assigned a name in the dict and an extension inserts itself before or after a given name. 

``` python
patterns.add(SomePattern(), '<emphasis')  # insert before "emphasis" pattern
del patterns['emphasis']                  # remove "emphasis" pattern
```

What I am proposing is that instead of an Ordered Dict, we use a list (as we did in version 1.x). However, each item in the list is assigned a "priority" attribute which is used to sort the list in order.  For example, each inlinepattern class would have a priority set (10, 15, 20, 25, 30, ...). Higher numbers get run first. An extension could set a priority of 22 to get placed between items with priorities of 20 & 25. If a second extension needed to also be between 20 & 25 but before the extension with priority 22, is could use priority 23 or 24, and we don't have the possible conflicts that exist now.

The tricky part would be in removing existing patterns. It is easy to do with the named keys. It might be a little more tricky without. And we can't hardcode index position as that can be changed by other extensions. The entire list would need to be searched for the given class instance. Do we set a "name" property on each class for this reason, rely only on the "priority" property, or something else? Perhaps the built-ins could all be assigned to constants. That way, the constant (a text-based name) could be used for reference purposes, but the value would be the integer (much like the logging modules error codes). Or maybe the constants could point to the class instances themselves.

Therefore, where `patterns` is the list of patterns, one might alter the list like this:

``` python
patterns.register(SomePattern(), priority=23)
patterns.deregister(inlinepatterns.EMPHASIS)
```

I'm using register/deregister as opposed to register/unregister for the reasons stated [here](http://english.stackexchange.com/questions/25931/unregister-vs-deregister) (although it could change by popular demand). However, what I'm not sure about is the best way to define the priority:

This is odd as the priority is a function of the registration process, not creation of the class instance:

``` python
myinstance = MyPattern(priority=23)
patterns.register(myinstance)
```

This is easy to understand but then requires the parser to monkeypatch the class instance to attach the priority to the class:

``` python
myinstance = MyPattern()
patterns.register(myinstance, priority=23)
```

In the first example, `register` is simply an alias to `list.append`. However, the second example would require something like this:

``` python
class PriorityList(list):
    def register(self, item, priority):
        item.priority = priority  # the monkeypatch
        self.append(item)
```

Of course, regardless of implementation details, we would only sort once after all extensions are loaded.

**WHY?**
1. Provides more flexibility to extension authors. Multiple third-party-extensions would be less likely to conflict with each other. 
   
   For example, in the current situation, Extension A removes "emphasis" and extension B tries to insert before emphasis (`<emphasis`). If the user lists the extensions `[B, A]`, everything works fine, but if she lists them as `[A, B]`, then a `KeyError` will be raised when setting up extension B. 
   
   Or two extensions might use the same name. For example multiple "math" extensions currently exist but each does something slightly different. A user could conceivably try to use two of them together, but one might replace the other.
2. Gets rid of the awkward `<emphasis` syntax. Ugh.
3. Removes the homegrown (and mostly untested) `OrderedDict` (the implementation that ships with Python only allows adding to the end so it is useless for this purpose). The fact that the new implementation is just a sorted list is an implementation detail that does not even need to be mentioned in the docs. Extension authors only need to know about and use the two methods `register` and `deregister` on a registry.

Any and all feedback is welcome.

**Comment by mitya57** [comment]
I think it is a good idea in general.

Were you going to break existing extensions for 3.0 anyway, or this is the first extensions API break?

**Comment by waylan** [comment]
Yes, the API is already breaking for version 3.0. So if this happens, it needs to happen then.

**Comment by ryneeverett** [comment]
Sorry if I missed it but would the priority value be duck-typed (only requirement being implementation of the dunder-comparison methods)? I only see integer examples but it seems like conflicts would arise unless floats were permitted.

**Comment by waylan** [comment]
I just posted a [gist](https://gist.github.com/waylan/56ade193466c24a4957f) with a first attempt at an implementation of the registry.

@ryneeverett, yes duck-typing would work fine. In fact, [I tested for this](https://gist.github.com/waylan/56ade193466c24a4957f#file-test_registry-py-L32). The [sort method](https://gist.github.com/waylan/56ade193466c24a4957f#file-registry-py-L45) is just `self._data.sort(key=lambda item: item.priority, reverse=True)`

I went with a new object (which holds the actual list in a private attribute) rather than a subclass of `list` so that we have total control over how items are accessed and/or added. For example, an error will always be raised if an item is added without a priority. I even created a [few](https://gist.github.com/waylan/56ade193466c24a4957f#file-test_registry-py-L18) [tests](https://gist.github.com/waylan/56ade193466c24a4957f#file-test_registry-py-L78) for that.

The one thing I'd like to change is that slicing returns a `list` rather than a new `Registry` object. Defining `__getitem__` gives us both `object[1]` and `object[1:]` support, so that method would need to check for slicing and act differently (wrap the return value).

I also chose to not allow a new Registry instance to be created by passing a list in (no args are accepted on `__init__`). If I change this, it would also make the slicing easier. But I'm not sure which way to enforce a priority for each item. Do I check that each item has a priority attribute which is not None? Do I require each item to be passed in as a two item tuple (`(item, 32)`)? 

Thoughts?

**Comment by waylan** [comment]
Just updated the [Gist](https://gist.github.com/waylan/56ade193466c24a4957f). `__getitem__` now checks for a slice object and acts correctly. Also, the sort method was made private and is called by any method which outputs data. The user should never get unsorted data because she forgot to call sort. In fact, the sort method was renamed `_sort` to indicate it is private. To avoid unnecessary sorting, the sort status is also stored in the instance so sorting is only done when needed.

Oh, and one thing I forgot to mention in response to @ryneeverett, if two items are given the same priority, there is not conflict per se. At least no error will be raised and neither item will be lost. They will simply have the same priority and will be in the order in which they were added. As the Python docs [state](https://docs.python.org/2/library/functions.html#sorted):

> The built-in `sorted()` function is guaranteed to be stable. A sort is stable if it guarantees not to change the relative order of elements that compare equal...

An interesting side effect of that is that an Extension author could assign the same priority as the built-in item he wants to insert _after_. As the built-ins will always be added before extensions, the "right thing" will happen. Of course, if other third-party extensions try to do the same thing, you could get unexpected results.

**Comment by ryneeverett** [comment]
> An interesting side effect of that is that an Extension author could assign the same priority as the built-in item he wants to insert after. As the built-ins will always be added before extensions, the "right thing" will happen. Of course, if other third-party extensions try to do the same thing, you could get unexpected results.

I think getting too close to the "boundaries" of other extensions like that should be discouraged because it handcuffs future extension developers.

**Comment by waylan** [comment]
I agree. If you notice, I said one "could" do that; not necessarily that one "should."  However, it is nice to know that there is no data loss.

**Comment by ryneeverett** [comment]
I'm all for the three objectives but I'm going to play the skeptic and ask: Will priority-based ordering be as stable as dependency-based ordering?

Unless an extension is tested against all others, I don't see how an author could be expected to choose the correct priority. (Even if they did, what if I had a private extension? And couldn't there be circular ordering requirements amongst 3+ extensions that cannot all be used simultaneously?)

Every new extension can potentially cause ripple effects because each extension author and user has different extensions of which they care about compatibility. Ripples may take a very long time depending on developer responsiveness and until they complete there could be widespread extension incompatibility due only to the assigned priority. Dependency-based ordering minimizes this.

On a more theoretical note, it seems like systems that manage complexity with local knowledge (_which particular patterns need to be applied before or after me?_) are more effective than those that require global knowledge (_where do I fit in the range of all existing extensions?_) Imagine if init systems like openrc or systemd were priority-based!

**Comment by facelessuser** [comment]
I imagine priority level alone is not enough.  I say this only because sometimes certain extensions need to be run before specific extensions due to the way they intereact, and sometimes they just need to be run at a certain priority level.  The ability to retrieve specific extensions priority level by name might be useful.  Now if everyone picks a priority level on day 1 and never changes them, then priority level will be more than sufficient.

I imagine in the beginning people will set priority levels that work.  More extensions will be added and cause conflicts.  To fix this, developers will change their plugins priority level, and this will cause cascading issues.  Being able to occasionally target priorities dynamically to avoid conflicts with certain plugins may be also be needed.  Maybe I'm wrong.

I think this system will also make replacing certain builtin extensions more awkward.

I think extension conflict will always exist in one way or another as each extension is not always as simple as insert at level X and we are good to go.  The way extensions play off each other is very important, so at times, these things will need to be dynamic.

**Comment by waylan** [comment]
Thanks for the feedback. Some of the points were repeated, so I've tried to address each point once below. Sorry if I missed anything.

> Will priority-based ordering be as stable as dependency-based ordering?

My inclination is that it would be more stable.  Today, if two extensions ask for the same location, only one wins (the other may even be overridden). With the change, one still wins (the first loaded gets to go first), but neither is overridden.

For example, suppose two extensions attempt to **replace** "emphasis". The first extension would replace the built-in "emphasis" pattern and the second would replace the "emphasis" pattern of the first extension. If the two extensions can both live side-by-side, then the new proposed method would work fine -- even if both are given the exact same priority.

> I think this system will also make replacing certain builtin extensions more awkward.

Why? I would not expect to load an extension, then load another one which is meant as a replacement. I would load one or the other. If an extension wants to override an existing extension, then subclass it, don't instruct your users to load in then try to override (parts of) it.

However, as for the built-in parts of the parser (in the core, not extensions), yes, it could potentially be more difficult to override, which is why I expect to assign each instance to a constant. Simply import the constant and pass it to the `deregister` method. As `deregister` accepts a `strict` parameter, you don't even need to check if it exists first (perhaps another extension already registered it). Just call `deregister` with `strict=False` and it will work fine regardless of whether the conflicting piece is loaded or not.

I suppose it might be wise to encourage extensions to do the same, but I don't think that should be necessary. Again, why is an extension being loaded that is being overridden?

> Every new extension can potentially cause ripple effects because each extension author and user has different extensions of which they care about compatibility. 

The same situation exists today. Someone creates an extension which works fine. Someone else creates a second extension which creates a conflict for the first. The first extension makes some changes, which requires the second to make changes and the cycle continues. I would expect less of that with the priority system -- which is part of why I suggest it. You actually get finer grained control (multiple degrees of adjustment--many multiples as you can use floats if you want). Will conflicts arise? Most certainly. Will they be easier to overcome than today? I think so.

> On a more theoretical note, it seems like systems that manage complexity with local knowledge are more effective than those that require global knowledge 

True, but I expect that most will operate on local knowledge. Most extension authors won't bother to look at what other third-party extensions are doing. That is part of why I like this better. Just because two extensions which can live side-by-side happen to get the same priority, does not mean that everything breaks. The same cannot be said for the existing system.

To be clear, I appreciate the feedback. It is good that these questions are being asked. Please, keep them coming. I think this is a good idea or I wouldn't have proposed it. However, I am not absolutely certain it is the right way yet. What I do know is that the current system needs to be improved/changed. If anyone is interested in proposing a better solution, I am open to considering it.

**Comment by erez-o** [comment]
1) If you do so, you'll have to introduce a float, not an int, as int allows only a finite number of extensions between two extensions, and it's only a matter of time until a an extension needs to be placed between two extensions that have a following number. 

2) I think allowing two extensions with the same value and same priority will lead to a system that is harder to debug and thus less stable.

3) there is a problem in the priority approach, where extension A notices it conflicts with B, and changing its priority level will change behavior for all its users. There will also be the issue where each extension manager wants the other to change his priority rather than its own.

4) the only way I see it working is if there will be a single repository/document/file where the priority levels of all extensions of Python-markdown are written, and any new extension needs to place itself vs the others. All users of Python-markdown will use it regardless which extensions they actually use.
This approach will also enforce a greater modularity, as an extension that does two things where each needs a different priority and can't be placed in the current list will have to be broken to two extensions.

5) if you think (4) is a good approach, there is no need for a number representing priority, but just a list.

Hope this helps, great package

**Comment by waylan** [comment]
> 1) If you do so, you'll have to introduce a float, not an int,...

As previously stated, both floats and integers work interchangeably.

> 3) there is a problem in the priority approach, where extension A notices it conflicts with B, and changing its priority level will change behavior for all its users. There will also be the issue where each extension manager wants the other to change his priority rather than its own.

Those same problems exist with the current approach of using text based names. Therefore, the proposed change is not a regression in this respect.

> 4) the only way I see it working is if there will be a single repository/document/file where the priority levels of all extensions of Python-markdown are written...

I disagree. We don't have a repository of all text based names and it hasn't been a problem. Don't see why changing to int/floats would be any different.

> 2) I think allowing two extensions with the same value and same priority will lead to a system that is harder to debug and thus less stable.

Maybe, maybe not. This is the one thing that gives me pause. As far as I can tell, it is equal to or better than the current approach in all other respects.

**Comment by ryneeverett** [comment]
> For example, suppose two extensions attempt to replace "emphasis". The first extension would replace the built-in "emphasis" pattern and the second would replace the "emphasis" pattern of the first extension. If the two extensions can both live side-by-side, then the new proposed method would work fine -- even if both are given the exact same priority.

Am I right to understand that replacement will no longer be possible?

**Comment by waylan** [comment]
> Am I right to understand that replacement will no longer be possible?

No, it will still be possible, just as two steps: remove the unwanted processor (deregister) and insert the new one (register).

**Comment by facelessuser** [comment]
But to replace it, you have to acquire the instance to deregister, right?

**Comment by waylan** [comment]
> But to replace it, you have to acquire the instance to deregister, right?

Yes, that is correct. For the built-in stuff, I intend to make that easy via constants. But for stuff added by extensions, you would presumably need to iterate through the list and check each item till you found the one you wanted to remove.

And there's the rub. I don't want to use OrderedDict (for the reasons stated above) and anything except an OrderedDict makes removing objects difficult.

**Comment by facelessuser** [comment]
> And there's the rub. I don't want to use OrderedDict (for the reasons stated above) and anything except an OrderedDict makes removing objects difficult.

That is the part I am worried about.  Walking the list, possibly importing the plugin you want to remove so you can check if a plugin is an instance of what you want to remove (this is I really don't want to do)...maybe we can just look at the class name...that could work better, maybe if you exposed helper methods to make it easier to identify or retrieve the index of a given plugin that would reduce the pain and make it more attractive.

**Comment by waylan** [comment]
> ...maybe if you exposed helper methods to make it easier to identify or retrieve the index of a given plugin that would reduce the pain and make it more attractive.

Interesting, I was just thinking that same thing. As I was writing a proposal, I realized that many of the built-in inlinepatterns use instances of the same class. In fact, the [tutorial](https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown) even encourages extensions to reuse those same classes.  How would one determine which instance of a class to remove?

Then I remembered that in my original proposal I suggested that each item could be given a unique name as a property on the class instance. You could then use the string of that name to deregister. That would work, and it would eliminate the need for constants.

Essentially, removing/referring to existing items would work the same as it does now: you use the string based name. However, the order of items would be determined by the assigned priority rather than the awkward string-based syntax we have now (`_begin`, `<before`, `>after`, `_end`).

**Comment by facelessuser** [comment]
> Then I remembered that in my original proposal I suggested that each item could be given a unique name as a property on the class instance. You could then use the string of that name to deregister. That would work, and it would eliminate the need for constants.

Yeah, a unique name or unique Id maybe even a UUID.  Anything allowing the retrieval of a specific extension.

**Comment by waylan** [comment]
In summary, here are the apparent pros and cons of this proposal:

**Pros:**
1. Eliminate the awkward syntax: `_begin`, `<before`, `>after`, `_end`.
2. Added flexibility in placing your extension where you want it (a range
   of numbers as opposed to before or after an already known item).
3. Remove the homegrown and not fully tested OrderedDict.

**Netural:**
1. Today extensions get conflicts when two try to use the same designation
   for placement. With the change, those same conflicts could exist when
   extensions use the same priority.

**Inconclusive:**
1. Removal could be problematic if not implemented properly. However, unique
   names should make this work fine. Needs testing.

**Cons:**
1. ??

I think the last con just got moved to inconclusive. If I can resolve that with some testing, I think this looks good. Am I missing anything?

**Comment by facelessuser** [comment]
When everything gets far enough along, some beta releases may help as people trying it out may expose some things.  Looking forward to playing around with 3.0 as things get closer to the end.

**Comment by ryneeverett** [comment]
I'm +1. It hadn't occurred to me that a location value in 2.x can only specify a single value, so the complex circular scenarios I was imagining would lose support never had it (at least practically) to begin with.

**Comment by ryneeverett** [comment]
That said, a more flexible implementation than either the current one or the proposed one would support the following scenario:

_2.x_

```
A ... >C
B ... >A
C ... >B
```

Any combination of 2 of these extensions work together. However since they can only specify a single location value, it's extremely improbable.

_3.x_

```
A ... 20
B ... 22
C ... 25
```

In 3.x, the only way to use `A` and `C` (assuming the the previous block accurately portrays their real constraints) would be to fork one just to change the priority value.

A real scenario would likely involve more than three extensions, and could result in a perpetual flux.

Maybe they would never actually have circular relationships like that, I don't know.

**Comment by waylan** [comment]
I just refactored the [Gist](https://gist.github.com/waylan/56ade193466c24a4957f) to work with names (uses priority to sort and names to remove/replace). The full details are documented in the docstrings. The old version is [here](https://gist.github.com/waylan/56ade193466c24a4957f/f7ae783820fd3436354f98ff488df5ebd69539fc) for comparison.

Note that when a new item is registered with a "name" which already exists, the existing item is removed before the new item is saved. You cannot have two items with the same name. The new one replaces the existing item. Therefore, unlike in the previous iteration, you do not need to explicitly remove an item before adding its replacement.

I think this removes the last concern. Thoughts?
