### ISSUE TITLE
Placeholder slips to HTML markup

### ISSUE THREAD

**Issue by earshinov** [Python-Markdown/markdown#42]
When in Markdown source an HTML comment contains Markdown's link markup, the resulting HTML contains link placeholder in place of the comment's text:

Example.md:

<pre><code>
Please see &lt;!-- [Example][1] --&gt;

<span>[</span>1]: http://example.com/
</code></pre>

Example.html (rendered with python-markdown 2.0.3):

<pre><code>
&lt;p&gt;Please see &lt;!-- klzzwxh:0000 --&gt;&lt;/p&gt;
</code></pre>

Actually there are STX and EXT chars in the output, they are just not shown.

**Comment by waylan** [comment]
This has already been fixed in the current code and will be available in the next release (currently in alpha - see [downloads](https://github.com/waylan/Python-Markdown/downloads)).

``` python
>>> markdown.version
'2.1.0.alpha'
>>> markdown.markdown("Please see <!-- [Example][1] -->")
u'<p>Please see <!-- [Example][1] --></p>'
```

**Comment by earshinov** [comment]
OK, sorry that I didn't test the latest version.
