### ISSUE TITLE
slugify extension options should support importing function by path

### ISSUE THREAD

**Issue by mistresseve666** [Python-Markdown/markdown#421]
Extensions like `toc` currently assume the `slugify` option specifies a callable.

In some cases, `markdown.Markdown` kwargs might be configured via text files (such as yaml). This prevents the slugify parameter from being specified as a string (e.g. `'mycodebase.toc_slugify'`).

Could `python-markdown` extensions that require a `slugify` callable, namely `toc` and `headerid`, accept a `slugify` option as a string and automatically import it?

**Comment by waylan** [comment]
While I'm not completely opposed to the idea, it most likely won't happen for some time. Python-Markdown it currently in "maintainance mode" as we work towards 3.0. In other words the 2.x line will only receive bug fixes going forward with no new features.

The cited example of using YAML config files is not a very strong case as the PyYaml Lib allows python objects to be assigned as values. You just need to explicitly [define the type](http://pyyaml.org/wiki/PyYAMLDocumentation#Namesandmodules).

Additionally, while accepted strings (using dot notation) and then importing using that string is already in use in version 2.x (for extension names), that behavior will be removed in version 3.0 (we will be using entry_points instead). Therefore, I'm even more hesitant to support Python dot notation strings elsewhere in the code.

Additionally, part of the version 3.0 [Roadmap](https://github.com/waylan/Python-Markdown/wiki/3.0-Roadmap) includes breaking out all extensions from the main Markdown package into their own standalone packages. That being the case, each extension could grow on its own (and more easy be forked). So at that time it might be worth reconsidering.

However, at this time, for this package, I am going to close this as "wontfix" When the version 3 implementation of the TOC extension is broken out into its own package, you can raise the issue there.

**Comment by mistresseve666** [comment]
With the 3.0 roadmap in mind, I see that as a completely reasonable approach :+1: . It could be a future enhancement once the official python-markdown extensions are broken into dedicated packages.
