### ISSUE TITLE
UL after OL creates odd result

### ISSUE THREAD

**Issue by benjaoming** [Python-Markdown/markdown#422]
Thanks for all the great work on the markdown parser!!

Would you agree that this is an issue? Take from django-wiki/django-wiki#445

```
➜  ~  cat | markdown_py
Does it work?

 - Dog
 - Cat
 - Mouse

 1. Dog
 1. Cat
 1. Mouse


<p>Does it work?</p>
<ul>
<li>Dog</li>
<li>Cat</li>
<li>
<p>Mouse</p>
</li>
<li>
<p>Dog</p>
</li>
<li>Cat</li>
<li>Mouse</li>
</ul>%                   
```

**Comment by mitya57** [comment]
According to [our documentation](http://pythonhosted.org/Markdown/#differences):

> **Consecutive Lists**
> 
> While the syntax rules are not clear on this, many implementations (including the original) do not end one list and start a second list when the list marker (asterisks, pluses, hyphens, and numbers) changes. For consistency, Python-Markdown maintains the same behavior with no plans to change in the foreseeable future. That said, the [Sane List Extension](http://pythonhosted.org/Markdown/extensions/sane_lists.html) is available to provide a less surprising behavior.

Please use the mentioned extension if you want Python-Markdown to start a new list.

**Comment by benjaoming** [comment]
Sorry, I would have referred to the docs, but I really wasn't expecting this behaviour to be described there!! Thanks for the reference and the extension!
