### ISSUE TITLE
Is anyone having trouble with images showing up on markdown rendered pages?

### ISSUE THREAD

**Issue by JellisHeRo** [Python-Markdown/markdown#424]
I use django and and markdown to render ".md" blog posts. However, I cant seem to have stored images show up on my blog posts. Its strange, because...
- HTTP urls work just fine, and...
- When Im not using the markdown overlay, (like in my home/landing page or something) the images show up. 
### An example

In my .md docs, I can have two images, one imported via URL and the other being from my static files... 

```
    ![](https://i.ytimg.com/vi/TusH5ICDUXw/mqdefault.jpg ) # HTTP url

    ![]({% static 'images/blog/density-plot-post.png' %})  # from staticfiles storage
                or ![](full/path/to/images/blog/density-plot-post.png) 
                or <img src="{% static 'images/blog/density-plot-post.png' %}" >
```

...but all I would see are these two images
![](https://i.ytimg.com/vi/TusH5ICDUXw/mqdefault.jpg) **this**..
![]({% static 'images/blog/density-plot-post.png' %}) **and this** (not showing my image)

Again, I want to point out that this image not showing does in fact show when I am not using markdown.

I am also pretty new to this, so I dont know if this is a new kind of issue you've heard of, but maybe markdown isn't recognizing the image pattern or something. Is there an extension that works with stored images in particular, or is there a method to help me work with image pattern recognition in my markdown documents?

**Comment by waylan** [comment]
> ```
>   ![]({% static 'images/blog/density-plot-post.png' %})  or ![](full/path/to/images/blog/density-plot-post.png) 
> ```

That image includes a Django template tag. Markdown has no knowledge of Django templates and cannot process template markup. If you would like to run  a Markdown file through Django's template engine, you will need to do that outside of the Markdown lib.

As this is not related to Markdown, I am closing it. We cannot provide support for Django templates here.

**Comment by JellisHeRo** [comment]
I understand with regards to the template tag, but that doesn't ease to the slightest my concerns when i hard code the source path instead, hence the 'or's that I used. I switched it up just to make sure if its the template tags, and I got the same result. I used the full source and I have also used the html <img> tag: same result. Is that simply all Django? Its very possible, but when Im doing this while not using markdown, its all fine, so I have my doubts.

**Comment by waylan** [comment]
Can you give me an example markdown document and the resulting HTML document from that example?

**Comment by erez-o** [comment]
It looks entirely Django

I use markdown in my django site as well. You should first let django render the template tags, and only then apply markdown. Don't know the exact details of your implementation, but you can use django render to string, then apply markdown.

Do note that the .md files you've created would not be standard, and would not be read correctly in any markdown viewer. Generaly speaking. It's not a good design, but again, I don't know your specific task.

**Comment by JellisHeRo** [comment]
Thanks for your responses!

@erez-o that seems to make sense. I didnt think that I may have to render in an orderly fashion. Do you have a particular example (or some code hanging around) on how I can do that? I am not sure how that may work on my end. I've used `render_to_string` once and its just given me request errors. Ive just used render or render_to_response (in this case they seem interchangeable)

@Waylan sure. This is my markdown content. Its just some random text along with 4 differing ways that I tried to call the image from my files.

**markdown content**

```
<h1> Hi </h1>
<img class="centered" src="{% static 'images/blog/literate_testing.png'  %}"> image1 (in markdown content)

![](C:/Users/Jaysp_000/firstSite/PROJECTone/markdown/images/blog/literate_testing.png) image2

![](images/blog/literate_testing.png) image3

![][logo] image4


This past summer I attended the French R meeting in Lyon. But that's secondary for this 
story. The important part happened while I was on the train on my way to Lyon.


[logo]: images/blog/literate_testing.png 
```

My rationale for inserting the HTML tags were for seeing if HTML in general would show up in any way, which would help me specify this issue. I got this resulting HTML...
![result](https://cloud.githubusercontent.com/assets/9903923/9144016/074b9306-3d18-11e5-8ad4-931f6c66e3ae.PNG)

Afterwards I questioned whether it was my file paths that I messed up, so in my templates I inserted a path to the image file above the rendered content...

```
<img class="centered" src="{% static 'images/blog/literate_testing.png'  %}"> image1 (not in markdown content)
{{ post.content | safe }}
```

...and got this result.
![result2](https://cloud.githubusercontent.com/assets/9903923/9144328/1c3e1e44-3d1a-11e5-85f5-f82f1b5b9e03.PNG)

Thus why I thought that it had something to do with the way this was being rendered. I did this two different ways: the first while using models/admin with `django_markdown` and this way: just using markdown files and Python Markdown. I got virtually the same results, so that's why I was thinking there was something I was missing with Python Markdown, but perhaps there is more to what @erez-o  pointed out than I was focusing on.

**Comment by waylan** [comment]
That is completely useless to me. I need the HTML code generated by Markdown (not a snapshot of how it displays in the browser). Perhaps you could use the "view page source" feature of your browser to view the HTML which you can then copy and paste as text into a comment.

Regardless, I can comment on the input:

```
<img class="centered" src="{% static 'images/blog/literate_testing.png'  %}"> i
```

That will never work inside a Markdown document as you are using Template syntax. Unless, you are doing something unusual (and know what you are doing), never try to use template syntax within Markdown as Markdown knows nothing about it.

```
![](C:/Users/Jaysp_000/firstSite/PROJECTone/markdown/images/blog/literate_testing.png) image2
```

That will not work from your web server as that is an absolute path from your system root. The server root is a very different thing and all absolute urls need to be from the server root.

```
![](images/blog/literate_testing.png) image3
```

If the `images` directory i son you server root, and your server is configured correctly, then this should work. If it is not working then you either have the path wrong or your server is configured incorrectly. Either way, that is not a Markdown problem.

```
![][logo] image4

[logo]: images/blog/literate_testing.png 
```

The same thing applies to this as the previous example.

May I suggest you run your server and try to view the image directly. Type the url to the image directly into your browser's address bar (http://servername/images/blog/literate_testing.png  replacing servername with the name of your server, perhaps localhost). If the image does not get displayed, then  you either have the path wrong or your server is configured incorrectly. Either way, that is not a Markdown problem.

**Comment by erez-o** [comment]
@JellisHeRo Note that the questions are not an issue of the markdown package. Markdown package gets an .md input and returns an .html output, and you didn't describe any bug in markdown. I think you'll find more help in Stackoverflow, but I'll try my best:

1) read https://docs.djangoproject.com/en/dev/howto/static-files/#serving-files-uploaded-by-a-user, and any questions asked about serving images in stackoverflow or other sources.

2) `render_to_string`:
From looking at the source code of django (https://docs.djangoproject.com/en/1.7/_modules/django/shortcuts/#render_to_response) , you can see that both `render` and `render_to_response`,  end up being a wrapper to `render_to_string`.

```
from django.template.loader import render_to_string
html = render_to_string('my_template.html', {'foo': 'bar'})
return HttpResponse(html)
```

If you're not an expert in django, I would not advise you to change all the `render` to `render_to_string`, but to follow to (3,4)

3) Markdown is usually needed to allow users that are not fluent in html to add content to your site. You would not want users to be able to write django template tags, like {% static 'images/blog/literate_testing.png'  %} and load it. I think it would create a security risk as well.

4) Usually your template should have fields only you know (like {% static 'images/blog/literate_testing.png'  %}) that can contain templates, and other fields that the user entered that can be .md input. Only these fields do you want to render to html. The way to do it is to write a template filter tag.

You would probably need Bleach, so I'm just copy pasting my markdown_filter file:

```
from django import template
from django.template.defaultfilters import stringfilter
from django.utils.safestring import mark_safe
import markdown
import bleach
register = template.Library()

ALLOWED_TAGS = [
    'h1','h2','h3','h4','h5','h6',
    'p','dl','dt','dd','ul','ol','li',
    'table', 'thead', 'th', 'tr','td', 'tbody',
    'b','i','strong','em','tt',
    'span','div','blockquote','code','pre',
    'hr','br',
    'a','img',
    'abbr',
    'acronym',
    'br',
]

ALLOWED_ATTRIBUTES = {
    '*': ['class', 'id'],
    'a': ['href', 'title'],
    'abbr': ['title'],
    'acronym': ['title'],
    'img': ['src', 'alt'],
}


@register.filter(is_safe=True)
def mrkdown(value):
    """
    converts markdown to html
    """

    html = bleach.linkify(bleach.clean(markdown.markdown(value, ['markdown.extensions.extra', 'markdown.extensions.admonition', 'markdown.extensions.tables', 'markdown.extensions.toc(permalink=True)']), tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES))

    return mark_safe(html)
```

and inside the template itself, you would have {% load markdown_filter %} in the beginning, and any field you need to convert to markdown, you would write {{field|mrkdown}}

Hope this helps you

**Comment by desmond75** [comment]
I am creating a portfolio using github static page and i want to display some images of projects completed and finding it difficult to do that.I know the syntax for image display but what i do not seem to get here is where to place image on github and and use the path to display it. syntax for image display
