### ISSUE TITLE
Queston - If I want text box in the content, does markdown extension make sense?

### ISSUE THREAD

**Issue by jpatel3** [Python-Markdown/markdown#425]
I want to write some custom parsing along with markdown where textbox can be in the middle of the content. All it need to do is replace some custom style with textbox. 

Is there any better way to do this or markdown extension is fine to use?

**Comment by waylan** [comment]
If I am understanding your correctly, you are looking for something like [admonitions](https://pythonhosted.org/Markdown/extensions/admonition.html).

If not, and you are not reporting a bug (or making a feature request), please take the discussion to the [mailing list](http://lists.sourceforge.net/lists/listinfo/python-markdown-discuss).

**Comment by jpatel3** [comment]
Thank you @waylan . It's different than admonitions. I have started discussion on mailing list. Thanks. 

Closing the item for now.
