### ISSUE TITLE
output_format "plain-text

### ISSUE THREAD

**Issue by shitcricket** [Python-Markdown/markdown#426]
I need to render a "plain text" version of a markdown document, i.e. it should not contain any markdown syntax. In particular, link tags should be flattened:

```
Hello [world](http://www.world.com)!
```

should become

```
Hello world!
```

So far all the solutions I've seen suggested revolved around rendering HTML and then using Bleach or BeautifulSoup to massage the output to fit one's needs. It seems to me that a plain text output option (possibly implemented as an extension instead of adding it to the core) would be a simpler and leaner approach.

Thoughts?

**Comment by waylan** [comment]
If any raw HTML is included in a Markdown document, then Markdown would need to use Bleach or BeautifulSoup to render that raw HTML to plain text. For that reason, and to ensure consistency, you might as well just work with the output of Markdown yourself.

That said, the Markdown class was designed in such a way that you could add your own third party serializer which would serialize the ElementTree object to whatever form you wanted. It is only documented in the source code comments, but would probably look something like this:

``` python
def to_plain_text(element):
    Implement plain text serializer here ...

md = markdown.Markdown()
md.serializer = to_plain_text
plain_text = md.convert(source)
```

For that matter, as the Extension API gives you access to the Markdown class, you could swap out the serializer from within an Extension:

``` python
from markdown.extensions import Extension

class PlainTextExtension(Extension):
   def extendMarkdown(self, md, md_globals):
       md.serializer = to_plain_text
```

However, given the fact that this will not work for raw HTML, it is not something that I am interested in including in the library itself. It can exist as a third party extension (or one off depending on your needs).

I am closing this issue. If you need any assistance in developing your solution, please use the email list.
