### ISSUE TITLE
Line started with # within code block is not parsed as code

### ISSUE THREAD

**Issue by yangl1996** [Python-Markdown/markdown#427]
A line started with '#' within code block is not parsed as code, but as title instead.

For example:

``````
```
# cd ..
```
``````

Should be parsed as

```
# cd ..
```

But currently as

```
# cd

```

This happens when exporting the parsed string to HTML :)

**Comment by mitya57** [comment]
I cannot confirm it. With your input and [`markdown.extensions.fenced_code`](http://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html) extension enabled, I get the expected output:

``` html
<pre><code># cd ..
</code></pre>
```

**Comment by yangl1996** [comment]
I didn't enable markdown.extensions.fenced_code when I was testing.

Sorry for that :P

Thank you so much for helping troubleshoot it!
