### ISSUE TITLE
Unicode and spaces problem in lists

### ISSUE THREAD

**Issue by i-erokhin** [Python-Markdown/markdown#428]
The string:

```
* набор для ремонта бескамерных шин - продается в любом магазине автозапчастей
* набор для ремонта бескамерных шин - продается в любом магазине автозапчастей
* набор для ремонта бескамерных шин - продается в любом магазине автозапчастей
```

Result:
- набор для ремонта бескамерных шин - продается в любом магазине автозапчастей
  * набор для ремонта бескамерных шин - продается в любом магазине автозапчастей
- набор для ремонта бескамерных шин - продается в любом магазине автозапчастей

As you can see, the bug is right here.

PS: the screenshot for history ))

![screen shot 2015-08-24 at 16 52 00](https://cloud.githubusercontent.com/assets/9545969/9441729/7d96bfca-4a80-11e5-89bb-809d099a365d.png)

PPS: Python 3.4.3, markdown.version 2.6.2 (in my env)

**Comment by waylan** [comment]
@i-erokhin I just copy and pasted your sample document (I had to use the "edit" button to get the actual source) . The second list item is formatted incorrectly. The space after the asterisk (`*`) on the second line is not a space character (Unicode char `U+0020`) but a "no-break space" character (Unicode char `U+00A0`) (see [Wikipedia](https://en.wikipedia.org/wiki/Whitespace_character) for a complete list). The Markdown [syntax rules](http://daringfireball.net/projects/markdown/syntax#list) requires a space character only  (Unicode char `U+0020`). Once I replaced that character, it worked fine.  In fact, this behavior is common across all Markdown implementations (at least the ones I'm aware of). See Babelmark for comparison: [your sample](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+%D0%BD%D0%B0%D0%B1%D0%BE%D1%80+%D0%B4%D0%BB%D1%8F+%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%D0%B0+%D0%B1%D0%B5%D1%81%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D1%85+%D1%88%D0%B8%D0%BD+-+%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B5%D1%82%D1%81%D1%8F+%D0%B2+%D0%BB%D1%8E%D0%B1%D0%BE%D0%BC+%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B5+%D0%B0%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%87%D0%B0%D1%81%D1%82%D0%B5%D0%B9%0A*%C2%A0%D0%BD%D0%B0%D0%B1%D0%BE%D1%80+%D0%B4%D0%BB%D1%8F+%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%D0%B0+%D0%B1%D0%B5%D1%81%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D1%85+%D1%88%D0%B8%D0%BD+-+%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B5%D1%82%D1%81%D1%8F+%D0%B2+%D0%BB%D1%8E%D0%B1%D0%BE%D0%BC+%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B5+%D0%B0%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%87%D0%B0%D1%81%D1%82%D0%B5%D0%B9%0A*+%D0%BD%D0%B0%D0%B1%D0%BE%D1%80+%D0%B4%D0%BB%D1%8F+%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%D0%B0+%D0%B1%D0%B5%D1%81%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D1%85+%D1%88%D0%B8%D0%BD+-+%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B5%D1%82%D1%81%D1%8F+%D0%B2+%D0%BB%D1%8E%D0%B1%D0%BE%D0%BC+%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B5+%D0%B0%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%87%D0%B0%D1%81%D1%82%D0%B5%D0%B9) and a [corrected version](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+%D0%BD%D0%B0%D0%B1%D0%BE%D1%80+%D0%B4%D0%BB%D1%8F+%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%D0%B0+%D0%B1%D0%B5%D1%81%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D1%85+%D1%88%D0%B8%D0%BD+-+%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B5%D1%82%D1%81%D1%8F+%D0%B2+%D0%BB%D1%8E%D0%B1%D0%BE%D0%BC+%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B5+%D0%B0%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%87%D0%B0%D1%81%D1%82%D0%B5%D0%B9%0A*+%D0%BD%D0%B0%D0%B1%D0%BE%D1%80+%D0%B4%D0%BB%D1%8F+%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%D0%B0+%D0%B1%D0%B5%D1%81%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D1%85+%D1%88%D0%B8%D0%BD+-+%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B5%D1%82%D1%81%D1%8F+%D0%B2+%D0%BB%D1%8E%D0%B1%D0%BE%D0%BC+%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B5+%D0%B0%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%87%D0%B0%D1%81%D1%82%D0%B5%D0%B9%0A*+%D0%BD%D0%B0%D0%B1%D0%BE%D1%80+%D0%B4%D0%BB%D1%8F+%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%D0%B0+%D0%B1%D0%B5%D1%81%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D1%85+%D1%88%D0%B8%D0%BD+-+%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B5%D1%82%D1%81%D1%8F+%D0%B2+%D0%BB%D1%8E%D0%B1%D0%BE%D0%BC+%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B5+%D0%B0%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%87%D0%B0%D1%81%D1%82%D0%B5%D0%B9). As there is no bug here, I am closing this.

**Comment by waylan** [comment]
By the way, a good hint that the error was with your markup is that the same error replicated here on GitHub which does not use Python-Markdown but a different implementation. When you see multiple implementations exhibiting the same behavior, it is usually a good sign that the behavior is intended and the error is not with the parser.

**Comment by i-erokhin** [comment]
Ok, this is not a bug. 

This unicode character appears in "textarea" in Safari, it is very unexpected behavior of the browser, sorry.

**Comment by waylan** [comment]
I believe the standard keyboard shortcut `Option-Space` will type a non-breaking space in an English Mac keyboard (not sure about non-English keyboards). I'm assuming that is what happened to you on accident. It is easy enough to do with no visual indication that a different character was typed. No big deal, although a bit of a pain to debug when it causes behavior changes like you experienced.

**Comment by i-erokhin** [comment]
> I believe the standard keyboard shortcut Option-Space will type a non-breaking space 

Exactly!

```
* one (space after asterisk)
* two (Option-Space after asterisk)
```
- one (space after asterisk)
  * two (Option-Space after asterisk)

Thank you for your detailed comments!
