### ISSUE TITLE
would it be possible to add consistent copyright headers to the code?

### ISSUE THREAD

**Issue by dpranke** [Python-Markdown/markdown#435]
Hi,

I'm checking in a copy of Python-Markdown into the Chromium code base, because we want to have a tool that we can use to locally render MD for our documentation, and Python-Markdown works great for this.

(see https://codereview.chromium.org/1392733002/ if you're curious).

Chromium has a process by which we check to make sure that all of the third-party code we include has appropriate licensing clauses, and while the BSD licensing for Python-Markdown is quite clear (thanks!) the info is annotated a bit inconsistently from file to file. 

Would it be possible for you to adopt a consistent copyright or license clause across all of the files so that we can programmatically scan them?

**Comment by waylan** [comment]
Can you give me some examples of inconsistency? There is the `LICENSE.md` file and of course the separate license in `markdown/serializers.py` (which we cannot change as it is for borrowed code from ElementTree). There are no other licenses that I recall. So I guess its not clear to me what the problem is.

**Comment by dpranke** [comment]
Oh, sorry, I think I got confused because the markdown/extensions/_.py all contain the "All changes Copyright ..." and "License: [BSD]" lines, but the markdown/_.py files don't seem to contain any license or copyright notices at all, apart from **init**.py.

Would you have any desire to add the "License: [BSD]" line to the other markdown/*.py files?
