### ISSUE TITLE
Pipe inside code block inside table cell doesn't get rendered properly

### ISSUE THREAD

**Issue by MustafaHaddara** [Python-Markdown/markdown#436]
Using a pipe character `|` inside of a code block inside of a table cell doesn't maintain the code block. eg. 

```
Column 1 | Column 2 | Column 3
---------|----------|---------
Pipe     | `|`      | word
```

Should work, but doesn't. Instead, we see this: 
![pipe demo](https://cloud.githubusercontent.com/assets/11722214/10646220/0be0c8b4-7800-11e5-9e4a-9fbd7b92b730.png)

A workaround for now is to replace the ``|`` with `<code>&#124;</code>` (ie. the html literal). This renders correctly. 
![pipe-correct](https://cloud.githubusercontent.com/assets/11722214/10647770/664d02ba-7808-11e5-9b32-70a1c626a871.png)

See https://github.com/mkdocs/mkdocs/issues/743 for more details

**Comment by waylan** [comment]
Hmm, so I'm not sure of the cleanest way to address this. 

Currently I'm just doing `row.split('|')`. Obviously, this is a no-go when pipes are included in a  code span. That means I need to parse the row accounting for quoted strings (quoted with backticks).

I thought maybe the `csv` lib could do this:

```
>>> list(csv.reader(['foo | `|` | bar | 42'], delimiter='|', quotechar='`', skipinitialspace=True))
[['foo ', '| ', 'bar ', '42']]
```

Unfortunately, `csv.reader` strips the `quotechar` from the output, which means we loose the codespan. In other words the output should be: `[['foo', '`|`', 'bar ', '42']]`. Also, `skipinitialspace=True` is required to make it work if the code span is padded with initial whitespace. But there is no way to have it strip trailing whitespace which is a little inconsistent (although certainly workable). Finally, on Python 2 there is the weirdness that Unicode input is not supported (you have to encode as UTF-8, read, then yield items, decoding each back to Unicode).

Looks like I would need to write my own parser. I don't have time for that right now. You'll have to use the workaround for now. Of course, patches (pull requests) are always welcome.

**Comment by MustafaHaddara** [comment]
Whelp, here's a patch https://github.com/waylan/Python-Markdown/pull/437 

I'm not sure if it's the best approach, but it's one way of going about it.

**Comment by PabloLION** [comment]
Hi maintainers.
This issue re-appeared. I'm with py3.9 and Mac M1Max
I did `pip install markdown`, showing `Successfully installed markdown-3.3.6` and getting `/opt/homebrew/lib/python3.9/site-packages/Markdown-3.3.6.dist-info/`

This code piece
```python3
import markdown
str= """
## test

| test              | test |
| ----------------- | ---- |
| <code> \| </code> | a    |

another table

| test            | test |
| --------------- | ---- |
| <pre> \| </pre> | a    |
"""

html = markdown.markdown(str)
print(html)
```

prints this result

```bash
<h2>test</h2>
<p>| test              | test |
| ----------------- | ---- |
| <code> \| </code> | a    |</p>
<p>another table</p>
<p>| test            | test |
| --------------- | ---- |
| <pre> \| </pre> | a    |</p>
```

So, is this function down or incorrectly implemented?
Should I create a new issue?

**Comment by facelessuser** [comment]
@PabloLION, you need to enable the `tables` extension.

**Comment by PabloLION** [comment]
@facelessuser  Thanks. Just found it [here](https://python-markdown.github.io/extensions/). Thing is I'm using `mkdocs`.. I'll try to see how to combine them. Thanks again.

**Comment by facelessuser** [comment]
https://www.mkdocs.org/user-guide/configuration/#markdown_extensions. It's all in the docs 😉 .

**Comment by PabloLION** [comment]
Thanks again 😄
Although setting the `markdown_extensions:` doesn't work for me (I saw `tables` in the list of the link you posted)
I tried all these line by line and no one worked. I guess it's a mkdocs bug. (with python `markdown.markdown(str, extensions=['markdown.extensions.tables'])` worked fine)


```
markdown_extensions:
  - tables
  - markdown.extensions.tables
  - tables: {}
  - markdown.extensions.tables: {}
  - extra:
    - tables
    - markdown.extensions.tables
    - tables: {}
    - markdown.extensions.tables: {}
```

`tables` is used by default. This is not a common problem and I was confused here. [See the solution and more details](https://github.com/mkdocs/mkdocs/issues/2761)

**Comment by vedranmiletic** [comment]
I guess it is what it is now, but I wish we took a different approach here with mandatory escaping of pipes in tables, even under backticks.

We are not bound by what other implementations do, of course, but in the end it is nice to have some interoperability. FWIW, [GFM](https://github.github.com/gfm/#example-200) requires escaping so linters such as markdownlint implement it, cf. [issue 1206](https://github.com/DavidAnson/markdownlint/issues/1206) and both HackMD and VS Code adhere to mandatory escaping like GFM describes it.

**Comment by nwalters512** [comment]
A +1 for a different approach - or at a minimum, supporting escaped pipes as well. While I understand that it's a non-goal of this project to be compatible with GFM or others, so much tooling now is working on GFM-style Markdown, which makes it hard to interact with the rest of the ecosystem. One concrete example is Prettier, which doesn't understand unescaped pipes within backticks in table cells: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBhCAbArgWygAgEZ8AffdbPfAJlPM1wIGYAdKAWk665O7-d79ObAO4QATgBMi+WWTFSasugumsoqmWQAGmstW0qJatiAA0ICAAcYAS2gBnZKACG48RBEAFNwicoXDBEXAE8nCwAjcRcwAGs4GABlFxw4ABlbKDhkADNAhzgLCAiAKzgwGAB1aKtkECtxOALxADdsyOi4hMSrGMyAc2QYcSxCkAKcWyGRsbgADys4cVtU2ECAeUXomAkvCAdbO2g6hElzEHmtlYQYQIAVJag3Wybc-LGDqH6MOABFLAg8DeGAKFhKDjmiQGP3+gOySDyILGAEcAfAvB4rP4QC4HOwsnBJITzsMXLYMAN0DgcC46oEMOdPt84ABBGDDWwRLDopYZLLA0EgAAWMBwGEqQsOTV6YDgiT8h1sLUOITqYAc4RALVGAEkoETYIkwMsbCz9YkYCEfgKxg19nBqi5aigGk0lm1zplmjAMS5+jSbRZeuJmnUaeJYpJPFBzg1MlVbJIYELkAAOAAMFkaqNsjV9-tpCPeFluEUqieTyGoFiwBTuLgi-kRgrgOAihKJkjSLi+WD9cAAYhIaeyBnTuRAQABfKdAA
