### ISSUE TITLE
Can't pass extension arguments to Markdown

### ISSUE THREAD

**Issue by Wilfred** [Python-Markdown/markdown#44]
According to http://www.freewisdom.org/projects/python-markdown/Using_as_a_Module , I should be able to pass in extension arguments as follows:

```
import markdown
md = markdown.Markdown(extensions=['toc'], extension_configs= {'toc' : ('anchorlink', True)},)
```

However, this produces the following traceback:

```
ValueError                                Traceback (most recent call last)
/home/wilfred/bleeding_edge/Python-Markdown/<ipython-input-19-31b461a39945> in <module>()
----> 1 md = markdown.Markdown(extensions=['toc'], extension_configs= {'toc' : ('anchorlink', True)},)

/home/wilfred/bleeding_edge/Python-Markdown/markdown/__init__.py in __init__(self, *args, **kwargs)
    132         self.htmlStash = util.HtmlStash()
    133         self.registerExtensions(extensions=kwargs.get('extensions', []),
--> 134                                 configs=kwargs.get('extension_configs', {}))
    135         self.set_output_format(kwargs.get('output_format', 'xhtml1'))
    136         self.reset()

/home/wilfred/bleeding_edge/Python-Markdown/markdown/__init__.py in registerExtensions(self, extensions, configs)
    158         for ext in extensions:
    159             if isinstance(ext, basestring):
--> 160                 ext = self.build_extension(ext, configs.get(ext, []))
    161             if isinstance(ext, Extension):
    162                 # might raise NotImplementedError, but that's the extension author's problem


/home/wilfred/bleeding_edge/Python-Markdown/markdown/__init__.py in build_extension(self, ext_name, configs)
    177 
    178         # Parse extensions config params (ignore the order)

--> 179         configs = dict(configs)
    180         pos = ext_name.find("(") # find the first "("
    181         if pos > 0:

ValueError: dictionary update sequence element #0 has length 10; 2 is required
```

The call that's dying is `dict(('anchorlink', True))`. Would it make sense for extension_configs to be a dict of dicts? e.g.:

```
markdown.Markdown(extensions=['toc'], extension_configs= {'toc' : {'anchorlink': True}},)
```

The alternative syntax works fine:

```
markdown.Markdown(extensions=['toc(anchorlink=1)'])
```

although according to http://www.freewisdom.org/projects/python-markdown/Table_of_Contents I should be able to pass booleans:

```
md = markdown.Markdown(extensions=['toc(anchorlink=True)'])
```

but this dies slightly later (I'm not 100% sure if this is the same issue, apologies if not) with:

```
In [33]: md = markdown.Markdown(extensions=['toc(anchorlink=True)'])

In [34]: md.convert("[TOC]\n\n# foo\n\n## bar")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/wilfred/bleeding_edge/Python-Markdown/<ipython-input-34-aafe6026c2af> in <module>()
----> 1 md.convert("[TOC]\n\n# foo\n\n## bar")

/home/wilfred/bleeding_edge/Python-Markdown/markdown/__init__.pyc in convert(self, source)
    285         # Run the tree-processors

    286         for treeprocessor in self.treeprocessors.values():
--> 287             newRoot = treeprocessor.run(root)
    288             if newRoot:
    289                 root = newRoot

/home/wilfred/bleeding_edge/Python-Markdown/markdown/extensions/toc.pyc in run(self, doc)
    102                 link.attrib["href"] = '#' + id
    103 
--> 104                 if int(self.config["anchorlink"]):
    105                     anchor = etree.Element("a")
    106                     anchor.text = c.text

ValueError: invalid literal for int() with base 10: 'True'
```

**Comment by waylan** [comment]
I see multiple references to the documentation on freewisdom.org. First, that documentation is for version 2.0.3. The code here on github however, is at version 2.1.0-alpha (with updated docs in the docs dir). Are you seeing the same problems when using the latest code _and_ documentation? I ask because I seem to recall correcting some errors recently in that part of the docs.

**Comment by Wilfred** [comment]
```
md = markdown.Markdown(extensions=['toc'], extension_configs= {'toc' : ('anchorlink', True)},)
```

This crashes on both 2.0.3 and 2.1.0-alpha. 2.1's documentation has the correct syntax:

```
md = markdown.Markdown(extensions=['toc'], extension_configs= {'toc' : [('anchorlink', True)]},)
```

which works on both versions. I'll update the 2.0 docs.

---

```
md = markdown.Markdown(extensions=['toc(anchorlink=True)'])
```

Both 2.0's and 2.1's docs suggest this should work. It doesn't on either version.

**Comment by waylan** [comment]
On Wed, Oct 5, 2011 at 10:43 AM, Wilfred Hughes wrote:

>    md = markdown.Markdown(extensions=['toc(anchorlink=True)'])
> 
> Both 2.0's and 2.1's docs suggest this should work. It doesn't on either version.

No I suppose it wouldn't. After all `"True" != True`. Where
specifically do the docs suggest this would work. I realize it could
be understood to be implied in the "command_line" docs, but the
example there only passes in a string not a Boolean.

Have you tried `anchorlink=1`? I only ask because I recall markdown
using `0/1` for `True/False` in early versions (before I joined the
project). I occasionally run into a few remnants of that.

Either way, I suppose this is a bug as some config options currently
cannot be set from the command line - at least not in an obvious way.
Thanks for the report.

**Comment by Wilfred** [comment]
> Have you tried `anchorlink=1`?

Yep, and that works nicely.

> Where specifically do the docs suggest this would work.

In docs/extensions/toc.md:

> anchorlink: Set to True to have the headers link to themselves. Default is False.

Thanks again :)
