### ISSUE TITLE
Tables extension drops character after code block

### ISSUE THREAD

**Issue by jandecaluwe** [Python-Markdown/markdown#440]
There is an issue now with code blocks in the tables extension. The final character after a code block is dropped. For example:

```
`file_ext`        | Change default file extension (`'.html'`) for processed `.md` files.
```

results in:

```
<td><code>file_ext</code></td>
<td>Change default file extension (<code>'.html'</code> for processed <code>.md</code>files.</td>
```

**Comment by waylan** [comment]
Not sure I follow. Do you mean code spans? After all. there are no code _blocks_ in your example. Also, what output were you expecting? I don't see anything wrong with the example you provided.

**Comment by waylan** [comment]
Ok, nevermind. I see it now. The closing parenthesis is missing from the first code span and the whitespace character from the second one. Perhaps a result of #439?

Which version are you using?

**Comment by waylan** [comment]
So, here is a simple example:

```
foo | bar
--- | ---
foo | (`bar`) and `baz`.
```

Which outputs:

```
<table>
<thead>
<tr>
<th>foo</th>
<th>bar</th>
</tr>
</thead>
<tbody>
<tr>
<td>foo</td>
<td>(<code>bar</code> and <code>baz</code></td>
</tr>
</tbody>
</table>
```

And reverting #439 has no effect on the behavior. Also it appears that the problem only occurs within tables.

**Comment by waylan** [comment]
This is clearly a result of #437. I had forgotten about that. @MustafaHaddara do you have any input?

**Comment by MustafaHaddara** [comment]
Yeah this is probably on me. I'll take a look and see if I can pinpoint the problem.

**Comment by mitya57** [comment]
I have proposed a pull request #441. @MustafaHaddara please look at it — I don't know why adding a `- 1` is needed by it appears to fix this.

**Comment by waylan** [comment]
Yep, that makes sense to me. I've just merged it.

**Comment by MustafaHaddara** [comment]
Yeah, looking at it, we find a match to the code span, then we get the index of the start of the remaining text and point the cursor `i` to that index. 

Then at the bottom of the loop (line 125 in `tables.py`) we increment `i`. 

So either we could subtract 1 from `i`, as @mitya57 did in the pull request, or I suppose we could have added a `continue` just after line 124 in `tables.py`. 

Thanks for fixing this.
