### ISSUE TITLE
List handling not consistent with Markdown.pl

### ISSUE THREAD

**Issue by kitt-cat** [Python-Markdown/markdown#442]
Given this input markdown

```
Some text

* **Example**

 This should be part of the list element

* **Other example**

 But it's not in to python-markdown :/

* **list element**

 Instead it's a separate list!

End text
```

I expect it to render like this:

> Some text
> - **Example**
>   
>   This should be part of the list element
> - **Other example**
>   
>   But it's not in to python-markdown :/
> - **list element**
>   
>   Instead it's a separate list!
> 
> End text

But python-markdown gives this to me:

```
<p>Some text</p>
<ul>
<li><strong>Example</strong></li>
</ul>
<p>This should be part of the list element</p>
<ul>
<li><strong>Other example</strong></li>
</ul>
<p>But it's not in to python-markdown :/</p>
<ul>
<li><strong>list element</strong></li>
</ul>
<p>Instead it's a separate list!</p>
<p>End text</p>
```

Every list element is put in its own list!

---

`Markdown.pl` from https://daringfireball.net/projects/markdown/ behaves as expected:

```
<p>Some text</p>

<ul>
<li><p><strong>Example</strong></p>

<p>This should be part of the list element</p></li>
<li><p><strong>Other example</strong></p>

<p>But it's not in to python-markdown :/</p></li>
<li><p><strong>list element</strong></p>

<p>Instead it's a separate list!</p></li>
</ul>

<p>End text</p>
```

**Comment by mitya57** [comment]
You need to use four spaces for indentation. The “Indentation/Tab Length” section in the [documentation](http://pythonhosted.org/Markdown/#differences) explains why it is so and how to change it.

Let me quote it here:

> The [syntax rules](http://daringfireball.net/projects/markdown/syntax#list) clearly state that when a list item consists of multiple paragraphs, “each subsequent paragraph in a list item **must** be indented by either 4 spaces or one tab” (emphasis added). However, many implementations do not enforce this rule and allow less than 4 spaces of indentation. The implementers of Python-Markdown consider it a bug to not enforce this rule.
> 
> This applies to any block level elements nested in a list, including paragraphs, sub-lists, blockquotes, code blocks, etc. They **must** always be indented by at least four spaces (or one tab) for each level of nesting.
> 
> In the event that one would prefer different behavior, [tab_length](http://pythonhosted.org/Markdown/reference.html#tab_length) can be set to whatever length is desired. Be warned however, as this will affect indentation for all aspects of the syntax (including root level code blocks).
