### ISSUE TITLE
Predictable named anchor links for headers?

### ISSUE THREAD

**Issue by surkova** [Python-Markdown/markdown#446]
Hi there

I have a use case for TOC extension that doesn't seem to be covered, but I though that someone might have a piece of advice on how to proceed with my problem.

I have an arbitrary text that goes like this: `Read about purchasing in section 1, read about shipping section 2` etc. I need to make `section 1` and `section 2` into anchor links to headers `# About purchasing` and `# About shipping`:

```
Read about purchasing in [section 1]({{ section_1_link }}), read about shipping [section 2]({{section_2_link}})
```

or 

```
Read about purchasing in [section 1](#section_1), read about shipping [section 2](#section_2)
```

Moreover, I have a whole bunch of such texts in different languages (translations of the same text).

Following the current logic, there's no way for me to predict what `slugify` will do to my headers to generate the links (given that headers might change I don't want the links to break).

Is there a way to generate given names for every header?

**Comment by waylan** [comment]
Have you tried the [Attribute Lists](https://pythonhosted.org/Markdown/extensions/attr_list.html) extension? With that extension you can define the slugs right in your document and the TOC extension will not override them. For example:

``` md
# About purchasing # { #section_1 }

...

# About shipping # { #section_2 }

...
```

And then elsewhere do:

``` md
Read about purchasing in [section 1](#section_1), read about shipping [section 2](#section_2)
```

**Comment by surkova** [comment]
@waylan thanks! it worked :)
