### ISSUE TITLE
Using codehilite with Pygments doesn't place code blocks inside code elements

### ISSUE THREAD

**Issue by StevenMaude** [Python-Markdown/markdown#447]
I'm using Python-Markdown 2.6.5 and Pygments 2.0.2 as installed from PyPI.

With Pygments installed:

``` python
>>> text = """
...     :::python
...     import foo
... """
>>> markdown.markdown(text, extensions=['codehilite'])
u'<div class="codehilite"><pre><span class="kn">import</span> <span class="nn">foo</span>\n</pre></div>'
```

Presentation works OK in this case, but I'd expect `<code>` tags to be present too to correctly indicate the semantics of the content.

Without Pygments installed, the behaviour's more what I would expect as the code is content that forms part of a `<code>` element:

``` python
>>> text = """
...     :::python
...     import foo
... """
>>> markdown.markdown(text, extensions=['codehilite'])
'<pre class="codehilite"><code class="language-python">import foo</code></pre>'
```

Can see in the codehilite [code](https://github.com/waylan/Python-Markdown/blob/14bcbe842af094874acf63244b6068653608508e/markdown/extensions/codehilite.py#L106-L139) that if Pygments is unavailable, code tags are added, but no similar thing is done when Pygments is used.

**Comment by waylan** [comment]
While I understand your concern, Pygments does not offer support for wrapping the code in code tags. Therefore, we don't either. We just use whatever Pygments returns. If you want to address this upstream (with Pygments), I would be happy to support it. But this is not something that we can do on this end.

**Comment by StevenMaude** [comment]
Thanks for the quick reply; I wasn't sure if you'd consider it a Pygments problem or not.

For anyone else who happens to read this, there's a stale pull request on Pygments [here](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/438/) to address this.

**Comment by p-ouellette** [comment]
Pygments recently added the `wrapcode` option for wrapping code in code tags: https://bitbucket.org/birkenfeld/pygments-main/commits/9ac63688129f98b8b1c2e320d6ea8f701ef185d1.

Can this option be set by default or should a codehilite option be added for it?

**Comment by waylan** [comment]
@pauloue thanks for the update. Note that this issue falls under #334 which covers a general refactor to support all Pygments options.

**Comment by p-ouellette** [comment]
Please see #822 for an initial attempt at implementing #334.
