### ISSUE TITLE
Nested list requires 4 spaces instead of 2

### ISSUE THREAD

**Issue by davidshen84** [Python-Markdown/markdown#451]
Most common Markdown editor uses 2 spaces as the indentation for nested list. But this library requires 4, and there's no way to configure this value.

Ex:
- level 1
  - level 2

Would it be possible to change the nested list indentation to **2**, or add a configuration value?

**Comment by waylan** [comment]
The [documentation](https://pythonhosted.org/Markdown/index.html#differences) clearly states:

> - **Indentation/Tab Length**
>   
>   The [syntax rules](http://daringfireball.net/projects/markdown/syntax#list) clearly state that when a list item consists of multiple paragraphs, "each subsequent paragraph in a list item **must** be indented by either 4 spaces or one tab" (emphasis added). However, many implementations do not enforce  this rule and allow less than 4 spaces of indentation. The implementers of Python-Markdown consider it a bug to not enforce this rule. 
>   
>   This applies to any block level elements nested in a list, including  paragraphs, sub-lists, blockquotes, code blocks, etc. They **must** always be indented by at least four spaces (or one tab) for each level of nesting.
>   
>   In the event that one would prefer different behavior, [tab_length](https://pythonhosted.org/Markdown/reference.html#tab_length) can be set to whatever length is  desired. Be warned however, as this will affect indentation for all aspects of the syntax (including root level code blocks).

Of course, if you would like different behavior, you are free to create your own extension which does whatever you want. I, however, have no interest in implementing a bug just to "match" other implementations.

**Comment by Ark-kun** [comment]
>Of course, if you would like different behavior, you are free to create your own extension which does whatever you want. I, however, have no interest in implementing a bug just to "match" other implementations.

Meanwhile. The creator of Markdown said this:

>For use in situations like user-submitted comments, GitHub Flavored Markdown is a superior variant. It changes just three rules from regular Markdown, all of which make for a better set of formatting rules for people who don’t even know the rules.
>★ Friday, 23 October 2009

**Comment by Ark-kun** [comment]
BTW, the stubbornness of this library just broke my website after applying auto-formatter.
I do not think John's intent ever was to cause pain and frustration to people. Quite the opposite.
