### ISSUE TITLE
Nested (and indented) raw HTML with blank lines breaks

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#452]
Simple example:

``` markdown
<div>
    <div>
        Div with a blank line

        in the middle.
    </div>
    <div>
        This gets treated as a code block
    </div>
</div>
```

Results:

``` html
<div>
    <div>
        Div with a blank line

        in the middle.
    </div>

<pre><code>&lt;div&gt;
    This gets treated as a code block
&lt;/div&gt;
</code></pre>
</div>
```

Removing the blank line in the first child `div` resolves the problem. But this should work without altering the HTML. This bug was first reported to [MkDocs](/mkdocs/mkdocs/issues/791).

**Comment by Felk** [comment]
on 2.6.8 a very similar bug still occurs.

	>>> x = """<i>
	...     <i>
	...
	...     </i>
	... </i>"""
	>>> print(md.convert(x))
	<p><i>
		<i></p>
	<pre><code>&lt;/i&gt;
	</code></pre>
	<p></i></p>

Workaround is to either avoid empty lines in html, or don't indent with tabs or multiples of 4 spaces

**Comment by facelessuser** [comment]
Isn't that an inline tag?

**Comment by Felk** [comment]
It doesn't matter what tag it is. Even tables work. After the empty line the closing tag gets treated as a markdown code block.

EDIT: oh, it actually works properly with `<div>` for the example above. However, here's a slightly different example that still breaks, and I have no idea why (i only added a headline above):

	>>> x = """# headline
	... <div>
	...     <div>
	...
	...     </div>
	... </div>"""
	>>> print(md.convert(x))
	<h1>headline</h1>
	<p><div>
		<div></p>
	<pre><code>&lt;/div&gt;
	</code></pre>
	</div>

If there's an additional newline after the headline, it works again. In my case it's a nested table with some jinja2 directives that implicitly cause some newlines in the html if I don't explicitly suppress them, which I could do of course.

**Comment by facelessuser** [comment]
> EDIT: oh, it actually works properly with <div> for the example above.

Yup, inline are handled differently.

> However, here's a slightly different example that still breaks, and I have no idea why (i only added a headline above):

If you put a space after the header, it works.  I'd have to look at the Markdown spec to see if this is a bug.

**Comment by facelessuser** [comment]
I'd check this out and see how wildly across the board everyone else handles it: https://johnmacfarlane.net/babelmark2/?text=%23+Header%0A%3Cdiv%3E%0A++++%3Cdiv%3E%0A%0A++++%3C%2Fdiv%3E%0A%3C%2Fdiv%3E.

I'd say we're in company with most people.  @waylan would need to say what he expects in this scenario.

**Comment by waylan** [comment]
>     <i>
>         <i>
>
>         </i>
>     </i>

This is **not** a bug. Span-level raw HTML gets the Markdown inside it parsed (as per the rules). And span-level raw HTML does not span multiple paragraphs. Of course, a paragraph ends at the first blank line, so the first paragraph is (correctly):

```html
<p><i>
	<i></p>
```

Then the first line after the blank line is indented four spaces, so it is (correctly) a code block. And the last line is not indented so we have another paragraph (`<p></i></p>`).

This is just some very poorly formatted raw HTML which results in invalid output. However, that is completely the users error. Note that all implementations give similar [ugly results][0] for that input (its bad input so the results are bond to vary but they are all very similar).

And now for this example:

>     >>> x = """# headline
>     ... <div>
>     ...     <div>
>     ...
>     ...     </div>
>     ... </div>"""
>     >>> print(md.convert(x))
>     <h1>headline</h1>
>     <p><div>
>         <div></p>
>     <pre><code>&lt;/div&gt;
>     </code></pre>
>     </div>

Note what the [rules][2] say:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

By a strict reading of the rules, that is not strictly a bug. However, the reference implementation and most others do output what is clearly intended. I suspect the problem is related to the fact that a header is only ever one line so it is the only case in which  block-level raw HTML could possibly not have a blank line before it. I'm "meh" about changing it. If someone else wants to they can, but we are technically following the rules so I'm not wasting my time on it (except to review a PR).

> In my case it's a nested table with some jinja2 directives that implicitly cause some newlines in the html if I don't explicitly suppress them, which I could do of course.

Hmm, so you complain about bad output when you are intentionally feeding in poorly formatted input?  I'd like to note that there are [Markdown linters][1] out there which require much stricter formatting than the rules require (such as always following a header with a blank line). Its just good form and avoids surprises.

> It doesn't matter what tag it is. 

Again, the [rules][2] state (emphasis in original):

> Unlike block-level HTML tags, Markdown syntax *is* processed within span-level tags.

Finally, in the future please report unrelated issues as new issues.

[0]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Ci%3E%0A++++%3Ci%3E%0A%0A++++%3C%2Fi%3E%0A%3C%2Fi%3E
[1]: https://duckduckgo.com/?t=lm&q=markdown+linter&ia=software
[2]: http://daringfireball.net/projects/markdown/syntax#html

**Comment by Felk** [comment]
I figured it out and everything works nicely now, thanks for taking the time to explain the details to me. Sorry for putting it in this issue, I didn't know that this was unrelated to the original
