### ISSUE TITLE
Tests fail with Pygments 2.1

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#453]
Looks like Pygments 2.1 broke the codehilite tests: https://bugs.debian.org/813028.

I tried restarting the latest build on Travis so that the error is reproduced there, but got a different failure…

**Comment by waylan** [comment]
Interesting. I have not been following Pygments and wondered when some change of theirs would break things. It appears from the Debian bug report that Pygments changed the names of the HTML classes assigned to the various parts. An easy fix for that it to have our tests simply verify that we get highlighted code without actually do a character for character comparison of the output.

The Travis error appears to be unrelated. Some sort of failure when installing the dependencies.  I'm [getting](https://travis-ci.org/waylan/Python-Markdown/jobs/98800386#L207) that pip has "no such option: --download-cache". However, our Travis config defers to tox and tox calls pip, so maybe this is a tox bug. Not sure what to make of that.

**Comment by waylan** [comment]
I reported the travis/tox/pip error to tox. See that [report](https://bitbucket.org/hpk42/tox/issues/308/pip-version-8-incompatibility-download) if you are curious about it. Now lets focus on the Pygments failure here.

**Comment by waylan** [comment]
So I fixed the travis/tox/pip issue (see eda5d198) and I'm [not seeing](https://travis-ci.org/waylan/Python-Markdown/builds/105491889) this Pygments error. Although it appears that pip version 8 is not Python3.2 compatible (see [release notes](https://pip.pypa.io/en/latest/news/)) so we have an [error](https://travis-ci.org/waylan/Python-Markdown/jobs/105491891) there. Sigh.

**Comment by waylan** [comment]
Addressed the py32 issue in 5562b054b. Still, [not seeing](https://travis-ci.org/waylan/Python-Markdown/builds/105499427) any Pygments related failures.

**Comment by mitya57** [comment]
Ah, that's because there is no Pygments in `test-requirements.txt` and thus the codehilite tests are skipped (how about adding it there)?

However I am confident that there _were_ changes in Pygments 2.1 which affected HTML output. For example Sphinx devs changed their tests because of this: sphinx-doc/sphinx@5574aba60ed76f2b.

Re Python 3.2, I don't think we should care about it anymore (but we should definitely add 3.5 if Travis supports it).

**Comment by waylan** [comment]
Thanks @mitya57 for passing that report on. It [appears](https://travis-ci.org/waylan/Python-Markdown/builds/105591153) to be fixed now.

> but we should definitely add 3.5 if Travis supports it

I agree. However, Travis support is only "sort of". See [here](https://github.com/mkdocs/mkdocs/pull/755#issuecomment-157571422) for an explanation. I figure I'll add that with the next major release. Hopefully by then Travis support for 3.5 will be complete.

**Comment by mitya57** [comment]
Thanks for fixing it so quickly! Works for me now too.
