### ISSUE TITLE
mailto: URLs are html-encoded

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#456]
Hi Waylan,

Forwarding a bug report from [Debian #816218](https://bugs.debian.org/816218):

---

Hello,
thank you for maintaining markdown.

I have noticed that rendering email links generates a rather overquoted href:

``` python
>>> import markdown
>>> markdown.markdown("<test@example.org>")
'<p><a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#116;&#101;&#115;&#116;&#64;&#101;&#120;&#97;&#109;&#112;&#108;&#101;&#46;&#111;&#114;&#103;">&#116;&#101;&#115;&#116;&#64;&#101;&#120;&#97;&#109;&#112;&#108;&#101;&#46;&#111;&#114;&#103;</a></p>'
```

Chromium opens it correctly, so I wonder if this is just some antispam measure. However, chromium opens it correctly, so I'm not sure it is really useful as an antispam measure.

Looking at AutomailPattern's implementation in `inlinepatterns.py` it seems intentional, and I think it should at least be documented, and, if possible, configurable.

This is making it rather complicated for me to postprocess `<a>` links in the markdown ElementTree.

Thank you,
Enrico

**Comment by waylan** [comment]
This is an often overlooked requirement of the Markdown [syntax rules](http://daringfireball.net/projects/markdown/syntax#autolink). I realize that it actually does little to avoid spam, but it is required by the rules and therefore I will not consider removing it. If users prefer, they can always override/change the default behavior with an extension. However, to offer anything except this as the default behavior would be a bug.

**Comment by mitya57** [comment]
Ok, thanks for the quick response, I have forwarded it to the original submitter.

**Comment by waylan** [comment]
Thanks @mitya57. I appreciate you passing these on to me and forwarding my responses.
