### ISSUE TITLE
PrettifyTreeprocessor breaks if tree contains comments

### ISSUE THREAD

**Issue by atul-bhouraskar** [Python-Markdown/markdown#46]
If an extension (e.g. inlinepattern) adds a comment to the tree, then markdown fails with an exception (TypeError) while subsequently running the PrettifyTreeprocessor.

The offending code is in treeprocessors.py in the _prettifyETree(self, elem) method. 

The code attempts to verify that the comment is block level by calling markdown.isBlockLevel(e.tag) on the comment. However e.tag evaluates to a function for a comment and not to a string that the isBlockLevel function is expecting, causing the TypeError exception to be raised.

The code might need to explicitly check for comments and ignore them in this processor.

**Comment by waylan** [comment]
This had already been fixed in the latest code in the git repo. Closed.
