### ISSUE TITLE
Freeze with table rendered without Markdown Extra

### ISSUE THREAD

**Issue by jpfleury** [Python-Markdown/markdown#47]
1. Create a file `m.py` with the following content:
   
   ```
   import markdown
   
   text = """
   Lorem ipsum                         | Lorem ipsum | Lorem ipsum
   ----------------------------------- | :---------: | :---------:
   Lorem ipsum dolor sit amet inceptos | Lorem ipsum | Lorem ipsum
   """
   
   print markdown.markdown(text)
   ```
2. Run the file:
   
   ```
   $ python m.py
   ```

**Actual result:** Python-Markdown freezes. If we interrupt the process, we have the following output:

```
$ python m.py 
^CTraceback (most recent call last):
  File "m.py", line 9, in <module>
    print markdown.markdown(text)
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/__init__.py", line 386, in markdown
    return md.convert(text)
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/__init__.py", line 283, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/blockparser.py", line 62, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/blockparser.py", line 77, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/blockparser.py", line 93, in parseBlocks
    if processor.test(parent, blocks[0]):
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/blockprocessors.py", line 470, in test
    return bool(self.SEARCH_RE.search(block))
KeyboardInterrupt
$
```

**Expected result:** no freeze. Both PHP Markdown (no Extra) and Markdown.pl output the following:

<pre><code>&lt;p&gt;Lorem ipsum                         | Lorem ipsum | Lorem ipsum
----------------------------------- | :---------: | :---------:
Lorem ipsum dolor sit amet inceptos | Lorem ipsum | Lorem ipsum&lt;/p&gt;
</code></pre>

**More information:**
- The bug doesn't occur with extension Extra:
  
  ```
  print markdown.markdown(text, extensions=['extra'])
  ```
- Tested with `waylan-Python-Markdown-2.1.0.beta-0-ge8cdb0b.zip`.

**Comment by jpfleury** [comment]
May be related to https://github.com/waylan/Python-Markdown/issues/48

**Comment by waylan** [comment]
Bah! The new Horizonal Rule regex added at 619613e2 is choking on the table syntax. This isn't a problem when the table extension is used as it parses the table before the HR blockprocessor ever gets to it -- unless, of course the table is not valid (at in issue #48 marked a duplicate of this). Guess I'll have to dig back into that HR regex. Ugh.

Thanks for the report. We don't want markdown hanging like that. Especially as it is often used on web servers.

**Comment by waylan** [comment]
So I don't forget this I'm pasting it here. I threw together the following little timeit script to time the (simplified) HR regex:

``` python

import timeit


SETUP = """
import re
RE = re.compile(r'^[ ]{0,3}(-+[ ]{0,2}){3,}[ ]*$', re.MULTILINE)
"""

if __name__ == '__main__':
    for i in range(3,20):
        s = '-'*i + '|'
        print str(i)+':', timeit.timeit(
            stmt = "RE.search('%s')" % s,
            setup = SETUP,
            number=100
        )
```

Here is a sample of the output:

```
3: 0.000312805175781
4: 0.000509023666382
5: 0.00100803375244
6: 0.002445936203
7: 0.0041880607605
8: 0.0075569152832
9: 0.0195791721344
10: 0.0372581481934
11: 0.0711460113525
12: 0.139706134796
13: 0.278136014938
14: 0.55503487587
15: 1.10221886635
16: 2.21200704575
17: 4.40101408958
18: 8.85019803047
19: 17.6753211021
```

Note that the number to the left of the colon is the number of dashes (`-`) followed by a single `|`. 

This regex just takes to long to run! It doubles for each single dash added.

However, if I remove the final `$` from the end of the regex I get blazing fast speeds:

```
3: 0.000293970108032
4: 0.000334024429321
5: 0.000384092330933
6: 0.000756978988647
7: 0.000377178192139
8: 0.000638961791992
9: 0.000677824020386
10: 0.000797986984253
11: 0.00043797492981
12: 0.000778913497925
13: 0.000298976898193
14: 0.00059700012207
15: 0.000599145889282
16: 0.000709056854248
17: 0.000557899475098
18: 0.000375986099243
19: 0.000642061233521
```

**Comment by jpfleury** [comment]
Oh, I think it's the same problem I had with my language definition for Markdown in gedit. See [my bug report](https://bugzilla.gnome.org/show_bug.cgi?id=650334), particularly my [comment 4](https://bugzilla.gnome.org/show_bug.cgi?id=650334#c4):

> Thanks to José Aliste on irc for discussion about this report.
> 
> So, backtracking can make some regex very slow, with an exponential complexity. For now, there's no benchmarking to automatically detect these cases, so we must deal with them while using language files.
> 
> A solution to these slow regex is to make use of atomic grouping or possessive quantifiers (linear complexity). See the following articles:
> - [Runaway Regular Expressions: Catastrophic Backtracking](http://www.regular-expressions.info/catastrophic.html)
> - [Atomic Grouping](http://www.regular-expressions.info/atomic.html)
> - [Possessive Quantifiers](http://www.regular-expressions.info/possessive.html)
> 
> ---
> 
> For this particular report, the following 2 regex are a lot faster:
> 
> ```
> ^ {0,3}(\*+ {0,2}){3,}+[ \t]*$
> ^ {0,3}(\* {0,2}){3,}[ \t]*$
> ```

Finally, in my language definition file, I used the following (and it's a lot faster):

```
^[ ]{0,3}           # Maximum 3 spaces at the beginning of the line.
(
  (-[ ]{0,2}){3,} | # 3 or more hyphens, with 2 spaces maximum between each hyphen.
  (_[ ]{0,2}){3,} | # Idem, but with underscores.
  (\*[ ]{0,2}){3,}  # Idem, but with asterisks.
)
[ \t]*$             # Optional trailing spaces or tabs.
```

**Comment by waylan** [comment]
Yeah, I'm using the same regex as you suggest and I understand that it is a backtracking problem. The sample in my timeit script actually is simpler as I removed the matches for underscores and asterisks - it only matches dashes.  Just for kicks I ran it with the complete regex and I get the same slow results.
