### ISSUE TITLE
extra and codehilite: can't turn off Pygments with fenced code blocks

### ISSUE THREAD

**Issue by szhorvat** [Python-Markdown/markdown#471]
When using the `extra` extension for fenced code blocks, along with `codehilite`, it is not possible to turn off Pygments highlighting.

Example input markdown:

``````
```foo
xxx
```

    :::foo
    xxx
``````

Command line:

```
python -m markdown -x extra -x "codehilite(use_pygments=False)" somefile.md
```

Output:

``` html
<div class="codehilite"><pre><span></span>xxx
</pre></div>

<pre class="codehilite"><code class="language-foo">xxx</code></pre>
```

As you can see the fenced code block is still using Pygments (i.e. it generates `<span>` and doesn't output `class="language-foo"`.

**Comment by waylan** [comment]
This was fixed in dd669e3 and will be available in the next release.
