### ISSUE TITLE
code block nested in list

### ISSUE THREAD

**Issue by yanxurui** [Python-Markdown/markdown#472]
Hi, I am a beginner in python-markdown. 
I noticed that the latest version doesn't support code block nested in list like this.
1. foo
   
   ``` python
   print 'hello'
   print 'world'
   ```
2. bar

Is there any way to support it?
What should I do? 
THANKS

**Comment by waylan** [comment]
As the rules [state](http://daringfireball.net/projects/markdown/syntax#list):

> To put a code block within a list item, the code block needs to be indented twice — 8 spaces or two tabs:
> -   A list item with a code block:
>   
>   ```
>   <code goes here>
>   ```

However, after looking at your example (via the edit feature -- it would have helped if your example was in a code block) it appears that you are trying to use a fenced code block in a list. That is simply not possible at this time. See #53 for more info. As this appears to be a duplicate of that issue, I'm closing this.

**Comment by yanxurui** [comment]
@waylan Thanks a lot. I solved it by using an extension.

**Comment by ghost** [comment]
@yanxurui mind showing your extension? I need this solved too (and also for blockquotes). If I can't do it with this library, I might have to go use mistune after all.

**Comment by yanxurui** [comment]
Hi I believe it's `pymdownx.github` that does the work for me.
Unfortunately, The github extension in pymdownx is [deprecated](https://facelessuser.github.io/pymdown-extensions/).

**Comment by facelessuser** [comment]
@yanxurui @yujiri8 It is not `pymdownx.github` that provides this behavior, it is `pymdownx.superfences` that provides nested fence code. If you want a setup that does what the old `pymdownx.github` extension did, you can set it up with this configuration: https://facelessuser.github.io/pymdown-extensions/faq/#github-ish-configurations.

`pymdownx.github` never did anything except setup the configuration  of  the other extensions.

**Comment by yanxurui** [comment]
@facelessuser thanks that's awesome. I am wondering what blows you here?

**Comment by facelessuser** [comment]
> I am wondering what **blows** you here?

I'm not sure if I get your meaning in regards to **blows**. Maybe you meant **brings**?  If so, I am a member of the Python Markdown org.
