### ISSUE TITLE
Pipes in two consecutive list items render a table

### ISSUE THREAD

**Issue by sheljohn** [Python-Markdown/markdown#479]
I guess this is on the same vein as "Pipe inside code-block inside table", but I would consider this bug slightly worse, because it gets rendered partly bold and partly as a table, even though there is no table or bold markup involved.

Here is a minimal example:

```
- `this|does`
- `not|work`
```

Curiously though, this works fine:

```
- `this|does`
- `not work`
- `oh|wait`
```

**Comment by waylan** [comment]
Hmm, actually it is much simpler than that:

```
- this|should
- not |be a table
```

It has nothing to do with code spans. What is considered a table is not strict enough. Get my example to work and your example would work correctly also.

As it stands now, anything is a table if the first two lines of a block both contain pipes. Clearly, that is a little aggressive.

**Comment by sheljohn** [comment]
Doing this:

```
- this|should
- not |be
- a |table
```

does not work for me.

---

Would it maybe make sense to say that for it to be a table, you would need:
- at least three pipes per line;
- at least two lines;
- each line should begin and end with a pipe.

I think it's fair to say that tables in pretty much any language are difficult to deal with, so IMO people would expect that to get a "fancy" table (ie, without outer border, or within a list) they should write it down with HTML tags. Whereas I think people expect that inline code and lists should work flawlessly in Markdown. Do you think that's reasonable?

---

Another option would be to copy what [GFM does](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables):

> There must be at least 3 dashes separating each header cell.
> The outer pipes (|) are optional

Although IMO requiring table header cells is a bit too much. And apparently omitting the outer pipes doesn't render a table without borders, so I really don't understand the point.

**Comment by waylan** [comment]
To be clear, any fix will not be changing the syntax in any way. A fix _must_ maintain the same (intended & documented) syntax supported now. We just need to do a better job of avoiding false positives.

**Comment by sheljohn** [comment]
> As it stands now, anything is a table if the first two lines of a block both contain pipes.

Is that the intended syntax? I understand compatibility and stability issues, I really do, but that seems like a wrong definition to start with I have to say :/ If that's the case, could you please be so kind to point me where I should look to change this definition in the code so i could maybe create a fork?

**Comment by waylan** [comment]
> > As it stands now, anything is a table if the first two lines of a block both contain pipes.
> 
> Is that the intended syntax? 

No, I was simply acknowledging what the bug is in that comment. It should not actually work that way which should have been clear by my next statement:

> Clearly, that is a little aggressive.

The tables extension is intended to be a direct clone of [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#table)'s table implementation. The behavior should be identical to that.

**Comment by sheljohn** [comment]
@waylan Is there any way I can help fix this? I wouldn't know where to look in the code, but if you could point me to the right place I could give it a try a write a pull request if you'd like?

**Comment by amwbc** [comment]
+1 - i am right this minute having a problem with this.
Can I help? Encourage? Bribe?

**Comment by adammichaelwood** [comment]
(amwbc is also me -- that is a "work" gh account I happened to be logged into)

I started working on this as an extension.

It looks like the simplest solution is to do it in preprocessor and catch lines that begin with hyphens (minus leading whitespace) and simply swap out pipes for the html character code `&#124;`

Is there any reason this is a terrible idea?

**Comment by waylan** [comment]
Preprossesors in general are a bad idea as you can't get their output into the document object. They may even go away in a future release. 

The existing Extension is [here](https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/tables.py) and presumably needs to be tightened up a little to avoid some false positives (I don't have time to work on this right now but pull requests are welcome). Alternatively, there are some [third-party](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions) table extensions. Perhaps some of those don't have this issue.

**Comment by adammichaelwood** [comment]
I'll add tests and do a PR this evening or tomorrow, but I got this working locally for now. - I just added `and not rows[0].strip().startswith('-')` to the test block, at line 33.

Any reason this is a terrible approach?

**Comment by waylan** [comment]
Well, list items can start with other characters, such as `*`, `+`, as well as ordered lists (`1.`, `2.`, ...). Generally, these types of conflicts can be handled by changing the order in which the various processors are run. If tables were run after lists, then the problem may just go way. I don't recall off hand, but there may be a legitimate reason for the tables processor to be run first, in which case a slightly more sophisticated variation of your proposal would be the way to handle it.

As lists are part of the standard (default) syntax and tables are an add-on, I do not want code in the list processor special casing tables, but it is fine to have code in the tables extension special casing lists. Although, in an ideal world, a sufficiently strict match shouldn't need to special case anything.

**Comment by adammichaelwood** [comment]
Cool. I'll look at what happens with re-ordering the processors (which I suspect will have its own set of problems) and then (assuming this is the way to go) do a better version of this.

Is there a reason the first row of a table should be allowed to start with a list-starting character? 

Two other thoughts about catching false positives...

1

IF you're trying to match PHP Markdown Extra, those instructions say the following (my emphasis added):

> First line contains column headers; second line contains a **mandatory separator line** between the headers and the content; each following line is a row in the table.

The separator line is hyphens and pipes. Could we just check for that? 

2

Could we check for the same number of pipes in the first two rows? For a table to work as expected, there should (I think?) need to be the same number of pipes.

**Comment by waylan** [comment]
> Is there a reason the first row of a table should be allowed to start with a list-starting character?

Sort of. The asterisk can be used for both a list item bullet and to indicate emphasis/bold. The difference is that a list item also requires a space after the bullet.  In other words `* this` is a list item while `*this` is not (notice the second example is missing the space). The same applies to ordered lists (one or more digits, followed by a dot, followed by a space). So the "list item token" is the combination of the bullet and the space following it. Finally, as a reminder, the list item token can also be indented with up to 3 spaces and still be a valid list item token.

> The separator line is hyphens and pipes. Could we just check for that?

I was going to say that headings are not mandatory, but I just checked and PHP Extra's docs make no mention of that (I know some Markdown libs with table support have made table headings optional).  I don't recall off-hand, but if we require headings, then yes that approach would work, but if we do not require headings, then no. And I don't want to break the existing functionality in that regard regardless of what the PHP lib does.

> Could we check for the same number of pipes in the first two rows? For a table to work as expected, there should (I think?) need to be the same number of pipes.

I think you will find that that does not help. Look at the examples above. They contain the same number of pipes per line but are clearly not intended to be tables.

**Comment by adammichaelwood** [comment]
Currently, Python Markdown does not allow tables without a header.
In fact - it already checks to make sure that the the second line is a separator.

For that reason, this is not a table:

```
This | isn't | a |  Table
because | there | aren't | hyphens 
```

Interestingly that means that though, as reported:

```
- `this|does`
- `not|work`
```

The following does work:

```
 * asterisks | for | bullets
 * solves | the | problem
```

So... I think that my first naive solution above it not a good one, and that the right approach is to improve the _existing_ second-line check for a separator line of hyphens, pipes, and colons.

**Comment by waylan** [comment]
Ahh, the second line with a hyphen and a pipe is enough to trick it into seeing a separator line. Right, only allow separator line chars on that line. If it contains anything that is not a hyphen, pipe or colon, then it is not a separator line. That should actually be easier to implement.

**Comment by adammichaelwood** [comment]
Starting to set up testing... what versions of Python need to be supported?

**Comment by waylan** [comment]
At least everything listed in the [tox.ini](https://github.com/waylan/Python-Markdown/blob/master/tox.ini#L2) file: `py27, py32, py33, py34, pypy`, although 3.5 should probably be added to that list (and we don't actually run the 3.2 tests in [Travis](https://github.com/waylan/Python-Markdown/blob/master/.travis.yml#L3)).

**Comment by adammichaelwood** [comment]
PR submitted.

thinking about problem: maybe an hour
writing code: 90 seconds
setting up test environ: 8 days

**Comment by waylan** [comment]
@adammichaelwood thanks for the work on this.

> setting up test environ: 8 days

Sorry, I should have picked up on your hint previusly. To avoid this problem myself, I crated [this](https://github.com/waylan/Python-Markdown/wiki/Test-Environment-Setup) wiki page some time ago. Although, with Travis running automated tests, I usually just test in my primary Python version and push up a pull request and let Travis run the rest.

**Comment by amwbc** [comment]
Oh, no worries --

I found the wiki page, that wasn't the problem. Issue was I don't run ubuntu, and couldn't follow the not-easy instructions without apt. So virtualbox. And then deadsnakes doesn't work on Ubuntu 16.10, only 16.04.

Once I got the OS sorted out, your instructions were pretty easy. And now I have Ubuntu on my Mac, so I can work on other things, too.
