### ISSUE TITLE
Heading within a list is not rendered as expected

### ISSUE THREAD

**Issue by rs2** [Python-Markdown/markdown#481]
I.e. 
`* ## Foobar`
Is expected to be an H2 bullet point.

**Comment by waylan** [comment]
I'm getting:

``` html
<ul>
  <li>
    <h2>Foobar</h2>
  </li>
</ul>
```

Which is correct. What are you getting and which version are you using?

**Comment by waylan** [comment]
I'm closing this due to an inability to reproduce and/or a lack of information.

**Comment by rs2** [comment]
:+1:
