### ISSUE TITLE
Base64 encoded images don't convert

### ISSUE THREAD

**Issue by Bobspadger** [Python-Markdown/markdown#491]
Example: (trimmed)

```
md = """
my bits of markdown text
![](data:image/jpeg;base64,%2F9j%2F4AAQSkZJRgABAQEAZABkAAD%2F2w......
```

This converts into:

```
<p>![](data:image/jpeg;base64,%2F9j%2F4AAQSkZJRgABAQ.......
```

Code:

```
md = """markdown text with base64 image"""
html = markdown.markdown(md)
```

Is this the expected behaviour, as I would of thought I should of got `<img>` tags.

Help appreciated.

**Comment by waylan** [comment]
I realize you are providing a truncated example here, but given your example (with the closing parenthesis added), I can't replicate the problem. 

``` python
>>> import markdown
>>> text = """
... my bits of markdown text
... ![](data:image/jpeg;base64,%2F9j%2F4AAQSkZJRgABAQEAZABkAAD%2F2w)
... """
>>> markdown.markdown(text)
u'<p>my bits of markdown text\n<img alt="" src="data:image/jpeg;base64,%2F9j%2F4AAQSkZJRgABAQEAZABkAAD%2F2w" /></p>'
```

**Comment by Bobspadger** [comment]
@waylan 

Ah, I think I've found the issue, this was coming from a DB, and the data had been truncated.

Sorry for bothering you :)

Alex
