### ISSUE TITLE
Does not produce valid X(HTML)

### ISSUE THREAD

**Issue by l0b0** [Python-Markdown/markdown#492]
Both HTML and XHTML need to have at least `html`, `head` and `title` to be valid. And a `DOCTYPE` declaration is very useful to specify the [encoding](https://unix.stackexchange.com/questions/308469/how-to-set-fallback-encoding-to-utf-8-in-firefox) of the document.

**Comment by waylan** [comment]
Markdown produces an (X)HTML fragment. It was never intended to do any more than that. If you want a complete HTML document, then it is your responsibility to wrap it. This has been the behavior of the original Markdown implementation from the beginning, which we mirror with no intention of changing.

As an aside, we only output Unicode text, so an encoding would not be applicable anyway. True, the CLI outputs an encoded file, but this is a library first (to be called by other Python code). The CLI is only provided as a convenience. The assumption is that the output of the CLI would be piped to something else which wraps the (X)HTML fragment.

**Comment by sleske** [comment]
To add another voice:
For the library, I can understand that producing the HTML wrapping is out of scope - after all, a library is by definition not intended to work on its own. However, the command line script can run on its own, and would be much more useful if it offered an option to produce a complete HTML document.

Are there objections to adding a command line option to do HTML wrapping?
Something like:

```
-c, --complete-html
Output a complete HTML document, instead of an HTML fragment.
The document will contain an encoding declaration, so web browsers
can display it correctly even as a local file.
```

The option would just add a standard HTML document start/end, including `<meta charset="utf-8">`. I'd be happy to provide a patch/pull request if there is interest in including this.

As far as I can see, it should be possible to do this in `__main__.py`, so there is no need to change the library itself.

**Comment by waylan** [comment]
> Are there objections to adding a command line option to do HTML wrapping?

Yes. The implementations which include something of the sort need to support some sort of templating system which is something other than Markdown. If you want that, then use a Static Site Generator (which is its intended purpose). If you don't need that sort of sophistication, then use the existing tool with pipes (etc) to build your complete document (you are using the command line after all; might as well use it to the full). There's no need for us to add anything as it would either be out-of-scope or is already possible with the existing tools.

**Comment by sleske** [comment]
>  If you don't need that sort of sophistication, then use the existing tool with pipes (etc) to build your complete document (you are using the command line after all; might as well use it to the full). There's no need for us to add anything as it would either be out-of-scope or is already possible with the existing tools.

Yes, creating a complete HTML document is possible with existing tools - but if all you want is an HTML document you can read in a browser, it is a bit tedious.

The use-case I have in mind is: You have a markdown document, and want to convert it to HTML to read it conveniently. Maybe to quickly preview markdown you write yourself, or some documentation that is provided as markdown... Having a simple command line utility to do this is useful.

This situation led me to the `markdown_py` script, and I was a bit annoyed that it omits the HTML header/ending. Thus my question about adding an option. I could not find any command line utility that does this.

If you feel this use case is not significant enough, then I won't insist further (and hack up a wrapper script). Anyway, thank you for the feedback.

**Comment by waylan** [comment]
No matter how simple of a solution was provided, there would inevitably be someone who would argue that it shouldn't be to much to add just a little bit more. I have to draw the line somewhere and I have drawn the line where I have because the original reference implementation (markdown.pl) didn't include such a feature either. The creator of Markdown saw it as being out-of-scope, so I do as well.

**Comment by sleske** [comment]
Yes, I see your point about scope creep.

Also, I just noticed that pandoc ( http://pandoc.org/ , or on GitHub at https://github.com/jgm/pandoc ) has exactly what I wanted. The `pandoc` command line tool has the option `--standalone` to produce complete HTML documents. So I'll just use that and not bother you anymore :-).

Maybe the links will help others who are looking for a simple command-line converter Markdown -> HTML.

Thank you for your detailed feedback about the project scope, and happy hacking!
