### ISSUE TITLE
mardown fails combining fenced-code and attr-list (or extra)

### ISSUE THREAD

**Issue by amr66** [Python-Markdown/markdown#496]
I'm trying to have highlighted code with `<pre><code>` and an id in pre.
See my question at http://stackoverflow.com/questions/39636154/mardown-fails-combining-fenced-code-and-attr-list
i tried many combinations, original php-markdown says, that it is possible, python markdown can't do it?
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ {.html #example-1}
    &lt;p&gt;paragraph &lt;b&gt;emphasis&lt;/b&gt;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
any chance to have this with python markdown extra?

**Comment by waylan** [comment]
This is not supported at this time. Perhaps this will be added in the future but no specific plans exist. 

Of course anyone can add whatever features they desire if they want to create their own extensions.

**Comment by amr66** [comment]
Thank you for your quick answer!
