### ISSUE TITLE
Allow modification of the class of the pre-tag in a fenced code block.

### ISSUE THREAD

**Issue by jimktrains** [Python-Markdown/markdown#506]
One use-case would be http://prismjs.com/ where the pre-tag needs to have a class of line-number to take advantage of line numbering.

**Comment by jimktrains** [comment]
Here is a proposed diff

``` diff
diff --git a/markdown/extensions/fenced_code.py b/markdown/extensions/fenced_code.py
index 8c9935e..27e9510 100644
--- a/markdown/extensions/fenced_code.py
+++ b/markdown/extensions/fenced_code.py
@@ -40,11 +40,12 @@ class FencedBlockPreprocessor(Preprocessor):
 (\{?\.?(?P<lang>[a-zA-Z0-9_+-]*))?[ ]*  # Optional {, and lang
 # Optional highlight lines, single- or double-quote-delimited
 (hl_lines=(?P<quot>"|')(?P<hl_lines>.*?)(?P=quot))?[ ]*
+(pre_class=(?P<quot2>"|')(?P<pre_class>.*?)(?P=quot2))?[ ]*
 }?[ ]*\n                                # Optional closing }
 (?P<code>.*?)(?<=\n)
 (?P=fence)[ ]*$''', re.MULTILINE | re.DOTALL | re.VERBOSE)
-    CODE_WRAP = '<pre><code%s>%s</code></pre>'
-    LANG_TAG = ' class="%s"'
+    CODE_WRAP = '<pre%(pre_class)s><code%(lang)s>%(code)s</code></pre>'
+    CLASS_TAG = ' class="%s"'

     def __init__(self, md):
         super(FencedBlockPreprocessor, self).__init__(md)
@@ -70,8 +71,10 @@ class FencedBlockPreprocessor(Preprocessor):
             if m:
                 lang = ''
                 if m.group('lang'):
-                    lang = self.LANG_TAG % m.group('lang')
-
+                    lang = self.CLASS_TAG % m.group('lang')
+                pre_class = ''
+                if m.group('pre_class'):
+                    pre_class = self.CLASS_TAG % m.group('pre_class')
                 # If config is not empty, then the codehighlite extension
                 # is enabled, so we call it to highlight the code
                 if self.codehilite_conf:
@@ -89,8 +92,9 @@ class FencedBlockPreprocessor(Preprocessor):

                     code = highliter.hilite()
                 else:
-                    code = self.CODE_WRAP % (lang,
-                                             self._escape(m.group('code')))
+                    code = self.CODE_WRAP % {"pre_class": pre_class,
+                                             "lang": lang,
+                                             "code": self._escape(m.group('code'))}

                 placeholder = self.markdown.htmlStash.store(code, safe=True)
                 text = '%s\n%s\n%s' % (text[:m.start()],
```

As such

```
~~~{.language-python pre_class="line-numbers"}
print()
~~~
```

would render

```
<pre class="line-numbers"><code class="language-python>
print()
</code></pre>
```

**Comment by waylan** [comment]
As I explain in great detail [here](http://achinghead.com/marking-up-code.html), all code related attributes should be assigned to the `code` tag and not the `pre` tag. I am opposed to doing otherwise and certainly refuse to support any library which does so (that library should be the one to make the change for the reasons stated in the link above). Of course, if you disagree, you are free to create your own Extension which acts in whichever way you desire.

**Comment by waylan** [comment]
I should also add that #334 is a more general issue for expanding the options and any support for line numbering would come under that.

**Comment by jimktrains** [comment]
Perhaps I'm dull, but the post you linked to really doesn't contain any rationale as to why the pre tag shouldn't have a class.  You appear to be arguing that it shouldn't contain the language declaration class. I'm neither proposing that, nor am I proposing bare pre-tags.

Moreover, line numbering is not a code-related attribute -- you can line-number any text.

While it's your library and you're free to make any decision you want, speaking condescending to someone interested in helping isn't a good way to foster a community.

Since I'd prefer to use the smallest number of dependencies possible, i.e. not my own fenced code extension, can you recommend a syntax highlighting javascript library that doesn't require a class on the pre-tag for line-number support? I do not want the HTML to contain the syntax-derived tags for a variety of reasons.

**Comment by waylan** [comment]
Sorry @jimktrains if my response came across condescending.  My annoyance was not directed at you but the library your were attempting to use. And you have a point, the linked article does not specifically address line-numbering. However, I think the same reasoning applies--the class should be defined on the code tag.

In any event, my JS highlighting library of choice is [highlight.js](https://highlightjs.org/), but it may not support line numbers. A lot of people seem to like [Google Code Prettify](https://github.com/google/code-prettify), which offers a lot of options (the classes can be defined on either the `pre` or `code` tag), but I've never been a fan as you can't define the language (it guesses, often incorrectly).

**Comment by jimktrains** [comment]
No worries! Tone is hard in text and I probably took it a little more harshly than I should have.  I'll look at some of those options. Thanks!
