### ISSUE TITLE
Codehilite doesn't mantain indentation?

### ISSUE THREAD

**Issue by doppioandante** [Python-Markdown/markdown#509]
Hello, I'm using the same procedure outlined [here](http://sebastianraschka.com/Articles/2014_markdown_syntax_color.html) but newlines or spaces are not preserved inside the generated pre block... what am I doing wrong?
I modified the source to use <br> instead of \n as line separator, but the indentation is gone.
Something down the way is stripping the whitespaces maybe?

**Comment by waylan** [comment]
Can you provide a simple example input and the generated output as well as the output you expected ?

**Comment by doppioandante** [comment]
Sorry this was my fault, I was using a sh script to automatize the conversion, and at a certain point there was

```
echo $HTML > blabla.html
```

Which eats all the spaces, the fix is to wrap $HTML around double quotes.
