### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [Python-Markdown/markdown#512]
http://pythonwheels.com/

Right now, only the `tar.gz` and `zip` files are being distributed on PyPI for [Python-Markdown](https://pypi.python.org/pypi/Markdown), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install Python-Markdown with just the wheel, without having to do any extra work.

**Comment by waylan** [comment]
Wheel support has already been added in the 3.0 branch and will be available with the next major release.
