### ISSUE TITLE
Lines starting with a hash without spaces before the words recognized as headers

### ISSUE THREAD

**Issue by jaywink** [Python-Markdown/markdown#513]
For example:

`#markdown` would render as a header. Commonly, especially in social media applications, this would indicate a hashtag. Having them render as headers causes [weird looking posts](https://jasonrobinson.me/public/).

As per the examples in the [original spec](http://daringfireball.net/projects/markdown/syntax#header), the hash is followed by a space. This is how for example GitHub and CommonMark markdown works.

```
#foobar

# foobar
```

Becomes

#foobar

# foobar

**Comment by waylan** [comment]
As demonstrated by [Babelmark][1], we are in the majority here. While I agree your suggested behavior would make sense, the existing behavior has been the norm from the begin (over a decade). Many thousands of documents would break if that behavior was changed.

Yes, CommonMark has defined a stricter spec, but CommonMark is not Markdown (maybe a younger sister) and I don't care what they do (or claim). Python-Markdown is a Markdown parser, not a CommonMark parser.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23foobar%0A%0A%23+foobar

**Comment by waylan** [comment]
I should point out that if you really want a hashtag at the beginning of a line (or by itself on a line) just escape the hash:

    \#foobar

And that renders fine as [Babelmark][1] demonstrates.

Oh and of course, if you would like a different behavior, it would be relatively simple to change it with an Extension.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5C%23foobar%0A%0A%23+foobar
