### ISSUE TITLE
Optionally provide file path to Preprocessor.run

### ISSUE THREAD

**Issue by Larivact** [Python-Markdown/markdown#520]
Some Preprocessors would benefit from knowing the path of the file they are processing, see cmacmackin/markdown-include#7.

Python-Markdown could check if a Preprocessor's run method expects a path argument using

```python
import inspect
if 'path' in inspect.getargspec(pp.run).args:
    pass
```

**Comment by waylan** [comment]
All user specific variables should be contained in the config options of the extension. There is no reason for Markdown to add any additional functionality.

That said, you need to be careful. A user could create an instance of the `markdown.Markdown` class and pass multiple pages through that one instance. However, the extension configs are passed in on instance creation, not when calling the `convert` method on the instance. Therefore, there is no "per page" scope unless the extension specifically accounts for it (it would need to be [registered extension][1] with a `reset` method). Even so, there is no mechanism to pass in values per page.

In such a case, the answer is to only allow an instance to only handle one page (use the `markdown.markdown` wrapper function). Then with each page, you can pass in a path as an extension config setting. Just be sure to document that the extension will fail if a single `markdown.Markdown` instance is used with multiple pages.

It might look something like this (assuming markdown_include adds support for it):

```python
import markdown
from markdown_include.include import MarkdownInclude

for page in pages:
    markdown_include = MarkdownInclude(page_path=page.path)
    write(markdown.markdown(page.source, extensions=[markdown_include]))
```

[1]: https://pythonhosted.org/Markdown/extensions/api.html#registerextension
