### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#538]
Hi Waylan!

There has been some awesome bugfix work by @facelessuser and you in the recent days. Will it be possible to have a new release within a couple of days?
Then it will be possible to ship it in Debian 9 (the deadline for uploading packages before freeze is Jan 26th).

**Comment by waylan** [comment]
Actually, yes, I was planning to do a release soon. Probably on the 25th but no later than the 26th.

**Comment by waylan** [comment]
Just pushed [2.6.8](https://github.com/waylan/Python-Markdown/releases/tag/2.6.8-final).

**Comment by mitya57** [comment]
Thank you! It will land in Debian in a few hours and then in Ubuntu in a few more hours ;)
