### ISSUE TITLE
toc extension patch

### ISSUE THREAD

**Issue by thread13** [Python-Markdown/markdown#54]
A quick hack to support non-ascii headings :  

=== diff -u toc.py.old toc.py >>> ===

```
   --- toc.py.old   2011-11-20 20:03:03.000000000 +1100
   +++ toc.py   2011-11-20 20:04:22.000000000 +1100
   @@ -76,7 +76,7 @@
                    # Do not override pre-existing ids 
                    if not "id" in c.attrib:
                        id = self.config["slugify"][0](c.text)
   -                    if id in used_ids:
   +                    if ( id == '' ) or ( id in used_ids ):
                            ctr = 1
                            while "%s_%d" % (id, ctr) in used_ids:
                                ctr += 1
```

=== <<< ===  

Basically the slugify() method makes an empty slug for non-ascii headings, so we name them as "_%d" % (heading_occurence) then .

**Comment by waylan** [comment]
As the code has changed drastically here, your patch will not apply to the current code. In fact, we are now running `unicodedata.normalize()` on headers in our `slugify()` function to support non-ascii headers. Therefore, your patch should be unnecessary.

**Comment by thread13** [comment]
Indeed, the patch does not apply any more.

But I am happy to report that the problem (making empty slugs for non-ascii headings) was successfully moved with the code to a new location; as I can not reopen this bug, I will file [a new one](https://github.com/waylan/Python-Markdown/issues/99) instead.
