### ISSUE TITLE
Wikilinks extension should support custom link text

### ISSUE THREAD

**Issue by clarfonthey** [Python-Markdown/markdown#541]
For example, doing either `[Link][[Page]]` (Markdown style) or `[[Link|Page]]` (wiki style).

**Comment by waylan** [comment]
Then you can just use a normal markdown link. I'm not interested in adding any features to this extension (If anything I would remove it). Of course, you (or anyone) are free to fork it and modify it however you like as long as you following the licence.

**Comment by clarfonthey** [comment]
That's fair! I feel that removing/deprecating it is best if it doesn't support features like this, because otherwise it's not too useful. Thanks for the quick response.
