### ISSUE TITLE
[Question] Disable convertation in 2 block-level HTML elements

### ISSUE THREAD

**Issue by Kristinita** [Python-Markdown/markdown#542]
### 1. Summary

I don't need conversation `<` → `&lt;` and `>` → `&gt;` in my code besides code inside `<pre>` tag.

### 2. Expected behavior

I have `test1.md` file. Content of a file:

```html
<p>Sasha unbelievable <span id="obf"><script>document.getElementById("obf").innerHTML="<n uers=\"znvygb:FnfunTbqqrff@xevfgvavgn.eh\" gnetrg=\"_oynax\">R-znvy</n>".replace(/[a-zA-Z]/g,function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);});document.body.appendChild(eo);</script>
 <noscript><span style="unicode-bidi:bidi-override;direction:rtl;">ur.atinitsirk@sseddoGahsaS</span></noscript></span> and very beautiful!</p>
```

Output:

```html
   <p>Sasha unbelievable <span id="obf"><script>document.getElementById("obf").innerHTML="<n uers=\"znvygb:FnfunTbqqrff@xevfgvavgn.eh\" gnetrg=\"_oynax\">R-znvy</n>".replace(/[a-zA-Z]/g,function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);});document.body.appendChild(eo);</script>
<noscript><span style="unicode-bidi:bidi-override;direction:rtl;">ur.atinitsirk@sseddoGahsaS</span></noscript></span> and very&nbsp;beautiful!</p>
```

### 3. Actual behavior

I have `test2.md` file. Content of a file:

```html
Sasha incredible!
<p>Sasha unbelievable <span id="obf"><script>document.getElementById("obf").innerHTML="<n uers=\"znvygb:FnfunTbqqrff@xevfgvavgn.eh\" gnetrg=\"_oynax\">R-znvy</n>".replace(/[a-zA-Z]/g,function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);});document.body.appendChild(eo);</script>
 <noscript><span style="unicode-bidi:bidi-override;direction:rtl;">ur.atinitsirk@sseddoGahsaS</span></noscript></span> and very beautiful!</p>
```

Output:

```html
    <p>Sasha incredible!
<p>Sasha unbelievable <span id="obf"><script>document.getElementById("obf").innerHTML="<n uers=\"znvygb:FnfunTbqqrff@xevfgvavgn.eh\" gnetrg=\"_oynax\">R-znvy</n>".replace(/[a-zA-Z]/g,function(c){return String.fromCharCode((c&lt;="Z"?90:122)&gt;=(c=c.charCodeAt(0)+13)?c:c-26);});document.body.appendChild(eo);</script>
 <noscript><span style="unicode-bidi:bidi-override;direction:rtl;">ur.atinitsirk@sseddoGahsaS</span></noscript></span> and very&nbsp;beautiful!</p></p>
```

In output `<` → `&lt;` and `>` → `&gt;`; and my script doesn't work.

### 4. Steps to reproduce

The problem is reproduced for me in [**ExportHTML**](https://github.com/facelessuser/ExportHtml) @facelessuser package.

I use [**Pelican**](https://blog.getpelican.com/) static site generator → `pip install markdown` → I wrote my `test2.md` file (I [**obfuscate**](http://rot13.florianbersier.com/) my e-mail) → `pelican content` → I get actual behavior.

I read that [**Markdown don't format inside block-level HTML elements**](http://stackoverflow.com/a/701098/5951529), but inside 2 `<p>` tags I get unexpected behavior.

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Pelican:**
3.7.1
**Python Markdown:**
2.6.8

Thanks.

**Comment by waylan** [comment]
@Kristinita I'm assuming that you are suggesting that the first example is working correctly and the second is not. Did I understand that correctly? The only notable difference I see is that the second example has a line of text immediately before the raw HTML. However, note that the [rules][1] state (emphasis added):

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — ***must be separated from surrounding content by blank lines***, and the start and end tags of the block should not be indented with tabs or spaces.

In your case you do not have a blank line between the preceding text and the raw HTML, which causes the raw HTML to (correctly) **not** be recognized as a raw HTML block. Add a blank line and it will work as you desire:

### The (corrected) Input:

```markdown
Sasha incredible!

<p>Sasha unbelievable <span id="obf"><script>document.getElementById("obf").innerHTML="<n uers=\"znvygb:FnfunTbqqrff@xevfgvavgn.eh\" gnetrg=\"_oynax\">R-znvy</n>".replace(/[a-zA-Z]/g,function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);});document.body.appendChild(eo);</script>
 <noscript><span style="unicode-bidi:bidi-override;direction:rtl;">ur.atinitsirk@sseddoGahsaS</span></noscript></span> and very beautiful!</p>
```

### The Output:

```html
<p>Sasha incredible!</p>
<p>Sasha unbelievable <span id="obf"><script>document.getElementById("obf").innerHTML="<n uers=\"znvygb:FnfunTbqqrff@xevfgvavgn.eh\" gnetrg=\"_oynax\">R-znvy</n>".replace(/[a-zA-Z]/g,function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);});document.body.appendChild(eo);</script>
 <noscript><span style="unicode-bidi:bidi-override;direction:rtl;">ur.atinitsirk@sseddoGahsaS</span></noscript></span> and very beautiful!</p>
```
[1]: http://daringfireball.net/projects/markdown/syntax#html
