### ISSUE TITLE
Markdown extension didn't work

### ISSUE THREAD

**Issue by cropse** [Python-Markdown/markdown#544]
## platform environment:
* OSX 10.10.5
* Python 3.5.2
* Markdown 2.6.8

`import markdown`
`text = "A setext style header {: #setext}"`
`html = markdown.markdown(text, ['markdown.extensions.extra'])`
`# also tried 'markdown.extensions.attr_list'`
`print(html)`

It return:
`<p>A setext style header {: #setext}</p>`

**Comment by waylan** [comment]
You need to actually crate a header. In other words the line needs to begin with hash characters:

```python
text = "# A setext style header {: #setext}"
```

**Comment by waylan** [comment]
Sorry, Atx-style headers use hash characters. If you want a Setext-style header, then you need a second line which makes it a header:

```python
text = "A setext style header {: #setext}\n===================="
# or
text = """
A setext style header {: #setext}
====================
"""
```

**Comment by cropse** [comment]
Sorry, I didn't notice it, thanks for your patience
It really solves my problem
