### ISSUE TITLE
Unexpected list translation

### ISSUE THREAD

**Issue by Superdanby** [Python-Markdown/markdown#547]
Original Markdown code: 
```markdown
- a
- b
- c

1. 1
2. 2
3. 3
```
After translation:

![](http://i.imgur.com/8xmzvUe.png)

which is
```html
<ul>
<li>a</li>
<li>b</li>
<li>
<p>c</p>
</li>
<li>
<p>1</p>
</li>
<li>2</li>
<li>3</li>
</ul>
```

instead of:
![image](https://cloud.githubusercontent.com/assets/17717083/23165311/197a5ad0-f801-11e6-8bb5-9b695d81dc99.png)

which is
```html
<ul>
<li>a</li>
<li>b</li>
<li>c</li>
<ul>
<ol>
<li>1</li>
<li>2</li>
<li>3</li>
</ul>
```

**Comment by waylan** [comment]
Actually, that is the correct behavior (you can search the closed issues for an explanation), which is why we have the [Sane Lists][1] extension. Just enable the Sane Lists extension and you will get the behavior you want.

[1]: https://pythonhosted.org/Markdown/extensions/sane_lists.html

**Comment by waylan** [comment]
See #64 for more info. Also our [documentation][1] states:

> * Consecutive Lists
>
>     While the syntax rules are not clear on this, many implementations (including the original) do not end one list and start a second list when the list marker (asterisks, pluses, hyphens, and numbers) changes. For consistency, Python-Markdown maintains the same behavior with no plans to change in the foreseeable future. That said, the [Sane List Extension][2] is available to provide a less surprising behavior.

[1]: https://pythonhosted.org/Markdown/#differences
[2]: https://pythonhosted.org/Markdown/extensions/sane_lists.html

**Comment by Superdanby** [comment]
This is really helpful. Thanks!
