### ISSUE TITLE
Subclassing an extension?

### ISSUE THREAD

**Issue by twardoch** [Python-Markdown/markdown#548]
I'd like to extend an existing Python-Markdown extension. 

Specifically, I want to create a custom extension which does the same processing as [`pymdownx.mark`](https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/mark.py) but in addition to performing the transformation, it should do some logging. 

Most specifically, I want to write out to an external file all content portions matched by the extension (i.e. in this case all `==such text==`). 

Could anyone kindly provide a minimal example how I could subclass/inherit from an existing extension and add functionality to it but keeping the original functionality?

**Comment by waylan** [comment]
The [tutorial][1] should provide everything you need.

[1]: https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown

**Comment by facelessuser** [comment]
Also, @twardoch, as you used `pymdownx` as an example, there are extensions within `pymdownx` that subclass classes from existing Python Markdown extensions, you can look at those and see how the subclassing is performed.
