### ISSUE TITLE
TOC extension shold ignore it's own heading

### ISSUE THREAD

**Issue by fladd** [Python-Markdown/markdown#552]
The TOC extension should ignore all headings above where it is called, or at least the heading it is called in.

This:
```
# Table of Contents

[TOC]

# Section 1

## Section 1.1

# Section 2

## Section 2.2

# Section 3

## Section 3.3
```

Will result in "Table of Contents" being part of the table of contents :-)

**Comment by waylan** [comment]
Thanks for your suggestion, In all the years this extension has existed, this is the first request for this feature. In other words, it doesn't appear to be a popular request. Therefore, I would suggest that if you really want this, fork the existing extension and develop it yourself. If it becomes wildly popular, then we will reconsider.

If it helps, I don't use the `[TOC]` to insert the TOC into a document. Instead, I always insert the TOC into a side bar or similar via a template. Therefore the TOC is never inline with the document and never under any specific header. The `[TOC]` feature was simply to offer feature parity with other implementations. It would be interesting to see how they deal with the stated problem (IIRC, they don't).

**Comment by fladd** [comment]
I am sorry, I was under the impression that I simply discovered a bug, as I could not make any sense out of the described behaviour. Reading your response - taking my bug report as a feature suggestion - I now realize that the described behaviour is apparently both (1) known and (2) intended for some reason. Thanks for the clarification.
