### ISSUE TITLE
Footnote extension: `BACKLINK_TEXT` does not work

### ISSUE THREAD

**Issue by fladd** [Python-Markdown/markdown#553]
The `BACKLINK_TEXT` setting of the footnotes extension does not work.

The following code has no effect on the backlink symbol, while the other settings on the other extensions do work:

```
extension_configs = {
        'markdown.extensions.toc': {
            'permalink': "#"
        },
        'markdown.extensions.codehilite': {
            'guess_lang': False
        },
        'markdown.extensions.footnotes': {
            'BACKLINK_TEXT': "X"
        }
} 
```

**Comment by waylan** [comment]
I'm not able to replicate the problem in the current version:

```python
>>> import markdown
>>> markdown.version
'2.6.8'
>>> text = '''paragraph[^1]
... 
... [^1]: A Footnote'''
>>> markdown.markdown(text, extensions=['markdown.extensions.footnotes'], extension_configs={'markdown.extensions.footnotes': {'BACKLINK_TEXT': 'back'}})
u'<p>paragraph<sup id="fnref:1"><a class="footnote-ref" href="#fn:1" rel="footnote">1</a></sup></p>\n<div class="footnote">\n<hr />\n<ol>\n<li id="fn:1">\n<p>A Footnote&#160;<a class="footnote-backref" href="#fnref:1" rev="footnote" title="Jump back to footnote 1 in the text">back</a></p>\n</li>\n</ol>\n</div>'
```

But, I did notice we don't have a test for this, so I just pushed one: cd752c0.

**Comment by fladd** [comment]
Interesting, in isolation (using the exact code from your answer) it works, just not, when used together with the other extensions. Is it known to be incompatible with any extensions? I use the following:
```
extensions = ['markdown.extensions.toc',
                       'markdown.extensions.codehilite',
                       'pymdownx.extra',
                       'pymdownx.github'    
                      ] 
```
Where `pymdownx.extra` contains/loads `markdown.extensions.footnotes`.

**Comment by waylan** [comment]
Ah, I would suggest reporting this as a bug to pymdownx. If you are not calling the footnote extension directly, then pymdownx would need to pass the config on. I haven't looked looked at that code, so I'm not sure how it's being done.

**Comment by facelessuser** [comment]
FYI, `markdown.extensions.extra` doesn't recognize `{'markdown.extensions.footnotes': {'BACKLINK_TEXT': 'back'}}` either (at least from my tests).  Is this something that is expected?

As a side note, I would advice not using both `pymdownx.extra` and `pymdownx.github` as including both may include some extensions twice causing unexpected behavior: http://facelessuser.github.io/pymdown-extensions/usage_notes/.  Pick one wrapper extension, and manually configure the missing extensions.

**Comment by facelessuser** [comment]
This was my run:

```py
>>> markdown.markdown(text, extensions=['markdown.extensions.extra'], extension_configs='markdown.extensions.footnotes': {'BACKLINK_TEXT': 'back'}})
u'<p>paragraph<sup id="fnref:1"><a class="footnote-ref" href="#fn:1" rel="footnote">1</a></sup></p>\n<div class="footnote">\n<hr />\n<ol>\n<li id="fn:1">\n<p>Footnote&#160;<a class="footnote-backref" href="#fnref:1" rev="footnote" title="Jump back to footnote 1 in the text">&#8617;</a></p>\n</li>\n</ol>\n</div>'
```

**Comment by waylan** [comment]
Interesting. I just noticed that we don't document anything regarding using config settings with `markdown.extensions.extra`. I looked at the code and it was not immediately obvious so I guessed and this works.

```python
>>> markdown.markdown(text, extensions=['markdown.extensions.extra'], extension_configs={'markdown.extensions.extra': {'markdown.extensions.footnotes': {'BACKLINK_TEXT': 'back'}}})
u'<p>paragraph<sup id="fnref:1"><a class="footnote-ref" href="#fn:1" rel="footnote">1</a></sup></p>\n<div class="footnote">\n<hr />\n<ol>\n<li id="fn:1">\n<p>A Footnote&#160;<a class="footnote-backref" href="#fnref:1" rev="footnote" title="Jump back to footnote 1 in the text">back</a></p>\n</li>\n</ol>\n</div>'
```

While it makes sense (sort of), it is certainly less than ideal (that's a lot of nested dicts). However, I don't think I'll be changing it as I'm inclined to not have an "extra" extension in the future (3.0). Just let each stand on their own.

**Comment by facelessuser** [comment]
> I'm inclined to not have an "extra" extension in the future (3.0). Just let each stand on their own.

I've been considering this myself.

Thanks for outlining how nested settings work, I had no idea that it was possible.

**Comment by waylan** [comment]
> Thanks for outlining how nested settings work, I had no idea that it was possible.

It has to work that way now as an extension only gets settings for itself. Therefore extra never sees settings for "footnotes". However, extra makes custom calls to the extension loading methods so any settings not passed to extra are not available when footnotes is loaded. The only way to pass to extra and tell extra which extension they belong to is to nest them. Well, I suppose you could make extra aware of each supported extensions' configs, but ugh.

**Comment by facelessuser** [comment]
> Well, I suppose you could make extra aware of each supported extensions' configs, but ugh.


Nah, what you're doing makes the most sense.  I wrongfully assumed that extra was prepackaged and didn't accept settings.

I do plan on dropping "wrapper" extensions in the future, but until i start the deprecation, I'll mimic what you do in extra in regards to settings.
