### ISSUE TITLE
Docs erroneously say that `odict.add()` only has two mandatory parameters

### ISSUE THREAD

**Issue by alexwlchan** [Python-Markdown/markdown#554]
Quoting from the [Extension API docs](https://pythonhosted.org/Markdown/extensions/api.html#ordereddict) (emphasis mine):

> The `add()` method accepts three arguments:
>
> * `key`: A string. The key is used for later reference to the item.
> * `value`: The object instance stored in this item.
> * `location`: **Optional**. The items location in relation to other items.

But the [source code for the method](https://github.com/waylan/Python-Markdown/blob/master/markdown/odict.py#L170) shows that all three arguments are required:

```python
def add(self, key, value, location):
    """ Insert by key location. """
```

Either the "Optional" should be removed from the docs, or the parameter should be made optional.

I’d mildly prefer the latter, as I have some cases where the location really doesn’t matter, but it’s not a strong preference.

**Comment by waylan** [comment]
Not sure why the docs say "optional". It never has been and doesn't make sense to be. I'll update the docs. Thanks for the report.

**Comment by john-kurkowski** [comment]
Thanks! Can you publish the doc update? http://pythonhosted.org/Markdown/extensions/api.html#ordereddict still says "Optional."

**Comment by waylan** [comment]
The docs are updated on each release.

**Comment by waylan** [comment]
Hmm, looks like we didn't update the docs when we released 2.6.9. Opps.

**Comment by facelessuser** [comment]
Docs don't auto-deploy on release?  I figured they did, but I never really checked.

**Comment by waylan** [comment]
No, I never got that automated. The releases are so few and far between and it was never a problem to run `make docs` and then use the "edit" page on PyPI to upload the zip file. That is, until now. See #601 for the current state and my proposal to address it.

**Comment by facelessuser** [comment]
Have you settled on a theme? If you have (and when I have some time), I can probably set it up.

**Comment by facelessuser** [comment]
That is of course if you are ready to jump to Mkdocs.

**Comment by waylan** [comment]
The switch to MkDocs exists in the md3 branch at 6f87b32. That commit should "cherry-pick" and merge relatively easily. And I just finished and released the [MkDocs-Nature][1] theme to use with it (the md3 branch is currently using readthedocs). Whoever gets to it first...

[1]: https://waylan.github.io/mkdocs-nature/
