### ISSUE TITLE
toc extension permalink id do not support utf8 first character

### ISSUE THREAD

**Issue by ngtrian** [Python-Markdown/markdown#555]
I using toc extension with mkdocs.

toc can not convert character bellow to id:

> đ

**Comment by waylan** [comment]
Yes, as per the spec, the URL hash must be in ASCII characters only. Currently, we don't try to convert non ASCII characters to ASCII, so the behaviour is less than ideal in that case. However, you can provide your own [slugify function][1], so you can have it convert it however you want.

As it happens, there is the excellent [awesome-slugify][2] library which provides a number of options for slugifying various Unicode strings into readable ASCII. And the callables it provides work fine with Python-Markdown.

It's better for such a special purpose library to concentrate on their speciality, than for us to try to replicate it here. And as awesome-slugify's defaults are slightly different than ours, it would be a backward incompatible change for us to switch, so we are not making any changes here.

[1]: https://pythonhosted.org/Markdown/extensions/toc.html#usage
[2]: https://github.com/dimka665/awesome-slugify

**Comment by ngtrian** [comment]
I have fix a problem with pymdownx

`pip install pymdown-extensions`

**mkdocs.yml**

```
- toc:
   slugify: !!python/name:pymdownx.slugs.uslugify
```

Thanks for suppport
