### ISSUE TITLE
Chance to change the permalink symbol style

### ISSUE THREAD

**Issue by ghtmtt** [Python-Markdown/markdown#557]
Hi,

hoping this is the right place where to write. I'm using the markdown extension together with pelican.
It work exactly as I needed. The `pelicanconf.py` looks like:

```
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.toc': {'permalink': True}
    }
}
```

I was wondering if there is a chance to change the symbol size and opacity (for my website it looks a little too big). 

Thanks!

**Comment by facelessuser** [comment]
Yup, just target it with CSS.  The permalink is an anchor tag with the class `headerlink` applied to it.

**Comment by ghtmtt** [comment]
Thanks for the super quick reply. So you mean adding a key to the dict, like:
```
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.toc': {'permalink': True},
         'markdown.extensions.toc': {'target': 'css'}
    }
}

```

but what should be the `target` and `css` within the dictionary? 

While the css could be something like:

```
a.headerlink {
    color: grey;
    padding-left: .5em;
    visibility: hidden;
}
```

Many thanks again!

**Comment by waylan** [comment]
Your Markdown setting would be:

```
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.toc': {'permalink': True}
    }
}
```

The "headerlink" class is assigned automatically. You then just need to tell Pelican to use your additional CSS, which is beyond the scope of the help we can provide here.

**Comment by ghtmtt** [comment]
Ok, perfect clear now! Super thanks for the availability! 

Awesome work!
