### ISSUE TITLE
Issue: nl2br extension and lists

### ISSUE THREAD

**Issue by ghost** [Python-Markdown/markdown#56]
When using the nl2br extension i have found the following bug. If you were to create a markdown list then try to write a snippet of code the code does not get put into `<pre>` or `<code>` tags.

I believe the cause of this to be that the nl2br is not escaping out of the list causing the following syntax.

```
<ul>
    <li>
        <p>Helloworld</p>
        <p>My code snippet</p>
    </li>
</ul>
```

**Comment by waylan** [comment]
As you have not provided your input, I can't be sure but I'm guessing you do not have enough indent on your code block. Remember that blocks inside lists are already indented once, so a code block would be indented twice - once to make it a child of the list and twice to make it a code block.

So, if you were **not** using nl2br, your input would look like this (spaces replaced with `.` for illustrative purposes):

```
* Helloworld

........My code snippet
```

For that matter, even when using nl2br, I would still leave the blank line before the code block. Does it even work outside of a list with no blank line? Guess I'm a little confused what nl2br has to do with it. Maybe if I had your source text that would help.

**Comment by waylan** [comment]
Without any further information, I'm closing this for the reasons in my previous comment. I can't reproduce any bug here. Just bad input by the document author.
