### ISSUE TITLE
use 'pymdownx.superfences':Mismatched anonymous define() module

### ISSUE THREAD

**Issue by lierisme** [Python-Markdown/markdown#563]
# use MkDocs

## mydocs.yml:
site_name: My Docs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
markdown_extensions:
    - pymdownx.superfences

## test.md
\```flow
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...

st->op1->cond
cond(yes)->io->e
cond(no)->sub1(right)->op1
\```

## run: mkdocs serve
http://127.0.0.1:8000

## result:
**Uncaught Error: Mismatched anonymous define() module: function ()** ......

why???
help!
thanks!

**Comment by facelessuser** [comment]
This is better suited for the repo containing SuperFences. https://github.com/facelessuser/pymdown-extensions.

**Comment by waylan** [comment]
> This is better suited for the repo containing SuperFences. 

I agree. Please follow up there.
