### ISSUE TITLE
[Question] Disable auto-remove space characters in line begin.

### ISSUE THREAD

**Issue by Kristinita** [Python-Markdown/markdown#564]
### 1. Briefly

I don't find:

    if I have [**space characters**](http://www.fileformat.info/info/unicode/category/Zs/list.htm) in line begin:

        how I can disable auto-remove space characters?

### 2. Argumentation

I write my texts in “Python-style” with spaces in line begin as in section 1 of this post.

### 3. Settings

For example, I have `Kristina.md` file, it content:

```markdown
    Kristina sunny!
```

I use [**U+2005 symbols**](http://www.fileformat.info/info/unicode/char/2005/index.htm) in line begin.

### 4. Steps to reproduce

I reproduce the problem with [**another unicode space symbols**](http://www.fileformat.info/info/unicode/category/Zs/list.htm),

    exclude default [**U+0020 space**](http://www.fileformat.info/info/unicode/char/0020/index.htm).

I convert `Kristina.md` to HTML use any methods.

### 5. Expected behavior

```html
<p>    Kristina sunny!</p>
```

[**28 results**](https://johnmacfarlane.net/babelmark2/?text=%E2%80%85%E2%80%85%E2%80%85%E2%80%85Kristina+sunny!) in Babelmark.

### 6. Actual behavior

```html
<p>Kristina sunny!</p>
```

[**4 results**](https://johnmacfarlane.net/babelmark2/?text=%E2%80%85%E2%80%85%E2%80%85%E2%80%85Kristina+sunny!) in Babelmark include Python Markdown.

### 7. Did not help

1. Googling,
1. I don't find an extension for Python Markdown.

Thanks.

**Comment by facelessuser** [comment]
Python Markdown usually follows `Markdown.pl`, but it appears it doesn't in this case, but only @waylan can say if this is something that should change.

I don't have an an easy answer for it to just work as is, but here are some workarounds:

1. You could just specify the html entity: `&#x2005;` opposed to the literal character. This will work fine and will pass through giving you what you'd expect: `&#x2005;&#x2005;&#x2005;&#x2005;Kristina sunny!`.
2. You could use an extension like http://facelessuser.github.io/pymdown-extensions/extensions/escapeall/.  This would allow you to escape the character and it would also pass through as you expect. `\ \ \ Kristina sunny!`.

**Comment by waylan** [comment]
The reason that many implementations treat Unicode spaces differently that non-unicode spaces is that Markdown predated Unicode (or at least Unicode was not common or widely supported yet). For example, the reference implementation (markdown.pl) is completely not Unicode aware. To that parser, the Unicode spaces and a normal space which you type with your space bar are different characters. The fact that your input works as you desire is purely by accident.

Fortunately for us, Python is very much Unicode aware and in fact, the Python-Markdown library only accepts Unicode input. Therefore any character that the Python regex engine matches to `\s` is seen as a normal space character. To alter that behavior would require either using something other than the standard lib regex engine or a complete refactor of every regular expression in the parser. 

However, you should be careful with spaces in HTML. Browsers collapse consecutive spaces into a single space. I haven't recently checked how they behave with some of the special Unicode space characters, but in the past they were generally unreliable and is was understood that you should only use HTML entities if you wanted the browser to behave as desired.

From the beginning of Markdown, the way to obtain your desired result would have been to use the non-breaking space HTML entity: `&nbsp;`. However, as browsers don't collapse the entity with spaces, you only need every other space to be an entity.  Like this:

    &nbsp; &nbsp; Kristina sunny!

Which gives you:

    <p>&nbsp; &nbsp; Kristina sunny!</p>

Interestingly, [Babelmark] indicates that some more modern implementations (Commonmark and friends) do not retain the HTML entities but convert them to spaces. However, Python-Markdown is proudly an old-school parser and I have no interest in following the new fork which is not really Markdown IMO.

[Babelmark]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%26nbsp%3B+%26nbsp%3B+Kristina+sunny!
