### ISSUE TITLE
Timetable for next release?

### ISSUE THREAD

**Issue by facelessuser** [Python-Markdown/markdown#568]
Been keeping an eye out for any showstopper bugs in the last release, but just haven't seen any in the last 5 months.  I wanted to give it about 5-6 months before I asked, but how long to a new bug fix release?

I was hoping to push a the new official release as a SublimeText dependency (for plugins that use it), and I wanted to have the fix for this https://github.com/waylan/Python-Markdown/issues/539 as I skipped pushing out the last version because of this.

No rush; just curious.

**Comment by waylan** [comment]
I hadn't remembered that there were any notable changes since the last release. I should be able to get one out later this week or next.

**Comment by waylan** [comment]
Oh, and thanks for the reminder.

**Comment by facelessuser** [comment]
np and thanks!

**Comment by facelessuser** [comment]
I understand you are probably just busy and probably haven't forgotten, but I figured I 'd just send a reminder due to what was last discussed. Thanks.

**Comment by waylan** [comment]
Yup, it completely slipped my mind.

**Comment by facelessuser** [comment]
Figured I'd go ahead and send a new reminder :slightly_smiling_face: .

**Comment by waylan** [comment]
Finally got the release out for 2.6.9. Sorry for the long delay.
