### ISSUE TITLE
Access markdown content before html conversion

### ISSUE THREAD

**Issue by jaysudodeveloper** [Python-Markdown/markdown#569]
Im working on a static site generator using jinja2 and markdown as the core of the static site generator. Is there a way i can access the markdown content as python class attributes in a way that would let me use them in jinja2 as template variables and not just use the resulting html. 

For example if i have i markdown list, i am hoping i can access it as a python list so that in my jinja2 template i can iterate over it and have my own nested/css html instead of the resulting html from markdown.

**Comment by waylan** [comment]
No there is not really a way to do that. Via our Plugin API you can access the [ElementTree object][1], but there are [additional steps][2] that happen after it is serialized to an HTML string. The only way to get a completely converted document is to accept the string of HTML. If you really need some sort of object, the best approach would be to parse the HTML string into something useful. 

[1]: https://pythonhosted.org/Markdown/extensions/api.html#treeprocessors
[2]: https://pythonhosted.org/Markdown/extensions/api.html#postprocessors

**Comment by jaysudodeveloper** [comment]
Aight i appreciate the response. I think the best solution ive found so far is to use one of the extensions that let me provide css in the markdown that relate to my style sheet. Which to some extend fixes my issue but limits what i wanted to achieve. 

Would this be something you could implement as a future feature? The meta attribute extension im using heavily, but i dont know enough about writing parsers to implement the said feature.

**Comment by waylan** [comment]
The only way to implement such a feature would be to completely remove the need for the postprocessors and that would take a major refactor. I have neither the need nor the time for such a feature myself, so, no it is not likely to ever happen.
