### ISSUE TITLE
Pythonhosted.org down for 4 days, consider using readthedocs.org

### ISSUE THREAD

**Issue by ashb** [Python-Markdown/markdown#571]
The docs links for this project is currently unavailable (taking 30+s to serve a 500 page) and has been in this stage for about 4 days.

Might it be worth considering moving the docs links from pypi/homepage etc to http://readthedocs.org/?

**Comment by waylan** [comment]
Interesting. Hadn't noticed myself. Thanks for the report. According to [this], it not just this project either. Unfortunately, there is no official response yet.

As far as readthedocs goes, AFAICT they don't provide a way to upload already built HTML. That being the case, I'm not interested. I don't want to use Sphinx/ReST (why would Python-Markdown not be documented in Markdown?) and they only support an old outdated (and not very good) version of MkDocs.

The fact is, any free (or even paid) hosting service could just disappear one day. Some seem to think that readthedocs has a better future ahead of it, but that's not really what's important. It's about what feature-set matches your needs and readthedocs doesn't do it for me.

[this]: https://mail.python.org/pipermail/python-list/2017-July/723444.html

**Comment by ashb** [comment]
> As far as readthedocs goes, AFAICT they don't provide a way to upload already built HTML. That being the case, I'm not interested. I don't want to use Sphinx/ReST (why would Python-Markdown not be documented in Markdown?) and they only support an old outdated (and not very good) version of MkDocs.

Yes that is a fair point :)

**Comment by waylan** [comment]
It's back now.
