### ISSUE TITLE
Alt attribute for images with html5 output format is broken

### ISSUE THREAD

**Issue by sedrubal** [Python-Markdown/markdown#578]
The `alt` attribute for `<img>` tags breaks when you choose `html5` as output format, but only if the alt tag should be `alt="alt"` 😄 .

```sh
$ echo '![alt](img.png)' | p -m markdown -o html5
<p><img alt src="img.png"></p>
```

```sh
$ echo '![altt](img.png)' | p -m markdown -o html5
<p><img alt="altt" src="img.png"></p>
```

**Comment by waylan** [comment]
This would appear to be a side effect of using ElementTree, which provides no native way to represent HTML boolean attributes (like "checked"... for example in XHTML, the proper output would be `checked="checked"`, but in HTML5, it would be `checked`). Our serializer assumes any attribute in which the attribute name and the value are equal should be a boolean attribute. Therefore, when it sees `alt="alt"`, it outputs `alt`.

Given that there is a very narrow edge case in which that behavior could be wrong (document authors manually defining values which are equal to the attribute name), I'm not terribly concerned about it. After all, it seems highly unlikely that `"alt"` is actually useful as alt text for an image.

To be clear, this is a bug, it just not near the top of the list. That said, a PR is welcome if someone is motivated to provide a fix.

**Comment by sedrubal** [comment]
Ah ok thanks for clarifying. I'm ok with a wontfix, but I was quite confused while I wrote unittests for another function using the markdown module 😄

**Comment by waylan** [comment]
That was my guess... that you discovered this writing tests. Can't think of any other situation where this would actually be both encountered and noticed.

**Comment by waylan** [comment]
I'm not sure if we really need to make any changes here. The only "fix" would be to include a list all all known boolean HTML attributes (they are clearly defined in the HTML spec) and only condense them, but not any others.
