### ISSUE TITLE
allow a subset of markdown

### ISSUE THREAD

**Issue by frederikcreemers** [Python-Markdown/markdown#58]
While it's nice to have safe mode, as a website owner, you sometimes want to limit the abilities of users even more. For example, on blog articles posted by users, you want all the markdown options, but in comments, you only want links, **bold** and _italic_ text, and inline code snippets. A way to do that would be nice.

What I propose, is that you can use the markdown function like this:

```
markdown("**bold** and _italic_",allowed_tags=['b','a','i','u'],safe_mode='escape')
```

**Comment by waylan** [comment]
I'll start by pointing out that "safe-mode" was a poor name choice that we continue to use for backward comparability (old code still works with our newer versions). What it really is is a no-markup mode. In other words, it is just a way to disallow raw html and really doesn't guarantee safety. If you want safety, then a dedicated library would provide a better solution. Perhaps something like [Bleach](https://github.com/jsocol/bleach) which could be run on markdown's output to strip out all tags not in your white list. With Bleach you don't even need our "safe-mode", which has actually been my suggested approach to the problem for some time now.

That said if you really want to do this with markdown there already exists a way. You can use our [Extension API](https://github.com/waylan/Python-Markdown/blob/master/docs/writing_extensions.md) to remove the various components of the markdown parser that you do not want. Based on your request, an extension which removed most of the inline patterns should do the trick. Of course, the source text would then be passed through unparsed (i.e., a markdown link would come through in its raw non-html form). Then again, you could write a replacement inline pattern which simply returned the plain text with markup removed. But then you're re-implementing Bleach.

Given the above, I'm closing this "won't fix."
