### ISSUE TITLE
How do I add new css style?

### ISSUE THREAD

**Issue by liuyug** [Python-Markdown/markdown#586]
I want add new css style or theme...  How do I?

**Comment by waylan** [comment]
The Markdown parser only outputs an HTML fragment. That fragment still needs to be wrapped in  `<html><body>` tags and a `<head>` needs to be added as well. There are multiple ways to accomplish that, which are outside the scope of a Markdown parser. Here are a few common ways (in order of complexity) to get you started:

1. Write out each piece sequentially to a file via a command line script.
2. Use a templating system, passing in the Markdown output as the context.
3. Use a static site generator which automates templating and provides customizable themes.
4. Use a web framework or CMS.

If you just have a one-off, number 1 above is pretty simple. As part of a custom (Python) tool, number 2 is more flexible. Personally, number 3 is probably best for most people. Depending on your needs, you may find that either MkDocs or Pelican will serve you well (both use Python-Markdown and offer full support for our extension system).
