### ISSUE TITLE
Incorrect result with multi-level lists

### ISSUE THREAD

**Issue by vejuhust** [Python-Markdown/markdown#589]
e.g. Markdown input:

```markdown
* Item 1
  1. Hello
  2. World
* Item 2
  - Subitem A
  - Subitem B following:
    + What
    + The
    + Code
* Item 3 - yes! just a single item
```

GitHub's output:

```html
<ul>
    <li>Item 1
        <ol>
            <li>Hello</li>
            <li>World</li>
        </ol>
    </li>
    <li>Item 2
        <ul>
            <li>Subitem A</li>
            <li>Subitem B following:
                <ul>
                    <li>What</li>
                    <li>The</li>
                    <li>Code</li>
                </ul>
            </li>
        </ul>
    </li>
    <li>Item 3 - yes! just a single item</li>
</ul>
```

Python-Markdown's output:

```html
<ul>
    <li>Item 1</li>
    <li>Hello</li>
    <li>World</li>
    <li>Item 2</li>
    <li>Subitem A</li>
    <li>Subitem B following:
        <ul>
            <li>What</li>
            <li>The</li>
            <li>Code</li>
        </ul>
    </li>
    <li>Item 3 - yes! just a single item</li>
</ul>
```

Can you please fix this?

**Comment by facelessuser** [comment]
Did you indent 4 spaces? It looks like you did only 3.

**Comment by waylan** [comment]
The [documentation][1] states:

> * Indentation/Tab Length
> 
>     The syntax rules clearly state that when a list item consists of multiple paragraphs, “each subsequent paragraph in a list item **must** be indented by either 4 spaces or one tab” (emphasis added). However, many implementations do not enforce this rule and allow less than 4 spaces of indentation. The implementers of Python-Markdown consider it a bug to not enforce this rule.
> 
>     This applies to any block level elements nested in a list, including paragraphs, sub-lists, blockquotes, code blocks, etc. They must always be indented by at least four spaces (or one tab) for each level of nesting.
> 
>     In the event that one would prefer different behavior, [tab_length][2] can be set to whatever length is desired. Be warned however, as this will affect indentation for all aspects of the syntax (including root level code blocks).

It would appear that there is nothing for us to fix as you have only indented by 3 spaces. I would suggest following the rules and indent by four spaces.

[1]: https://pythonhosted.org/Markdown/#differences
[2]: https://pythonhosted.org/Markdown/reference.html#tab_length

**Comment by vejuhust** [comment]
@waylan @facelessuser  Thanks! I indented 2 spaces, replaced it with 4, works now.
