### ISSUE TITLE
Unordered lists require a newline before the first bullet point

### ISSUE THREAD

**Issue by sedrubal** [Python-Markdown/markdown#591]
This:

```py
markdown.markdown('''bla:
- bla''')
```

returns

```html
<p>bla:\n  - bla</p>
```

but I expected

```html
<p>bla:</p>\n<ul>\n<li>bla</li>\n</ul>
```

This works as expected:

```py
markdown.markdown('''bla:

- bla''')
```

**Comment by facelessuser** [comment]
From what I understand, this is expected, and will not change.  @waylan, can answer for sure.

**Comment by waylan** [comment]
@facelessuser is correct. To be clear, Python-Markdown is NOT a Commonmark parser. The Commonmark spec supports the requested behavior and acknowledges that that behavior is in conflict with the original Markdown rules. We follow the original Markdown rules. I'm quite happy with the company we share on [Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=bla%3A%0A-+bla)

**Comment by sedrubal** [comment]
Thanks for clarifying :wink:

**Comment by prestonraab** [comment]
Here's the Commonmark example for future reference: [https://spec.commonmark.org/0.31.2/#example-303](https://spec.commonmark.org/0.31.2/#example-303)

The Commonmark spec also provides a reason for the original Markdown behavior:

> Markdown.pl does not allow this, through fear of triggering a list via a numeral in a hard-wrapped line:
>
> The number of windows in my house is
> 14.  The number of doors is 6.

**Comment by josephbirkner** [comment]
It would be really good if there was an option to change this behavior, so the markdown rendering can be aligned with the one used by GitHub. Would a contribution for this be accepted @waylan ?

**Comment by facelessuser** [comment]
I think the general statement has been, we are not a CommonMark parser, but an old school parser. People are free to override the behavior with their own plugin if desired.

Personally, I think it is much more clear to separate lists from paragraphs, but I realize this is a subjective opinion.

**Comment by waylan** [comment]
Anyone is free to create an extension. So if you want a specific behavior, then you can create an extension which behaves that way. As I will never use the alternate behavior, it does not make sense for me to maintain it. Therefore, it is best as a third-party extension.
