### ISSUE TITLE
Code block in Django web renders bad

### ISSUE THREAD

**Issue by polrodoreda** [Python-Markdown/markdown#609]
I implement markdown in a django blog. All renders good except code block that, instead of:
```python
def hello():
    print 'Hello'
```
 is interpreted like:

:::python 
def hello(): 
print 'Hello'

What am I doing wrong? Or it is a bug?

**Comment by waylan** [comment]
I'm going to need a lot more info to help you with that. What does the original Markdown source text look like? What arguments are being passed to Markdown? What HTML is being output? What CSS rules are being applied to that HTML? 

I suspect that as you obtain that info, you will likely find the problem yourself. If not, please provide that info here as text in code blocks (not screenshots) and we'll help you work it out.

**Comment by polrodoreda** [comment]
Okey, Let me explain.
I installed markdown and pygments. Then I execute `pygmentize -S default -f html -a .codehilite > easydjango/static/css/custom.css` to create pygments css file.

I crete a templatetag like this:

```python
@register.filter
def markdownify(text):
    return markdown.markdown(text, safe_mode='escape', extension=['markdown.extensions.codehilite'])
```

After that I've experimented some issues.

If the source code looks like:

\```pyhton
def hello():
    print 'Hello'
\```

The output is: \```pyhton def hello(): print 'Hello'\```.

If the source code is:

    :::python
    def hello():
        print 'Hello'

The output will be (without codehilite classes):

:::python
def hello():
    print 'Hello'

**Comment by facelessuser** [comment]
Code blocks need to be indented.  Codehilite allows you to add a language header, but it still requires you to indent your code.

**Comment by polrodoreda** [comment]
Yes, I try it too and the response is the same as the last one I explain in the other comment

**Comment by facelessuser** [comment]
@polrodoreda, also it is `extensions` with an `s` for the parameter, not `extension`.

**Comment by polrodoreda** [comment]
Thank you!! What a big mistake. Sorry!

**Comment by waylan** [comment]
I see that you initially tried a fenced code bock:

````
```pyhton
def hello():
print 'Hello'
```
````

Note also that fenced code blocks are non-standard Markdown. If you want to use them, you need to enable the `fenced-code` extension as well.
