### ISSUE TITLE
Footnotes extenssion text not internationalised

### ISSUE THREAD

**Issue by jorgesumle** [Python-Markdown/markdown#610]
There is some text in English and no easy way to customize it. Concretely the text `Jump back to footnote %d in the text"` used in the `title` attribute in the content of the footnote.

I think the extenssion should detect the language of the user and use a corresponding string. The extenssion is assuming everybody speaks English and doesn't say anything about that in the readme. What do you think?

**Comment by facelessuser** [comment]
Yeah, I personally think there should be a way to customize it. 

> I think the extenssion should detect the language of the user and use a corresponding string.

I'm personally against such an approach as that pushes a bunch of logic into the extension that I think shouldn't be there.  I would argue that you should just be able to customize the string directly via an extension option.  That leaves it to the user to explicitly specify what they want instead of the extension trying to detect a language and look for the proper translation (which may not be available) etc.

**Comment by waylan** [comment]
I agree with @facelessuser. I'm not interested in maintaining a long list of translations. Adding an option for the user to provide their own string both addresses the need and matches the pattern used in other extensions. Of course, PRs are welcome.

**Comment by jorgesumle** [comment]
I've sent a pull request to @waylan. https://notabug.org/jorgesumle/markdown

**Comment by waylan** [comment]
@jorgesumle we follow the [GitHub workflow][1] (we review, commit on and have automated tests that run from GitHub PRs). Please submit your [Pull Request][2] here in GitHub.

[1]: https://help.github.com/articles/github-flow/
[2]: https://help.github.com/articles/about-pull-requests/

**Comment by jorgesumle** [comment]
> @jorgesumle we follow the GitHub workflow 

OK, I understand that. But note that I sent the pull request using a standard Git workflow that works for every platform, see the Git documentation: https://www.git-scm.com/docs/git-request-pull

I tried the GitHub way, but I got a weird error.

```$ hub pull-request -h Python-Markdown:master
Aborted: 1 commits are not yet pushed to jorgesumle/master
```

But as you can see the commit is here: https://github.com/jorgesumle/markdown

Maybe you can help me figure it out. Else you'll have to wait until I sort that out. GitHub is a pain in the ass. Maybe it's a [hub](https://github.com/github/hub) bug or I'm doing something wrong.

**Comment by jorgesumle** [comment]
> @jorgesumle we follow the GitHub workflow

OK, I understand and respect that. But note that I sent the pull request using a standard Git workflow that works for every platform, see the Git documentation: https://www.git-scm.com/docs/git-request-pull

I tried the GitHub way, but I got a weird error.
<pre><samp>$ hub pull-request -h Python-Markdown:master
Aborted: 1 commits are not yet pushed to jorgesumle/master
(use `-f` to force submit a pull request anyway)</samp></pre>

But as you can see the commit is here: https://github.com/jorgesumle/markdown

Maybe you can help me figure it out. Else you'll have to wait until I sort that out. GitHub is a pain in the ass. Maybe it's a [hub](https://github.com/github/hub) bug or I'm doing something wrong.

**Comment by waylan** [comment]
Hmm, `$ hub pull-request -h Python-Markdown:master` is not a standard git command so I'm not sure what you were trying to do. I just use standard git on the command line and push my changes to GitHub. The fact that I'm using GitHub is completely transparent, except that once GitHub sees a change to my personal clone, it offers to create a pull request (from the project's home page) which I do with only a couple mouse clicks.

In any event, I work on Python-Markdown in my spare time which is rather limited these days. I don't have time to go chasing suggested code changes elsewhere, especially for a feature I have no need for. I'm happy to incorporate the feature if you do the work. Or you will have to wait till I have the time and don't have anything higher on my priority list to work on.

**Comment by jorgesumle** [comment]
For the record, I could solve my issue following the [online documentation example of hub](https://hub.github.com/). The man page confused me a little bit.

Correction to myself, it should be 'extension' not <del>extenssion</del>
