### ISSUE TITLE
The following content is decoded incorrectly

### ISSUE THREAD

**Issue by ghost** [Python-Markdown/markdown#636]
* dddddddddddddddddd
    * hhhhhhhhhhhhhhhhh
    * uuuuuuuuuuuuuuuu

    1. ggggggggggggggg
    2. rrrrrrrrrrrrrrr
    3. yyyyyyyyyyyyyyyy

**Comment by mitya57** [comment]
You did not specify what output you get and what you expected. I assume that you expected a new list, but got the previous list continued. This is intended behaviour, as described [our documentation](https://python-markdown.github.io/#differences):

> **Consecutive Lists**
> 
> While the syntax rules are not clear on this, many implementations (including the original) do not end one list and start a second list when the list marker (asterisks, pluses, hyphens, and numbers) changes. For consistency, Python-Markdown maintains the same behavior with no plans to change in the foreseeable future. That said, the [Sane List Extension](https://python-markdown.github.io/extensions/sane_lists/) is available to provide a less surprising behavior.

Please use the mentioned extension if you want Python-Markdown to start a new list.

Also, please search for existing issues before filing a new one. This was discussed many times, at least in #64, #107, #175, #422, #547 and #612.
