### ISSUE TITLE
Limit the TOC level depth in extensions/toc

### ISSUE THREAD

**Issue by the9000** [Python-Markdown/markdown#637]
####  Use case
Take a document, such as an API description, or a document converted from Org mode, with lots of deep-level headers and very short texts under each of them.
A TOC of such a document becomes excessively long and detailed. (My particular case is what mkdocs generates.)

#### A fix
* Add a config parameter that optionally limits the maximum level of headers included in the TOC.
* Filter the levels [where they are generated](https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/toc.py#L242;) according to that parameter.

 I'll gladly make a PR, but would appreciate any advice on the best way to add a config parameter.

**Comment by waylan** [comment]
I'm sure this is a duplicate, but I can't seem to find it, In any event, we have traditionally been resistant to adding more config options. That certainly has been the stated reason for not yet adding this feature in previous discussions (which I can't find now).

Regardless, the TOC level depth is completely controlled by themes from within the templates. Our position in the past has been that you should be able to override this with [theme customization][1]. However, it occurs to me that as themes can now [define their own settings][2] (as of version 0.17), this could be user configurable as a theme setting. I would be willing to consider a PR which added a theme setting to both of the built-in themes.

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir
[2]: http://www.mkdocs.org/user-guide/custom-themes/#theme-configuration

**Comment by mitya57** [comment]
@waylan Did you realize that this issue is for Python-Markdown, not for mkdocs?

I know that you are a developer of both projects, so this can be quite confusing :)

**Comment by waylan** [comment]
Oh whoops. Thanks for the headsup @mitya57.

**Comment by waylan** [comment]
Interestingly, the OP made this statement:

> (My particular case is what mkdocs generates.)

So, in the end, I did point to the correct way to address this in MkDocs. Although, by default, the builtin MkDocs themes limit the depth to 2 so I'm not sure why you're having a problem with excessively deep TOC. If you are using a third-party theme, then take that up with the devs of that theme. Otherwise, you are free to submit a PR to MkDocs as stated above.

I'm not so sure I want to add that option to the Markdown extension.

**Comment by ghost** [comment]
It's quite common to use markdown headings for structure and viewability, including deeper level headings however in the TOC you may not want to call them all out.  I have a document that has H1-H6, but I only want to show the higher level headings in the TOC, h1-h4.

**Comment by RoyiAvital** [comment]
@bpaduch ,

I would go even farther.
I would like to set the range of headers (Namely also the minimum).  
As `H1` is usually dedicated to the document title there is no sense of having it in the Table of Content.
So I'd like option to choose `H2-H5` for instance.

**Comment by waylan** [comment]
@RoyiAvital that can be set with the [extension options][1]. Set `baselevel=2`. Or in a MkDocs config file do:

```yaml
markdown_extensions:
    - toc:
        baselevel: 2
```

[1]: https://python-markdown.github.io/extensions/toc/#usage

**Comment by ghost** [comment]
@waylan - I found the `baselevel` option doesn't actually limit headings but adjusts the headings, and essentially bumps them up so there is heading for that baselevel (just like in their example, a heading 1 and 2 becomes heading 3 and 4).

The same happens if I apply to my docs.  For example, in markdown I have:

```
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
```
What comes out is that the parser reformats the heading level and bumps them up a level, so that the desired `baselevel` isn't rendered.  

```
<h3>Heading 2 -> becomes heading 3
<h4> Heading 3  -> becomes heading 4
<h5>Heading 4 -> becomes heading 5
<h6> Heading 5 -> becomes heading 6
```

TBH, this is strange because now you have different heading levels from the actual markdown, and the contents for heading 2 still display, but now as an h3.

Maybe I'm interpreting incorrectly but that's the results that occur when I apply it.

**Comment by waylan** [comment]
@bpaduch my last comment was responding to @RoyiAvital's request which is different that yours. As I explained in previous comments, what you are requesting is not currently supported and I'm not inclined to add such a feature to the extension myself.

**Comment by RoyiAvital** [comment]
@waylan ,
I asked to be able to set a range of Headers (Say `H2-H5`) which will be shown in the Table of Content.
I don't understand how what you wrote does it.

**Comment by waylan** [comment]
@RoyiAvital you are asking for something different that the matter being discussed in this issue. If the comment I made doesn't address your issue, then please continue the discussion elsewhere.

**Comment by RoyiAvital** [comment]
The issue asks to have limit on the order of the header to be included in the generated Table of Content.
You can think as limiting it on one side.

All I asked is if someone puts effort in that he should have the option to limit form both sides.  
Namely only put in the Table of Content headers with number `minHeader` to `maxHeader`.  
For instance if `minHeaderLevel = 2` and `maxHeaderLevel = 4` then:

```
# Header Level 1 % Will be ignored
## Header Level 2 % Will be shown
### Header Level 3 % Will be shown
#### Header Level 4 % Will be shown
#### Another Header Level 4 % Will be shown
##### Header Level 5 % Will be ignored
```

**Comment by waylan** [comment]
Sorry @RoyiAvital I misunderstood your request. To me this whole request is not something I would ever want so when I saw your request I assumed you meant you wanted the `baselevel` feature.

**Comment by RoyiAvital** [comment]
I actually doesn't understand what's `baselevel` is.

What I want is not to include Level 1 Header (Single `#`) as use it for the document title.
From that I need to be able not to include too high levels (Like 5 `#` -> `##### Five Level Header`).

**Comment by waylan** [comment]
This appears to have been addressed with #686.

**Comment by RoyiAvital** [comment]
@waylan , could you explain what was done there?

**Comment by waylan** [comment]
@RoyiAvital a new config option was added: `toc_depth` which is documented [here](https://github.com/Python-Markdown/markdown/pull/686/files#diff-731fbc40acda2f8813e2f1b97f4c83c9R138).

**Comment by RoyiAvital** [comment]
@waylan , What about the option to set the first level to be included?

To make it more clear, I want the TOC to include only `<h2>` to `<h4>` (Where `<h2>` is the highest level).

**Comment by waylan** [comment]
@RoyiAvital that was not part of the original request, nor is it anything I have any use for, or am interested in having. Of course, if a PR is submitted I'll consider it.

**Comment by RoyiAvital** [comment]
@waylan ,
Are you OK with the case that you use `<h1>` for the Title of the Document yet it appears in the TOC?
Most TOC generators (See Word, Libre Office, Apple Write) exclude the document title from the TOC.
We can't do that in Python Markdown.

**Comment by waylan** [comment]
I use the meta extension and include the title of the document in the meta-data. My templates then insert that Title into the HTML separate from the body of my document which comes from the Markdown. Therefore, I never get the document title included in my TOC.

I work on Python-Markdown as a volunteer in my spare time and I don't have any reason to use up my spare time on features I have no use for. Therefore, if this is something you care about, you need to do the work. If someone submits a PR, I'll take the time to review it, and if it passes my review, I'll merge it. Other than that, I have more important things (to me) to work on.
