### ISSUE TITLE
Relative urls are mapped to None

### ISSUE THREAD

**Issue by micael-grilo** [Python-Markdown/markdown#645]
Hi, 

I don't know if this is a bug or if i'm doing it wrong, I need relative urls on markdown but they are being displayed as None.

![image](https://user-images.githubusercontent.com/9539326/36911153-944c4704-1e3a-11e8-9b33-6d980f117b82.png)

![image](https://user-images.githubusercontent.com/9539326/36911261-e6c26bee-1e3a-11e8-874f-8ac12f4bd655.png)

Regards,

**Comment by facelessuser** [comment]
You will have to provide more information as I suspect this has to do with something in your environment outside of Python Markdown.  Are you using some document generation software, because this is what I get:

```python
>>> import markdown
>>> markdown.markdown('[Local Administration](../topics/test/)')
'<p><a href="../topics/test/">Local Administration</a></p>'
```

**Comment by micael-grilo** [comment]
Yes, you are right. The issue was not on markdown but with bleach.linkify() that was transforming the awesome markdown work when we used relative links. Sorry for this misunderstood.
Thanks for your help, you can close this. :)
