### ISSUE TITLE
What's the easiest way to embed links in code blocks?

### ISSUE THREAD

**Issue by brian-armstrong** [Python-Markdown/markdown#646]
Hi,

First, thanks for maintaining this awesome project.

I'm cooking up some documentation for my project using mkdocs. I'd like to be able to link type names inside code blocks to their respective docs, e.g. `int foo(Bar bar);` would include a link on `Bar` to Bar's section in the docs. I already have the machinery in place to place the reference on `Bar`, and in non-blocks, this works fine using the standard `[]()` style markdown links. But in code blocks this doesn't work, of course.

Does this seem doable with a plugin? Do you have recommendations on the easiest way to do this? Do you know of any plugins that do this already?

Thanks!

**Comment by facelessuser** [comment]
Code highlighting is actually performed by Pygments when installed.  When Pygments is not installed, the content is wrapped in pre/code blocks and the content is escaped to allow for a JavaScript highlighter to handle the actual highlighting.

By injecting links before highlighting, you would most likely break many highlighter's ability to highlight that code. You could devise a way to highlight after the content has been converted to HTML, but that would have to occur via an extension, or some JavaScript library.  You could also augment an existing highlighter for your purposes that would highlight **and** linkify what you'd like as well.  All of this of course may be easier said than done.

**Comment by waylan** [comment]
I'm not aware of any extension (we don't call them plugins) which supports that. I would think the most likely solution would be to use a JavaScript based syntax highlighter. Some are more extendable than others. Unfortunately I can't make any specific recommendation as I've never had the desire or need for such a feature. As this is a support question rather than a bug report or feature request, I'm closing this.

**Comment by brian-armstrong** [comment]
For anyone who's curious, the easiest way to do this turned out to be modifying pygments behavior using http://mcs.une.edu.au/doc/python3-pygments/html/docs/filterdevelopment.html

Basically, if you want to attach links or change the formatting of items in code fenced blocks (with Pygments), you can just write one of these filters. You're getting a feed of tokens found by Pygments' lexers, and they have some vague token type information on them. In my case, I already have a dictionary of type names I want to generate links to, so my filter just checks each value in the stream for a match to one of my dictionary keys if the token type is a type name. My filter can then yield a new name that's actually a block of HTML encasing the name itself.

The other piece of the puzzle is bypassing Pygments' escaping. For that, I used the python markdown escape postprocessor. The escape postprocessor already runs, you just need to convince it to run on your name. So instead of `<a href="foo">`, concat `\u000260\u0003a href=\u000234\u0003foo\u000234\u0003\u000262\u0003'`, which will get unescaped later.

You have to add your filter to the lexer in markdown.extensions.codehilite. A good place for that is https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/codehilite.py#L117 where the lexer already exists.

Hope that helps someone else. Make cool docs :)
