### ISSUE TITLE
Feature Request: links inside code blocks

### ISSUE THREAD

**Issue by brian-armstrong** [Python-Markdown/markdown#647]
It'd be very handy to be able to create links inside code blocks. You can find plenty of examples of project docs that place links inside syntax-highlighted pre tags, e.g. code blocks, so it's certainly a common pattern. Python-markdown should add this handy functionality.

**Comment by waylan** [comment]
First of all, our code highlighting extension relies entirely on Pygments for highlighting. So any additions to that extension would need to be addressed upstream with Pygments.  Alternatively, this could be addressed in a third party extension which uses a different syntax highlighting implementation. Either way, I work on Markdown in my spare time as a volunteer and I have no need or desire for this feature. Therefore I have no motivation to do the work. The best way forward would be to develop this as a third party extension (whether it forks the included extension or starts fresh).
