### ISSUE TITLE
Including a `#!/usr/bin/env ...` breaks code block; doesn't render as expected. 

### ISSUE THREAD

**Issue by steve1281** [Python-Markdown/markdown#648]
Example below, first showing that situation where it fails, and another without the `#!/usr/bin/env ...` showing it working. 

Script:
```
Script started on Sun 11 Mar 2018 09:13:38 PM EDT

$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>> test = """
... ```
... #!/usr/bin/env xdg-open
... test 
...     test 
...     test
... ```
... """
>>> test
'\n```\n#!/usr/bin/env xdg-open\ntest \n    test \n    test\n```\n'
>>> m = markdown.Markdown()
>>> m.convert(test)
u'<p>```</p>\n<h1>!/usr/bin/env xdg-open</h1>\n<p>test \n    test \n    test\n```</p>'
>>> test2 = """
... ```
... test
...    test
...    test
... ```
... """
>>> test2
'```\ntest\n   test\n   test\n```\n'
>>> m.convert(test2)
u'<p><code>test\n   test\n   test</code></p>'
>>> quit()

Script done on Sun 11 Mar 2018 09:16:49 PM EDT

```

**Comment by facelessuser** [comment]
I'm not sure if you are reporting this issue because the first doesn't work or because the second one does work.

Personally, I find it odd that the second one does work.

The first one would work if you enabled `fenced_code` extension:

```py
>>> markdown.markdown(test, extensions=["markdown.extensions.fenced_code"])
u'<pre><code>#!/usr/bin/env xdg-open\ntest\n    test\n    test\n</code></pre>'
```

With that said, the second example shouldn't be working with fenced code disabled...

Maybe @waylan knows why the second example is working when it shouldn't?  I would think the second example to be a bug.

**Comment by waylan** [comment]
As @facelessuser points out, you need to enable the [fenced_code][0] extension. As a reminder, fenced code blocks are a non-standard feature of Markdown. Therefore, you don't get that feature by default.

The second example is correct in its behavior (see [Babelmark][1]). As a reminder, inline code spans can use any number of backticks as long as both the opening and closing set have equal length and are both within the same paragraph (the first example interprets the `#!` line as a header, breaking the single paragraph). Notice that the output does not include any `<pre>` tag. Therefore, the output includes an inline code span, not a code block. While the difference is subtle on the console, in the browser, it would be obvious as white space would be collapsed (line breaks and tabs would not be preserved).

I'm closing this as there are no bugs here.

[0]: https://python-markdown.github.io/extensions/fenced_code_blocks/
[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60%0Atest%0A++++test%0A++++test%0A%60%60%60

**Comment by facelessuser** [comment]
Inline span :facepalm:, it's so obvious now.

**Comment by steve1281** [comment]
Sorry, I was confused because it worked in a simple case, but not a more complicated one.

Sent from my iPhone

On Mar 11, 2018, at 22:47, Isaac Muse <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure if you are reporting this issue because the first doesn't work or because the second one does work.

Personally, I find it odd that the second one does work.

The first one would work if you enabled fenced_code extension:

>>> markdown.markdown(test, extensions=["markdown.extensions.fenced_code"])
u'<pre><code>#!/usr/bin/env xdg-open\ntest\n    test\n    test\n</code></pre>'

With that said, the second example shouldn't be working with fenced code disabled...

Maybe @waylan<https://github.com/waylan> knows why the second example is working when it shouldn't? I would think the second example to be a bug.

**Comment by facelessuser** [comment]
No worries.  I was a bit confused myself and thought there was a bug until waylan pointed out it was just an inline code block.
