### ISSUE TITLE
Additional paragraph if two consecutive lists are entered

### ISSUE THREAD

**Issue by jannschu** [Python-Markdown/markdown#649]
Input:
```
- A
- B

1. C
2. D
```

Output (indented):

```
<ul>
  <li>A</li>
  <li><p>B</p></li>
  <li><p>C</p></li>
  <li>D</li>
</ul>
```

Expected:

```
<ul>
  <li>A</li>
  <li>B</li>
</ul>
<ol>
  <li>C</li>
  <li>D</li>
</ol>
```

Wokraround:

Input
```
- A
- B

<!--fix-->

1. C
2. D
```

**Comment by facelessuser** [comment]
Please see existing issues: https://github.com/Python-Markdown/markdown/issues/636.

This is expected behavior, but [Sane Lists](https://python-markdown.github.io/extensions/sane_lists/) is most likely what you are looking for.

**Comment by jannschu** [comment]
Markdown biting me once again :-)

Thanks for the link, sorry for duplicate.
