### ISSUE TITLE
extensions: WikiLinks doesn't conform to its spec

### ISSUE THREAD

**Issue by raliste** [Python-Markdown/markdown#650]
[[Links/With/Subdir/Do/Not/Work]]

[[Links/With/Title|Neither]]

**Comment by facelessuser** [comment]
@raliste, please read the documentation to see what is supported: https://python-markdown.github.io/extensions/wikilinks/.

It does work as we do have tests that validate its behavior: https://github.com/Python-Markdown/markdown/blob/master/tests/extensions/wikilinks.txt.

If there are documented features that don't work, please provide clear examples and explain how you are attempting to use it.  Then we can look into an appropriate fix.

Keep in mind, this extension has been around for a while, and I don't think it is claimed anywhere that it is a 1:1 support for wiki links, only that it targets links in the style `[[My Wiki Link]]`.  If it is working as documented, but falls short of your desired features, it might be something to consider writing your own extension for as I'm pretty sure we are currently in a feature freeze for the time being until a 3.0 release.  At that time, extensions are planned (or at least where planned) to be split out into separate repos leaving core Markdown features being the only thing shipped by default.  All other extensions would be installed à la carte.   At that time new features might be considered. This plan may or may not still be planned, but in general, new features are on hold.

**Comment by waylan** [comment]
@facelessuser summed things up well. The WikiLinks extension is not intended to match the behavior of any spec from any wiki system. It is only expected to match its own documentation. If I were inclined to make any changes to the extension it would be to remove it entirely. As there are no reported bugs (differences between the documented behavior and actual behavior), I'm closing this as wontfix.
