### ISSUE TITLE
Multi-line code block does not work properly

### ISSUE THREAD

**Issue by yuuki0xff** [Python-Markdown/markdown#653]
I found an issue that [multi-line code block (fenced code block)](http://spec.commonmark.org/0.28/#fenced-code-blocks) does not work properly. This library should surround multi-line code with `<pre><code>` instead of `<p><code>`.

	#!/usr/bin/env python2
	import markdown
	m = markdown.Markdown()
	m.convert('''
	```
	line1
	line2
	```
	''')
	# expected result:  u'<pre><code>line1\nline2</code></pre>'
	# actual result: u'<p><code>line1\nline2</code></p>'

**Comment by mitya57** [comment]
You should enable the [`fenced_code`](https://python-markdown.github.io/extensions/fenced_code_blocks/) extension, which you have not done. Without that, your markup is treated as inline code.

**Comment by sovetov** [comment]
@mitya57 what's the rationale behind the decision not to make that the default behavior?

**Comment by facelessuser** [comment]
> what's the rationale behind the decision not to make that the default behavior?

It is not in the Markdown Specification: https://daringfireball.net/projects/markdown/syntax. Because it is not in the Markdown specification, it is an extension of the Markdown spec; therefore, it is an optional feature you can enable.
