### ISSUE TITLE
Smarty converts apostrophes into quotes

### ISSUE THREAD

**Issue by mayo** [Python-Markdown/markdown#654]
I seem to be getting apostrophes getting replaced with quotes. Eg:
```
there's one for the books... 'test'.
```
gets converted to 
```
<p>there&rsquo;s one for the books&hellip; &lsquo;test&rsquo;.</p>
```
In "there's", it's supposed to be `&apos;` rather than `&lsquo;`.

My configuration is:
```
md = markdown.Markdown(extensions=['markdown.extensions.smarty'], output_format='html5')
md.convert("there's one for the books... 'test'.")
```

**Comment by waylan** [comment]
AFAICT, Smartypants has never had support for apostrophes. The original project's [documentation] only mentions the following:

> SmartyPants can perform the following transformations:
> 
> * Straight quotes ( " and ' ) into “curly” quote HTML entities
> * Backticks-style quotes (``like this'') into “curly” quote HTML entities
> * Dashes (“--” and “---”) into en- and em-dash entities
> * Three consecutive dots (“...”) into an ellipsis entity

No mention of apostrophes. And you can test the reference implementation [here] and see the same behavior we have. I'm not inclined to add a feature not supported by the original.

[documentation]: https://daringfireball.net/projects/smartypants/
[here]: https://daringfireball.net/projects/smartypants/

**Comment by mayo** [comment]
I agree. Looking closer at the test case, what confused me is that the test case uses left (opening) quote in place of right quote. If I put in the proper quote, things appear as expected.

**Comment by mitya57** [comment]
> Looking closer at the test case, what confused me is that the test case uses left (opening) quote in place of right quote.

I do not see where it happens. In your output, it is `&rsquo;` which looks correct to me.

This line: `<p>there&rsquo;s one for the books&hellip; &lsquo;test&rsquo;.</p>` renders as:

> there&rsquo;s one for the books&hellip; &lsquo;test&rsquo;.

**Comment by mayo** [comment]
@mitya57 Sorry for not being more clear, I was referring to the Python-Markdown unit tests:

https://github.com/Python-Markdown/markdown/blob/a4d4b61b5ce4a7dd96ddc13c66b8716d3ad8eb51/tests/test_extensions.py#L894-L896 `right-single-quote` and `right-double-quote` as defined as left quotes.

**Comment by waylan** [comment]
@mayo those "substitutions" are only to test that setting custom substitutions works (some languages require different defaults). That test is **not** testing the default behavior. Which substitutions are actually used in that test are not significant in any way. The test passes as long as the substitutions set in the config options for that test are what is actually used in the output. The config options are defined in the [docs][0]. Note that the entity set for the `right-single-quote` substitution key is used for all right-single-quotes regardless of whether they are technically "apostrophes" or "quotes". SmartyPants simply does not differentiate between the two.

The tests for the default behavior are found in [markdown/tests/extensions/smarty.txt][1] and [markdown/tests/extensions/smarty.html][2].

[0]: https://python-markdown.github.io/extensions/smarty/#summary
[1]: https://github.com/Python-Markdown/markdown/blob/a4d4b61b5ce4a7dd96ddc13c66b8716d3ad8eb51/tests/extensions/smarty.txt
[2]: https://github.com/Python-Markdown/markdown/blob/a4d4b61b5ce4a7dd96ddc13c66b8716d3ad8eb51/tests/extensions/smarty.html

**Comment by mayo** [comment]
@waylan I understand, that's why I just closed the issue. With @mitya57 asking, I just clarified where my confusion came from. Thank you both for your time.
