### ISSUE TITLE
Inline footnote support

### ISSUE THREAD

**Issue by mustafa0x** [Python-Markdown/markdown#658]
Is there any interest in adding support for the inline footnote syntax (pandoc: `^[text]`, MMD: `[^text]`)?

**Comment by facelessuser** [comment]
There is already a supported footnote extension: https://python-markdown.github.io/extensions/footnotes/.  In general though, Python Markdown is meant to support the core Markdown functionality and it is encouraged that users write and support their own desired extensions for custom functionality.

**Comment by waylan** [comment]
No I do not have any interest in adding support. However, anyone is free to create their own extensions.
