### ISSUE TITLE
Markdown no longer rendered in exported HTML

### ISSUE THREAD

**Issue by tilusnet** [Python-Markdown/markdown#661]
This is broken, unfortunately python-marked documents cannot be shared with external audience due to this bug.

**Comment by facelessuser** [comment]
This is extremely vague. Python markdown is working for me and many, many people.  Most likely you have a local issue, but I cannot even begin to help without you providing details on how to reproduce the issue.

**Comment by tilusnet** [comment]
It surely works, except when the HTML is exported, what I said in the title.
Here's how I export: in the UI, select File, the Download as HTML. The exported HTML does not contain any rendered markdown, but the raw markdown.
I am realising I just paraphrased myself. Perhaps clearer still?

**Comment by facelessuser** [comment]
What UI? This is a command line script/ library.

**Comment by tilusnet** [comment]
Oh I see now why I was vague.
So I got directed to the wrong repo, sorry ─ I was probably meant to [look here somewhere](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/python-markdown).
