### ISSUE TITLE
Footnotes persisting through repeated use of Markdown instance

### ISSUE THREAD

**Issue by smari** [Python-Markdown/markdown#663]
Hi!
Most state clears, as it should, between `convert()` calls, but for some reason, footnotes persist. For instance:
```python
import markdown

m = markdown.Markdown(extensions=['extra'])
# (using 'extra' extension to make footnotes work; using 'footnotes' is sufficient though.)

t1 = """
This is a test. ["Testing is fun."][1].

 [^1]: It sure is!
"""

t2 = """
This does not contain footnotes.
"""

print(m.convert(t1))
print("----")
print(m.convert(t2))
```
Will output:

```html
$ python mdtest.py 
<p>This is a test. ["Testing is fun."][1].</p>
<div class="footnote">
<hr />
<ol>
<li id="fn:1">
<p>It sure is!&#160;<a class="footnote-backref" href="#fnref:1" rev="footnote" title="Jump back to footnote 1 in the text">&#8617;</a></p>
</li>
</ol>
</div>
----
<p>This does not contain footnotes.</p>
<div class="footnote">
<hr />
<ol>
<li id="fn:1">
<p>It sure is!&#160;<a class="footnote-backref" href="#fnref:1" rev="footnote" title="Jump back to footnote 1 in the text">&#8617;</a></p>
</li>
</ol>
</div>
```

Reinitializing the converter between calls works, but for my purposes that is a convoluted workaround.

Thanks!

**Comment by smari** [comment]
(fwiw, calling m.reset() between calls is also sufficient, but seems like it shouldn't be necessary)

**Comment by waylan** [comment]
This is  feature, not a bug. Suppose you had a blog with multiple posts on your homepage. Each footnote reference would need to be unique. If we completely reset the footnotes after processing each post, this would not be possible. However, the current implementation makes this work seamlessly.

Note that this is fully [documented][1]. Except for the rare circumstances where you do not want to "reset," it is expected that a call to `reset` be made between every call to `convert`. Note that using the `markdown.markdown` wrapper function gives you a new class instance each time it is called, so you get a fresh start with each call. In my experience, most people use the function and never encounter this issue. The class is at a lower level for more advanced usage and requires more effort (like calling `reset`) to use. 

[1]: https://python-markdown.github.io/reference/#convert

**Comment by smari** [comment]
Ah, okay. That sounds reasonable. Thanks!
