### ISSUE TITLE
LaTeX formula format support

### ISSUE THREAD

**Issue by yalunren** [Python-Markdown/markdown#665]
Is is possible to support the LaTeX formula? It will render text into formula. I see some markdown support this format. 

thanks!

e.g. http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference

**Comment by waylan** [comment]
LaTeX support is not a standard Markdown feature. In Python-Markdown many non-standard features are supported by extensions. If an extension exists, then you need to install and enable the extension. You should check the list of [third party extensions][1] to see if any exist which meet your needs.

[1]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
