### ISSUE TITLE
Git Repositories not Displaying Python Jypyter Notebooks for casual users

### ISSUE THREAD

**Issue by TheMitchWorksPro** [Python-Markdown/markdown#666]
If a user is logged out, and clicks on the link for the Jupyter notebooks on my project, the notebooks do not display.  It strikes me that people who come here looking for some of the samples of my project may or may not be logged in at the time.

If this is expected normal behavior feel free to close this issue and/or consider it as an enhancement request.  It would be good if users can always see what is in a public repo even if they are not specifically logged in.

If this is unexpected behavior, then that's why it is reported here as an issue.  Here is a sample link.  Log in and you can see it.  It previews nicely.  Log out and you can navigate my site between you get to this URL (for the notebook) it fails to load:

https://github.com/TheMitchWorksPro/DataTech_Playground/blob/master/PY_Basics/TMWP_Pandas_Dataframe_Basics.ipynb

**Comment by waylan** [comment]
GitHub does not use Python-Markdown and the developers of Python-Markdown have no affiliation with GitHub except that we use their services. Please report this issue to the appropriate GitHub project (sorry, I don't even know what that would be).
