### ISSUE TITLE
Double escaping of ampersand in URLs

### ISSUE THREAD

**Issue by letmaik** [Python-Markdown/markdown#669]
```py
>>> markdown.markdown('[title](http://example.com/?a=1&amp;b=2)')
'<p><a href="http://example.com/?a=1&amp;amp;b=2">title</a></p>'
```
The `&amp;` in the markdown should stay unchanged, which is what happens on https://daringfireball.net/projects/markdown/dingus:
```html
<p><a href="http://example.com/?a=1&amp;b=2">title</a></p>
```

**Comment by facelessuser** [comment]
This appears to be a bug as it conflicts with the reference implementation.

I think I have a solution for this.  I believe we should avoid escaping `&` in the serializer if the attribute is `src` or `href`.

**Comment by facelessuser** [comment]
Hmm. Looking at the reference again, I think we should instead just not convert `&` when part of `&amp;`.

**Comment by facelessuser** [comment]
Pull has been created for review.

**Comment by waylan** [comment]
I agree that our behavior differs from the reference implementation (and about half off the implementations on [Babelmark][1]). However, my initial inclination is to see this more as user error than a bug. The URL is still wrong regardless of whether we entity escape it or not. The user should probably be using URL encoding (`%26amp%3B`) which completely avoids this issue altogether. Why we don't currently auto-escape URLs was discussed in #270. Although, it appears we never fully resolved the matter there. I suspect this is a small edge case in a much bigger issue.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Btitle%5D(http%3A%2F%2Fexample.com%2F%3Fa%3D1%26amp%3Bb%3D2)

**Comment by facelessuser** [comment]
I think in way you are right with your statement that `&` should be percent encoded, but I also think our handling of them in this case is inconsistent with how they are handled elsewhere. I discuss this more in pull #670. My current approach is probably not correct, but I think it still could be solved in a sane manner as there are some cases, like our handling of `alt` for images that also suffers from double escaping which should not require percent encoding.
