### ISSUE TITLE
Meta extension does not reset attribute

### ISSUE THREAD

**Issue by Glandos** [Python-Markdown/markdown#671]
Hi,
Here is a test case:

```ipython
In [1]: from markdown import Markdown

In [2]: md = Markdown(extensions=['markdown.extensions.meta'])

In [3]: md.convert('''Title:   My Document
   ...: Summary: A brief description of my document.
   ...: Authors: Waylan Limberg
   ...:          John Doe
   ...: Date:    October 2, 2007
   ...: blank-value:
   ...: base_url: http://example.com
   ...: 
   ...: This is the first paragraph of the document.''')
Out[3]: '<p>This is the first paragraph of the document.</p>'

In [4]: md.Meta
Out[4]: 
{'title': ['My Document'],
 'summary': ['A brief description of my document.'],
 'authors': ['Waylan Limberg', 'John Doe'],
 'date': ['October 2, 2007'],
 'blank-value': [''],
 'base_url': ['http://example.com']}

In [5]: md.reset()
Out[5]: <markdown.Markdown at 0x7fc5a9b784e0>

In [6]: md.convert('''Title: Small doc
   ...: 
   ...: Content''')
Out[6]: '<p>Content</p>'

In [7]: md.Meta
Out[7]: {'title': ['Small doc']}

In [8]: md.reset()
Out[8]: <markdown.Markdown at 0x7fc5a9b784e0>

In [9]: md.convert('')
Out[9]: ''

In [10]: md.Meta
Out[10]: {'title': ['Small doc']}

```

A call to `reset()` does not remove the `Meta` attribute from the `Markdown` class. And since a call to `convert()` with an empty string does not call preprocessors (maybe it should?), the `Meta` attributes has invalid data.

**Comment by waylan** [comment]
Interesting edge case. I specifically recall looking at this before and determining that each call to `convert` would overwrite the meta data. Apparently I hadn't considered the case of an empty document. When `convert` detects an empty document, it immediately returns and does not run anything. Of course, that means it doesn't overwrite the meta data either.

**Comment by facelessuser** [comment]
What would need to happen is the `meta` extension should:

1. Register itself like the `footnotes` extension does: https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/footnotes.py#L70

2. Provide a reset method that clears `md.Meta`: https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/footnotes.py#L102.

3. A test case would also need to be provided.

This would get in fastest via pull request. If not, I may get around to looking at it mid to late July (if someone doesn't get to it before me 🙂 ).  The fix should be trivial.  If you are interested, I wold attempt a pull.

**Comment by Glandos** [comment]
I did all the PR using GitHub interface (after some tests on my machine) since I don't have push access from here. But it should be good.
