### ISSUE TITLE
Elusive documentation

### ISSUE THREAD

**Issue by kkroening** [Python-Markdown/markdown#674]
Where should someone go to figure out how to use this project? It's not at all clear from the top-level README since the mention of the `docs` directory is tiny compared to all the links pointing to the github-docs page.

The top-level README points to the github-docs page, which at best has an "Installation" section that says how to `pip install` it, and that's it.

Maybe the `docs` directory is the right place to look, but anyone coming to this project for the first time ends up going to the github-docs page and has no idea where to go, and will spend many minutes digging through there, clicking all the hyperlinks that lead to a rabbit hole of loosely related blog posts.

And when they come back to the README they'll be lucky to see the tiny `docs` mention, and then go there and be equally confused because they don't know which file to look at.

At least a "Hello world" in the README, or a pointer to the docs dir, or... something... _anything_ obvious that points someone in the right direction?

Even if I get this working and it's the best tool/library ever, I can't rightfully use it in a project or recommend it to anyone because they'll have no idea where to find API docs.

**Comment by kkroening** [comment]
In my view, [Basics](https://github.com/Python-Markdown/markdown/blob/master/docs/reference.md#the-basics) section should be one of the very first things anyone sees when they come across this project.

Maybe copy/paste that into the top-level `README.md`?

Just an idea, but I'm sure it would save a lot of people a lot of confusion.

Thanks.

**Comment by waylan** [comment]
I suppose we could add a "getting started" section to the front page of the documentation. However, I'm surprised you couldn't find what you wanted. From the "Installation" page, simply click "next" and you get [what you were looking for][1]. Continuing with "next" progressively takes you through all of the documentation in a logical manner. These pages are not "loosely related blog posts". In fact they are not blog posts at all but part of a step-by-step guide of carefully ordered pages. Or if you want to jump to a specific page, from any page click [index][1] in the top right corner and you get a list of all pages listed in order. 

As far as adding some documentation to the README, why would we want to maintain two copies of the documentation? The README points to the official documentation which contains all of the documentation for the project. Adding documentation to a separate location only confuses people as they don't know where to look. And if we miss updating one location for some future change, then the users are confused when the documentation at one location contradicts the documentation at another. Therefore, we only document anything in one location and that location is https://python-markdown.github.io/.

[1]: https://python-markdown.github.io/reference/
[2]: https://python-markdown.github.io/sitemap.html

**Comment by kkroening** [comment]
> From the "Installation" page, simply click "next" and you get what you were looking for.

Ok but notice how it's missing from the table of contents and how small the "next" buttons are, and outside the flow of the main articles they are (i.e. either on the sidebar or the top and bottom of the docs). Count the number of clicks it takes to get to any sort of hello-world. And that's assuming the user clicks all the right things and doesn't end up going to the "Extension API" or something like that because they're like "for the love of god just show me the API."

As you're someone familiar with the project you know exactly what to click to get to what you want, but it's another story for someone who hasn't seen it before.

It would probably be beneficial to watch someone check out your library who's never used it before: watch over their shoulder as they try to navigate the docs and don't give them any hints as to where to go, and then just see what happens.

Anyways, I guess this is just all my opinion so it's up to you to do what you want with this information, but I hope it's helpful/constructive feedback.

Thanks,
Karl
