### ISSUE TITLE
bare URLs in footnotes don't get autolinked

### ISSUE THREAD

**Issue by petermolnar** [Python-Markdown/markdown#678]
If there is a bare URL in a footnote, it doesn't get auto-linked, unless it's wrapped in <>. 

```python
import markdown

text = """
... Exercitationem nam ducimus consequatur aut porro vel. Corporis expedita necessitatibus rerum aut voluptas. Quia provident modi suscipit qui beatae. Hic quae tempora dolorum ut dicta vitae illo et. Voluptateset omnis est velit laborum at quidem[^1] qui.

[^1]: https://lipsum.com"""

markdown.Markdown(output_format='html5',extensions=['extra']).convert(text) 
```

```html                        
<p>Exercitationem nam ducimus consequatur aut porro vel. Corporis expedita necessitatibus rerum aut voluptas. Quia provident modi suscipit qui beatae. Hic quae tempora dolorum ut dicta vitae illo et. Voluptates
et omnis est velit laborum at quidem<sup id="fnref-1"><a class="footnote-ref" href="#fn-1">1</a></sup> qui.</p>\n<div class="footnote">\n<hr>\n<ol>\n<li id="fn-1">\n<p>https://lipsum.com&#160;<a class="footnote-backref" href="#fnref-1" title="Jump back to footnote 1 in the text">&#8617;</a></p>\n</li>\n</ol>\n</div>
```

It this expected behaviour or a bug?
If expected, can it be altered?

I'm aware it can be forced by adding <> around the link - that will render as URL. 
However, I'm migrating from Pandoc as my converter, and I'd prefer not to alter hundreds of files.

**Comment by petermolnar** [comment]
Not a bug, autolinking is not in extras, my bad.

**Comment by waylan** [comment]
Autolinking is not part of the [Markdown rules][1]. Some implementations have added that behavior, but a strict reading of the rules prohibits such behavior. I don't recall, but you may find a [third party extension][2] which adds that behavior to Python-Markdown.

[1]: http://daringfireball.net/projects/markdown/syntax#html 
[2]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions
