### ISSUE TITLE
Supporting namespaces in extension-output

### ISSUE THREAD

**Issue by GammaSQ** [Python-Markdown/markdown#679]
I want to implement a TeX to MathML parser as extension. It works fine if I use plain `<math></math>`-tags as extension-output. However, if I understood the specs correctly, MathML2 requires an `xmlns="http://www.w3.org/1998/Math/MathML"` attribute:
https://www.w3.org/TR/MathML2/chapter7.html
(It is never stated specifically weather the attribute is *required* or just *allowed*. MathML3 does not require this attribute in HTML-only context.)

The moment I add this attribute I get the following error:

    Traceback (most recent call last):
      File "test.py", line 3, in <module>
        print(markdown("$x^2$", extensions=[TeXExtension()]))
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/__init__.py", line 494, in markdown
        return md.convert(text)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/__init__.py", line 380, in convert
        output = self.serializer(root)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/serializers.py", line 282, in to_xhtml_string
        return _write_html(ElementTree(element).getroot(), format="xhtml")
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/serializers.py", line 203, in _write_html
        _serialize_html(write, root, qnames, namespaces, format)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/serializers.py", line 173, in _serialize_html
        items.sort(key=lambda x: x[1])  # sort on prefix
    AttributeError: 'dict_items' object has no attribute 'sort'

This is a [Python3-issue](https://stackoverflow.com/questions/28039155/dict-items-object-has-no-attribute-sortreplace-min), so I changed `items.sort( ` to `items=sorted(items, `, but now I get this error:

    Traceback (most recent call last):
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/__init__.py", line 384, in convert
        '<%s>' % self.doc_tag) + len(self.doc_tag) + 2
    ValueError: substring not found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "test.py", line 3, in <module>
        print(markdown("$x^2$", extensions=[TeXExtension()]))
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/__init__.py", line 494, in markdown
        return md.convert(text)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/markdown/__init__.py", line 394, in convert
        'tags. Document=%r' % output.strip())
    ValueError: Markdown failed to strip top-level tags. Document='<div xmlns:ns0="http://www.w3.org/1998/Math/MathML">\n<p><ns0:math display="block">\n<ns0:semantics>\n  <ns0:msup>\n    <ns0:mi>x</ns0:mi>\n    <ns0:mn>2</ns0:mn>\n  </ns0:msup>\n<ns0:annotations>x^2</ns0:annotations>\n</ns0:semantics>\n</ns0:math></p>\n</div>'

Since the `item.sort` call happens after an `if namespaces:`, I'm assuming there is a bigger issue regarding handling namespaces

For comparison, the MathML I'm returning from `handleMatch` (using `etree.fromstring(math)`) is:

    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
    <semantics>
      <msup>
        <mi>x</mi>
        <mn>2</mn>
      </msup>
    <annotations>x^2</annotations>
    </semantics>
    </math>

**Comment by waylan** [comment]
Interesting. I always anticipated someone might have a legitimate use for namespaces, but have never needed them myself. In fact, I left support in our custom serializer, which was adapted from the ElementTree library's standard serializer. Now, on to the issues you are having...

Yes, the `items.sort(...)` code needs to be updated for Python 3. All that is doing is ensuring the attributes are returned in the output in the same order every time. While not terribly important, it annoys users (especially when they don't understand that Python doesn't retain order in a dict) and it makes tests easier (which is the real reason). I'm surprised we haven't received a report before now. 

Your second issue appears to be related to the undocumented [stripTopLevelTags][1] attribute of `Markdown` class instances. That attribute is only referenced in [one location][2], immediately after the ElementTree object is sterilized to a string. A simple solution may be for your extension to set that attribute to `False`. However, I'd like for this to work without doing that.

For some background, Markdown does not have any concept of a root element as Markdown only ever produces an HTML fragment, never a whole document (therefore no `html` or `body` tags). The root of the document can contain multiple elements. This is direct conflict with ElementTree which requires a root element that then contains all of the multiple elements. Therefore, we set [Markdown.toc_tag][3] to a `div` and [use that][4] as a container for the rest of the elements. Then after the the document is serialized, that wrapping `div` element is striped from the output (unfortunately, ElementTree can't do something like `serialize(root.innerHTML)` so we fake it). Striping that wrapping `div` is where you are encountering your error as the `div` apparently includes an attribute identifying the namespace you used.

Setting the `stripTopLevelTags` attribute to False would cause the striping of the wrapping `div` to be skipped and avoid the error you are getting. However, the output would be wrapped in a `div`, which could be surprising (although not likely harmful). However, I'm not sure about where the namespace is defined and whether that is correct.

[1]: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L71
[2]: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L247-L260
[3]: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L26
[4]: https://github.com/Python-Markdown/markdown/blob/master/markdown/blockparser.py#L64

**Comment by waylan** [comment]
Note that in #643 we discuss removing the namespace support (`qname`) from the serializer. The stated reason is that no one ever uses it. Clearly that is not a correct assessment. However, after considering this issue, it seems that what is does is take any namespaces defined within the document and references them in the root element on sterilization. While that might make sense for XML, it does not for HTML fragments. Perhaps the solution is to remove the `qname` stuff from the serializer. Then any namespaces would simply be treated like any other HTML attribute and only ever be set on the element defined. Or does the namespace get set on the root when you create the child element with the namespace, in which case modifying the serializer would make no difference.

Having never needed namespaces myself, I'm not really sure what happens. It would be interesting to see some sample output with the `stripTopLevelTags` attribute set to `False`.

**Comment by waylan** [comment]
Note the last line of the error:

    ValueError: Markdown failed to strip top-level tags. Document='<div xmlns:ns0="http://www.w3.org/1998/Math/MathML">\n<p><ns0:math display="block">\n<ns0:semantics>\n  <ns0:msup>\n    <ns0:mi>x</ns0:mi>\n    <ns0:mn>2</ns0:mn>\n  </ns0:msup>\n<ns0:annotations>x^2</ns0:annotations>\n</ns0:semantics>\n</ns0:math></p>\n</div>'

Let's pull the string of HTML out of that message and prettify it:

```html
<div xmlns:ns0="http://www.w3.org/1998/Math/MathML">
    <p>
        <ns0:math display="block">
            <ns0:semantics>
                <ns0:msup>
                     <ns0:mi>x</ns0:mi>
                     <ns0:mn>2</ns0:mn>
                 </ns0:msup>
                <ns0:annotations>x^2</ns0:annotations>
            </ns0:semantics>
        </ns0:math>
    </p>
</div>
```

While that works for XML, that is not what we want for HTML. Altering the `stripTopLevelTags` behavior won't fix that problem (it actually makes it worse as `ns0` would no linger be defined). I suspect removing the `qname` stuff from the serializer will.

**Comment by waylan** [comment]
Okay, I did some testing. First I tried:

```python
def testNameSpace(self):
    div = markdown.util.etree.Element('div')
    math = markdown.util.etree.SubElement(div, 'math')
    math.set('xmlns', 'http://www.w3.org/1998/Math/MathML')
    math.set('display', 'block')
    sem = markdown.util.etree.SubElement(math, 'semantics')
    msup = markdown.util.etree.SubElement(sem, 'msup')
    mi = markdown.util.etree.SubElement(msup, 'mi')
    mi.text = 'x'
    mn = markdown.util.etree.SubElement(msup, 'mn')
    mn.text = '2'
    ann = markdown.util.etree.SubElement(sem, 'annotations')
    ann.text = 'x^2'
    self.assertEqual(
        markdown.serializers.to_xhtml_string(div),
        '<div>'
        '<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">'
        '<semantics>'
        '<msup>'
        '<mi>x</mi>'
        '<mn>2</mn>'
        '</msup>'
        '<annotations>x^2</annotations>'
        '</semantics>'
        '</math>'
        '</div>'
    )
```

And that passed just fine. Then I tried:

```python
def testNameSpace(self):
    div = markdown.util.etree.Element('div')
    qname = markdown.util.etree.QName('http://www.w3.org/1998/Math/MathML', 'math')
    math = markdown.util.etree.SubElement(div, qname)
    math.set('display', 'block')
    sem = markdown.util.etree.SubElement(math, 'semantics')
    msup = markdown.util.etree.SubElement(sem, 'msup')
    mi = markdown.util.etree.SubElement(msup, 'mi')
    mi.text = 'x'
    mn = markdown.util.etree.SubElement(msup, 'mn')
    mn.text = '2'
    ann = markdown.util.etree.SubElement(sem, 'annotations')
    ann.text = 'x^2'
    self.assertEqual(
        markdown.serializers.to_xhtml_string(div),
        '<div>'
        '<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">'
        '<semantics>'
        '<msup>'
        '<mi>x</mi>'
        '<mn>2</mn>'
        '</msup>'
        '<annotations>x^2</annotations>'
        '</semantics>'
        '</math>'
        '</div>'
    )
```

And that fails (the actual output is the same as in my previous comment). Notice that the difference is in the way the namespace was set. In the first example, the `xmlns` attribute was set on the `math` element, whereas in the second example, a `QName` object is used. 

On a more practical note, after a closer reading of the original report, I notice that the extension is generating the HTML (the `math` tag and its contents) as a string and then passing that to `etree.fromstring` to get the ElementTree object which is returned by the extension. As a workaround, I would suggest to instead pass the string to the [htmlStash][1] instance and return the placeholder. Markdown will then swap out the placeholder for the raw HTML after serizalation without trying to munge it up.

In case its not obvious by now, `etree.fromstring` is returning an element with a `QName` (same as the second example above) and that is what is breaking things. We should fix that, not by completely removing qname support from the serializer, but by changing the way they are handled by the serializer so that the second test above passes.

[1]: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L76

**Comment by GammaSQ** [comment]
Ad removing namespace-support and treating `xmlns="..."` as standard HTML tag:
For THIS specific problem, it would be the behaviour I expected. However, there is this option ['xhtml' as output_format](https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L37), and I never learned xhtml, so maybe special treatment would be required in that case? On the other hand I wouldn't know of a legitimate xhtml-usecase either.

Ad using the htmlStash: I'm not entirely sure how I would go about that? Do I get a `Markdown`-instance passed somewhere I'm not aware of? (currently inherit from `inlinepatterns.Pattern`, `handleMatch` produces the placeholder)

**Comment by GammaSQ** [comment]
Implemented the workaround. In case somebody else finds this helpful:
in the `extendMarkdown`-method, a `Markdown`-instance is passed as second argument. Passing that again as second argument to the `Pattern`-instance will make it available there as `self.markdown`, i.e.:

    class SomePattern(Pattern):
        def handleMatch(self, m):
            return self.markdown.htmlStash.store(stuff)

    class SomeExtension(Extension):
        def extendMarkdown(self, md, md_globals):
            md.someComplexPattern['name'] = SomePattern(r'pattern', md)

**Comment by waylan** [comment]
There are two ways to do namespaces in HTML. 

1. The first is directly borrowed from XML:

    ```html
    <html xmlns="http://www.w3.org/1999/xhtml"
       xmlns:mathml="http://www.w3.org/1998/Math/MathML"
       xmlns:svg="http://www.w3.org/2000/svg"
    >
    ...
    <mathml:math>
    ...
    </mathml:math
    ...
    <svg:svg>
    ...
    </svg:svg>
    ```

    In that case, all namespaces are defined on the `<html>` tag (with the first one being the default). Note that any non-default namespaces are also given a nickname (`mathml` and `svg` in the example above) and then that nickname is used elsewhere in the document to identify elements which belong to that namespace (`<nickname:tag>`). This is the current behavior of the serializer. However there are a few problems.

    As we output a HTML fragment, we have no way of defining the namespaces on the `<html>` tag. However, the serializer does define them in the wrapping `<div>`. A workaround could be to not remove the wrapping `<div>` if it defined namespaces. It would be slightly odd to have them defined there, but it would maintain consistency.

    Another option would be to require the user to include those definitions in the wrapping HTML they provide, in which case we would need to ensure we consistently assign nicknames to each namespace.   By way of explanation, the serializer includes a namespace_map, which contains a few well known namespace URLs and a common nickname for each. However, any unknown namespaces are names `ns{0}` where `{0]` is an incrementing number. If document one contains a MathML namespace first, if gets the `ns0` nickname while another document may get `ns1` for MathML as it contains a SVG namespace earlier in the document. To avoid that, we would need to provide a predefined nickname for every possible namespace. As users can define their own namespaces, that's not a reasonable solution.

2. The second way to use namespaces in HTML is as follows:

    ```html
    <html xmlns="http://www.w3.org/1999/xhtml">
    ...
    <math xmlns="http://www.w3.org/1998/Math/MathML">
    ...
    </math>
    ...
    <svg xmlns="http://www.w3.org/2000/svg">
    ...
    </svg>
    ```

    Note that while the above example includes the default namespace in the `<html>` tag, it can be omitted. In any event, each namespace is defined on its parent element. As no global nicknames are used, each fragment is a complete standalone object. And we don't need to worry about providing a 
consistent nickname.

In the end, we have three possible solutions:

1. Leave the serializer as-is but skip striping the wrapping `<div>` if it contains namespace definitions.
2. Alter the serializer to not assign nicknames to to namepsaces and leave each as a standalone fragment.
3. Leave defining the namespaces to the user (in their `<html>` tag) and use nicknames throughout the output, which limits us to only support known namespaces. 

I expect option 1 would be the least amount of work, but option 2 is what we should do.

**Comment by waylan** [comment]
FYI, option 2 has been applied in #681 and will be available in the next release.

**Comment by crisluengo** [comment]
I was having trouble copying SVG files inline into the ElementTree, because of the namespaces used. 
`xlink:href=...` kept being translated to `{http://www.w3.org/1999/xlink}href=...` in the HTML output generated by Markdown. I'm not sure why this is happening, I can't make sense of what happens in the serializer, but the `QName` code is not being triggered. Eventually I came to this issue. Great information here. 

`md.htmlStash.store(svg)` did the trick!

I would suggest to describe this in the documentation a bit. I'm sure I'm not the only one inserting raw HTML from a 3rd party tool into the ElementTree. `AtomicString` is mentioned, `md.htmlStash` is only listed in a list of "stuff you can access".

Many thanks for this wonderful tool!
