### ISSUE TITLE
python-markdown doesn't render any text after certain html elements

### ISSUE THREAD

**Issue by startling** [Python-Markdown/markdown#68]
Using python-markdown, anything after certain html elements will not render. The following example, 

```
<!-- comment -->
_italics_

__bold__
```

gets rendered as 

```
<!-- comment -->
_italics_

__bold__
```

without appropriately rendering the bold or italics into html. The Markdown reference implementation, `markdown.pl`, renders it as

```
<p><!-- comment -->
<em>italics</em></p>

<p><strong>bold</strong></p>
```

so I'm guessing it's a bug, not a feature. Note that this only happens when markdown text directly follows elements without an end tag. The following renders fine:

```
<b> html bold </b>
_hello_

__bold__
```

but this one doesn't:

```
<p>
_hello_

__bold__
```

This can be worked around by putting a blank line immediately after the html element. So, this one renders as expected:

```
<!-- comment -->

_hello_

__bold__
```

This is different from [issue #57](https://github.com/waylan/Python-Markdown/issues/57), which appears to have been solved.

**Comment by waylan** [comment]
Yes, the first example is a bug. Nothing else is though. Consider how a browser would consider this example:

```
<p>
_hello_

 __bold__
```

With no closing 'p' tag, the paragraph goes to the end of the document, just like in a browser. So, the text you think should be parsed as markdown is inside the 'p' tag and part of raw html and not parsed.

Oh, and yes, this is separate from issue #57, although not for the reason you would expect. Thanks for the report.

**Comment by startling** [comment]
Thanks!
