### ISSUE TITLE
is there a way to render math in toc?

### ISSUE THREAD

**Issue by Ir1d** [Python-Markdown/markdown#699]
Hi, I was trying to include math formula in toc, and I found that this feature was not included.

For example: `### $a_i$` would result in `a_ia_i` in the toc.

I opened a issue [here](https://github.com/squidfunk/mkdocs-material/issues/849) and realised that toc also doesn't support bold or italicize.

Wondering if this feature can be supported or is there a way to hack into this and include math in toc on my own?

Thx in advance.

**Comment by waylan** [comment]
This is directly related to #660. Our sanitizer is pretty dumb about how and what it removes from TOC items. It strips out everything except plain text.

There are some things we definitely want to have stripped (links for example), but it is not always clear. For example, I might want italics in my header, but not in the TOC item for that header. Whereas another person might want it preserved in both. And something like math is only supported through third party extensions. I would not expect the TOC extension to know how to handle math unless it provided a hook for the math extension to inform it. And I'm not sure what that hook might look like.

We could have a whitelist of elements to leave in. Or a blacklist of elements to strip. Ether way, in most cases when we strip an element, we preserve the text content of the element. However, in the case of #660, we not only need to strip the element tags, but also the content. The trick there is that we shouldn't just strip all `<sup>` elements, but only the ones which point to a footnote. That is a little more complicated than a simple list of elements regardless of whether it is a whitelist or a blacklist.

**Comment by waylan** [comment]
IIRC, MultiMarkdown provides a more sophisticated way of handling this stuff, and they support math. Or maybe its Pandoc that I'm thinking of. Perhaps we should investigate their behaviors.

**Comment by waylan** [comment]
@Ir1d would #700 be a reasonable solution for you? You can find the documentation [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).

I realize it is more of a workaround for you as you would need to manually define the text of the TOC item, but there are valid use cases for that outside of yours. Specifically, it solves the problem I have, which is demonstrated in the example in the docs.

The one limitation is that it only accepts plain text (Markdown syntax does not bet parsed). However, I believe that would not be a problem for you as your math should get passed through unaltered to be processed by a JS lib in the browser.

```md
### $a_i$ { #a_i data-toc-label="$a_i$" }
```

would result in the following TOC item:

```html
<li><a href="#a_i">$a_i$</a></li>
```

**Comment by facelessuser** [comment]
It depends on the method of translating math with the said JS lib.  For instance, the preferred way to insert math (if using MathJax) is using a script with type `math/tex`.  Plain text translations with the lib can sometimes be problematic.  If you are taking the script approach like the user above is using with `arithmatex`, plain text won't won't target as math as only script tags are being targeted.  I guess you could do both though.  I assume HTML cannot be passed via this method.

**Comment by waylan** [comment]
> For instance, the preferred way to insert math (if using MathJax) is using a script with type `math/tex`.

Ah, I missed that, I don't use math myself, so I don't always remember the details.

> I assume HTML cannot be passed via this method.

Actually it can:

```python
>>> import markdown
>>> t = """# $a_i$ { #a_i data-toc-label='<script type="math/tex">$a_i$</script>' }"""
>>> md = markdown.Markdown(extensions=['attr_list', 'toc'])
>>> md.convert(t)
'<h1 data-toc-label="<script type="math/tex">$a_i$</script>" id="a_i">$a_i$</h1>'
>>> md.toc
'<div class="toc">\n<ul>\n<li><a href="#a_i"><script type="math/tex">$a_i$</script></a></li>\n</ul>\n</div>\n'
```

The one thing I'm surprised about is that the content of the `data-toc-label` is not escaped when serialized. I was expecting `<h1 data-toc-label="%lt;script type="math/tex"%gt;$a_i$&lt'/script&gt;" id="a_i">$a_i$</h1>`.

I wonder if the TOC extension should remove the `data-toc-label` attribute after retrieving its contents?

**Comment by waylan** [comment]
> I wonder if the TOC extension should remove the `data-toc-label` attribute after retrieving its contents?

I did this in cd62333. Now the behavior is:

```python
>>> import markdown
>>> t = """# $a_i$ { #a_i data-toc-label='<script type="math/tex">$a_i$</script>' }"""
>>> md = markdown.Markdown(extensions=['attr_list', 'toc'])
>>> md.convert(t)
'<h1 id="a_i">$a_i$</h1>'
>>> md.toc
'<div class="toc">\n<ul>\n<li><a href="#a_i"><script type="math/tex">$a_i$</script></a></li>\n</ul>\n</div>\n'
```

It occurs to me that the "math" extensions could shortcut this for users. If math it in a header, the extension could potentially define a custom `data-toc-label` attribute on the header. Although, that should only happen if the `toc` extension is also enabled. And then there is the problem that inlinepatterns don't have access to the parent. Might be tricky.

**Comment by facelessuser** [comment]
> It occurs to me that the "math" extensions could shortcut this for users. If math it in a header, the extension could potentially define a custom data-toc-label attribute on the header. Although, that should only happen if the toc extension is also enabled. And then there is the problem that inlinepatterns don't have access to the parent. Might be tricky.

Maybe, maybe not.  I think with a treeprocessor, at least Arithmatex, should be able to inject these.  Just scan for script tags with the appropriate type, or in the case of the non-script format, look for the elements with the `arithmatex` class.  You just have to execute it before TOC's treeprocessor. Not sure if it would translate easily to all math extensions, it just depends how the extension is implemented.  I'd have to play around with this once it drops in a release to be sure though, this is just in theory.

**Comment by Ir1d** [comment]
Hi, I noticed that the PR mentioned above is now merged and released, thx!
btw, do you think it might be good to introduce into doc on how to use math in toc?

**Comment by waylan** [comment]
> do you think it might be good to introduce into doc on how to use math in toc?

That would be the responsibility of the math extensions.

And now that I took another look at this, it appears I mislabeled it yesterday. We have done all we can, any additional support is left to the third party extensions to implement.
