### ISSUE TITLE
pkg_resources can't find entry points with nosetests. but it can with unittest, noses

### ISSUE THREAD

**Issue by keenguy** [Python-Markdown/markdown#706]
I'm trying the **md3** branch...

When executing `nosetests` (actually, `nosetests markdown/test.py`) , the `pkg_resources.iter_entry_points` call in `build_extension` function of `markdown/core.py` can't find entry points for any extensions. But it works with unittest and nose2. Maybe it's a problem of **nose**...

I think those file tests are useful since they seems more extensive than those unittests.

**Comment by waylan** [comment]
The md3 branch is no longer being maintained. Any and all work in the md3 branch which is being retained has been merged with the master branch.
