### ISSUE TITLE
Issues with converting multiplied linebreaks

### ISSUE THREAD

**Issue by iamthen0ise** [Python-Markdown/markdown#707]
Hi!

It's seems like i can't convert double newline into markdown native format.

I need to wrap line like 
`Up/n/nDown`.

Expecting 
`<p>Up</p><br/><br/><p>Down</p>`

Got 
`<p>Up</p>\n<p>Down</p>`

My code:

```
import markdown


line ="Up/n/nDown"
markdown.markdown(line, extensions=['markdown.extensions.nl2br'])
```

Replacing `\n` with newline with two leading spaces returns the same result.

I will appreciate any assistance. 
Thank you!

**Comment by facelessuser** [comment]
This is exactly how it should work.  Blocks are separated by two new lines in Markdown:

```
I'm a
block

I'm a different
block
```

But what Markdown normally does when rendering in HTML is this:

```html
<p>I'm a block</p>\n<p>I'm a different block</p>
```

What `nl2br` does is turn **single** newlines **within** a block to `<br/>` (there may be `\n` in the actual HTML output, but I am just approximating):

```html
<p>I'm a<br/>block</p>\n<p>I'm a different<br/>block</p>
```

So in your example, you have two distinct, separate blocks, so no `<br/>` tags where injected, and you just get:

```html
<p>Up</p>\n<p>Down</p>
```

**Comment by waylan** [comment]
I agree with @facelessuser. 

If you want to include multiple blank lines within a single block (paragraph), then you would need to use raw HTML to insert the `<br>` tags yourself. Perhaps like this: `Up<br><br>Down`.

As there is no bug here, I'm closing this.
