### ISSUE TITLE
option to enable or disable only some tags support for markdown parser

### ISSUE THREAD

**Issue by rach** [Python-Markdown/markdown#71]
I have some case when I don't want to support all the markdown notation like '#' or others

**Comment by waylan** [comment]
This is a duplicate of #58.

You can use our Extension API to remove the various components of the markdown parser that you do not want.

As the requested behavior is already possible, I'm closing this.

**Comment by waylan** [comment]
Oh, sorry, met to link to the Extension API: https://github.com/waylan/Python-Markdown/blob/master/docs/writing_extensions.md

**Comment by rach** [comment]
Thanks a lot ... I will write the extension and close the fork that I started
Are you interest by the extension ?
