### ISSUE TITLE
3.0 lacks markdown.version

### ISSUE THREAD

**Issue by keenerd** [Python-Markdown/markdown#710]
In 2.6.11 (and older versions) one could `import markdown; markdown.version` and this is no longer present in 3.0: `AttributeError: 'module' object has no attribute 'version'`

Please add this to the [release notes](https://python-markdown.github.io/change_log/release-3.0/) if it was intentional.

**Comment by waylan** [comment]
This is a duplicate of #709.

**Comment by keenerd** [comment]
Apologies.  Didn't think to dig through the recent PRs.
