### ISSUE TITLE
markdown.version throws attribute error breaking Django Rest Framework

### ISSUE THREAD

**Issue by mlissner** [Python-Markdown/markdown#711]
Over in Django REST Framework, they have a library with the following code:

https://github.com/encode/django-rest-framework/blob/master/rest_framework/compat.py#L164-L172

Notably, it uses `markdown.version` to do some version sniffing. In 3.0, this throws an attribute error. 

Bugs:

 - Should this come back in 3.0.1, say?
 - I don't see this documented in the changelog.

It'd be great to see it coming back. Otherwise, I suspect the Django REST Framework folks will need to adapt to not use this attribute or catch it when it fails.

**Comment by facelessuser** [comment]
This is a duplicate of #709

**Comment by mlissner** [comment]
Thanks! I searched for an issue, but didn't find one. I guess this'll at least help the next couple people until it's released.
