### ISSUE TITLE
Hexadecimal HTML entities are not rendered

### ISSUE THREAD

**Issue by bs-jena** [Python-Markdown/markdown#712]
According to standard Markdown, HTML entities are to be recognized and rendered correctly (https://daringfireball.net/projects/markdown/syntax#autoescape). Up to v2.6.11, Python-Markdown has been able to do so, but with v3 it does not work any longer.

A hex HTML entity is not recognized. The leading ampersand is rendered as "`&amp;`", and in HTML, the entity consequently reads as the entity itself, like, for example `&#x25a0;` instead of the intended ■.

**Comment by mitya57** [comment]
`git bisect` tells me that this has been broken by #670 (commit 59406c41e7c3548d1c95a2091e2d676323494f62).
