### ISSUE TITLE
Missing markdown.version crashes other projects

### ISSUE THREAD

**Issue by kravietz** [Python-Markdown/markdown#716]
Until 2.6.11 the `markdown` module had `markdown.version` constant that is being used by a number of projects e.g. `django-rest-framework` to selectively enable/disable features. This constant seem to have been removed in 3.0 which causes these checks to fail and crash any application that uses upgraded `markdown` package.

**Comment by waylan** [comment]
This is a duplicate of #709, #710, #711, #714, #715...
