### ISSUE TITLE
Option for show label of language name in Codehilite

### ISSUE THREAD

**Issue by ngtrian** [Python-Markdown/markdown#720]
Like image

![image](https://user-images.githubusercontent.com/4327817/46258195-7fcaea80-c4f0-11e8-8abb-19c10efe90f1.png)

**Comment by waylan** [comment]
The HTML generated by the extension is whatever output Pygments gives us. If there are any changes to be made to the HTML, then that issue should be raised upstream with Pygments. If Pygments already offers such a feature and you would like us to add a setting for it, then please point us to the Pygments documentation for the feature and/or (even better) submit a pull request.

However, if the feature can be implemented simply with some CSS rules (without any changes to the HTML), then that is outside the scope of the extension as the extension does not provide any CSS. All CSS is the responsibility of the user.

**Comment by waylan** [comment]
This is being closed due to the lack of followup information.
