### ISSUE TITLE
genhtml third party extension to write markdown in python

### ISSUE THREAD

**Issue by Aluriak** [Python-Markdown/markdown#722]
[genhtml](https://github.com/Aluriak/genhtml-markdown) allows to write python code that will be executed at compile time, and its standard output will be copied in place, replacing the python code itself by either markdown or html.
I'm using it for auto-generating images and charts in my blog, or compile-time templating.
You can think of it as a reversed jupyter notebook.

You may want to include it in the third-party list of extensions.

**Comment by facelessuser** [comment]
You are free to edit the wiki and add 3rd party extensions. The wiki is maintained by the community.
