### ISSUE TITLE
Ignore h1 in the Table of Contents

### ISSUE THREAD

**Issue by lahwaacz** [Python-Markdown/markdown#724]
It is possible to limit the depth of the table of contents using the `toc_depth` parameter as well as to set the base level for sections using the `baselevel`. But I don't see how to skip the base level of sections in the table of contents, i.e. to ignore all `h1` sections in the toc. This is useful especially if the page has only a single `h1` title which represents the title of the whole page rather than a section title.

**Comment by waylan** [comment]
This is not supported at this time and I have no intention of adding support.

**Comment by Narann** [comment]
I search "python markdown toc exclude h1" on Google, fall here and read this.

So, just to say having an option to the `[TOC]` tag to skip `h1` would be useful to me.
