### ISSUE TITLE
Move defined block list to init

### ISSUE THREAD

**Issue by facelessuser** [Python-Markdown/markdown#730]
I believe we should move the block HTML list to the class init https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L55.

I believe much like the escaped character list, if plugins take advantage of this, it will modify the base class instead of the class instance.

I'm opening this issue to allow disagreement with this before I do the work.

**Comment by waylan** [comment]
> I believe much like the escaped character list, if plugins take advantage of this, it will modify the base class instead of the class instance.

You are correct. This could be a problem in multi-treadled environments, etc.
