### ISSUE TITLE
For compatibility with RMarkdown and bookdown support of ```{text, label-id}...``` is needed

### ISSUE THREAD

**Issue by N0rbert** [Python-Markdown/markdown#745]
I have a problem with labeled code fence blocks.
I'm using ReText 7.0.4 as pre-production environment for editing RMarkdown files with [bookdown extensions for custom blocks](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems). I tried to report the following [issue to the author](https://github.com/retext-project/retext/issues/405). And we closed this issue.

ReText uses Python-Markdown with all extensions as Markdown parser.

The simplest minimal working example is below:

<pre>
Code with label

```{python, label=first}
some
code
here

```

---

Code with extra fields

```{sh, echo=FALSE, comment=""}
some
code
here
```
</pre>

I have enabled `fenced_code` extension in ReText.

I found problematic zone in `fenced_code.py` file - it [is regular expression](https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/fenced_code.py#L38).

I suggest to rewrite it to the form `(\{?\.?(?P<lang>[\w#.+-]*))?([ ]*|[ ,="\w-]+)` to allow having `{language, code-label="", extra=""}`:

```
(?P<fence>^(?:~{3,}|`{3,}))[ ]*         # Opening ``` or ~~~
---> (\{?\.?(?P<lang>[\w#.+-]*))?([ ]*|[ ,="\w-]+)        # Optional {, and lang <---
# Optional highlight lines, single- or double-quote-delimited
(hl_lines=(?P<quot>"|')(?P<hl_lines>.*?)(?P=quot))?[ ]*
}?[ ]*\n                                # Optional closing }
(?P<code>.*?)(?<=\n)
(?P=fence)[ ]*$
```

I have tested it using [DebuggEx](https://www.debuggex.com/r/Aq53gOcXp0MXp4uq) and with my local ReText version. Now it renders the test document above as expected.

How do you think - is it possible to include this simple fix into your code?

**Comment by facelessuser** [comment]
The current `fenced_code` extension was a clone of PHP Markdown's Extra additions. It does not support commas between parameters as PHP Markdown did not either.  It is unlikey it will be changed to be a clone RMarkdown's behavior.

With that said, I have an extension [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) which allows you to create custom code blocks, and even add your own set of options, such as `label`. It's syntax is roughly the same as `fenced_code`. Speaking as the author of SuperFences, I have no intentions at this time of supporting the commas in the syntax over there either.

There is also the option of forking a suitable fence extension, add your functionality, and maintain it yourself. This is a perfectly reasonable option.  I am assuming ReText allows you to pull in custom extensions?  I haven't used ReText.

**Comment by N0rbert** [comment]
Thank you for reply!

From user point of view I can say that many other Markdown editors support the mentioned syntax. The example list is long: RStudio, GhostWriter, VNote, Typora, Formiko, MicroPad, Dellinger, CuteMarkEd, Marker. 
I understand that PHP Markdown is older than RMarkdown, but the latter is very powerful but lacks WYSIWYG Markdown editor.
ReText is great and with this simple one line patch it will become the most useful, fast and feature-rich Markdown editor.

I have already patched my locally installed Python-Markdown (dependency of ReText), but it would be great if you include my small change into the distribution. 
I still hope about this. Patching or forking is not a good solution for possible large audiences.

**Comment by facelessuser** [comment]
I don't think all of those do support that syntax. I just tried out Dillinger, and it treats `{sh}` as the `language-{sh}`. It doesn't properly parse it. Some may be passing the syntax through, but that doesn't mean it supports it.  What is the convert used in all of these?  And how do you know they all support Rmarkdown syntax properly?

**Comment by N0rbert** [comment]
I see you can't get me correctly. 
So I'll repeat the whole story. I'm using ReText which is based on Python-Markdown for pre-production of RMarkdown (+bookdown) documents. This means that I want to use all great WYSIWYG functionality of the ReText. So all syntactically correct objects should render correctly or as-is (or partialy, or dropped) if editor does not know about some RMarkdown/bookdown extensions. In this particular case the Python-Markdown do not know about extra fields in fenced code blocks. So I have expanded regular expression to support RMarkdown extensions. You can use aforementioned issue link to get screenshots.

About Dellinger I do not know how do you opened it, but my render is below, and it is correct.
![dellinger](https://user-images.githubusercontent.com/309456/47637897-1f21e280-db6e-11e8-84c6-efa2a25719d3.png)
About other editors - I have tested all of them on my big real RMarkdown document with headers, bold, italic, inline code, inline equations, numbered equations and labeled _code fence blocks_. Editors are usually based on Pandoc, CommonMark, MultiMarkdown, etc. The result of the comparison is that ReText is outstanding on all parameters.

I do not need parsing of code fence arguments, I need them to not to break the formatting of the document. Example of wrong formatting is below (Python-Markdown is not patched here):

![wrong formatting](https://user-images.githubusercontent.com/309456/47613808-79f00700-daa6-11e8-9884-b3ea77403a37.png)


After patching of Python-Markdown code ReText works as I expect (added `meta` extension to drop YAML-header lines):

![retext-fixed](https://user-images.githubusercontent.com/309456/47638566-f569bb00-db6f-11e8-97c7-3b7dbf23cfbf.png)

So I'll ask you again - please include my simple one line change to the Python-Markdown code. You can ask me to do comprehensive testing of it if not sure. 

The result would be great for both Python-Markdown and ReText end-users. From their point-of-view the manual patching will not be an option. They will install ReText with `pip3`, which will install all dependencies including Python-Markdown.

**Comment by facelessuser** [comment]
> I see you can't get me correctly.

I believe I really do.  I'm saying that what you are requesting breaks the spec on which the extension was built.  Your asking us to relax the spec on which the extension was built to still render code blocks that are syntatically incorrect. Am I wrong?

> About Dellinger I do not know how do you opened it, but my render is below, and it is correct.

Apologies, I apparently was looking at an online editor called `Dillinger`, not `Dellinger`, but either way, you've confirmed what I thought. These editors are based off very specific markdown converters which happen to convieniently render wrong HTML the way that suits your needs.

See results here (most that render a fence block with pre and code blocks either give very wrong classes, or straight up bad HTML): https://johnmacfarlane.net/babelmark2/?text=%60%60%60%7Bpython%2C+label%3D%22label%22%7D%0Aimport+test%0A%60%60%60%0A.

Keep in mind, I'm not the one who makes the final decision.  As a member on the team, I am merely expressing my opinion.  @waylan, will give the final word.  The advantage of Python Markdown is that it allows extensions.  I imagine that the official answer will be to write your own extension as this is a very niche need that breaks the specs on which the `fenced_code` extension was built.  But I will let him answer.

**Comment by waylan** [comment]
Our [Contributing Guide][1] states:

> Feature requests will often be closed with a recommendation that they be implemented as third party extensions outside of the core Python-Markdown library. Keeping new feature requests implemented as third party extensions allows us to keep the maintenance overhead of Python-Markdown to a minimum, so that the focus can be on continued stability, bug fixes, and documentation.

You are asking to support a new feature which I have no need for and no interest in maintaining. Of course, you are free to create any extension you want which has any behavior you want. And if you do so within the confines of the license, you can even fork the existing extension and modify it to meet your needs.

For the record, our implementation of fenced code blocks is a clone of [this][2] and anything in addition to that is outside the scope of the existing extension. In fact, many years ago, Michel Fortin and I developed that syntax together (with input from various members of the old Markdown mailing list) and released our implementations within a few days of each other (before any other implementations existed). As I see it, any variations of the syntax are unofficial variations. And any additions (such as r-markdown) should be implemented with some new different syntax. But that is my personal opinion. Of course, anyone is free to implement there own thing however they want. Just don't expect me to support it.

[1]: https://github.com/Python-Markdown/markdown/blob/master/docs/contributing.md#issues
[2]: https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks
