### ISSUE TITLE
Feature: local images as data URIs?

### ISSUE THREAD

**Issue by fengwang** [Python-Markdown/markdown#747]
Is is possible to convert a file `example.md` with code like this inside

`![](./0_8.png)`

to URI 

```
<img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAU0lEQVR4nAFIALf/AQAbOgv+8czlBC5F9Bso5Q/QAY/LcxoMDGYrBAQZ/a0SGB8MAgjpqvfGx9MNBO4ICPzs9f/zASdd/PQM9S2FAQAfYSr+35fiC0sfIOsGuCgAAAAASUVORK5CYII=" />
```

where image `0_8.png` is in a same folder as `example.md`.

For me, this feature makes a lot of sense to implement a local wiki without introducing external image links.

P.S.: I have implemented this feature in a dirty and quick way in [this repo](https://github.com/fengwang/markdown).

**Comment by facelessuser** [comment]
Something like this is well suited as a 3rd party extension. One such extension already exists: https://facelessuser.github.io/pymdown-extensions/extensions/b64/.

**Comment by waylan** [comment]
> Something like this is well suited as a 3rd party extension.

I agree.
