### ISSUE TITLE
Tables extension: proposal to support column spanning

### ISSUE THREAD

**Issue by Neepawa** [Python-Markdown/markdown#748]
I've migrated from  MultiMarkdown/cmark to Python Markdown due to its extensions API, which is missing from every other Markdown implementation I've encountered to date. Tables in other Markdown variants support the use of two or more "|" characters with no spaces between them to collapse columns, which in HTML is rendered with the _colspan_ attribute. I see this feature is missing from Python Markdown. 
While I believe I have the skills needed to implement this, I thought I would check with the community first to see if this is a desired feature. If so, I'll update the tables extension and submit a pull request.

**Comment by mitya57** [comment]
There is already at least one third-party extension for it, see https://github.com/Griffon26/mdx_spantables.

**Comment by waylan** [comment]
As @mitya57 stated, this can be implemented via a third party extension. Please see my response to #74 for a full explanation of my position on expanding the table syntax.

**Comment by Neepawa** [comment]
@mitya57: Thanks for the link to mdx_spantables. It's not in the list of [third party extensions][TPE], and I hadn't thought of searching all of GitHub for it. 

@waylan: Thanks for the explanation. Perhaps that comment could be included in the source code for the tables extension?

[TPE]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

**Comment by mitya57** [comment]
@Neepawa The wiki is editable by anyone so you can add it there.

**Comment by Neepawa** [comment]
Ah, thanks! I was thinking it was a README file, which meant updating it would require a clone, an update, and a pull request. It's not _really_ obvious the page is a wiki, aside from the text "Clone this wiki" on the right hand side, outside of the main text.
