### ISSUE TITLE
CODEHILITE - Feature Request - Lines highlighting

### ISSUE THREAD

**Issue by mantielero** [Python-Markdown/markdown#749]
It would be nice to support the following way of defining the lines to highlight:
```
   ```python {1,2,6-10}
```
This is how [markdown-it-highlight-lines](https://github.com/egoist/markdown-it-highlight-lines) does it. It looks shorter and support ranges.

**Comment by waylan** [comment]
We already support highlighting lines with `hl_lines="1 3"`. Note that everything within quotes is passed unaltered to Pygments. Therefore, supporting ranges is an upstream issue. I haven't checked recently, but I thought they did.

That said, you are free to create your own third party extension which implements whatever you want.
