### ISSUE TITLE
Prettier support

### ISSUE THREAD

**Issue by lydell** [Python-Markdown/markdown#751]
I know about #451 and about the following:

> https://daringfireball.net/projects/markdown/syntax#list
>
> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab

But not even the original markdown implementation follows that. Try pasting the following:

```md
- one

  two
```

…in https://daringfireball.net/projects/markdown/dingus. Result:

```html
<ul>
<li><p>one</p>

<p>two</p></li>
</ul>
```

And since then, [CommonMark](https://commonmark.org/) has gained popularity, and it allows fewer spaces:

> https://spec.commonmark.org/0.28/#example-219
>
> ```md
> - one
>
>   two
> ```
>
> ```html
> <ul>
> <li>
> <p>one</p>
> <p>two</p>
> </li>
> </ul>
> ```

And here’s the thing: [Prettier](https://prettier.io/) can auto-format markdown, and it uses CommonMark spec. Which unfortunately means that it turns more 4 spaces into the more good-looking 2 spaces:

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABNOAdKv0HowDuEIANCBAA4wCW0AzsqAIYBO7ExAChwsxSsAbhDoATCiABG7VmADWcGAGVq8ulADmyGOwCucSpsZx2MHnK0BbVsgBmrADanKAK0YAPAEJzFylVZrOAAZTTgHZ1cQdXZTdmQQW3YFcW4oKWp2TRgAdQkYAAtkAA4ABkosiFNcuWpErLh44QjKdjgAR306dstWGzskRxcjEFNrOl0DUcZNLSc4AEV9CHhIkcoYVml88SLkACZNuTonOYBhCGtbRKgsKX1TABVtwWHTAF8PoA)
```sh
--parser markdown
```

**Input:**
```markdown
- one

    two
```

**Output:**
```markdown
- one

  two

```

Which means that I cannot use Prettier to format markdown that will be parsed using this package :(

Would you be willing to reconsider this?

- Not even the original implementation follows the 4 space rule.
- Most markdown implementations don’t either.
- Being able to use Prettier would be awesome!

EDIT: This fixes the issue: https://github.com/radude/mdx_truly_sane_lists

**Comment by waylan** [comment]
> Not even the original implementation follows the 4 space rule.

I consider this a bug and will never be convinced otherwise.

> Most markdown implementations don’t either.

Those implementation also have a bug.

As an side, I do not consider CommonMark to be Markdown (but a derivative). Therefore, it is not relevant to this discussion.

> Being able to use Prettier would be awesome!

Great. Then you may implement your own extension which supports that syntax.

Finally, all of these points have been discussed with more detail elsewhere. Therefore this is a duplicate.

**Comment by lydell** [comment]
Thanks for answering!

> all of these points have been discussed with more detail elsewhere

Where?

EDIT: Here: #3, #125, #227, #313, #442, #451.

**Comment by lydell** [comment]
Also, just out of pure curiosity: What's the benefit of enforcing 4 spaces?

**Allow fewer spaces:**
Pros: Wide compatibility ([28 impls support it, 5 doesn't](https://johnmacfarlane.net/babelmark2/?normalize=1&text=-+one%0A%0A++two))
Cons: None?

**Enforce 4 spaces:**
Pros: ???
Cons: Worse compatibility

**Comment by mitya57** [comment]
Cons of fewer spaces are:

- Breaking compatibility. The existing documents will start to render differently.
- Breaking the Markdown specification, which is the first place to look at for syntax rules. The Markdown.pl implementation is only on the second place, we look there only if the spec is not clear enough.

**Comment by lydell** [comment]
Cool, thanks for the answer!

> Breaking compatibility. The existing documents will start to render differently.

Yeah, backwards compatibility is important. :+1:

> Breaking the Markdown specification, which is the first place to look at for syntax rules.

Even the HTML standard has made changes after de facto usage in browsers. ¯\\\_(ツ)\_/¯

Still, my question was what the _benefit_ of 4 spaces was. Is there any?

**Comment by facelessuser** [comment]
I can't honestly say there is a *benefit* to 4 spaces. It's just what the spec had said.  And now with a history of support for this behavior, it is hard to break it now.  This is a really a discussion of what is better as much as what the original spec indicated.  That is generally the aim of Python Markdown, that and the ability to easily extend it to whatever you want.

With that said, there is no reason you can't implement an extension to do as you desire. Even as a member of this team, I try not to push my personal preferred syntax, and instead keep it to my own [3rd party extensions](https://github.com/facelessuser/pymdown-extensions).

If you don't want to write your own extension, you may find that there is an extension for this already somewhere, I haven't looked.

As an alternative to writing your own extension, I've seen people mitigate the "ugliness" by indenting their lists two spaces so everything lines up:

```
  - List 1
  - List 2
    - Sub list A paragrah 1
       
       Sublist A paragraph 2
```

  - List 1
  - List 2
    - Sub list A paragrah 1
       
       Sublist A paragraph 2
 
Anyways, there are options available.

**Comment by lydell** [comment]
Thanks, I found an extension that works for me in one of the other 6 duplicates: https://github.com/radude/mdx_truly_sane_lists

I've made a PR to mention it in the docs: #752
