### ISSUE TITLE
Clarify in docs that high value corresponds to high extension priority

### ISSUE THREAD

**Issue by Griffon26** [Python-Markdown/markdown#755]
There are domains in software engineering where a high priority corresponds with a low value (interrupts, linux nice level, ...), so I think it's worth being explicit that a higher value corresponds to a higher priority.

**Comment by waylan** [comment]
We already [have the following][1]:

> When registering an item, a “name” and a “priority” must be provided. All items are automatically sorted by “priority” from highest to lowest.

Not sure how to clarify that any more. Unless you think we should add similar language elsewhere. A PR is always welcome.

[1]: https://python-markdown.github.io/extensions/api/#registry

**Comment by Griffon26** [comment]
No, this is the part I was talking about. I was unsure what it meant because the quotes around priority are essential for the meaning of the sentence (`"priority"` would refer to the parameter, while `priority` would refer to the concept). Without quotes it would not have been defined if low or high values correspond to higher priority.

I'd prefer it if the meaning was in the sentence structure and not in the quotes alone.

I was thinking about something like this:
> When registering an item, a “name” and a “priority” must be provided. All items are automatically sorted by the value of the "priority" parameter such that the item with the highest value will be processed first.

**Comment by waylan** [comment]
I'm sorry, but I understand those two sentences to be relaying the exact same information. Neither is more or less clear to me. However, I authored the first, so I may be biased. Maybe non-native speakers could struggle with it? In any event, as previously stated, a PR is welcome.
