### ISSUE TITLE
blank line in code blocks

### ISSUE THREAD

**Issue by renegat4** [Python-Markdown/markdown#758]
````python
import markdown

s = """ 
# Hallo, das ist ein Test

```
<html>
  <head></head>

  <body>
    <h1>Hallo</h1>
  </body>                                                         
</html>
```
"""

print(markdown.markdown(s))
````

The blank line between `</head>` and `<body>` breaks the output. HTML-characters are not converted to named entities ('<' becomes '&amp;lt;').

**Comment by waylan** [comment]
Fenced code blocks are not a standard feature of Markdown. You need to enable the [extension][1]:

```python
markdown.markdown(s, extensions=['fenced_code'])
```

[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/
