### ISSUE TITLE
CodeHilite extension attempts to highlight escaped characters

### ISSUE THREAD

**Issue by pigmonkey** [Python-Markdown/markdown#759]
A character like `>` gets escaped to `&gt;` via Markdown.

```
>>> import markdown
>>> text = """
...     :::bash
...     echo foo > bar.txt
...     """
>>> markdown.markdown(text)
'<pre><code>:::bash\necho foo &gt; bar.txt\n</code></pre>'
```

Which is fine, until I try to use CodeHilite.

```
>>> markdown.markdown(text, extensions=['codehilite'])
'<div class="codehilite"><pre><span></span><span class="nb">echo</span> foo <span class="p">&amp;</span>gt<span class="p">;</span> bar.txt\n</pre></div>'
```

It attempts to highlight the escaped character, turning `&gt;` into `<span class="p">&amp;</span>gt<span class="p">;</span>`.

I just noticed this behaviour after upgrading from markdown 2.6.11 to 3.0.1. I'm not sure if this new behavior is intentional and I just need to somehow alter my configuration to prevent it.

For now I have downgraded back to 2.6.11, which results in the expected behavior:

```
>>> markdown.markdown(text, extensions=['codehilite'])
'<div class="codehilite"><pre><span></span><span class="nb">echo</span> foo &gt; bar.txt\n</pre></div>
```

**Comment by facelessuser** [comment]
There are a number of duplicates of this: https://github.com/Python-Markdown/markdown/issues/746.  It has already been fixed on master.  Hopefully we will get a release soon.  As this is a sizable annoyance, I am hoping we don't prolong a release much longer.

**Comment by pigmonkey** [comment]
Thanks. I missed that issue. I'll wait for the next release.
