### ISSUE TITLE
Indented quotes in lists don't work

### ISSUE THREAD

**Issue by Koopiq** [Python-Markdown/markdown#761]
Hi. It's me again. I'm not sure if this is a bug since some markdown implementations have this behavior as well. But it does differ from Markdown.pl.

```markdown
- list
    > quote
```

Python-Markdown renders it as:

```html
<ul>
<li>list
    &gt; quote</li>
</ul>
```

While Markdown.pl renders it with a blockquote. [Here is Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+list%0A++++%3E+quote).

But it works fine with 2 spaces OR tab/3/4spaces + blank line before the quote:

```markdown
- list
  > quote 2 spaces (works)

---

- list

    > tabbed quote blank before (works)
```

**Comment by facelessuser** [comment]
>  I'm not sure if this is a bug since some markdown implementations have this behavior as well.

It is not a bug. This is a design decision that is well documented [here](https://python-markdown.github.io/#differences).
