### ISSUE TITLE
Add support for escaping trailing hashes in headers

### ISSUE THREAD

**Issue by facelessuser** [Python-Markdown/markdown#762]
Originally reported in MkDocs issue https://github.com/mkdocs/mkdocs/issues/1693.

**Comment by waylan** [comment]
I haven't tested it, but I'm assuming the [regex][1] should be modified as as follows:

```diff
- RE = re.compile(r'(^|\n)(?P<level>#{1,6})(?P<header>.*?)#*(\n|$)')
+ RE = re.compile(r'(^|\n)(?P<level>#{1,6})(?P<header>.*?)((?<!\\)#)*(\n|$)')
```

[1]: https://github.com/Python-Markdown/markdown/blob/e8e5a087ef9185aaf5d25ccfc9a18f06eac4e097/markdown/blockprocessors.py#L448

**Comment by facelessuser** [comment]
Yup, I was thinking something similar.  I'll run it through some tests and adjust if needed.

**Comment by facelessuser** [comment]
The pattern suggested above unfortunately still has issues: `r'(^|\n)(?P<level>#{1,6})(?P<header>.*?)((?<!\\)#)*(\n|$)'`. But the truth is I was expecting this issue just based on my experience with similar situations in the past:

![header-fix1](https://user-images.githubusercontent.com/1055125/49481210-1369b180-f7e7-11e8-9589-23730c4db879.png)

Most likely, I will use something like this: `(^|\n)(?P<level>#{1,6})(?P<header>(?:\\.|[^\\]+)*?)#*(\n|$)`:

![header-fix2](https://user-images.githubusercontent.com/1055125/49481243-3eec9c00-f7e7-11e8-8c6b-b861483f999a.png)
