### ISSUE TITLE
Insert an extension with a priority higher than...

### ISSUE THREAD

**Issue by sander76** [Python-Markdown/markdown#764]
Trying to use the `register` method instead of the `add` method in registering an inline extension.

This extension needs to have a priority higher than the "reference" extension.
However, I can't seem to find a proper way to get the `priority` value of the "reference" extension to register my extension with a higher value. I could get it using dunder properties, but I don't think that's the proper way..

Am I missing something ?

**Comment by waylan** [comment]
I'm not familiar with the "reference" *extension*. 

If the extension is a third party extension which has not yet been updated to use the new priority API, but still uses the old before/after syntax, then we find the priority of the patterns it goes between, and then split the difference between them to determine a priority to assign it. In other words, if it is to be inserted between patterns with priorities of `10` and `20`, it will be assigned a priority of `15`. Of course, if another extension takes the `15` priority first, then you may find something different.

If, instead you mean the "reference" *pattern*, all the patterns are assigned their priorities in the [source code][1]. The `reference` pattern has a priority of `170`. However, there is also [image_reference][2] (`140`) and [short_reference][3] (`130`) and I'm not sure which you need.

[1]: https://github.com/Python-Markdown/markdown/blob/master/markdown/inlinepatterns.py#L79
[2]: https://github.com/Python-Markdown/markdown/blob/master/markdown/inlinepatterns.py#L83
[3]: https://github.com/Python-Markdown/markdown/blob/master/markdown/inlinepatterns.py#L86

**Comment by sander76** [comment]
@waylan I'm mixing things up a bit. I mean the reference *pattern* . I'm working on an inline pattern which should have priority over the *reference* pattern. I used to be able to use the ```add``` method and provide a "<reference" keyword to have it priority over the reference pattern. I was looking to do the same with the now preferred ```register``` method.

**Comment by waylan** [comment]
I suspected as much. The last paragraph in my previous comment should have the information you need.

**Comment by sander76** [comment]
Thanks a lot!
