### ISSUE TITLE
wheel includes headerid.py

### ISSUE THREAD

**Issue by lazka** [Python-Markdown/markdown#765]
After updating some things to 3.0 I got  some weird mixed results with headerid.py missing on one machine and working on another.

Turns out the wheel build on PyPI still includes it while the source tarball doesn't. Is that on purpose?

**Comment by waylan** [comment]
Whoops. I must have built from a dirty clone. That extension is [deprecated][1] and should not be included.

[1]: https://python-markdown.github.io/change_log/release-3.0/#headerid-extension-deprecated

**Comment by lazka** [comment]
ok, thanks :) I'll give the toc extension a try

**Comment by waylan** [comment]
Fixed with the release of 3.1. See #809.
