### ISSUE TITLE
toc extension: allow toc_depth=0

### ISSUE THREAD

**Issue by lazka** [Python-Markdown/markdown#767]
After upgrading from 2.6.x to 3.x I was looking for a replacement for `['attr_list', HeaderIdExtension(forceid=False)]` and this seems to do the trick: `['attr_list', TocExtension(toc_depth=0)]`

The docs state that toc_depth should be >=1 and I also don't see this case in the tests, so I was wondering if it's safe to use this or if there is a better way:

```python
import markdown
from markdown.extensions.toc import TocExtension

text ="""\
# Some Header
# Header with ID # { #foo }"""

output = """\
<h1>Some Header</h1>
<h1 id="foo">Header with ID</h1>"""
html = markdown.markdown(text, extensions=['attr_list', TocExtension(toc_depth=0)])

assert html == output
```

Thanks!

**Comment by waylan** [comment]
For a Table of Contents to make any sense, every item must have an Id. Therefore, we do not support turning off Ids.

This is the one feature of the old headerid extension which does not carry through to the toc extension. Auto-generating Ids for headers which do not have them manually defined is harmless, so I see no need for the feature.

**Comment by lazka** [comment]
I'd like to avoid clashes between multiple rendered documents on the same page. But I guess it'll have to work.

Thanks for the clarification and the quick response!

**Comment by waylan** [comment]
> I'd like to avoid clashes between multiple rendered documents on the same page.

See the documentation for [markdown.Markdown.convert()][1]. Notice that you can create one instance of the `markdown.Markdown` class and pass multiple documents to it. If you do **not** call `reset` between converting documents, then the `toc` extension should ensure all headers are unique across all documents. In fact, that behavior was implemented specifically for this use case.

[1]: https://python-markdown.github.io/reference/#convert

**Comment by lazka** [comment]
Thanks!
