### ISSUE TITLE
`stashed_nodes` not present when running inline patterns early

### ISSUE THREAD

**Issue by timakro** [Python-Markdown/markdown#773]
I am writing an extension which runs existing inline patterns from a block processor (I know that sounds insane). Those inline processors use the `unescape` method which fails in my case because the `stashed_nodes` dictionary is not created yet at that time.

There is already [a check inside the `unescape` method to not fail in case the `inline` tree processor does not exist](https://github.com/Python-Markdown/markdown/blob/596be577c69c13ac3addcc84701e0a1014b088b0/markdown/inlinepatterns.py#L228-L231). This should be changed to also handle `AttributeError` as well.

I can open a pull request if that is desired.

**Comment by timakro** [comment]
Here is my extension which implements [Pandoc-style image captions](http://pandoc.org/MANUAL.html#extension-implicit_figures) with a current workaround for the problem.

```python
from markdown import util
from markdown.extensions import Extension
from markdown.blockprocessors import BlockProcessor


class FigureCaptionProcessor(BlockProcessor):

    def test(self, parent, block):
        for pattern_name in ('image_link', 'image_reference'):
            pattern = self.parser.md.inlinePatterns[pattern_name]
            m = pattern.getCompiledRegExp().match(block)
            if m:
                self.img_el, start, end = pattern.handleMatch(m, block)
                if start == 0 and end == len(block):
                    return True
        return False

    def run(self, parent, blocks):
        blocks.pop(0)
        el = util.etree.SubElement(parent, 'figure')
        el.append(self.img_el)
        caption_el = util.etree.SubElement(el, 'figcaption')
        caption_el.text = self.img_el.get('alt')


class FigureCaptionExtension(Extension):

    def extendMarkdown(self, md):

        # We are running inline patterns from a block processor before
        # intended. Those inline patterns check a placeholder dictionary which
        # is not yet created at that time. To avoid failure we create it here.
        md.treeprocessors['inline'].stashed_nodes = {}
        md.parser.blockprocessors.register(FigureCaptionProcessor(md.parser),
                                           'figure-caption', 15)
```

**Comment by facelessuser** [comment]
I'm not sure I understand why `stashed_nodes` needs to be changed.  Why don't you just derive your extension from the existing image inlinePattern, and override related methods to get your output, and then just replace the original image pattern in the inlinePatterns with yours.  You could even use a treeprocessor to add figures and figcaption after the fact in the element tree.

I don't so what the requested change adds to Python Markdown as a whole except to provide a workaround for a highly specific case that most people would never need.

Maybe I'm missing something?

**Comment by waylan** [comment]
I have to agree with @facelessuser. If you are doing inline processing, then do it with inline processing. Otherwise your code is going to need to adapt to work with what we have.

**Comment by timakro** [comment]
I tried your approach first @facelessuser but to get rid of the enclosing paragraph a block processor is required. Thanks for having a look though.

**Comment by facelessuser** [comment]
@timakro, use a treeprocessor and find all the links and see if they are the only child in a paragraph (I only briefly looked at the linked Pandoc feature). You should be able to analyze the image to determine if it needs a caption or whatever.  If you are concerned that you might grab a link that wasn't explicitly done via the markdown syntax, you could override the existing pattern and add a special attribute that you could look for in the treeprocessor.  That way you could know it was handled by the Markdown processor and not some alternative means.  You can modify the tree in the treeprocessor.  As I said, I think there are other ways to do this.
