### ISSUE TITLE
toc: toc_depth as range

### ISSUE THREAD

**Issue by klml** [Python-Markdown/markdown#786]
Currently [toc_depth](https://python-markdown.github.io/extensions/toc/) *defines up to which section level “n” ( \<h1> to <hn>, where 1 <= n <= 6) to include in the Table of Contents.*

Would be nice to have it not only defining *up to which* but *from and up to which* section level to include in the Table of Contents.
So you could include section level only from range ```h2``` to ```h6``` to the Table of Contents.

I could pass in a PR, should I change *toc_depth* to an array or introduce a new config value (e.g. *toc_height*)?

## use case
I want to use ```h1``` as sole [document title](https://www.w3.org/QA/Tips/Use_h1_for_Title) and so it should not be part of the ToC.

**Comment by waylan** [comment]
This may be a duplicate of #637. However that discussion took a lot of turns so it is unclear. Regardless, the [final comment][1] on that issue is relevant:

> I use the meta extension and include the title of the document in the meta-data. My templates then insert that Title into the HTML separate from the body of my document which comes from the Markdown. Therefore, I never get the document title included in my TOC.
> 
> I work on Python-Markdown as a volunteer in my spare time and I don't have any reason to use up my spare time on features I have no use for. Therefore, if this is something you care about, you need to do the work. If someone submits a PR, I'll take the time to review it, and if it passes my review, I'll merge it. Other than that, I have more important things (to me) to work on.

[1]: https://github.com/Python-Markdown/markdown/issues/637#issuecomment-408430235
