### ISSUE TITLE
clickable text URLs

### ISSUE THREAD

**Issue by sharpaper** [Python-Markdown/markdown#789]
How can I convert textual URLs to clickable HTML URLs? For example if I have a markdown `http://example.org` I'd like to convert it to `<a href="http://example.org">http://example.org</a>`.

Thanks.

**Comment by waylan** [comment]
The Markdown way to do this is to [surround the links with angle brackets][1]:

```md
<http://example.org>
```

However, if you want any plain text URL to be converted to a link, you can use an extension. I believe you can find one in the [list of third party extensions][2].

[1]: https://daringfireball.net/projects/markdown/syntax#autolink
[2]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions
