### ISSUE TITLE
support mail list times out

### ISSUE THREAD

**Issue by philbarker** [Python-Markdown/markdown#793]
README says:

> **Support**
> You may ask for help and discuss various other issues on the mailing list

I get a timeout error from the SourceForge url that links to. Does the mailing list still exist?

**Comment by waylan** [comment]
Sourceforge has dropped support for the list. We should probably remove the link to it. You can ask support questions here on GitHub.

**Comment by philbarker** [comment]
Thanks @waylan I was looking for feedback on an extension I written. Seems like more of a mail list request than a github issue, but if anyone has comments on https://github.com/philbarker/ocxsect I would welcome hearing them.
