### ISSUE TITLE
Unexpected behavior - markdown works/fails inside <details> block

### ISSUE THREAD

**Issue by craigphicks** [Python-Markdown/markdown#794]
Testing with 
    python3 -m markdown
no extensions.

This is a "doesn't work" example:
```
<details><summary>
## ng
</summary>
*test*
</details>

```
where the contents remains absolutely untranslated.  However this "works" example - 
```
 <details><summary>
## ok - indent 1
</summary>
*test*
</details>
```
is translated to 
```
<p><details><summary></p>
<h2>ok - indent 1</h2>
<p></summary>
<em>test</em>
</details></p>
```
Actually, I should qualify "works" to limit it Firefox v65.0 because I haven't tested other browsers.

Basically, placing a space ' ' in front of details results in some p-pairs strategically surrounding elements in such a way that markdown is willing to go in and translate where it felt inhibited to do so before.

I don't know if it's a bug or a feature but it is unexpected.

**Comment by facelessuser** [comment]
This should not work because Markdown in a block element is not parsed.

```
<details><summary>
## ng
</summary>
*test*
</details>
```

Really, you should have your block tags on separate lines, not mixed with `<summary>`. Anyways, you can read the docs on HTML blocks here: https://python-markdown.github.io/extensions/extra/#markdown-inside-html-blocks.  You shouldn't normally have content within parsed unless you use the `extra` extension.

Placing a space in front of `<details>` most likely throws off the HTML block recognizer which is why it then parses the content. Basically, since you aren't using the block HTML as defined in the spec, it treats it as inline content and wraps it in `<p>`.

**Comment by craigphicks** [comment]
Thanks for the information and pointer to documentation.
When you say 
<blockquote>
Really, you should have your block tags on separate lines, not mixed with &lt;summary&gt;
</blockquote>
do you mean in terms of markdown specs, HTML5 specs, or both?

Is it you conclusion that the behavior with a space before the block tag is unspecified and so cannot be relied upon long term?

Is this result, with the `<p>`-`<\p>` ranges half-overlapping the `<details>`-`</details>` range actually illegal HTML5?  (So it might fail in some browsers).

**Comment by craigphicks** [comment]
For the record, adding the `extra` extension, and adding attribues - 
```
<details markdown=1>
<summary markdown=1>
```
enabled translation of the body and the header respectively. So thanks!

**Comment by craigphicks** [comment]
This is a report on using the `extra` extension -
    python3 -m markdown -x extra
and formatting the tags thusly - 
```
<details markdown=1>
<summary>
### step 12
</summary>
... various markdown content and text ...
</details>
</details>
```

Nested `<details>` were included.

Results:
One set of nested blocks worked well.  Another failed miserably, making a terrible half translated mess. 

In comparison, the hack of putting a space ' ' before <detail><summary>  worked perfectly from the pint of view of completing all the markdown parsing at multiple nested levels.
(Whether the resulting HTML, with `<p>` half overlapping blocks, is legal and acceptable by all browsers is another issue.  Firefox and Chromium are OK as far as my testing went).

My gut feeling is that this problem (parsing in nested blocks) shouldn't be so hard - otherwise the space method wouldn't work so well so easily.

**Comment by waylan** [comment]
First, you need to include `markdown=1` on each nested level of raw HTML which you want Markdown to parse.

Second, please provide a minimum failing example of the source text, and the actual output you are receiving. It may also be helpful to provide the HTML output you expect.

**Comment by craigphicks** [comment]
The space-before-blocktag hack solution has the disadvantages of 
 - 1] producing doubtful HTML5 output, with `<p>`-`</p>` scopes half-overlapping other tag-pair scopes.
 - 2] depending upon the undocumented behavior of the markdown parser, which could change   

The `markdown.extra` and `pymdownx.extra` solutions requiring the notation
```
    <blocktag markdown=1>
    ... some markdown ...
    </blocktag>
```
has the disadvantages -
 - 1] sometimes not working, e.g. in the [simple example](https://gist.githubusercontent.com/craigphicks/105bc0bffd1728baf341fc3f0ad61ed9/raw) I posted to gist.  
 - 2] The [markdown documentation](https://python-markdown.github.io/extensions/extra/#markdown-inside-html-blocks) also describes many arbitrary limitations like not processing various tags, no more than one level nesting, and requiring extra blank lines.  (I think my gist reference example satisfied those limitations - so I don't know why it failed).

The solution I am using now is:
 - a) Manually mark the open and closing blocktags whose scope should be markdown processed by inserting an `@`-sign.
```
        <@blocktag>
        .... some markdown content ....
        <@/blocktag>
```
 - b) Use `sed` as a pre-markdown process to convert those tags to HTML comments 
 - c) Apply markdown, e.g., `python3 -m markdown -x pymdownx`
 - d) Use `sed` as a post-markdown process to convert those HTML comments back to tags.

The code is as follows - 
```
sed -e 's/^<@\([^>]*\)>[[:space:]]*$/<!--UNIQUEID<\1>-->/' ${rname} > ${rname}.tmp.1
python3 -m markdown -x pymdownx.extra ${rname}.tmp.1 > ${rname}.tmp.2
sed -e 's/<!--UNIQUEID\(<[^>]*>\)-->/\1/g' ${rname}.tmp.2 > ${rname}.tmp.3
```

From the POV of the markdown process 
 - All ignored tags are treated equally - they are ignored.  The onus is on the user to ensure the markdown is compatible with the block tag type.
 - nesting is not a factor for ignored tags

The UI disadvantage of this method is
 - 1]  It requires marking the opening and closing tags.  A parsing tree method like markdown ***should*** be able to do this only marking the opening tag, e.g. `<block-tag markdown=1>`.
 - 2] It isn't smart about ignoring span-tags if they are unnecessarily marked.  (Markdown already ignores span tags).  I'm not sure whether an ignored span tag could have side effects on the markdown processing of it's body - i.e., whether there are any cases where the processing is span-context dependent, but I think not.

The UI advantage of this method is
 - 1] `@` sign is easier to write than `markdown=1`.

*Note:* It's notable that the markdown process was observed to sometimes prefix a comment line with a `<p>`.  So it's possible that comments might influence the way markdown adds `<p>`s to the body.  
If so, that's a markdown problem.

**Comment by waylan** [comment]
You seem to be arguing for a different syntax for working with raw HTML. This is not up for debate. The existing behavior has been in place for over a decade and used by many thousands of existing documents. If you are reporting a bug, please provide the requested information. Otherwise, you are free to develop your own extension which implements whichever behavior you want.

**Comment by craigphicks** [comment]
> First, you need to include `markdown=1` on each nested level of raw HTML which you want Markdown to parse.
> 
> Second, please provide a minimum failing example of the source text, and the actual output you are receiving. It may also be helpful to provide the HTML output you expect.

@waylan - Thank you.  I did post [a minimal clip on gist](https://gist.githubusercontent.com/craigphicks/105bc0bffd1728baf341fc3f0ad61ed9/raw).  The top levels `##` section are parsed.  Of the nested level `###` sections, the first `###step 1` is parsed while the second `### step 6` fails.  It was tested with with both
```
python3 - m markdown -x extra 
```
and 
```
python3 - m markdown -x pymdownx.extra 
```
They both produced the same results. Notably it was processed correctly with the [pandoc test page](https://pandoc.org/try/) selecting `MultiMarkdown` as the input and HTML5 as the output.

**Comment by craigphicks** [comment]
> You seem to be arguing for a different syntax for working with raw HTML. This is not up for debate. The existing behavior has been in place for over a decade and used by many thousands of existing documents. If you are reporting a bug, please provide the requested information. Otherwise, you are free to develop your own extension which implements whichever behavior you want.

***No***.  Specifically I said:

> The solution I am using now as a workaround **until markdown has a viable solution** is ...

and I listed as a **disadvantage** that 

> It requires marking the opening and closing tags. A parsing tree method like markdown **should** be able to do this only marking the opening tag, e.g. `<block-tag markdown=1>`

So please ignore the **_syntax_** I am using and focus on the **_semantics_**.  The **semantics** here is the action of parsing markdown inside blocks which may be nested.

The syntax I used was chosen only to avoid having to implement a parsing-tree based solution.  The semantics **could** be implemented in your python markdown parsing tree framework using the standard 

    `<block-tag markdown=1>`

The work-around solution I posted defines a proposed *semantics* for `<block-tag markdown=1>`.  By posting working code for that *semantics* (albeit using a different and temporary *syntax*) I was able to make those *semantics* absolutely clear and understandable. (While saving myself some hours of getting up to speed on a tree-parsing solution framework - which is time wasted when I will ultimately switch to the viable python markdown solution when it is ready).

How about the **semantics** ?

**Comment by facelessuser** [comment]
Seems the comment is throwing it off:

```
<!------------------------------------------------- -->
```

There is nothing wrong with the convention we are using, but the HTML parsing portion of this library gets hung up on things.  We really need a rewrite of this area.

**Comment by craigphicks** [comment]
> Seems the comment is throwing it off:
> 
> ```
> 
> ```
> 
> There is nothing wrong with the convention we are using, but the HTML parsing portion of this library gets hung up on things. We really need a rewrite of this area.

Thank you for following through.

The `<block-tag markdown=1>` convention is set.  

I have a question about this part of your documentation:

> The content of any raw HTML block element can be Markdown-formatted simply by adding a markdown attribute to the opening tag. The markdown attribute will be stripped from the output, but all other attributes will be preserved.
> If the markdown value is set to 1 (recommended) or any value other than span or block, the default behavior will be executed: p,h[1-6],li,dd,dt, td,th,legend, and address elements skip block parsing while others do not. If the default is overridden by a value of span, block parsing will be skipped regardless of tag. If the default is overridden by a value of block, block parsing will occur regardless of tag.

That second paragraph is very hard to understand or remember. Going forward, why not define as:

tag\attr     |  no markdown attr | markdown=1 | markdown=0
------------ |------------------------|-------------------|-----------------
Block-tag  |    no                       |   yes              |  no
Span-Tag  |   yes                      |   yes              | no

Also this part of your documentation:

> **Nested Markdown Inside HTML Blocks**
> Nested elements are more sensitive and must be used cautiously. To avoid unexpected results:
>  - Only nest elements within block mode elements.
>  -  Follow the closing tag of inner elements with a blank line.
>  - Only have one level of nesting.

The terms *sensitive* and *cautiously* are ambiguous.  If they were used after a sufficient technical explanation, that would be acceptable.  For example, explain precisely the rules the user must obey then admit they are difficult.  

By nesting does it include nesting of markdown block functions, e.g. blockquote and code?  I often see emails and comments with multiple levels of replies.  On the other hand AFAIK code doesn't accenp further markdown.  Neither case can be described as a nesting level of 1.

How about inline markdown?  

If it applies also the html-block, that would be make working with nested `<article>`,`<section>`,and `<details>` impossible. 

So the meaning of nesting should be qualified.

**Comment by waylan** [comment]
>  I did post a minimal clip on gist.

Yeah I briefly looked at that, but it was way to long to easily see what the problem is. Please break it down into three simple code blocks here in a comment: one with the source text, one with the actual output and one with the expected output. There is no need for the long-winded explanations. The input and output should speak for themselves.

**Comment by craigphicks** [comment]
@waylan - Hi.  Assuming that the problem is as @facelessuser  postulates:

> Seems the comment is throwing it off:

then it is not necessarily easy to reproduce.  I used lots of comment lines in the original document (all idential) and it didn't stop at any of the earlier ones. 

It is in a nested location, and the documentation does say 

> Nested elements are more sensitive and must be used cautiously.
