### ISSUE TITLE
checkspelling.sh missing from release tarball

### ISSUE THREAD

**Issue by thmo** [Python-Markdown/markdown#808]
`checkspelling.sh` is missing from release tarball, but it is referenced from `tox.ini`.

**Comment by waylan** [comment]
Hmm, I didn't remember that tox.ini is included in the release tarball. But it is along with the rest of the tests. I suppose we should include the documentation spellchecker if we are including the rest of the tests.

**Comment by waylan** [comment]
Upon further reflection, we should remove tox.ini from the release tarball. IIRC, that was added back when we were using nose for tests and the env created by the tox config was necessary to get tests to run. Now we just use `unittest` in the standard lib with no need for env setup. Additionally, the [Contributing Guide][1] now discourages using tox locally in favor of letting Travis CI run the tests. `makefile test` does not even make use of tox anymore.

[1]: https://python-markdown.github.io/contributing/#development-environment
