### ISSUE TITLE
Linkable admonitions

### ISSUE THREAD

**Issue by majkinetor** [Python-Markdown/markdown#810]
More options to point users to specific parts of the page is always good to have.
It would be good to have an option to pass a link to concrete admonition section on a page.

Currently we have `class="admonition-title"` and some id would be enough - even sequential but even better to craft it like for markdown headers.

**Comment by waylan** [comment]
Admonitions are based on restructuredText Admonitions. If the upstream implementation supported such a feature, I would be happy to add it. However, that is not the case. Therefore, we will not be adding such a feature here. However, you are free to create your own extensions which offer whatever behavior you want. You may even fork the existing extension as long as your fork honors the rather permissive license.
