### ISSUE TITLE
Set output_format before registering extensions

### ISSUE THREAD

**Issue by Celelibi** [Python-Markdown/markdown#814]
As per issue #238, the output format is set after the extensions have been loaded. However, this prevent extensions from knowing the choosen output format during the registration.

How about setting the `output_format` attribute just before the extensions are registered? The call to `set_output_format` can be kept after the registration so that extensions can register new serializers.

**Comment by waylan** [comment]
> so that extensions can register new serializers

I don't know that we ever contemplated supporting this. I've always assumed serializers would be added in a subclass, in which case extensions woudln't need to know or care about the output format. I'll have to think about this.

**Comment by waylan** [comment]
Extensions should never assume the output_format set at registration time is the format which will be used. For example a user could do:

```python
md = markdown.Markdown(extensions=['someext'])
md.set_output_format('html')
md.convert(src)
```

Therefore, if an extension's behavior should change based on output format, the extension should always check that at run time. As we provide a mechanism for the `Markdown` instance to be available to the extension, that is not difficult to do. I'm closing this wontfix.
