### ISSUE TITLE
SEPARATOR default in footnotes causes force reloading in IE11

### ISSUE THREAD

**Issue by tailriver** [Python-Markdown/markdown#819]
I found this issue on https://github.com/squidfunk/mkdocs-material/issues/1083 .

Can its default (`:`) change to other character (e.g. `_`) in future version?

**Comment by facelessuser** [comment]
You can change via the `SEPARATOR` option: https://python-markdown.github.io/extensions/footnotes/#usage.

**Comment by tailriver** [comment]
Thank you for your quick reply.
I would like to ask if there is a possibility of changing the default value to be suitable for almost all browsers.

**Comment by waylan** [comment]
For the record, Markdown generates the following HTML to represent a link to a footnote:

```html
<sup id="fnref:1"><a class="footnote-ref" href="#fn:1">1</a></sup>
```

And then the footnote itself is contained in a list item like this:

```html
<li id="fn:1">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.&nbsp;<a class="footnote-backref" href="#fnref:1" title="Jump back to footnote 1 in the text">↩</a></p>
</li>
```

So that the link points to `#fn:1` and the footnote links back to the link with `#fnref:1`.

If I understand correctly, the colons being in a URL hash breaks IE11? Can to provide a link to a report about this issue in IE11? I find it odd that this is the first report of the issue as we have been using a colon as the default for many years now.

**Comment by waylan** [comment]
I had forgot about #723. And in that issue I had forgotten about earlier changes. In any event #723 explains how we got to the current state. My inclination is to leave things as-is. You can always change the default with the setting, which is why we added the setting.

**Comment by tailriver** [comment]
I confirmed this behavior by https://squidfunk.github.io/mkdocs-material/extensions/footnotes/ at two independent PC. However, I agree that you feel odd.

> the colons being in a URL hash breaks IE11?

No. Simple HTML like below works as expected.

```html
<html>
<body>
<p><a href="#fn:target">link</a></p>
<div style="height:1000px">...</div>
<p id="fn:target">target</p>
</body>
</html>
```

Although I post this issue here by suggestion from mkdocs-material owner, I don't know which is the true cause.

**Comment by squidfunk** [comment]
I’ve dug into the [corresponding RFC](https://tools.ietf.org/html/rfc3986#section-3.5) which says that `:` is a valid hash fragment character indeed (see section 3.3 for the definition of `pchar` in the formal syntax). I’ve found no futher evidence that this seems to be a widespread problem. Now, as it’s non-standard behavior and IE is a discontinued browser, I would also suggest leaving it at `:`. I will bump Python Markdown to `3.x` for Material, so the separator can be used for configuration.

**Comment by squidfunk** [comment]
@waylan I looked at your `requirements.txt` and it defines `Markdown>=2.5` as a dependency. With my limited Python skills, I would assume that it would automatically install the latest version, i.e. 3.1, correct? I guess it would make more sense to leave the dependency out of Material.

**Comment by waylan** [comment]
@squidfunk your assumption is correct. I don’t see any reason for a theme to define a Markdown dependency separately from MkDocs.
