### ISSUE TITLE
Codehilite - Failed HTML escaping

### ISSUE THREAD

**Issue by ekaitz-zarraga** [Python-Markdown/markdown#821]
Hi,

I found an issue in Codehilite extension via Pelican. I tried to test if it failed here but I'm unable to run the code on my machine.

This is the issue I found:
https://github.com/getpelican/pelican/issues/2569

The easy way to test this is to create a Codehilite test with a, for instance, `<` inside and call it with pygments disabled. If it creates a `<pre><code>` block with the `<` converted to `&lt;` the error is present.

I'd like to solve it by myself but I've been unable to run the tests on my machine.

**Comment by facelessuser** [comment]
You didn't post what version of Python Marion you are using. Can you confirm the version?

**Comment by ekaitz-zarraga** [comment]
I rechecked versions. It was failing in 3.0 but in 3.1 is solved. Not your issue anymore, time to push Pelican to 3.1 I think.

Sorry for the noise.

**Comment by facelessuser** [comment]
Yup, it was a known issue that I specifically fixed, that's why I was curious about the version :slightly_smiling_face: .

**Comment by ekaitz-zarraga** [comment]
Thank you for your time! :smile:
