### ISSUE TITLE
TOC: Support HTML H* elements

### ISSUE THREAD

**Issue by balupton** [Python-Markdown/markdown#829]
Currently the TOC completely falls over if the markdown document has HTML H* elements, such as `<h1 id="header-1">Header 1</h1><h2 id="header-2">Header 2</h2>`.

For my particular use case, I have one markdown file that is generated HTML code from API documentation, that we want rendered into the rest of the documentation - it renders fine - but no TOC.

**Comment by waylan** [comment]
While I understand the desire for this feature, it would be extremely difficult to implement given how the raw HTML is handled. Personally, I have no interest in doing the work. Therefore, I am closing this as something which can be implemented as a third party extension.
