### ISSUE TITLE
Feature request: Poetry extension

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#83]
There should be a way to insert blocks of text where the newlines will be converted to `<br>` tag (or `<br />` for xhtml).

Example:

```
~~~
Line 1
Line 2

Line 3
Line 4
~~~
```

should result in

```
<p>Line 1<br>
Line 2</p>

<p>Line 3<br>
Line 4</p>
```

This is useful for poetry, for example; I guess this should be an extension rather than a core functionality. Of course, other formatting in such blocks should be possible as well, so code blocks can't be used for such purpose.

`~~~` is just an example marker, I think it's already used for something.

**Comment by waylan** [comment]
This already exists as the [NL2BR extension](http://packages.python.org/Markdown/extensions/nl2br.html) which has been included with Python-Markdown since the 2.1.0 release.

**Comment by mitya57** [comment]
@waylan: That's for the whole document, it will be good to have an ability to get some **parts** of the document rendered in such way...

**Comment by waylan** [comment]
I have no need for such an extension myself and have limited volunteer time. I certainly won't be implementing such an extension myself. Of course, you are welcome to do so, but even then, why should it be included with the markdown library? Is there other markdown implementations which ship with such a feature? Do we have a precedent here?

My suggestion would be for you to develop a third party extension (see the [docs](http://packages.python.org/Markdown/extensions/api.html)) and host it externally (listing it on the [wiki](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions)) and if it becomes popular, I'll reconsider including it at that time.

**Comment by davidchambers** [comment]
Two trailing spaces produces a line break in the HTML output:

``` pycon
>>> import markdown
>>> print markdown.markdown('foo  \nbar\n\nbaz')
<p>foo<br />
bar</p>
<p>baz</p>
```

Out of interest, [GitHub Flavored Markdown](http://github.github.com/github-flavored-markdown/) treats every newline as a line break.

**Comment by mitya57** [comment]
Thanks @davidchambers! This will suit me.
