### ISSUE TITLE
code blocks with multiple lines does not work

### ISSUE THREAD

**Issue by sebbekarlsson** [Python-Markdown/markdown#842]
The ones with three ` signs

**Comment by waylan** [comment]
Did you enable the [fenced code extension][1]? As a reminder, fenced code blocks are not part of standard Markdown and therefore are not enabled by default.

[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/

**Comment by sebbekarlsson** [comment]
So, how do I install it?
i am getting:
```AttributeError: 'module' object has no attribute 'fenced_code'```

when doing `markdown.extensions.fenced_code`

**Comment by waylan** [comment]
The extension is installed with Markdown. Could you show us the code you are using which is returning that error?

**Comment by sebbekarlsson** [comment]
Here is the code:
```import os
import glob
import markdown
import ntpath


class Post(object):

    def __init__(self, post_stamp):
        self.post_stamp = post_stamp
        self.filename = os.path.join('posts/{}.md'.format(post_stamp))
        self.contents = markdown.markdown(
            open(self.filename).read(),
            extensions=[markdown.extensions.fenced_code.FencedCodeExtension()]
        )

**Comment by waylan** [comment]
Try using the string `'fenced_code'` which is the named entry point:

```python
extensions=['fenced_code']
```

**Comment by sebbekarlsson** [comment]
Thank you, that works
