### ISSUE TITLE
Include example JSON configuration

### ISSUE THREAD

**Issue by sleepyhollo** [Python-Markdown/markdown#844]
Great library! Thanks for making it.

I am trying to use it to convert some local md files to html. It took me some trial and error to figure out the format for a JSON conf file. I was using the toc extension and tried many permutations on the following JSON

```
{
  "extension_configs":
  {
    "toc":
    {
      "toc_depth":"2-6"
    }
  }
}
```

Than I found out I had an extra layer of nesting and my file should be:
```
{
  "toc":
  {
    "toc_depth":"2-6"
  }
}
```

I think including some a few sample in the docs can help people get an idea of the format of the configuration files faster. I am using markdown 3.1.1

**Comment by waylan** [comment]
It is coincidental that we support JSON simply because the YAML parser supports JSON. If you want to use JSON, then you need to understand how YAML translates to JSON. That is not the responsibility of MkDocs to document.

That said, if there is any ambiguity in the documentation regarding how to format the YAML config options, please point out the specific issues so we can address them. Or even better, feel free to submit pull requests.

**Comment by waylan** [comment]
The [docs][1] state:

> The file must be in either the YAML or JSON format and contain YAML or JSON data that would map to a Python Dictionary in the format required by the `extension_configs` keyword of the `markdown.Markdown` class. 

As Python dicts and JSON share the same syntax, they (mostly) map 1-to-1. I'm not sure how much more clear we need to be. Simply create a JSON file which contains the equivalent of the Python dict which gets passed to  the `extension_configs` keyword. That dict would not contain a  `extension_configs` object, so neither would the JSON file.

In other words, the documentation already exists in the [Python specific instructions][2]. And we already provide a YAML example which does not include the `extension_configs` object in it, so why would JSON be any different. Seems to me it is fully covered.

That said, a pull request which improves the documentation is always welcome.

[1]: https://python-markdown.github.io/cli/#using-extensions
[2]: https://python-markdown.github.io/reference/#extension_configs

**Comment by sleepyhollo** [comment]
You are right. I was unable to understand it properly. 

Still, I made a wiki [page](https://github.com/Python-Markdown/markdown/wiki/Configuration-File-format). I will remove that and make PR for an example JSON file hopefully over the weekend. That will make the information more explicit.
