### ISSUE TITLE
Check for one or more spaces between link and title

### ISSUE THREAD

**Issue by gk7huki** [Python-Markdown/markdown#847]
In LinkInlineProcessor, RE_LINK checks for zero or more spaces between the link and title:
`\(\s*(?:(<[^<>]*>)\s*(?:('[^']*'|"[^"]*")\s*)?\))?`

This results in buggy behaviour with links ending with quotes:
```
>>> markdown.markdown('[text](http://link/q="value")')
'<p><a href="http://link/q=" title="value">text</a></p>'
```

I believe it should look for one or more spaces, i.e., use `\s+` instead of `\s*`:
`\(\s*(?:(<[^<>]*>)`**`\s+`**`(?:('[^']*'|"[^"]*")\s*)?\))?`

There might be something else I'm missing since the regex only seems to handle links covered by angular brackets and everything else goes through manual logic.

**Comment by waylan** [comment]
The reference implementation exhibits the same behavior. I'm not sure we are doing anything wrong here. In fact,  `http://link/q="value"` is not a valid URL. As I understand it, the double-quote character is not allowed and should be escaped (percent encoded). That being the case, we can safely assume that once we encounter a double quote we have reached the end of the URL and are now at the beginning of the title.

**Comment by gk7huki** [comment]
While it's true that characters like `"` need to be % encoded,
- Typing them as-is in the browser automatically handles % encoding. Here's a sample link that works fine in Firefox: `https://www.google.com/search?q="quoted+text"`
- Other special symbols like parentheses `()` are already supported in markdown links. So I think it could be useful to properly support quotes also.

For some context, I'm working on a chat client that's planned to support markdown, so the idea is to let users type markdown links containing such symbols. Of course, if the user were to copy-paste a link from the browser, it's already percent encoded.

With that said, if the reference implementation exhibits the same behaviour then I guess it's not really a bug in Python-Markdown anyway.

**Comment by waylan** [comment]
Be aware that Markdown expects the user to always provide percent encoded URLs, which is why it is not a bug. Of course, Markdown was originally developed back when browsers didn't automatically handle percent encoding. Regardless, Python-Markdown is proudly an "old-school" implementation of Markdown and will continue to maintain the existing behavior.

**Comment by waylan** [comment]
As a reminder, you are always free to create your own extension which alters the default behavior. You could create an extension which replaces the existing URL handling with something which expects unencoded URLs and encodes them, if you so desired.
