### ISSUE TITLE
headings inside lists

### ISSUE THREAD

**Issue by erez-o** [Python-Markdown/markdown#848]
Hi, 

`#` inside lists are turned to headings tags.

Code example:

```
Issues from github:

* First issue
* #257 -- another issue
* #256 -- another issue
```

Turns to
```html
<p>Issues from github:</p>
<ul>
<li>First issue</li>
<li><h1>257 -- another issue</h1></li>
<li><h1>256 -- another issue</h1></li>
</ul>
```

Expected result:
```html
<p>Issues from github:</p>
<ul>
<li>First issue</li>
<li>#257 -- another issue</li>
<li>#256 -- another issue</li>
</ul>
```

I Tried in Babelmark and the expected result is more common by roughly 3:1 ratio.

Thanks.

**Comment by waylan** [comment]
There are two factors involved in this:

1. Some implementations do not require a space between the hash and the first character of the header and other implementation do require the space. In other words, those implementations parse the following two lines differently (irrespective of whether they are nested in a list item):

        #foo
        # bar

    This difference is not supported by the rules or the reference implementation and is therefore a bug and not relevant to this discussion.

2. The reference implementation (and a few other old-school implementations) only recognize nested headers in loose list items (items which contain block level children). For example, the following list:

        * #no space tight
        * # with space tight
        * #no space loose

        * # with space loose

    generates the following output from the reference implementation:

        <ul>
            <li>#no space tight</li>
            <li># with space tight</li>
            <li>
                <h1>no space loose</h1>
            </li>
            <li>
                <h1>with space loose</h1>
            </li>
        </ul>

    I suppose this makes sense as a header is a block level element.

If we were to make any change it would be to match the reference implementation as highlighted in item 2 above. However, there are a lot of existing documents which rely on the current behavior and it would be a backward incompatible change to alter it.

More specifically, the fact that your reference to a GitHub issue was interpreted as a header wouldn't go away of such a change was made. It would only address the issue in the case of a tight list. In any other scenario, you would need to find an alternate way to reference your GitHub issues.

**Comment by erez-o** [comment]
Thanks for the detailed response.

1) I guess the only option to achieve my desired result is to make an extension? I've looked at the list of current 3rd party extensions and haven't found one, do you know if such an extension exists?

2) Regarding backward incompatibility in markdown - since the "markdown standard" is changing and has trends and additions, I think you're limiting yourself if you don't add more core extensions to account for the different behaviors. You can have a general settings for old markdown style and newer style to account for the general incompatibility.

**Comment by waylan** [comment]
> since the "markdown standard" is changing

The "Markdown standard" is [this][1] which hasn't changed in over a decade. That is the only standard Python-Markdown follows. Of course, with extensions, anything outside of that is possible.

[1]: http://daringfireball.net/projects/markdown/syntax

**Comment by burrscurr** [comment]
I had a similar problem like @erez-o. 

Writing this a tree processor like this solved my problem:
```python
class RemoveHeadingsInLists(Treeprocessor):
    def run(self, root: ElementTree):
        for li in root.iter(tag='li'):
            for h in list(li.iter(tag='h1')):
                li.text = '#' + h.text
                li.remove(h)
```
It removes all `<h1>` elements created inside a list item by assigning their text to the list item and deleting the `<h1>` element.
Register the extension like this (priority 100 works for me):

```python
        class MyExtension(Extension):
            def extendMarkdown(self, md):
                md.treeprocessors.register(RemoveHeadingsInLists(), 'removeheadingsinlists', 100)
```

I hope this helps others searching for a solution for the headings-inside-lists problem.

**Comment by erez-o** [comment]
Thx @burrscurr for your help.

I think your solution is slightly different than what I am looking for, because unless I'm mistaken, it will also remove headings in the following markdown snippet:

```
* First issue
* <h1>#257 -- another issue</h1>
* <h1>#256 -- another issue</h1>
```

where there is a consensus between markdown implementations that the h1 should remain. 

I think i'll look into modifying class HashHeaderProcessor depending if parent tag is li.

@waylan regarding my comment about the markdown standard I meant no disrespect. I meant only that there are some ambiguities in the original markdown syntax, and I think this great package can be even better had there been more extensions in the core python package that allow users to customize their desired behavior.

I can close the issue, but haven't because you added the bug tag.

Thx again @waylan and @burrscurr

**Comment by merriam** [comment]
I'm confused, as a bear of little brain.   The standard says `Atx-style headers use 1-6 hash characters at the start of the line`, so it seems clear that `* #anything, space or no space` is not at the start of the line and should not be a header.

This is more complicated?

**Comment by waylan** [comment]
@merriam, yes it is more complicated. Unfortunately the rules are not always clear. When there is a lack of clarity, then the behavior of the reference implementation can be looked at. In this case, allowing headers nested within lists is specifically coded into the reference implementation. It was not just a bug. Therefore, most implementations have followed that example. However, not every implementation has followed the reference implementation exactly.

Apparently in our case, we are failing to ensure that only loose list items are parsed for headers. Instead we are parsing all list items for potential headers.

**Comment by waylan** [comment]
> If we were to make any change it would be to match the reference implementation as highlighted in item 2 above. However, there are a lot of existing documents which rely on the current behavior and it would be a backward incompatible change to alter it.

i am closing this as wontfix for the reasons stated above. Of course, others are free to develop extensions which alter the behavior if they desire.
