### ISSUE TITLE
Support for markdown="1" without unrelated extensions

### ISSUE THREAD

**Issue by tharders** [Python-Markdown/markdown#849]
Currently the markdown="1" support is activated with the extra extension that automatically activates lots of other extensions.

It would really be helpful if it can be activated alone.

Shouldn't it be possible to extract the functionality into another extension?

Or maybe we could configure the extra extension to choose wich of the other extensions are actually loaded. For example a flag 'skipExtensionsWithoutConfig' for the extra extension or a 'disable' flag for all the extension.

**Comment by facelessuser** [comment]
Yeah, I split it out here: https://facelessuser.github.io/pymdown-extensions/extensions/extrarawhtml/.  I'd be happy if it was also split out here so I wouldn't have to maintain mine anymore, but either way, you can basically get what you want now with a third party extension.

**Comment by waylan** [comment]
A PR is always welcome.

**Comment by facelessuser** [comment]
Nice, I may implement this

**Comment by facelessuser** [comment]
@waylan, as I work to split this out, what do we want the extension to be called.

- raw_html
- markdown_html
- in_html

I was leaning towards `raw_html`, but really it doesn't matter to much to me. I more just want something I won't have to change later 🙂. Any thoughts or opinions on this matter?

**Comment by waylan** [comment]
I'm thinking something which conveys "Markdown in HTML" so maybe: `md_in_html`? I'm open to other ideas as well. I looked at a few other implementations and the only useful thing I found was Pandoc's `markdown_in_html_blocks`. While accurate, it's a little lengthy for my tastes.

**Comment by facelessuser** [comment]
`md_in_html` sounds good
