### ISSUE TITLE
Identation

### ISSUE THREAD

**Issue by noraj** [Python-Markdown/markdown#850]
Indentation with 4 spaces works for underdone list but not when using 2 spaces.

This is related to the lack of #851 https://spec.commonmark.org/0.29/#lists

**Comment by mitya57** [comment]
This is by design, as Python-Markdown follows the original Markdown rules (which require 4 spaces), not CommonMark.

This is documented in https://python-markdown.github.io/#differences.

**Comment by noraj** [comment]
> The syntax rules clearly state that when a list item consists of multiple paragraphs, “each subsequent paragraph in a list item must be indented by either 4 spaces or one tab” (emphasis added). However, many implementations do not enforce this rule and allow less than 4 spaces of indentation. The implementers of Python-Markdown consider it a bug to not enforce this rule.
