### ISSUE TITLE
Inconsistent formatting between #header and table of contents vs #header and first bullet of a list

### ISSUE THREAD

**Issue by AEHamrick** [Python-Markdown/markdown#852]
I'm seeing this on bitbucket cloud, which I understand uses python-markdown although I'm unfortunately not sure which version.

Below are examples of the formatting variation as seen in Chrome and the relevant HTML (although I may have missed something--not very HTML savvy if I'm honest.)

I'd appreciate some help understanding if what I'm seeing is a result of the markdown or HTML structure and if so if it's bitbucket's presentation, the markdown rendering, or something else. 

Unfortunately I don't have access to anything besides chrome right this minute so I can't verify if it's browser rendering for a while.

markdown:
```
# Contents  

[TOC]

# Assumptions & Conventions

* [...]
```

html:
![markdown_toc_html](https://user-images.githubusercontent.com/13300689/61959158-cfebcf80-af90-11e9-88bd-a3b8ec6ed0a1.JPG)

rendered (as seen in bitbucket) 
![markdown_toc_1](https://user-images.githubusercontent.com/13300689/61958905-43411180-af90-11e9-8f5f-5ed7041b99f8.JPG)
![markdown_toc_2](https://user-images.githubusercontent.com/13300689/61958904-43411180-af90-11e9-82c1-0db14c1b7a92.JPG)

**Comment by waylan** [comment]
I'm sorry, but it is not clear what the problem is. Please provide:

1. A Markdown document, 
2. the HTML output (not a screen shot, but actual text in a code block -- you may need to use your browsers "view source"f eature) and 
3. the HTML you expect.

**Comment by AEHamrick** [comment]
Hi @waylan, hopefully this helps:

1, the markdown:
```markdown
# Contents  

[TOC]

# I'm a header before a bulleted list

* Bullet 1  
* Bullet 2

# Something
# More
## To
## Fill
### The
#### TOC
* With
* Items
```

2, the html: 
(with bitbucket UI wrapping and such removed--if you need the actual full document let me know) 
```html
<h1 id="markdown-header-contents">Contents</h1>
<div class="toc">
<ul>
<li><a href="#markdown-header-contents">Contents</a></li>
<li><a href="#markdown-header-im-a-header-before-a-bulleted-list">I'm a header before a bulleted list</a></li>
<li><a href="#markdown-header-something">Something</a></li>
<li><a href="#markdown-header-more">More</a><ul>
<li><a href="#markdown-header-to">To</a></li>
<li><a href="#markdown-header-fill">Fill</a><ul>
<li><a href="#markdown-header-the">The</a><ul>
<li><a href="#markdown-header-toc">TOC</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
<h1 id="markdown-header-im-a-header-before-a-bulleted-list">I'm a header before a bulleted list</h1>
<ul>
<li>Bullet 1  </li>
<li>Bullet 2</li>
</ul>
<h1 id="markdown-header-something">Something</h1>
<h1 id="markdown-header-more">More</h1>
<h2 id="markdown-header-to">To</h2>
<h2 id="markdown-header-fill">Fill</h2>
<h3 id="markdown-header-the">The</h3>
<h4 id="markdown-header-toc">TOC</h4>
<ul>
<li>With</li>
<li>Items</li>
</ul>
```

3, the HTML I expect: 
As I said, I'm not good with HTML, but what I expect is that in the rendered document, the whitespace between  `# Contents` and the generated table of contents is the same as the spacing between `# I'm a header before a bulleted list` and the bullet point following.

**Comment by waylan** [comment]
There is absolutely nothing wrong with the HTML being rendered as far as I can tell. Without expected output to compare it to I'm not 100% sure In understand your concern, but it sounds to me like you want/need some CSS to define padding or margin on some HTML elements. Of course, Bitbucket is not likely to allow you to include your own custom CSS for security reasons. So you are stuck with Bitbucket's styling. This is out of scope for Markdown to handle. As a reminder, Markdown is a writing format, not a publishing format.

**Comment by AEHamrick** [comment]
Thanks @waylan, that makes perfect sense; appreciate your time
