### ISSUE TITLE
Code blocks with language not rendering correctly

### ISSUE THREAD

**Issue by Jamie-** [Python-Markdown/markdown#854]
When trying to markdown a code block with a specified language, the language is not added as a class like the docs seem to suggest, instead it just appears inside the code block.

Take the following example
```python
markdown.markdown("""```python
print('test')
```""")
```

This outputs
```
<p><code>python\nprint('test')</code></p>
```

What I'd expect to see is
```
<pre><code class="python">print('test')</code></pre>
```

I appreciate this part of the docs is for a different case but it's suggesting that the regular markdown syntax would produce the same output.
https://python-markdown.github.io/extensions/fenced_code_blocks/#language

Note also the use of `<p>` tags instead of `<pre>` which means when rendered in the browser any line breaks are not seen.

For reference, `markdown.__version__` reports I'm on 3.1.1 which appears to be the latest.

**Comment by waylan** [comment]
Extensions are not enabled by default, you need to explicitly enable them with the [extensions][1] keyword. Try this:

````python
markdown.markdown("""```python
print('test')
```""", extensions=['fenced_code'])
````

[1]: https://python-markdown.github.io/reference/#extensions

**Comment by Jamie-** [comment]
Ok, after some digging on StackOverflow I've found it's my mistake, I need to enable fenced code extensions. In which case, please can this bug be to update your docs to clarify this as it's really not clear.

This usage section should have a tiny code example to make this clear as the first few times I read this I wasn't sure what it meant.
https://python-markdown.github.io/extensions/fenced_code_blocks/#usage

For example:
````
import markdown
from markdown.extensions.fenced_code import FencedCodeExtension
text = """
```python
print('Hello, world')
```
"""
markdown.markdown(text, extensions=[FencedCodeExtension()])
````

**Comment by Jamie-** [comment]
Ah you beat me to it - a  docs update would be wonderful to clarify this though please!

**Comment by waylan** [comment]
The "Usage" section links to the main [Extensions][1] page, which contains an example. We also have the examples in the library reference (as linked above). It seems rather redundant to repeat the same thing for every extension.

[1]: https://python-markdown.github.io/extensions/

**Comment by Jamie-** [comment]
If you think that's adequate, sure, though I struggled to understand why it wasn't working from your docs alone. Personally I think too many examples is better than too few.

**Comment by waylan** [comment]
A PR is always welcome.

**Comment by Jamie-** [comment]
Please see PR https://github.com/Python-Markdown/markdown/pull/855
