### ISSUE TITLE
Adding class attribute to table

### ISSUE THREAD

**Issue by datapythonista** [Python-Markdown/markdown#856]
I'm using markdown to generate html that for a website based in bootstrap, and for tables to be formatted, bootstrap expects them to have a `class="table"` attribute:
```html
<table class="table">
    ...
</table>
```
I think it'd be very useful, and not very complex to have a configuration option `attributes` to be able to specify that `class="table"` should be added.

If there is interest, I'm happy to open a PR for it.

**Comment by waylan** [comment]
This sounds like a great candidate for a third party extension. Please see my response to #74 for a full explanation of my position on expanding the table syntax.

**Comment by datapythonista** [comment]
Thanks @waylan, that sounds good to me. Wanted to know your opinion (since bootstrap is quite common, thought you could be interested).

I think the best approach will be to inherit form the current table extension. Probably won't be needed, but I may still propose a PR that makes subclassing the extension easier, if that's all right.

Thanks!

**Comment by waylan** [comment]
> I may still propose a PR that makes subclassing the extension easier, if that's all right.

Sounds good to me.
