### ISSUE TITLE
Is it possible to generate borders with Markdown tables

### ISSUE THREAD

**Issue by Jacob-Barhak** [Python-Markdown/markdown#863]
The panel group redirected me to your issue tracker to see if markdown can provide remedy for this issue.

I am using panel that uses markdown and I am trying to generate a table with borders. Here is the code I am using in panel:
```
import panel as pn
from bokeh.resources import INLINE

SimpleTable = pn.panel("""
|     Time    | Number of Trial with Results | Unique Units |
|:-----------:|:----------------------------:|:------------:|
| 20 Apr 2018 |            30,763            |    21,094    |
|  7 Feb 2019 |            34,751            |    23,733    |
| 12 Apr 2019 |            35,926            |    24,548    |
|             |                              |              |

""")

SimpleTable.save('SimpleTable', resources=INLINE) 

```
The code generates a nice table, yet without borders. 

![image](https://user-images.githubusercontent.com/1986155/65892418-e4bb5980-e36b-11e9-8128-366f8b632de9.png)

Now the question is whether you can force table borders to be drawn in markdown or are visual look aspects need to be handled elsewhere by panel, bokeh, or some CSS.

It may be a question open for debate - will be happy to get feedback.

**Comment by jbednar** [comment]
For what it's worth, I think what Panel is doing with the input above is effectively:

```
import markdown

str = """
|     Time    | Number of Trial with Results | Unique Units |
|:-----------:|:----------------------------:|:------------:|
| 20 Apr 2018 |            30,763            |    21,094    |
|  7 Feb 2019 |            34,751            |    23,733    |
| 12 Apr 2019 |            35,926            |    24,548    |
|             |                              |              |
"""

extensions = ['markdown.extensions.extra', 'markdown.extensions.smarty']
html = markdown.markdown(str, extensions=extensions, output_format='html5')
```

The resulting `html` looks like this in a web browser if put in a bare page:

![image](https://user-images.githubusercontent.com/1695496/65894134-dcb0e900-e36e-11e9-9ebf-b08e703fc008.png)

And like this in a Jupyter notebook cell:

```
from IPython.display import HTML
HTML(html)
```

![image](https://user-images.githubusercontent.com/1695496/65894204-f5210380-e36e-11e9-84c0-8db1560a169e.png)

So it's possible to style it, presumably using the usual table CSS properties.

**Comment by Jacob-Barhak** [comment]
In that case, unless Markdown developers want to add more features related to CSS style, it seems we can close this in this issue tracker.

**Comment by waylan** [comment]
Python-Markdown simply outputs standard HTML for tables.  As explained in the [Markdown syntax rules][1] "HTML is a *publishing* format; Markdown is a *writing* format." Whether borders are displayed and/or the style of those borders are *publishing* matters and outside the scope of Markdown. However, basic CSS rules for styling the HTML will work fine. In fact, as @jbednar points out, different tools use different default styles for the same input. If you want to use custom styles, you need to explore what provisions your tool uses to define custom styles.

[1]: https://daringfireball.net/projects/markdown/syntax#html

**Comment by Jacob-Barhak** [comment]
Thanks Waylan,

There is a temporary solution found that can be found here: https://github.com/pyviz/panel/issues/668

It may not be very elegant, yet it seems to work for a simple example. Thanks for the feedback.
