### ISSUE TITLE
Wrong reference for extension

### ISSUE THREAD

**Issue by barretomateus** [Python-Markdown/markdown#868]
Hi everyone,

first I would like to thank you all for this amazing tool. It has been really helpful for me.

So, in the docs section, more precisely on the extensions index, the `legacy_attr` extension is spelled incorrectly. The correct is `legacy_attrs` and `markdown.extensions.legacy_attrs`. Without the `s` will raise a ModuleNotFoundError exception.

Thanks!

**Comment by nnrepos** [comment]
Hi, I've fixed this issue on my local fork, but when trying to run markdown, I get:
```python
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\Lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "markdown\__init__.py", line 22, in <module>
    from .core import Markdown, markdown, markdownFromFile
  File "markdown\core.py", line 27, in <module>
    from . import util
  File "markdown\util.py", line 27, in <module>
    from .pep562 import Pep562
  File "markdown\pep562.py", line 244, in <module>
    __version_info__ = Version(1, 0, 0, "final")
  File "markdown\pep562.py", line 140, in __new__
    return super().__new__(cls, major, minor, micro, release, pre, post, dev)
TypeError: super() takes at least 1 argument (0 given)
```
help would be appreciated

**Comment by mitya57** [comment]
@NNRepos The master branch no longer supports Python 2.

**Comment by nnrepos** [comment]
@mitya57 thanks. If this is the case, shouldn't the docs be changed to `pip3 install...`, and the `python2.7` tag removed?

**Comment by mitya57** [comment]
Do you mean the [python2] topic here on GitHub? I don't have rights to remove it, so @waylan should do it.

But I wonder if we should do it now or when the next version is released.

[python2]: https://github.com/topics/python2

**Comment by nnrepos** [comment]
@mitya57 I've used python3 this time. when running unittest, I get import errors (e.g. for yaml). Are these OK? It looks like my pull passed all tests on travis. If so, am I supposed to wait for @waylan to confirm my pull?
Thanks again :)

**Comment by mitya57** [comment]
> I've used python3 this time. when running unittest, I get import errors (e.g. for yaml).

Do you have it installed? Run `pip install PyYAML` if not.

> It looks like my pull passed all tests on travis. If so, am I supposed to wait for @waylan to confirm my pull?

I added my :+1:, but let's wait for Waylan to merge this, yes.

**Comment by waylan** [comment]
> If this is the case, shouldn't the docs be changed to pip3 install..., 

No, not necessarily. On many systems, Python3 is the default and `pip` gets you `pip3`. As Python will itself drop support for Python 2 on January 1, 2020, I expect that within a short time most systems will update so that `pip` gets you `pip3`.

> and the python2.7 tag removed?

It has been in #865. If you mean the tag in the Readme on the front page of the project, that is getting it's data from the most recent release on PyPI, which still supports Python2. It will get updated automatically when the next release is made.
