### ISSUE TITLE
Cannot install on Win 7 64bit, Python 3.7

### ISSUE THREAD

**Issue by ghost** [Python-Markdown/markdown#869]
Error message:

> Microsoft Windows [Version 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
> 
> C:\Users\user>python
> Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD6
> 4)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> C:\Users\user>python -m pip install markdown
> Collecting markdown
>   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, stat
> us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
> onnection.VerifiedHTTPSConnection object at 0x000000000497CBE0>: Failed to estab
> lish a new connection: [WinError 10013] An attempt was made to access a socket i
> n a way forbidden by its access permissions')': /simple/markdown/
>   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, stat
> us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
> onnection.VerifiedHTTPSConnection object at 0x00000000048242E8>: Failed to estab
> lish a new connection: [WinError 10013] An attempt was made to access a socket i
> n a way forbidden by its access permissions')': /simple/markdown/
>   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, stat
> us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
> onnection.VerifiedHTTPSConnection object at 0x00000000048240F0>: Failed to estab
> lish a new connection: [WinError 10013] An attempt was made to access a socket i
> n a way forbidden by its access permissions')': /simple/markdown/
>   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, stat
> us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
> onnection.VerifiedHTTPSConnection object at 0x0000000004824048>: Failed to estab
> lish a new connection: [WinError 10013] An attempt was made to access a socket i
> n a way forbidden by its access permissions')': /simple/markdown/
>   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, stat
> us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
> onnection.VerifiedHTTPSConnection object at 0x0000000004824518>: Failed to estab
> lish a new connection: [WinError 10013] An attempt was made to access a socket i
> n a way forbidden by its access permissions')': /simple/markdown/
>   ERROR: Could not find a version that satisfies the requirement markdown (from
> versions: none)
> ERROR: No matching distribution found for markdown
>

**Comment by waylan** [comment]
Based on the error, it appears that you were unable to connect to the server to download the package. As this has been closed, I assume you worked that out.

**Comment by ghost** [comment]
Yeah, that was the problem, my firewall blocked python.  I would have liked to delete it, but I couldn't, so I closed it :)
