### ISSUE TITLE
Show readable error on Python 2 use.

### ISSUE THREAD

**Issue by waylan** [Python-Markdown/markdown#871]
With #865 we dropped support for PY2 and the syntax was updated to be PY3 only. This results in an ugly error when used from PY2, as demonstrated in a [comment][1] on #868:

```python
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\Lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "markdown\__init__.py", line 22, in <module>
    from .core import Markdown, markdown, markdownFromFile
  File "markdown\core.py", line 27, in <module>
    from . import util
  File "markdown\util.py", line 27, in <module>
    from .pep562 import Pep562
  File "markdown\pep562.py", line 244, in <module>
    __version_info__ = Version(1, 0, 0, "final")
  File "markdown\pep562.py", line 140, in __new__
    return super().__new__(cls, major, minor, micro, release, pre, post, dev)
TypeError: super() takes at least 1 argument (0 given)
```

Perhaps in `markdown.__init__.py` we should test for the Python version and immediately issue a readable error if PY2 is in use.

I realize that given the metadata in `setup.py` most users won't get future releases to install on PY2, but that doesn't prevent everyone. For example, those who have used `setup.py develop` from their git working tree will have issues. 

Any feedback on this is welcome. Anyone know how other's are addressing this? Or is this something that we shouldn't worry about?

[1]: https://github.com/Python-Markdown/markdown/issues/868#issuecomment-547292661

**Comment by mitya57** [comment]
How about doing something like this in `markdown/__init__.py`:
```python
import sys

class PythonVersionTooOld(ImportError):
    pass

if sys.version_info < (3, 5):
    raise PythonVersionTooOld('Python 3.5 or later is required')
```

This way Python 2 modules which have code like this will fall back gracefully:
```python
try:
    import markdown
except ImportError:
    # some fallback path
```

**Comment by waylan** [comment]
Hmm, I hadn't considered creating a custom error class. But I suppose that gives people the option to filter that specific error separately if they desire.

Regarding the actual version check, I wonder if we could retrieve the minimum version from `pkg_resources`. That way, we wouldn't need to remember to update it in multiple places.

**Comment by mitya57** [comment]
`pkg_resources` won't work if they are running it from a git clone. And most likely they won't have it installed because setup.py no longer works with Python 2.

**Comment by waylan** [comment]
You can also get the same result from `pip install -e`  (`-e` or `--editable`) as from `setup.py develop` so there is still a way to do that. However, I was mostly thinking of anyone who already had it installed that way in the past.

Regardless, the package must be installed for the Markdown version stuff to work as that uses `pkg_resources`. And we import `meta.__version__` into `markdown.__init__.py` so we can assume that if anyone is importing `markdown` that the package is installed. In fact, if is is not installed, an error will occur on import. Therefore, we can always assume `pkg_resources` can retrieve any other data regarding the package as well.

**Comment by mitya57** [comment]
Ok, that makes sense.

**Comment by waylan** [comment]
I just realized using the Python version from `pkg_resources` won't address my use-case. If the user previously installed Markdown using `develop` and then updates her git working tree, the meta data retrieved from `pkg_resources` will still be the data provided when the install happened, not the new data in the working tree. I guess we can forget that idea.
