### ISSUE TITLE
TOC header issues

### ISSUE THREAD

**Issue by ayblaq** [Python-Markdown/markdown#872]
I recently started using mkdocs to convert my markdowns to HTML files. When I pass marker to toc configuration as '[[TOC]]', the string isn't replaced with a table of content. However, when some modification in replace_marker function of the markdown toc extension code from:
 `  if c.text and c.text.strip() == self.marker:
                for i in range(len(p)):
                    if p[i] == c:
                        p[i] = elem
                        break
`
to:
`            if text == self.marker:
                for i in range(len(p)):
                    if p[i] == c:
                        p[i] = elem
                        break`
the problem is solved. This problem hasn't be reported yet, and I am thinking maybe I am doing something wrong

**Comment by waylan** [comment]
Please provide a sample document which demonstrates the problem as well as the actual output and the expected output.

**Comment by ayblaq** [comment]
Hi @waylan 
The content of the md file looks like this 

```
[[_TOC_]]
#Introduction
Rooms module gives a quick overview of the conditions in the rooms. There are 3 different types on views in the room module. Main room list, that is represented as a table, floor view, that shows the floor plan, and single room view.
```
The output: 

```
<div class="md-content">
<article class="md-content__inner md-typeset">
<h1>Rooms module</h1>
<p>[[<em>TOC</em>]]</p>
<h3 id="introduction">Introduction</h3>
<p>Rooms module gives a quick overview of the conditions in the rooms. There are 3 different types on views in the room module. Main room list, that is represented as a table, floor view, that shows the floor plan, and single room view.</p>
</article>
</div>
```
Expected output and output after making changes to replace_marker function: 

```
<div class="md-content">
<article class="md-content__inner md-typeset">
<h1>Rooms module</h1>
<div class="toc">
<ul>
<li><a href="#introduction">Introduction</a></li>
</ul>
</div>
<h3 id="introduction">Introduction</h3>
<p>Rooms module gives a quick overview of the conditions in the rooms. There are 3 different types on views in the room module. Main room list, that is represented as a table, floor view, that shows the floor plan, and single room view.</p>
</article>
</div>
```

**Comment by waylan** [comment]
Please edit your comment above to insert the source of your input as a code block. You appear to have using escaping on the `TOC`, but now I don't know exactly what was in the original and what you added. Using a code block will eliminate any such confusion.

Also, please provide the output as HTML in a code block. Images are completely unhelpful.

**Comment by waylan** [comment]
@ayblaq I just edited your comment to use code blocks, not code spans. Please be aware of the difference. Also, notice how much easier it is both to read and to write with that format.

In any event, it appears that you are using `[[_TOC_]]` to designate where your TOC should go. However, the [documentation][1] clearly indicates that the proper format of the marker is `[TOC]`. So change your Markdown to:

```
[TOC]
#Introduction
Rooms module gives a quick overview of the conditions in the rooms. There are 3 different types on views in the room module. Main room list, that is represented as a table, floor view, that shows the floor plan, and single room view.
```

[1]: https://python-markdown.github.io/extensions/toc/#syntax

**Comment by ayblaq** [comment]
> [[_TOC_]]

Alright, noted.

Changing from `[[_TOC_]]` to `[[TOC]]` works but breaks the markdown in gitlab. This means it can't be automated.

**Comment by waylan** [comment]
Not `[[TOC]]`, but `[TOC]`. Only one set of brackets. Not two.

**Comment by waylan** [comment]
Note that if you want to change the marker, you can define your own marker with the `marker` [extention config setting](https://python-markdown.github.io/extensions/toc/#usage). However, as you have not mentioned that, I am assuming you are not doing that.
