### ISSUE TITLE
List processing wraps all items in <p>; except the first one

### ISSUE THREAD

**Issue by fancsali** [Python-Markdown/markdown#873]
Using Python 3.7.4 with markdown 3.1.1, the following happens:
```
Type "help", "copyright", "credits" or "license" for more information.
>>> from markdown import markdown
>>> markdown("XXX\n\n- AAA\n- BBB\n\n- CCC\n")
'<p>XXX</p>\n<ul>\n<li>AAA</li>\n<li>\n<p>BBB</p>\n</li>\n<li>\n<p>CCC</p>\n</li>\n</ul>'
```
... or in another words:

```
XXX

- AAA
- BBB

- CCC
```
 would render this:
```
<p>XXX</p>
<ul>
<li>AAA</li>
<li>
<p>BBB</p>
</li>
<li>
<p>CCC</p>
</li>
</ul>
```

Which seems to be odd to me: either all of them should be wrapped, or none.

**Comment by waylan** [comment]
Actually, this is the correct behavior as this exactly matches the behavior of the reference implementation. See the [Babelmark FAQ][1] (and the [partially tight list][2] example) for details. I realize that this behavior may be surprising to some and there is even a disagreement among implementations. However, we follow the reference implementation here so as not to contribute to the problem of implementations diverging.

Of course, you are always free to create an extension which implements different behavior. There are already a few extensions which alter the list parsing in other ways.

[1]: https://johnmacfarlane.net/babelmark2/faq.html 
[2]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+one%0A%0A2.+two%0A3.+three%0A
