### ISSUE TITLE
Allow lists to interrupt a paragraph

### ISSUE THREAD

**Issue by jalaziz** [Python-Markdown/markdown#874]
Allowing lists to interrupt paragraphs would lists to be defined without blank lines, as in:
```
Foo:
* Bar
* Baz
```

I realize lists interrupting paragraphs is not quite per the reference implementation. However, CommonMark [allows it](https://github.github.com/gfm/#example-283) for various reasons outline in the doc.

I'm fairly new to python-markdown, so I apologize if this has been asked before (I tried searching but found nothing). Is it possible to create an extension that enables this behavior? If so, could anyone offer some pointers on what would need to be done?

**Comment by waylan** [comment]
You can create whatever extension you want. However, personally I have no interest in this. I think Commonmark got this completely wrong. In fact, if there was one thing I would change about the reference implementation it would be always require a blank line between all block level types of content.

**Comment by jalaziz** [comment]
@waylan I completely understand that you don't want to include this, that's why I'm willing to write an extension.

In our case, we're trying to use mkdocs to create a doc site from docs that were originally written for Github, which is why the extension would be useful. I realize that I can "create whatever extension [I] want". What I'm unclear about is what the best approach would be? Any chance you're willing to offer any pointers?

I took a look at the `sane_lists` plugin, but it seems that building off that would not work as the blocks have already been split. Would this need to be a preprocessor? Or could it be done by building off a different processor?

**Comment by waylan** [comment]
My best guess is that you would need to either fork or subclass the paragraph blockproseccor to have it detect a list similar to how it special cases paragraphs within list-lists now (see [markdown/blockprocessors.py#L566][1]). Another example is how hash headers deal with additional lines of text (see [markdown/blockprocessors.py#L463][2]).

[1]: https://github.com/Python-Markdown/markdown/blob/master/markdown/blockprocessors.py#L566
[2]: https://github.com/Python-Markdown/markdown/blob/master/markdown/blockprocessors.py#L463

**Comment by jalaziz** [comment]
Thanks! This is immensely helpful. Should be able to take it from here.

**Comment by adamb70** [comment]
Just made [an extension](https://github.com/adamb70/mdx-breakless-lists) for this if anyone else wants to have the same feature.
