### ISSUE TITLE
Wikilinks: link-transform

### ISSUE THREAD

**Issue by klml** [Python-Markdown/markdown#875]
I would like to have an option to change the link-transform in [WikiLinks](https://python-markdown.github.io/extensions/wikilinks/).

Currently the link is created according to the text notation: `[[Wiki Link]]` produces `href="/Wiki_Link/"`

I would like to have the possibility to lowercase the link: `[[Wiki Link]]` should produce `href="/wiki_link/"` (and for the sake of completeness: uppercase;)

Is this in the scope of Python-Markdown? So I would create an PR.

**Comment by waylan** [comment]
If I make any changes to this extension is would be to remove it from being included with Markdown. It only remains as it is very old. I suspect a better approach for you would be to either fork it or create your own new extension which offers the behavior you desire.

**Comment by klml** [comment]
In any case somebody else needs this feature, I added it in [com/neurobin/mdx_wikilink_plus](https://github.com/neurobin/mdx_wikilink_plus#configuration) as `url_case`.
