### ISSUE TITLE
Bug when ul and ol lists together

### ISSUE THREAD

**Issue by melnikovsa** [Python-Markdown/markdown#888]
![image](https://user-images.githubusercontent.com/58511347/70135630-3bb31700-16ac-11ea-9ab2-596a27a2024d.png)
convert to 
![image](https://user-images.githubusercontent.com/58511347/70135659-4ec5e700-16ac-11ea-90ad-a8e0a7040c3c.png)

but must be
![image](https://user-images.githubusercontent.com/58511347/70135787-8af94780-16ac-11ea-957c-755736f6f5b3.png)

**Comment by facelessuser** [comment]
This behavior is documented. You might want to try https://python-markdown.github.io/extensions/sane_lists/.

**Comment by waylan** [comment]
@facelessuser is correct. The current behavior is supported by the original rules and reference implementation. However, for those who dislike that behavior, we have provided the `sane_lists` extension.

Closing this as there is no bug here.
