### ISSUE TITLE
Table with captions in them

### ISSUE THREAD

**Issue by rifazn** [Python-Markdown/markdown#889]
Is there any intention of including `<caption>` inside tables?

Right now, MultiMarkdown implementts the markdown for tables with caption like this:

```
| Header 1 | Header 2 | Header 3 |
| First elem | Second elem | Third elem |
[An Example Caption for table]
```

As seen on: https://fletcher.github.io/MultiMarkdown-6/syntax/tables.html

**Comment by waylan** [comment]
No we have no intention of adding support for any additional features to the tables extension. Of course, anyone is free to implement their own tables extension (or fork the existing one) which supports any features they want. In fact, there are multiple [third party][1] table extensions available. Perhaps one of those offers the feature you are looking for.

[1]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions
