### ISSUE TITLE
multiple escaped backslashes

### ISSUE THREAD

**Issue by mleue** [Python-Markdown/markdown#890]
Is this expected behavior?

```python
>>> markdown.markdown("\\")
'<p>\\</p>'
>>> markdown.markdown("\\\\")
'<p>\\</p>'
```

I would have expected

```python
>>> markdown.markdown("\\")
'<p>\\</p>'
>>> markdown.markdown("\\\\")
'<p>\\\\</p>'
```

markdown `3.1.1`
As far as I understand from here: https://daringfireball.net/projects/markdown/syntax#backslash escaping backslashes should be possible.

Thanks in advance for any help.

**Comment by waylan** [comment]
The problem is that the Python console is eating some of your backslashes and they never get passed to Markdown. For example try this:

```pycon
>>> print('\\\\')
\\
```

Notice that the Python console sees the first and third backslashes as escape characters and so the entire string is only two backslashes. Instead, you can use a raw string:

```pycon
>>> print(r'\\\\')
\\\\
>>> markdown.markdown(r'\\\\')
u'<p>\\\\</p>'
```

Another way to test this is to read in the contents of a file and pass that to Markdown. Again, you will find that the behavior is correct.

**Comment by mleue** [comment]
Hey @waylan , thanks a lot for replying so quickly.

I think I agree on all your points, and I also think that my expected examples reflect the correct usage of normal/raw strings.
I use normal strings (i.e. backslash initiates an escape sequence, double backslash denotes a single escaped backslash character) as inputs and I expect the same number of backslashes in the return since the python console returns the `__repr__` of the resulting html string, which also escapes the backslashes.

I think my confusion really boils down to the following:
```python
>>> "\\" == "\\\\"
False
>>> markdown.markdown("\\") == markdown.markdown("\\\\")
True
```

The strings are different (the first is a single backslash if you would write it to a text file, the second is a double backslash if you would write it to a text file). But `markdown` processes both to the exact same output.

**Comment by waylan** [comment]
Again the problem is with the Python console. Remove the console from the equation and everything works as it should. You can try the [online test tool][1] or read in from files to see what I mean. 

[1]: http://waylan.pythonanywhere.com/dingus

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mitya57** [comment]
@mleue I think Python-Markdown behaves according to the [syntax rules](https://daringfireball.net/projects/markdown/syntax#backslash):

- `'\\'` or `r'\'` is a single backslash. It is not followed by anything, so it is treated as a literal backslash, not as an escape character.
- `'\\\\'` or `r'\\'` is two backslashes. Here, the first backslash **is** followed by a character from the list (see the docs), so it is treated as escape character and it *escapes* the second backslash. If the second backslash were followed by another character, it would *lose* its escaping meaning.

    For example:
    ```python
    >>> markdown.markdown(r'\*foo*')  # the backslash is an escape character, it escapes the asterisk
    '<p>*foo*</p>'
    >>> markdown.markdown(r'\\*foo*')  # the second backslash is no longer an escape character
    '<p>\\<em>foo</em></p>'
    ```

If you want to get *n* literal backslashes in the output, then you need *2n* in the input (when not before characters from list, *2n−1* are enough). If that is a Python non-raw string, this becomes *4n* or *4n−2*.

I should also add that most other Markdown implementations produce [the same result](https://johnmacfarlane.net/babelmark2/?text=%5C%5C).

**Comment by mleue** [comment]
@mitya57 thanks a lot for this additional explanation, it did the trick for me.

I was only looking at how python itself handles escaping in strings, but I forgot that markdown also is a language that allows escaping. Basically there are 2 levels of escaping that can happen, first in the python string itself and then in markdown.

Maybe as a bit of background: I stumbled upon this issue while using some mathjax-style latex in my markdown. The viewer, that I use to display the final html, contains mathjax ... i.e. I don't need to convert the latex parts of my markdown documents, I really just need to pass them through unaltered.

Now latex math can contain double backslashes as linebreaks, e.g. I could have the following input markdown:

`Here is some *cool* matrix: $\begin{bmatrix}1 & 2 \\ 3 & 4 \end{bmatrix}$.`

What I want as the html output is:
`Here is some <em>cool</em> matrix: $\begin{bmatrix}1 & 2 \\ 3 & 4 \end{bmatrix}$.`

But what I currently get is:
`Here is some <em>cool</em> matrix: $\begin{bmatrix}1 & 2 \ 3 & 4 \end{bmatrix}$.` (which messes up the matrix)

I guess I should be using some kind of extension that passes the entire `$...$` sequence through the markdown processor unaltered?

Anyways, thanks a lot for the help and your work on this project in general.

**Comment by waylan** [comment]
> I guess I should be using some kind of extension that passes the entire `$...$` sequence through the markdown processor unaltered?

Yes you should. In fact there are a few extensions which do this very thing listed on the [wiki](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions)

**Comment by mitya57** [comment]
For MathJax, I would recommend @facelessuser's [arithmatex](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/) or my own [python-markdown-math](https://github.com/mitya57/python-markdown-math).
