### ISSUE TITLE
How do you run the tests?

### ISSUE THREAD

**Issue by Malvineous** [Python-Markdown/markdown#892]
I'm hunting down a bug I suspect may be in this package, so I'd like to test it out and write a unit test if the bug is indeed here.  Unfortunately however, not being a Python programmer, I can't figure out how to run the unit tests!

In `docs/test_tools.md` it says to run `python -m unittest discover tests`.  This came up with an error about not finding a module, and after a bit of investigation I worked out I had to install a package from my distro's repos called, of all things, `python-nose`.

Doing this allowed the original command to work, but I get a whole bunch of test failures, with reasons like this:
```
ModuleNotFoundError: No module named 'legacy_em'
ModuleNotFoundError: No module named 'tables'
ModuleNotFoundError: No module named 'toc'
```
I couldn't find any Python modules with these names, but upon looking in the source folders, it looks like these modules are provided by the code itself.  Just for some reason the tests can't find the code they are supposed to be testing.  I *think* this could be because I haven't installed python-markdown with `pip` (which I don't want to do, as I want to be able to debug the code and run the tests).

I found I can use `setup.py build` to put some files into a `build` folder, so I thought maybe I could fake an install by pointing Python at this folder:

    PYTHONPATH=./build/ python -m unittest discover tests
    PYTHONPATH=./build/lib/ python -m unittest discover tests
    PYTHONPATH=./build/lib/markdown/ python -m unittest discover tests
    PYTHONPATH=./build/lib/markdown/extensions/ python -m unittest discover tests

The first three make no difference, but the last one gives me a different error:

      File "build/lib/markdown/extensions/toc.py", line 16, in <module>
        from . import Extension
    ImportError: attempted relative import with no known parent package

I'm not really sure what to do here, as I fear I am going down the wrong path.  Have I missed something in the docs?  How might one check out the code and run the tests, if one does not have much in the way of Python modules already installed?

**Comment by waylan** [comment]
The test framework is documented [here][1]: However, upon review, I see there are a few details missing which are included in by response below. This information needs to be added to the documentation and I've labeled the issue as such. That said, most of the information below is in the documentation.

First of all, `python-nose` was a tool we used in the past. We are no longer using it and you should have no need for it. Are you sure you have a current version of Python-Markdown?

Also, for the tests to run completely, you may need the working tree of the git repo, not the tarball downloaded from PyPI. I'm not sure about that and you don't say which you are using.

As documented, you simply run the command `python -m unittest discover tests` to run the tests. That uses Python's standard library `unittest` tool with no additional dependancies needed.

However, for extensions to work properly, they need to be installed as their "short names" gets registered upon installation. In other words, if not installed, Markdown doesn't know how to find `footnotes` and any tests passing that string as an extension name will fail.<sup>*</sup> 

Additionally, as documented, many of the legacy tests require `Pytidylib`, which depends on a C library and is not strait forward to install on all systems. Therefore, we simply skip those tests if the lib is not installed. While probably not an issue for you, this can result in an incomplete set of tests being run.

If you don't want to install the Markdown library then the best solution is to install it into a [Python virtual environment][2]. You can then run the tests within that venv.

However, if you don't want to mess around with setting up venvs, we have a [tox][3] configuration file. Tox will set up venvs for various test environments, install the appropriate dependencies and run the tests for each automatically. In fact we use tox to automate our CI tests on [Travis][4]. Of course, the tests will only be successful for the venvs where you have the appropriate dependencies installed. For example, the C lib for `Pytidylib` and all supported versions of Python. Therefore, it is probably better to just create a venv, install the Markdown library and then run the tests there.

<sup>*</sup> <del>This is the detail which is missing from the documentation. Along with the solution of using a venv.</del>

[1]: https://python-markdown.github.io/test_tools/
[2]: https://docs.python.org/3/library/venv.html
[3]: http://testrun.org/tox/latest/
[4]: https://travis-ci.org/Python-Markdown/markdown

**Comment by waylan** [comment]
The missing pieces are documented in the Contributing Guide under [Development Environment][1]. I suppose, as a minimum, we should point to that from the test framework documentation. I don't see the need to repeat the info in both places.

[1]: https://python-markdown.github.io/contributing/#development-environment
