### ISSUE TITLE
should ~~hello~~ be converted into <del>hello</del>?

### ISSUE THREAD

**Issue by retsyo** [Python-Markdown/markdown#893]
I am using latesed cloned package with python 3.6 on win 64 bits

```python
>>> import markdown
>>> md = markdown.Markdown()
>>> md.convert('~~hello~~')
'<p>~~hello~~</p>'
```

should it be `<del>hello</del>`? Or any extension can do that? Thanks

**Comment by facelessuser** [comment]
No, this is not part of the Markdown spec. If you'd like such behavior you can use a third party plugin: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions.

I know there are at least two available. Full disclosure, this one is one that I wrote: 
 https://facelessuser.github.io/pymdown-extensions/extensions/tilde/. 

There is also https://github.com/aleray/mdx_del_ins available. I've never used it, and it hasn't been updated in 8 years, but it may work just fine.
