### ISSUE TITLE
image short-reference links not supported

### ISSUE THREAD

**Issue by erez-o** [Python-Markdown/markdown#894]
Hi, 

I've encountered an unexpected behavior:

Markdown:
```
[![Build Status]](https://travis-ci.org/commonmark/cmark)


[Build Status]: https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat
```

Produces 
```
<p>
  <a href="https://travis-ci.org/commonmark/cmark">![Build Status]</a>
</p>
```

Expected behavior: (inserted the above markdown snippet as is into this issue)

[![Build Status]](https://travis-ci.org/commonmark/cmark)

[Build Status]: https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat

or in html:
```
<p>
  <a href="https://travis-ci.org/commonmark/cmark"><img src="https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat" alt="Build Status"></a>
</p>
```
In babel:

https://babelmark.github.io/?text=%5B!%5BBuild+Status%5D%5D(https%3A%2F%2Ftravis-ci.org%2Fcommonmark%2Fcmark)%0A%0A%0A%5BBuild+Status%5D%3A+https%3A%2F%2Fimg.shields.io%2Ftravis%2Fcommonmark%2Fcmark%2Fmaster.svg%3Fstyle%3Dflat

**Comment by waylan** [comment]
I'm not sure this is a bug. I understand why one might think it is, but short reference links (where the label is the ref) are an undocumented feature of Markdown and, as demonstrated by Babelmark, this does not work in the reference implementation either.

Interestingly, the PHP and Python implementations parse the outer link, but miss the image, while `markdown.pl` (the reference implementation) misses the outer link but parses the image.

However, what is more interesting is the behavior when we separate the image link out from the wrapping link (see [babelmark][1]. It appears that Python-Markdown and `markdown.pl` 1.0.1 are the outliers in that neither recognize the short ref for images (`markdown.pl` also doesn't recognize the short ref for links as that was added in 1.0.2). This is clearly a bug. Why would we recognize short refs for links but not images?

[1]: https://babelmark.github.io/?text=!%5BBuild+Status%5D%0A%0A%5Bfoo%5D%0A%0A%5Bfoo%5D%3A+(https%3A%2F%2Ftravis-ci.org%2Fcommonmark%2Fcmark)%0A%5BBuild+Status%5D%3A+https%3A%2F%2Fimg.shields.io%2Ftravis%2Fcommonmark%2Fcmark%2Fmaster.svg%3Fstyle%3Dflat

**Comment by erez-o** [comment]
Ok, 

If I understand, you correctly, I think that once you recognize short refs as images, you would get the expected behavior I described above:

If 

```
![Build Status]

[Build Status]: https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat
```

Becomes 
```
<img src="https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat" alt="Build Status">
```

Then:
```
[<img src="https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat" alt="Build Status">](https://travis-ci.org/commonmark/cmark)


[Build Status]: https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat
```

Becomes (currently in python-markdown): 
```
<p>
  <a href="https://travis-ci.org/commonmark/cmark"><img src="https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat" alt="Build Status"></a>
</p>
```
<p>
  <a href="https://travis-ci.org/commonmark/cmark"><img src="https://img.shields.io/travis/commonmark/cmark/master.svg?style=flat" alt="Build Status"></a>
</p>

See [babel](https://babelmark.github.io/?text=%5B%3Cimg+src%3D%22https%3A%2F%2Fimg.shields.io%2Ftravis%2Fcommonmark%2Fcmark%2Fmaster.svg%3Fstyle%3Dflat%22+alt%3D%22Build+Status%22%3E%5D(https%3A%2F%2Ftravis-ci.org%2Fcommonmark%2Fcmark)%0A%0A%0A%5BBuild+Status%5D%3A+https%3A%2F%2Fimg.shields.io%2Ftravis%2Fcommonmark%2Fcmark%2Fmaster.svg%3Fstyle%3Dflat)
