### ISSUE TITLE
Single-item hostnames not recognised as links.

### ISSUE THREAD

**Issue by willstott101** [Python-Markdown/markdown#896]
We tend to give intranet servers a single-part hostname such as `george` so URLs end up being like this: https://george/wiki/

Links with hostnames like this are recognised and hyperlinked by GitLab and GitHub markdown. However this implementation does not recognise them as links.

I don't find it clear from the README if such improvements are in scope of this project of if the intent is to replicate the John Gruber implementation as closely as possible.

**Comment by waylan** [comment]
> if the intent is to replicate the John Gruber implementation as closely as possible

Yes, that. In fact, the [rules][0] and the reference implementation do not recognize any URLs unless they are wrapped in angle brackets. Python-Markdown follows the same behavior. The following works fine:

```
<https://george/wiki/>
```

However, Python-Markdown also offers an extension API which permits any and all aspects of the parser to be modified. In fact, you may find some [third-party extensions][1] which alter the behavior and provide what you are looking for. If not, you can always create your own extension.

As an aside, GitHub Markdown doesn't recognize URLs which are not wrapped in angle brackets either (Github's behavior matches commonmark as demonstrated by [Babelmark][2]). However, GitHub does a bunch of post-processing on the HTML generated from Markdown, as documented at [github/markup][3]. Note that the Markdown is converted to HTML in step 1, but plain URLs in the text (which are not wrapped in angle brackets) are converted to links in step 4. In other words, the behavior is not part of Markdown at all, but is applied to all markup languages supported by GitHub in a custom post-processor.

[0]: https://daringfireball.net/projects/markdown/syntax#autolink
[1]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions
[2]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Chttps%3A%2F%2Fexample.com%3E%0A%0Ahttps%3A%2F%2Fexample.com%0A%0A%3Chttps%3A%2F%2Fgeorge%2Fwiki%2F%3E%0A%0Ahttps%3A%2F%2Fgeorge%2Fwiki%2F%0A
[3]: https://github.com/github/markup#github-markup

**Comment by willstott101** [comment]
Thanks for the the information.

I was in a rush when I wrote this so I didn't take the time to investigate properly. I believe the extension I'm looking for is https://github.com/facelessuser/pymdown-extensions/ so I'll bring it up there.
