### ISSUE TITLE
HR preceeded by ***word*** doesn't render as HR

### ISSUE THREAD

**Issue by kutetapolu** [Python-Markdown/markdown#897]
Input:

```
***test***
***
```

Output (second line will be rendered as a literal `***`):

```html
<p><strong><em>test</em></strong>
***</p>
```

Expected output according to Markdown.pl:

```html
<p><strong><em>test</em></strong>
</p>
<hr />
```

The same problem occurs with `---` and `___` as HR.

I think it can be fixed by changing `RE` in `HRProcessor`:

```diff
497c497
<     RE = r'^[ ]{0,3}((-+[ ]{0,2}){3,}|(_+[ ]{0,2}){3,}|(\*+[ ]{0,2}){3,})[ ]*'
---
>     RE = r'^[ ]{0,3}((-+[ ]{0,2}){3,}|(_+[ ]{0,2}){3,}|(\*+[ ]{0,2}){3,})[ ]*$'
```

**Comment by waylan** [comment]
Here's what [Babelmark][1] shows. Looks like a bug.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=***test***%0A***
