### ISSUE TITLE
attr_list ext strips curly braces from table cells

### ISSUE THREAD

**Issue by mfrigerio17** [Python-Markdown/markdown#898]
Curly braces in the elements of a table get stripped away when the 'extra' extension is loaded

```python
#! /usr/bin/env python3
import markdown
from markdown.extensions.extra import ExtraExtension
from markdown.extensions.tables import TableExtension

text = '''
Try {}

A  |  B
---|---
a{}| b{}

'''

extra = ExtraExtension()
tables= TableExtension()

md = markdown.Markdown(extensions=[tables])
print( md.convert(text) ) # this is fine

print("\n\n")

md = markdown.Markdown(extensions=[tables, extra])
print( md.convert(text) ) # curly braces in the table are stripped
```

The output (comments added manually):
```
<p>Try {}</p>
<table>
<thead>
<tr>
<th>A</th>
<th>B</th>
</tr>
</thead>
<tbody>
<tr>
<td>a{}</td>  -- braces are there
<td>b{}</td>
</tr>
</tbody>
</table>



<p>Try {}</p>  -- these braces are preserved
<table>
<thead>
<tr>
<th>A</th>
<th>B</th>
</tr>
</thead>
<tbody>
<tr>
<td>a</td>  -- braces gone
<td>b</td>
</tr>
</tbody>
</table>
```

Is it an intended behaviour?

**Comment by facelessuser** [comment]
If I had to guess, it would probably be due to the inclusion of the [attr_list](https://python-markdown.github.io/extensions/attr_list/) extension in `extra`. As there is now additional syntax to be aware of, escaping the leading `{` may be the way to go.

Now, should `attr_list` even handle empty `{}`?  That is a good question that  should probably get discussed.

**Comment by waylan** [comment]
Yes, this is specific to the `attr_list` extension, which `extra` includes. What is not clear to me is why this is happening in table cells as it doesn't happen outside of table cells.

That said, things like `a{}` look like code to me and, if it is code, should be enclosed in code spans, which should eliminate the issue. 

```
A       | B
----- | -----
`a{}` | `b{}`
```

Alternatively, as the `attr_list` extension adds the curly brackets as syntax, it also adds support for those characters to be escaped; like this: `a\{}`.

Regardless, the behavior within a table cell should match the behavior outside of one, which it doesn't. So from that perspective we have a bug of sorts.

**Comment by jimporter** [comment]
> Regardless, the behavior within a table cell should match the behavior outside of one, which it doesn't. So from that perspective we have a bug of sorts.

That depends... this is happening because `<td>` is considered to be a "block level" element: https://github.com/Python-Markdown/markdown/blob/66517465786b90ccb7fcffeef7996b593374d889/markdown/core.py#L85

Block level elements are allowed (required?) to have their attr lists put on the same line, so that's why this is happening here. Maybe `<td>` shouldn't be a block level element though...

**Comment by waylan** [comment]
> Block level elements are allowed (required?) to have their attr lists put on the same line

Not true. Of all supported block-level elements, only header (`h1-6`) and `dt` elements can have an attr list on the same line. All other block level elements require the attr list to be on a separate line by itself (specifically the last line).

That said, I see we are special casing `td` elements specifically. 

https://github.com/Python-Markdown/markdown/blob/66517465786b90ccb7fcffeef7996b593374d889/markdown/extensions/attr_list.py#L120-L130

In fact, lines 123 and 124 were added in #267 specifically to ensure `td` elements get treated as inline elements by the attr list extension. Presumably that fix was incomplete as it is matching an empty list. It appears that that is the only place `BASE_RE` is used by itself. Everywhere else, `BASE_RE` is combined with a wrapper that in less likely to result in false matches. We probably need to modify the `td` case to not match an empty list.

**Comment by jimporter** [comment]
Oh, hm. I guess I didn't look closely enough at that code. Oh well. vOv
