### ISSUE TITLE
Inline HTML containing asterisks

### ISSUE THREAD

**Issue by beingryu** [Python-Markdown/markdown#90]
```
>>> markdown.markdown('<p>**test</p>test**')  
u'<p>**test</p>\n\n<p>test**</p>'

>>> markdown.markdown('<span>**test</span>test**')       
u'<p><span><strong>test</span>test</strong></p>'
```

As you can see, that's inconsistent behavior. AFAIK the former is right.

Sorry for my bad english :) Thanks.

**Comment by waylan** [comment]
First, I'll note that the [reference implementation](http://daringfireball.net/projects/markdown/dingus) has the exact same behavior.

In fact, the so-called "inconsistent behavior" is directly inline with the [syntax rules](http://daringfireball.net/projects/markdown/syntax#html). In fact, the rules state in part:

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block. ... Unlike block-level HTML tags, Markdown syntax is processed within span-level tags.

Therefore the `**` inside a `<p>` tag is not even seen by the parser. Whereas, with span level html, the parser makes no assumptions about the html and basically ignores it. If you want markdown and raw html together to result in valid html, then as the document author, it is your responsibility to ensure you provide valid input. In other words, this is a case of bad input, not a bug. I'd suggest using [backslash escapes](http://daringfireball.net/projects/markdown/syntax#backslash) to control the parsing of your input. For example: `<span>\*\*test</span>test\*\*`.

This is being closed wontfix.
