### ISSUE TITLE
Mkdocs build in Travis is failing after release of pymdown-extension v6.3 and markdown v3.2

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [Python-Markdown/markdown#905]
I have configured MKdocs website to be deployed using Travis ci. Its was working correctly till yesterday and build was working fine.

Suddenly today automation build started failing after release of latest version of pymdown-extension 6.3.

Issues in build logs is as follows 

`pkg_resources.VersionConflict: (pymdown-extensions 6.3 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pymdown-extensions<6.3,>=6.2'))`

**Comment by mitya57** [comment]
Something in your requirements specifies the required version of pymdown-extensions as `<6.3,>=6.2`. That is a bug in that requirement, not in Python-Markdown.

**Comment by facelessuser** [comment]
This is a mkdocs-material issue. I worked with them to specifically lock it to not use Markdown 3.2 and pymdown-extensions 6.3 until they released and the theme could be adjusted to account for the new change where both libraries are now changing the output of code blocks to be wrapped with the code tag. It throws off the current styling, so the intent was to help people not break their doc styling until Mkdocs-Material updates to handle this.

**Comment by waylan** [comment]
Thanks for the explanation @facelessuser. 

For future reference, this should have been reported to either pymdown or the theme, not here.
