### ISSUE TITLE
<Code> is also been treated as a block

### ISSUE THREAD

**Issue by yunyuyuan** [Python-Markdown/markdown#915]
**here is some md:**
this is code with blank line
\```python
import re

re.search('','')
\```

**result is:**
&lt;p&gt;this is code with blank line
\```python
import re&lt;/p&gt;
&lt;p&gt;re.search('','')
\```&lt;/p&gt;

seems like blockparser treated code block as paragraph block

**Comment by facelessuser** [comment]
"Fenced" code blocks are not part of the original Markdown spec. Do you have the fenced code extension enabled? https://python-markdown.github.io/extensions/fenced_code_blocks/

Or maybe some other third party fenced coffee extension enabled? https://facelessuser.github.io/pymdown-extensions/extensions/superfences/

If not, they will all be treated as inline.

**Comment by yunyuyuan** [comment]
> "Fenced" code blocks are not part of the original Markdown spec. Do you have the fenced code extension enabled? https://python-markdown.github.io/extensions/fenced_code_blocks/
> 
> Or maybe some other third party fenced coffee extension enabled? https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
> 
> If not, they will all be treated as inline.

Thank you very much!.I didn't read the manual carefully.Even I have wrote some functions to parser that without python-markdown😂
