### ISSUE TITLE
Links: different results for similar structures

### ISSUE THREAD

**Issue by tcpaiva** [Python-Markdown/markdown#916]
Hi,

I have been using `mkdocs` as a documentation hub for a project. And because of that, I got to know python-markdown, which is a very nice tool. To keep the source plain text files easy to read, I like to define links using ids, for example:
```
[this link example][0]
[0]: https://example.com
```

Unfortunately, `mkdocs` has a limited menu structure, which it doesn't support a page tied directly to a parent item in a nested menu (YAML limitation). Since that parent item takes the name from the folder structure directly, I had to write the directory name as multiple words, linke this:
```
this folder/readme.md
```

Then "linking by id" became a bit challenging, because it implies internal links with spaces in it. After playing a bit with python-markdown directly, I think I can summarize my question as the following: why do the alternatives below give me different results? I would expect that all of them would have results similar to the first one.
```
In [10]: a = '[my link](this folder/readme.md)'
In [11]: markdown.markdown(a)
Out[11]: '<p><a href="this folder/readme.md">my link</a></p>' 

In [12]: a = '[my link][1]\n[1]: <this folder/readme.md>'
In [13]: markdown.markdown(a)
Out[13]: '<p>[my link][1]\n[1]: <this folder/readme.md></p>'

In [14]: a = '[my link][1]\n[1]: this folder/readme.md ""'
In [15]: markdown.markdown(a)
Out[15]: '<p>[my link][1]\n[1]: this folder/readme.md ""</p>'
```

Thanks

**Comment by waylan** [comment]
This seems to have been broken in version 3.2. @facelessuser I'm thinking you worked on that stuff. Any input?

**Comment by tcpaiva** [comment]
Wow, thanks for the prompt support!

**Comment by facelessuser** [comment]
While I did rework link logic, I was under the impression that links do not allow spaces? I think we added spaces in image urls, but not normal URLs? Based on my understanding we shouldn't be allowing spaces in the first example? Is that the issue?

I guess I'm trying to identify what we don't like first. I can easily go in and adjust what is broken, but I think I'm looking to have articulated what we don't like as I can't fully remember what we expect.

Based on my memory, the only bug is the first.

**Comment by facelessuser** [comment]
Looking at the code, I modified logic for `[my link](somelink)`, `[link][reference]`, `![image](image)`  I don't think I modified logic for refrences `[ref]: somelink` nor did I modify `<autolinks>`.

I think I may have inadvertently caused both links and img links to use spaces.

**Comment by tcpaiva** [comment]
Hi, thanks again for your prompt answer. I would say that links with spaces are very handy in that situation. Do we have a reason to not like spaces in links? Maybe spaces in this context could be automatically translated to `%20` or something like that?

According to the markdown reference, I think titles should only be recognized when delimited by `""`, `''` or `()`. As in: 
```
[foo]: http://example.com/  "Optional Title Here"
[foo]: http://example.com/  'Optional Title Here'
[foo]: http://example.com/  (Optional Title Here)
```

**Comment by facelessuser** [comment]
This was a call by @waylan. I can't remember the specifics, but most Markdown parsers don't allow spaces in a link. You have to escape a space `%20`. There was some reason why we allowed it in images, but I remember the decision was explicitly to not allow spaces everywhere.

**Comment by facelessuser** [comment]
Whether this is desirable or not, I have a patch that can make sure links are consistent. Images of course would allow spaces as this was explicitly allowed..

```py
>>> import markdown                                                                                                                                                                                                                                                       
>>> markdown.__version__                                                                                                                                                                                                                                                  
'3.2.1'                                                                                                                                                                                                                                                                   
>>> a = '[my link](this folder/readme.md)'                                                                                                                                                                                                                                
>>> markdown.markdown(a)                                                                                                                                                                                                                                                  
'<p>[my link](this folder/readme.md)</p>'                                                                                                                                                                                                                                 
>>> a = '![my link](this folder/readme.img)'                                                                                                                                                                                                                              
>>> markdown.markdown(a)                                                                                                                                                                                                                                                  
'<p><img alt="my link" src="this folder/readme.img" /></p>'                                                                                                                                                                                                               
>>> 
```

As far as titles are concerned, those should work as expected:

```py
>>> a = '[my link][1]\n\n[1]: some/link "title with spaces"'                                                                                                                                                                                                              
>>> markdown.markdown(a)                                                                                                                                                                                                                                                  
'<p><a href="some/link" title="title with spaces">my link</a></p>'    
```

**Comment by facelessuser** [comment]
I'm going to look through the tests. I'm not sure what I remember.

**Comment by facelessuser** [comment]
Crawling back through issues, basically the stance was URLs do not allow spaces. But paths could, so I think we allowed it for images. Thinking about it now, you can have a URL to an image...so I'm not sure what the difference is exactly. We don't actually check if an image path starts with `http:`, we just allow spaces in image syntax while we weren't supposed to allow for normal links.

@waylan any thoughts?

**Comment by tcpaiva** [comment]
Maybe the image issue you refer to is [this one][0], no?

[0]: https://github.com/mkdocs/mkdocs/issues/1908

I think path with spaces get to a similar situation. I think I remember trying to use `%20` but then the  links were not recognized as internal. I am not sure now. I made too many tests to get to that minimal example. x)  

Do you think we could make life of the user easier if spaces are accepted and just automatically translated to `%20`?

PS: I just realized that you guys are working in both projects (mkdocs and python-markdown). Thanks for your hard work  =)

**Comment by facelessuser** [comment]
Ah, I think since we expect a user to use percent escapes, we don't do any further percent escapes. We could for when we accept spaces though. That makes sense.

**Comment by facelessuser** [comment]
From what I can tell through testing, images with spaces not converted to `%20` still work fine. I'm not sure we need to explicitly convert them.

**Comment by tcpaiva** [comment]
Right, I can see that they work. I would say that they work in the same way that `[a link](this folder/afile)` works. My question is why they are not allowed in the other link templates.  

Anyway, this discussion about `spaces` in URLs is endless. According to [this person][0], URI should not contain literal spaces. That seems to be the latest version of these rules.

[0]: https://stackoverflow.com/questions/5442658/spaces-in-urls/5442823#5442823

When I inspect the links in the website generated by the `mkdocs` framework, they seem to have literal spaces. But (surprisingly?) they bring me to the target correctly (at least firefox and chromium).

**Comment by waylan** [comment]
@facelessuser, thanks for the reminder. I had forgotten about that past discussion/decision and didn't have time to look it up earlier.

> This seems to have been broken in version 3.2.

I should have said "changed" rather than "broken" there. Sorry for any confusion I caused.

The behavior we are seeing is intentional and correct as explained by the following examples:

```
[1]: http://example.com Title
```

Note that the title is not deliminated by quotes or parentheses, which causes it to not be recognized as a link reference. This behavior is clearly [supported][1] by most implementations.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%5B1%5D%0A%0A%5B1%5D%3A+http%3A%2F%2Fexample.com+Title

When you surround the link with angle brackets, that does [not change][2]. However, the angle brackets are recognized as an auto link, which is weird, but not wrong from the parser's perspective.

```
[1]: <http://example.com> Title
```

[2]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%5B1%5D%0A%0A%5B1%5D%3A+%3Chttp%3A%2F%2Fexample.com%3E+Title

If you include a space inside the angle brackets, things [get more weird][3], but the reference implementation still does not recognize the line as a link reference.

```
[1]: <http://example.com/foo bar> "Title"
```

[3]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%5B1%5D%0A%0A%5B1%5D%3A+%3Chttp%3A%2F%2Fexample.com%2Ffoo+bar%3E+%22Title%22%0A

The conclusion is that Python-Markdown's behavior is correct. As a reminder, Markdown does **not** percent encode URLs in links, nor should it. The document author is expected to do that manually. So, yeah, there should be no spaces in URLs. Therefore, the correct input should be:

```
[1]: <http://example.com/foo%20bar> "Title"
```

And that [works as expected][4]:

```
<p><a href="http://example.com/foo%20bar" title="Title">foo</a>
</p>
```

[4]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%5B1%5D%0A%0A%5B1%5D%3A+%3Chttp%3A%2F%2Fexample.com%2Ffoo%2520bar%3E+%22Title%22

**Comment by facelessuser** [comment]
@waylan should I fix the issue where this is parsing for a normal link?

```
In [10]: a = '[my link](this folder/readme.md)'
In [11]: markdown.markdown(a)
Out[11]: '<p><a href="this folder/readme.md">my link</a></p>' 
```

I know we accept the space for image links, but I was under the impression we should not for normal links?

**Comment by waylan** [comment]
> should I fix the issue where this is parsing for a normal link?

Yes, that is a bug. See [Babelmark][1].

I suspect that difference is what prompted this report. If the behavior had been consistent, @tcpaiva might not have thought spaces were okay within URLs.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bmy+link%5D(this+folder%2Freadme.md)

**Comment by facelessuser** [comment]
Yep, I'll take on this task.

**Comment by tcpaiva** [comment]
I still have some questions. But I am making some tests here before saying something. I hope you don't mind.

**Comment by tcpaiva** [comment]
> Note that the title is not deliminated by quotes or parentheses, which causes it to not be recognized as a link reference. This behavior is clearly [supported](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%5B1%5D%0A%0A%5B1%5D%3A+http%3A%2F%2Fexample.com+Title) by most implementations.

Yes, I agree that quotes are required for `title`, if used.

> When you surround the link with angle brackets, that does [not change](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%5B1%5D%0A%0A%5B1%5D%3A+%3Chttp%3A%2F%2Fexample.com%3E+Title). However, the angle brackets are recognized as an auto link, which is weird, but not wrong from the parser's perspective.
> 
> ```
> [1]: <http://example.com> Title
> ```

I think we should not consider this case, since we agreed that quotes around title are required.

> If you include a space inside the angle brackets, things [get more weird](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%5B1%5D%0A%0A%5B1%5D%3A+%3Chttp%3A%2F%2Fexample.com%2Ffoo+bar%3E+%22Title%22%0A), but the reference implementation still does not recognize the line as a link reference.
> 
> ```
> [1]: <http://example.com/foo bar> "Title"
> ```

Surprisingly, some of the results were able to track the URL correctly, mainly if you disconsider the difference between `foo bar` and `foo%20` in results. At least they did not include the `<>` )(encoded or not).
 
> The conclusion is that Python-Markdown's behavior is correct. As a reminder, Markdown does **not** percent encode URLs in links, nor should it. The document author is expected to do that manually. So, yeah, there should be no spaces in URLs. Therefore, the correct input should be:
> 
> ```
> [1]: <http://example.com/foo%20bar> "Title"
> ```

Assuming it is an external link, OK, the person will just copy and paste there, which will probably come with `%20` as it should. For internal links in the `mkdocs` context, this is not so true. I wonder if it would be more user-friendly to just accept both of them and when finding spaces, replace it by `%20` (as you already probably do for pictures). I mean, if it is clear what the user is trying to do, why not just take it?

Moving to the `mkdocs` context, I made these additional tests:

```
1. [link](my test/README.md)
2. [link][2]
3. [link](my%20test/README.md)
4. [link][4]
5. [link][5]

[2]: <my test/README.md>
[4]: my%20test/README.md
[5]: <my%20test/README.md>
```
Generated links follow:
1. `https://tcpaiva.web.cern.ch/my%20test/`
2. `[link][2]` (no link)
3. `https://tcpaiva.web.cern.ch/my%20test/README.md`
4. `https://tcpaiva.web.cern.ch/my%20test/README.md`
5. `https://tcpaiva.web.cern.ch/my%20test/README.md`

With these warnings in the `mkdoc` compilation process:
```
WARNING -  Documentation file 'README.md' contains a link to 'my%20test/README.md' which is not found in the documentation files.
WARNING -  Documentation file 'README.md' contains a link to 'my%20test/README.md' which is not found in the documentation files.
WARNING -  Documentation file 'README.md' contains a link to 'my%20test/README.md' which is not found in the documentation files.
```

(1) is correct. (3), (4) and (5) seem fine but they actually target a raw `.md` file, which ti is not part of the website. Maybe this is a `mkdocs` issue instead?

BTW, is it documented how to handle spaces on the path of the link in `mkdocs`? I was not able to find it and I had to resort into trial & error.

Sorry for the long post. Thanks!

**Comment by facelessuser** [comment]
@waylan So I looked and found an old test from Yuri:

```
[Dawn of War](http://wikipedia.org/wiki/Dawn of War)


[Dawn of War](http://wikipedia.org/wiki/Dawn of War "Dawn of War")
```

```html
<p><a href="http://wikipedia.org/wiki/Dawn of War">Dawn of War</a></p>
<p><a href="http://wikipedia.org/wiki/Dawn of War" title="Dawn of War">Dawn of War</a></p>
```

So I guess URL have always accepted spaces? It explains why I implemented the rework like I did, because trying to fix it breaks old tests. Now I'm wondering if references `[ref]: link` should match this as well.

![sublime_merge_61LFS3Ryds](https://user-images.githubusercontent.com/1055125/75314195-48af5480-581c-11ea-9984-360bf6f4c1c4.png)

So I'm leaving things as is for now. Right now I'm not sure what, if anything there is to fix.

**Comment by waylan** [comment]
So that was part of 0a1c1b5a, which added 5,116 lines in 136 files. Note that there are no behavioral changes in the commit. It was the initial commit of tests unique to Python-Markdown, which tested the actual behavior of the parser at that time. This was way back when we thought that the original Markdown rules would continue to evolve. I don't consider that commit to be a hard rule in expected behavior. There are multiple errors in those tests including this one.

That said, there are potentially many existing documents which rely on the behavior which would break if we made a change. So, for backward compatibility purposes only, I'm willing to leave the behavior as-is. However, we are not adding the behavior anywhere it does not already exist. Spaces in URLs should be percent escaped.

**Comment by tcpaiva** [comment]
Thanks for looking into this, @waylan. I understand your point, but I think I see it in a different way. For users of the `mkdocs` framework, things get a bit backwards, for example the user has to know the exact URL of the link beforehand to do as you suggest. Which is not always obvious, since `mkdocs` changes the path a bit (like removing  `index.html` or converting the filename to a folder-like name). Maybe it is a pre-processing stage that `mkdocs` should take care of, I don't know. Anyway, thanks again. =)
