### ISSUE TITLE
`tables` missing from list of registered extensions

### ISSUE THREAD

**Issue by AnjoMan** [Python-Markdown/markdown#917]
When i get a `Markdown` object with the extension, i expect the extensions to show up in the list of registered extensions -- however, only some of them do. for example:

```python
md = Markdown(extensions=["footnotes", "tables"])
md.registeredExtensions
>>> [<markdown.extensions.footnotes.FootnoteExtension object at 0x7f5ebec97898>]
```

The footnotes extension, which is built into `markdown`, shows up in the list, however the `tables` extension does not.

This means I can't make a new Markdown object that copies the same extensions, e.g. by doing

```python
md2 = Markdown(extensions=md.registeredExtensions)
```

**Comment by facelessuser** [comment]
Not all extensions "register" for reset events.

**Comment by AnjoMan** [comment]
@facelessuser are you saying that the `registeredExtensions` attribute is not intended to list the extensions that were registered when the object was created? 

i know that when I make a `Markdown` object, all the extension names / objects are passed into the `registerExtensions` method, and that this is how they are able to modify the way the `convert` function processes inputs. so it seems like they are all registered, by one meaning of the word at least.

in any case, I guess I'm still wondering how I could know what extensions the object was created with.

**Comment by facelessuser** [comment]
Yup, that is what I'm saying. You can explore the processor objects in the class, but the class wasn't really designed to provide the info that you desire in the way you are doing things. I'm not near my computer, but when I am, maybe tomorrow, I can kind of illustrate what you can do.

People have proposed before to have all extensions automatically registered, even if they don't need to have reset events, but I don't recall what the decision was. Obviously they don't auto register now, but I don't remember if there was a decision against it.

**Comment by AnjoMan** [comment]
thanks @facelessuser ! just for context, I'm working on the `mkautodoc` extension, which injects function signatures and markdown docstrings into the document. currently it makes a new Markdown object to render the docstring, but if there is a way of using the one that `markdown` makes, that would be a good alternative. I tried just calling `.convert` but it seems like this interferes with the existing object state

**Comment by facelessuser** [comment]
Maybe it would be better to take this to chat instead of creating noise in this issue? Can you pop over here and maybe join the discord chat server? There's a link via one of the badge icons. Just explain what you need there and I can offer some suggestions.

https://github.com/facelessuser/pymdown-extensions

**Comment by waylan** [comment]
@facelessuser is correct. Extensions only need to register if they include a `reset` method. When `Markdown.reset` is called, all registered extensions get their `reset` method called. That is the one-and-only purpose of registering an extension (see [here][0] for how `reset` is used). Therefore, any extension which does not have a `reset` method does not need to be registered. 

Note that the connection between "registering" and `reset` is made repeatedly in the [documentation][1]. Also note that the documentation indicates that you must explicitly call `md.registerExtension(self)` if your extension needs to be registered. Therefore, it should be clear that extensions do not get "registered" by default.

If it helps, there are two sets of extensions: (1) "enabled"<sup>1</sup> extensions and (2) "registered" extensions. "Enabled" extensions are all extensions which the user has enabled for a `Markdown` instance. "Registered" extensions are a subset of the "enabled" extensions which explicitly include support for `reset`. The `Markdown` instance does not retain a list of all "enabled" extensions.

- - -

<sup>1</sup> To be clear, "enabled" is not any official term we use internally. I am simply using the term here for clarity. Internally, we just call them "extensions."

[0]: https://python-markdown.github.io/reference/#convert
[1]: https://python-markdown.github.io/extensions/api/#registerextension
