### ISSUE TITLE
Double underscores are re-rendered as strong in a highlighted code block

### ISSUE THREAD

**Issue by pawamoy** [Python-Markdown/markdown#920]
So, the context is very specific.

I'm currently working on [mkdocstrings](https://github.com/pawamoy/mkdocstrings). It's a plugin for mkdocs plus a markdown extension that allows to inject documentation in pages with the `::: identifier` syntax.

The full syntax is:

```
::: .*
    [YAML data]
```

...so I'm registering a BlockProcessor to easily get the YAML lines below the `:::` line.

When reading such blocks, the extension uses a particular "handler" to collect data about the identifier (for the Python language, it uses [pytkdocs](https://github.com/pawamoy/py-tkdocs) to recursively collect documentation for the related Python object).

Then, it uses these data to render Jinja templates, and load them back into the current `parent` element with `parent.append(XML(rendered))`.

The problem is that double underscores in highlighted code blocks (such as in `__init__`) are rendered again as `<strong>init</strong>` in the final output.

It happens somewhere here:

https://github.com/Python-Markdown/markdown/blob/c282d46a65996f38cfc66f01c2cfced0cddd9e57/markdown/core.py#L267-L294

I couldn't track it more precisely because PyCharm won't let me see the `_children` protected variable of `xml.etree.ElementTree.Element` instances, making it really hard to navigate into the tree to see what changes or not.

But I believe the (or an) InlineProcessor, which is also a TreeProcessor as stated in the docs, is responsible for this change.

As said before, my extension is currently registering a BlockProcessor. Would my issue be fixed if I used a TreeProcessor instead? Would it still be easy to read the `::: identifier` lines followed by YAML indented by four spaces? Or should I simply lower the priority of my extension, currently at 110? Reading the source, it seems that TreeProcessors are always executed after BlockProcessors, so changing the priority wouldn't change anything I guess.

Any help is appreciated :slightly_smiling_face: 

And thank you very much for this great Python package! 

Markdown version 3.2.1.

**Comment by facelessuser** [comment]
Once you process it in your block processor, are you expecting no other processors to touch it? Normally, once a block has been processed, it will be run through other processors, like inline processors, which may look for `__text__` and turn it to `strong` elements. What is your intention? There are ways to format content to not be touched further, but I need to understand what your intention is.

**Comment by pawamoy** [comment]
I think I can safely expect that no other processor touches it, since I render pure HTML.

My intention is really to generate HTML and append it to the tree.

**Comment by pawamoy** [comment]
It might again be an issue with using Pygments for highlighting. If I set `use_pygments=False` when instantiating a `pymdownx.highlight.Highlight` class, the `__init__` stays as is (though the code is not highlighted, but it might just be because the material theme does not provide the javascript to do so).

**Comment by facelessuser** [comment]
Are you using `pymdownx.highlight` in your plugin? If so, you may want to take this over to that repo (I'm the author of it).

The plugins that use it either stash the contents like it does in SuperFences: https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/superfences.py#L870 or InlineHilite: https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/inlinehilite.py#L143.

**Comment by pawamoy** [comment]
Yes I'm using `pymdownx.highlight`, I found it to be much easier to use in Python code than `CodeHilite`.

About `md.htmlStash.store`: since I parse again the generated HTML from Jinja templates into XML, I get this parsing error because of placeholders edges characters:

```
File "/home/pawamoy/data/dev/pawamoy/mkdocstrings/src/mkdocstrings/extension.py", line 53, in run
    as_xml = XML(rendered)
  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.6.9/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 33, column 0
```

(Just writing my progress here)

**Comment by waylan** [comment]
I'm assuming you are building your XML using ElementTree elements. In that case, assigning the string `__init__` to the element's `text` attribute will cause that text to be parsed as Markdown inline bold. That is how it is [documented][1] and how it is supposed to work:

> Sometimes you may want text inserted into an element to be parsed by Inline Patterns. In such a situation, simply insert the text as you normally would and the text will be automatically run through the Inline Patterns. However, if you do not want some text to be parsed by Inline Patterns, then insert the text as an `AtomicString`.
> 
>     from markdown.util import AtomicString
>     some_element.text = AtomicString(some_text)



[1]: https://python-markdown.github.io/extensions/api/#working_with_et

**Comment by waylan** [comment]
> As said before, my extension is currently registering a BlockProcessor. Would my issue be fixed if I used a TreeProcessor instead? Would it still be easy to read the `:::` identifier lines followed by YAML indented by four spaces? Or should I simply lower the priority of my extension, currently at 110? Reading the source, it seems that TreeProcessors are always executed after BlockProcessors, so changing the priority wouldn't change anything I guess.

If you used a TreeProcessor which ran after the `InlineProcessor` TreeProcessor, yes, that would prevent inline patterns from being run on your additions to the tree. However, It's not clear to me if that is a viable option for what you are trying to do.

**Comment by pawamoy** [comment]
So a brute-force solution would be to cast every `text` attribute with `AtomicString` :smile: 

I'm not asking you to study the architecture of my plugin, but here is a helpful diagram I believe, if you want to take a look: https://github.com/pawamoy/mkdocstrings/issues/28#issuecomment-600574760

I'll keep the BlockProcessor for now, and play with hightlighting options a bit more. Thanks :slightly_smiling_face:

**Comment by pawamoy** [comment]
I went with brute-casting everything to `AtomicString` :stuck_out_tongue: 

Thanks again @waylan EDIT: and @facelessuser, (forgot :cold_sweat:)
