### ISSUE TITLE
Block-level custom elements?

### ISSUE THREAD

**Issue by ghost** [Python-Markdown/markdown#925]
Version: Markdown 3.2.1, Python 3.7.

Block-level markdown processing works with markdown="1", but custom elements are assumed to be inline, which means block-level custom elements don't work; input:
````
<expand-note markdown="1">
```
inner text
```
</expand-note>
````
with `markdown.markdown(text, extensions=['fenced_code', 'md_in_html'])`, produces:
```
<p><expand-note markdown="1"></p>
<pre><code>inner text
</code></pre>

<p></expand-note></p>
```
Which of course causes browsers to insert a `</expand-note>` right after it opens. I've also tried `markdown="block"` and it gives the same behavior. It works with a standard block-level element, like `div`.

Is there a way I can solve this wthout editing the library's source code, or should I use [mistune](/lepture/mistune)?

**Comment by waylan** [comment]
Right. `markdown=1` (and variants) only work on known (valid) block-level tags as defined by the HTML5 spec. If you wanted to expand the list of tags, then you would need to add items to `markdown.Markdown().block_level_elements`, which is defined here:

https://github.com/Python-Markdown/markdown/blob/c116cfcca8bf610b643cbc7eafe9228f7a832fc3/markdown/core.py#L76-L86

Should be simple to do with an extension.

**Comment by ghost** [comment]
Thanks!
