### ISSUE TITLE
Admonition extension preventing ToC from rendering in Material for MkDocs

### ISSUE THREAD

**Issue by blakadder** [Python-Markdown/markdown#930]
I've created a tiny build at https://github.com/blakadder/docs-test to showcase the bug mentioned in https://github.com/squidfunk/mkdocs-material/issues/1563

- index.md shows the bug
- fix1 and fix2 show when the bug is not occurring

**Comment by facelessuser** [comment]
@blakadder, this is working according to the Markdown rules in place. Please place a new line between your headers and your admonitions if you'd like for them to work properly.
