### ISSUE TITLE
Less/greater than signs in headings appear as &lt/&gt in TOC

### ISSUE THREAD

**Issue by p-ouellette** [Python-Markdown/markdown#931]
![screen](https://user-images.githubusercontent.com/21223385/78505736-781e7e80-7743-11ea-9433-ef936c433e97.png)

That's an mkdocs site with the readthedocs theme. It's using git master HEAD of mkdocs and markdown. The issue was caused by  https://github.com/Python-Markdown/markdown/commit/74c0166c6903b07b3b2b9cbba36705d1414cbaf7. I haven't tested this using just markdown so it might be related to mkdocs.

**Comment by facelessuser** [comment]
What version of Markdown are you using? I'm not seeing this in the current version.

<img width="1050" alt="chrome_pMDuMrFSF6" src="https://user-images.githubusercontent.com/1055125/78508566-0c3d1580-7745-11ea-81be-d4e0369959f1.png">

**Comment by waylan** [comment]
I just tested the `readthedocs` theme with the latest on master and do not see the issue.

![Screen Shot 2020-04-05 at 5 08 23 PM](https://user-images.githubusercontent.com/78846/78510020-449e1d00-7760-11ea-8940-943768896071.png)

Note that in the picture you can see the Markdown text, the TOC and the main body. All appear correct.

**Comment by p-ouellette** [comment]
Reproduced using just markdown 3.2.1:
```bash
echo -e "[TOC]\n# `<test>`" | python -m markdown -x toc
```
```html
<div class="toc">
<ul>
<li><a href="#lttestgt">&amp;lt;test&amp;gt;</a></li>
</ul>
</div>
<h1 id="lttestgt"><code>&lt;test&gt;</code></h1>
```
With markdown 3.2 the above command outputs:
```html
<div class="toc">
<ul>
<li><a href="#lttestgt">&lt;test&gt;</a></li>
</ul>
</div>
<h1 id="lttestgt"><code>&lt;test&gt;</code></h1>
```

**Comment by waylan** [comment]
Ah, I missed that that was a code span. It would appear that code spans were not being considered in [this comment][1]. We do need the smart escape after all.

[1]: https://github.com/Python-Markdown/markdown/issues/906#issuecomment-583642050

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by facelessuser** [comment]
Okay, I guess my results were different as I'm using `pymdownx.inlinehilite`. It uses the `htmlstash` instead of `AtomicString`. I guess there is a difference in how those get handled...

**Comment by facelessuser** [comment]
I guess `htmlstash` must work while `AtomicString` does not due to the fact that the `htmlstash` placeholders don't get cleaned up until after the toc is generated. I imagine it just duplicates the placeholder, and the placeholders get replaced with the content post toc.

So yeah, we generally need a solution when handling AtomicStrings. I assume we can just detect AtomicString types and not escape them? I don't think we specifically need a smart escape.

**Comment by facelessuser** [comment]
I'll take a stab at it.

**Comment by facelessuser** [comment]
Yeah, I think all we really need is something like this:

```py
def get_name(el):
    """Get title name."""

    text = []
    for c in el.itertext():
        if isinstance(c, AtomicString):
            text.append(html.unescape(c))
        else:
            text.append(c)
    name = ''.join(text).strip()
    return name
```

This prevents us from getting weird ids such as `lttestgt` Which we previously got from `` `<text>` ``. And it returns a string that we can handle sanely. It just unescapes Atomic strings with `html.unescape` which uses html5 rules for entities (py34+).
