### ISSUE TITLE
Docs: Nature theme doesn't support latest change in CodeHilite

### ISSUE THREAD

**Issue by facelessuser** [Python-Markdown/markdown#936]
Not sure if it is already known, but our docs currently render code incorrectly (color wise). This is due to the change of wrapping `<code>` in `<pre>` by default now. Did we want to add some extra CSS and/or create an issue on the Nature theme?

**Comment by waylan** [comment]
Yeah, an issue on the theme would be appropriate which can be linked to from here so we can track it.

**Comment by facelessuser** [comment]
Do we want a stop gap fix with some extra CSS? Or do we not care?

**Comment by waylan** [comment]
I generally only rebuild the docs on a release, so a stop-gap isn't likely to move things any faster. The theme is pretty small and a release could happen anytime.

**Comment by facelessuser** [comment]
Sure, I'll see how responsive the nature theme author is.

**Comment by facelessuser** [comment]
I just realized you are the maintainer of the nature theme :laughing:.

**Comment by waylan** [comment]
Version 0.4 was just released. With the next documentation build we will get the fix.
