### ISSUE TITLE
enabled_tags configuation option for md_in_html

### ISSUE THREAD

**Issue by Gittenburg** [Python-Markdown/markdown#937]
I am using python-markdown for a project where the Markdown is also converted to PDF with pandoc. Since pandoc does not support the admonition syntax of python-markdown (jgm/pandoc#2610), I use custom HTML tags (`<warning>`, `<important>`, `<tip>`) instead which are easy to write a filter for in Pandoc. I enabled the tags by setting `block_level_elements` and would like to enable Markdown parsing inside them by default, so that we don't always have to specify the `markdown` attribute.

Would you accept a pull request adding an `enabled_tags` configuration option to the `md_in_html` extension? `MarkdownInHtmlExtension(enabled_tags=['warning'])` would enable Markdown in `<warning>` tags by default.

**Comment by waylan** [comment]
No. However this sounds like a great candidate for a third party extension. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
