### ISSUE TITLE
Automatically resize the image

### ISSUE THREAD

**Issue by ironrootx** [Python-Markdown/markdown#938]
When I was blogging with markdown, I found that the inserted images, converted into HTML, could not be automatically resized according to the size of the window, so the images were too large for my phone to view.

#### markdown
`![mark](http://cdn.earthseeker.cn/blog/20200412/5KGvtyNJEst3.jpg?imageslim)`

#### HTML
`<p><img alt="mark" src="http://cdn.earthseeker.cn/blog/20200412/5KGvtyNJEst3.jpg?imageslim"></p>`

### Solution.  Add a "style" attribute to the image tag

markdown/markdown/inlinepatterns.py 

**773line**
`el.set('alt', self.unescape(text))`
**add**
` el.set('style', 'width:100%;height:100%;')`

**Comment by mitya57** [comment]
You can specify whatever style you want with the Attribute Lists extension, see [this example](https://python-markdown.github.io/extensions/attr_list/#inline).

It is not the job of Markdown parser to add custom style attributes.
