### ISSUE TITLE
pkg_resources performance issues

### ISSUE THREAD

**Issue by tgbugs** [Python-Markdown/markdown#942]
https://github.com/pypa/setuptools/issues/510

https://github.com/Python-Markdown/markdown/blob/ada40c6619fd0be740af646b043937e560716c95/markdown/core.py#L26

One potential fix (that I have implemented manually) is to move the import statement inside https://github.com/Python-Markdown/markdown/blob/ada40c6619fd0be740af646b043937e560716c95/markdown/core.py#L154 and add an if statement to check it has already been imported and assigned as an instance variable.

**Comment by waylan** [comment]
A PR is welcome. And if you can provide some performance data with the PR that would be helpful.

**Comment by mitya57** [comment]
It may be also worth to switch to [importlib.metadata] module from the standard library, to get rid of `pkg_resources` runtime dependency. It is new in Python 3.8, but there is a backport to older versions too.

I haven't measured the performance though, but I expect that it will be definitely not slower than `pkg_resources`.

[importlib.metadata]: https://docs.python.org/3/library/importlib.metadata.html

**Comment by waylan** [comment]
I hadn't seen `importlib.metadata` before. Cool! Thanks for the pointer.
