### ISSUE TITLE
Understanding move to Extensions Registry?

### ISSUE THREAD

**Issue by merriam** [Python-Markdown/markdown#944]
I'm trying to understand why the utils registry went from the array looking system to a strict 'register/deregister' methods?

Viewing the register as an array of items, with the semantics for appending (to lowest priority), deleting (with `del`), replacing and iterating seemed very pythonic.  The `add()` function did have its wart of the '>other_filter' syntax; it seems to want keyword only `before` and `after` arguments.   In contrast the `register()` argument seems to require separate calls to determine the priority or just hardcoding numbers after reading the markdown source.

I feel like I'm missing something.   If it just code issues, would you welcome a pull request?

**Comment by waylan** [comment]
This was discussed extensively in #418 and #688. I think the title of #688 sums up the primary motivation for the change. We also discuss some of the problems with using `before` and `after`. In the end, hardcoding numbers provide way more flexibility. I wouldn't ever want to go back.
