### ISSUE TITLE
Incorrectly parsed inline code blocks

### ISSUE THREAD

**Issue by libka-b** [Python-Markdown/markdown#947]
Hello, suppose you have a code block like this:

> \`\`\`
>from markdown import markdown
>
>
>html = markdown("# blabla")
>\`\`\`

which should be rendered in markdown as:

```
from markdown import markdown

html = markdown("# blabla")
```

So it should turn into something like this in html:
```
<code>
from markdown import markdown

html = markdown("# blabla")
</code>
```

However what it actually turn into is this:
```
<p>```
from markdown import markdown</p>
<p>html = markdown("# blabla")
```</p>
```
which is clearly a bug.

**Comment by waylan** [comment]
Fenced code blocks are not a feature of the [standard Markdown Syntax][1]. However, they are supported by Python-Markdown with the [fenced_code][2] extension.

[1]: http://daringfireball.net/projects/markdown/syntax
[2]: https://python-markdown.github.io/extensions/fenced_code_blocks/
