### ISSUE TITLE
HTML5 entities without semicolon ';'

### ISSUE THREAD

**Issue by darkdragon-001** [Python-Markdown/markdown#952]
Some often-used HTML5 entities are defined/allowed in a version without the semicolon at the end: https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references

When I parse such an entity with `markdown()`, it is translated to `&amp;ENTITY` instead of staying `&ENTITY`. When using the version with semicolon it works.

When you need a list of such entities, you can generate it with the following code:

    import html
    for k in html.entities.html5:
        if k[-1]!=';':
            print(k)

**Comment by waylan** [comment]
According to [Babelmark][1], the current behavior is completely consistent with all Markdown implementations, including the reference implementation. Therefore, this is the expected behavior, not a bug. It is always better to be more explicit.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%26amp%3B%0A%0A%26amp%0A

**Comment by darkdragon-001** [comment]
Markdown claims to be compatible with HTML. HTML5 didn't exist when the reference implementation of Markdown was released. HTML5 is now standardized and released, so the new standard should be adapted. Just because other projects didn't implement the new standard doesn't mean one shouldn't start with it one self. While I agree that it is better to be more explicit, I would welcome the compatibility with the HTML standard very much!

**Comment by waylan** [comment]
As a reminder, the entire parser is overridable by extensions. If this is important to someone, they can implement an extension which provides the requested behavior.

However, Python-Markdown is not a pioneer in exploring new features. While we provide an extension API, the base parser is very conservative. The place to explore these things are in extensions, which anyone can do without the need to involve the core dev team.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
