### ISSUE TITLE
Markdown does not create W3C compliant URIs

### ISSUE THREAD

**Issue by igalic** [Python-Markdown/markdown#96]
I know this might be a little pretentious, but I'd like to be able to write readable URIs, such as:

```
mail to [dev@](mailto:dev@trafficserver.apache.org?subject=[PATCH] fix to docs or site).
```

And have Markdown create HTML output that is W3C compatible such as:

```
mail to<a href="mailto:dev@trafficserver.apache.org?subject=[PATCH]%20fix%20to%20docs%20or%20site">dev@</a>.
```

instead of:

```
mail to <a href="mailto:dev@trafficserver.apache.org?subject=[PATCH] fix to docs or site">dev@</a>.
```

**Comment by SimonSapin** [comment]
Adding a call to urllib.quote() somewhere should be easy, but there is an obvious risk of double-quoting.

`[a](b c)` should probably be quoted, but not `[a](b%20c)` (it is already). But guessing is dangerous: what about `[a](b c%20d)`? To avoid guessing, there should be a different syntax to mark URLs that need to be quoted and those that are already. But then I’m not sure it is a good idea.

**Comment by waylan** [comment]
I understand the reasoning behind wanting this, but Python-Markdown is a python implementation of the reference implementation ([markdown.pl](http://daringfireball.net/projects/markdown/)). As such, our behavior is going to match the reference implementation, which it does in this case.

Given the added risk of double-quoting mentioned in the comment above, I can't see any way to justify making this addition. If you want to have a href which is valid, then you need to author a valid href to begin with. In that regard, note this bit from the [syntax documentation](http://daringfireball.net/projects/markdown/syntax#html):

> Markdown is not a replacement for HTML, or even close to it. Its syntax is very small, corresponding only to a very small subset of HTML...

The point is that if you want anything beyond what markdown already provides, you should just use html. I think the same reasoning applies here. Of course, we also provide a very nice [Extension API](http://packages.python.org/Markdown/extensions/api.html) so you could easily write a simple extension which implemented this behavior. 

I'm closing this as wontfix.
