### ISSUE TITLE
Abbreviations are not keyboard friendly

### ISSUE THREAD

**Issue by galaxy4public** [Python-Markdown/markdown#960]
It would be really nice if the Abbreviations extension would generate keyboard friendly code, e.g. instead of:
`<abbr>title="Cascading Style Sheets">CSS</abbr>`
it would be much nicer to produce:
`<abbr>title="Cascading Style Sheets" tabindex="0">CSS</abbr>`

This way it would be possible to focus on the abbreviation using keyboard (or any other input device that moves focus).

Of course, the best implementation should allow to enable this conditionally (not everyone likes their focus flow to be unexpectedly modified by inserting abbreviations into it).  I think the following definition (which is in line with other implementations of extendable markdown syntax) would be sufficient:
`*[CSS]{tabindex=0}: Cascading Style Sheets` (basically, I am proposing to borrow the idea from how Markdown handles images and allows authors to specify classes and attributes for the generated tags)

**Comment by waylan** [comment]
Interesting. So I suppose this is an accessibility issue which means we shouldn't ignore it. How is this generally handled in HTML? I don't want to be reinventing the wheel here. I'd like to see some existing solutions.

**Comment by galaxy4public** [comment]
According to my research the majority of websites who are concerned about accessibility are using the following:

  - for desktop browsers where a pointer with ":hover" capability is present the standard `<abbr>` tag works fine
  - for screen readers the `title` attribute of the `<abbr>` element is read out after the content of the tag
  - for touch devices with no ":hover" capability the following block is enough to make `<abbr>` work on tap (I am not providing additional styling to make it nice):
```
@media (any-hover: none) {
abbr[title]:hover::after {
    content: attr(title);
    position: absolute;
}
}
```
   - the only accessibility issue with the current state of the `<abbr>` tag in Python Markdown is that it is not possible for keyboard users to get to the `title` attribute by any means -- they cannot focus on the element since to do so the element is supposed to have the `taborder` attribute to be non-negative (usually, one should use `tabindex="0"` to ensure that the element is inserted into the focus flow according to the layout.

The last item on this list is why I raised the issue, but when I thought about it, I think that if we are implementing something like this it should be a bit more generic, hence I proposed to re-use the way how the images I handled, i.e. `*[ABBRV]{tabindex="0"}: Description of the abbreviation`.

Hope this helps.

**Comment by galaxy4public** [comment]
The reason why the touch devices need the `@media` query is to ensure that on any other device with the pointer that has the ":hover" capability a user won't be presented with two tooltips (one is generated by the browser and another defined by the stylesheet).  Since on touch devices there are no tooltips for `<abbr>` we generate one using CSS.

**Comment by waylan** [comment]
When I asked this:

> How is this generally handled in HTML? I don't want to be reinventing the wheel here. I'd like to see some existing solutions.

I meant: please point me to other places where this solutions being used. Or point me to other solutions which are being used elsewhere. In other words, are other people solving this with `tab index` or are they using some other solution? I want to see links to real world examples. Not just an explanation of how you believe it should work, which was already sufficiently clear to me.

>  proposed to re-use the way how the images I handled,

I'm assuming you are referring to the [`attr_list`][1] extension. That is certainly a reasonable solution, but then that should work only when the `attr_list` extension is enabled by the user. In fact, that does already work:

```python
>>> import markdown
>>> scr = '''
... Some text ABBR{ tabindex='0' } more text.
...
... *[ABBR]: Abbreviations
... '''
>>> markdown.markdown(scr, extensions=['abbr', 'attr_list'])
'<p>Some text <abbr tabindex="0" title="Abbreviations">ABBR</abbr> more text.</p>'
```

Actually, that makes more sense that setting the tab index on the reference. As a reminder, you can have the same abbreviation repeated multiple times in a document. They can't all have the same tab index. By defining the tab index in the body of the document rather than the reference, you can set the tab index where it makes the most sense (perhaps on the first occurrence).

[1]: https://python-markdown.github.io/extensions/attr_list/

**Comment by galaxy4public** [comment]
First of all, I believe the best practice is actually only use the same `tabindex="0"` for focusable elements, this is from Google best practices: https://web.dev/tabindex/

Well, the links I can point to are:
  - https://bitsofco.de/making-abbr-work-for-touchscreen-keyboard-mouse/ (but the same author revised the approach in 2019 - https://bitsofco.de/revisiting-the-abbr-element/)
  - https://webaim.org/discussion/mail_thread?thread=6901 (a thread on keyboard only users)
  - https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/ (on whether tabindex for titles are good or bad)

Anyway, I think we can close the issue since what I wanted to achieve can be implemented (as you rightfully pointed out) with the `attr_list` extension.
