### ISSUE TITLE
Can you ignore a block?

### ISSUE THREAD

**Issue by domeniko-gentner** [Python-Markdown/markdown#963]
I have 2 blocks starting with certain patterns. I would like to simply ignore them for the next pass with a different parser. What would be the simplest way to ignore it? 

I have tried writing an extension, but tbh, the documentation is too sparse to really get it.
Would appreciate some help.

Here is an example:

```
{{ string }}
{{ string }}
{% string %}
{% string %}
```

**Comment by domeniko-gentner** [comment]
Alternatively, how can I make markdown not put existing html code inside a `<pre>` block?

**Comment by waylan** [comment]
You may want to check out some of the [math extensions][1] which do exactly what you are asking for. Of course, the skip math blocks, whereas you want to skip template blocks, but the basic concept is the same.

[1]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#math--latex
