### ISSUE TITLE
Incorrect output when HTML is broken

### ISSUE THREAD

**Issue by andreikop** [Python-Markdown/markdown#97]
When processing text below, original markdown and markdown_py produces different otuput. And, I think, markdown output is better...

----------- source
<table>
    tag is incorrectly closed
<table/>
## **but this line must be strong**

------------------markdown_py output
<table>
    tag is incorrectly closed
<table/>
## **but this line must be strong**

--------------------markdown output

<p><table>
    tag is incorrectly closed
<table/></p>

<p><strong>but this line must be strong</strong></p>

---

**Comment by andreikop** [comment]
Oops, bad idea to paste markdown blocks to markdown preprocessor.

When processing text below, original markdown and markdown_py produces different otuput. And, I think, markdown output is better...
source:

```
<table>
    tag is incorrectly closed
<table/>

**but this line must be strong**
```

markdown_py output:

```
<table>
    tag is incorrectly closed
<table/>

**but this line must be strong**
```

markdown output

```
<p><table>
    tag is incorrectly closed
<table/></p>

<p><strong>but this line must be strong</strong></p>
```

**Comment by waylan** [comment]
This is an interesting edge case and I'm not sure that either Python-Markdown or markdown.pl do the right thing. For example, markdown.pl wraps a `<table>` in a `<p>` which results in invalid html. While it is true that the raw HTML is invalid anyway, markdown should not generate invalid html - which markdown.pl does here.

On the other hand, Python-Markdown generates valid HTML, leaving the raw (invalid) HTML untouched. IMO this is a better approach as it more immediately notifies the document author that an error exists in the document's formatting and the error will be more quickly fixed.

That said, I suspect the real concern in this report is the later section of the document following the table. Python-Markdown is trying (and failing in this case) to emulate a browser's behavior. For example, consider this HTML:

``` html
<p> Some paragraph.

We never close the paragraph.
```

A browser will see that as one paragraph:

``` html
<p> Some paragraph.

We never close the paragraph.<p>
```

Python-Markdown is trying to emulate that behavior and therefore eats the rest of the document - including it as raw HTML. Of course, Python-Markdown also recognizes that a new `<p>` tag closes the previous `<p>` tag - but this is only special-cased in the code for `p` tags. It could arguably apply to tables as well.

In an ideal world, the parser would do the following:

```
Line 1: [start table]
Line 2: [body of table]
Line 3: [end table] [start (self-closing) table] [end (self-closing) table]
```

That said, Python-Markdown's HTML parser is (intentionally) rather nieve and I don't know that it should be intelligent enough to work this out. If not, I'm inclined to leave it as-is. I'll need to think some more about this.

**Comment by benjaoming** [comment]
A suggestion for someone who wishes to alert about incorrect HTML being generated from incorrect input:

```
from markdown import markdown
from markdown.util import etree
markdown_output = markdown(my_input)
try:
    etree.fromstring(markdown_output)
except etree.ParseError:
    print "Incorrect output"
```

This will not detect illegal groupings of tags, ie `<p><table></table></p>`. But if it is desired, one can also extend the built-in library HTMLParser.

I don't think this is a job for the core markdown as there are many levels of validating input, and this seems to be a case in which we should validate raw HTML input, which is just asking for trouble.

**Comment by waylan** [comment]
I agree with @benjaoming. Although html5lib and lxml are better html parsers that etree. But if you really want valid html, etree will strictly enforce that.

I'm closing this as its out of scope for Python-Markdown.
