### ISSUE TITLE
TableExtension support for multiline cells

### ISSUE THREAD

**Issue by timvink** [Python-Markdown/markdown#975]
The [docs](https://python-markdown.github.io/extensions/tables/) state that the TableExtension plugin uses the [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#table) format:

> Tables are defined using the syntax established in PHP Markdown Extra.

According to the docs of `python-tabulate`, that format should offer support for multi-line cells using newline characters ([source](https://github.com/astanin/python-tabulate#multiline-cells)).

`python-markdown` does not support them though:

```python
# Multi-line cells
# example from https://github.com/astanin/python-tabulate#multiline-cells
from tabulate import tabulate
table = [["eggs",451],["more\nspam",42]]
headers = ["item\nname", "qty"]
text = tabulate(table, headers, tablefmt="pipe")
print(text)
```
```nohighlight
| item   |   qty |
| name   |       |
|:-------|------:|
| eggs   |   451 |
| more   |    42 |
| spam   |       |
```
```python
import markdown
from markdown.extensions.tables import TableExtension
tables= TableExtension()
md = markdown.Markdown(extensions=[tables])
print(md.convert(text))
```
```nohighlight
<p>| item   |   qty |
| name   |       |
|:-------|------:|
| eggs   |   451 |
| more   |    42 |
| spam   |       |</p>
```

If I remove the newlines (`\n`), it renders correctly:

```python
table = [["eggs",451],["more spam",42]]
headers = ["item name", "qty"]
text = tabulate(table, headers, tablefmt="pipe")
print(md.convert(text))
```
```nohighlight
<table>
<thead>
<tr>
<th align="left">item name</th>
<th align="right">qty</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">eggs</td>
<td align="right">451</td>
</tr>
<tr>
<td align="left">more spam</td>
<td align="right">42</td>
</tr>
</tbody>
</table>
```

I would expect `TableExtension` to convert `\n` to `<br />`. 

Perhaps I am missing something? If this is a bug / enhancement, I'd be willing to give a PR a try!

**Comment by waylan** [comment]
I'm sorry but Tabulate's documentation is wrong. I just checked multiple implementations and none support multiline cells. If you want a line break, then you need to insert the `<br>` tag yourself.

For reference, I did a analysis of various implementations [here][1] some time ago. Our behavior matches the other implementations, including PHP Markdown Extra (you can try PHP [online][2]. It ignores the first line of your sample table).

Perhaps a more interesting comparison, is [this one][3], which compares the different table syntaxes supported by Pandoc. We only support what they call `pipe_tables`.  However, as I note in my analysis:

> Note that the syntax does not offer any way to define when one row ends and another row begins (unlike the other types of tables). As you cannot define the division between rows, then the only way it can work is if each line is its own row. For that reason, a row cannot contain multiple lines of text.

I couldn't help but notice that tabulate also calls the same style `pipe` tables. Presumably they borrowed the name from Pandoc. Yet, Pandoc's documentation clearly [states][4] (emphasis added):

> The cells of pipe tables cannot contain block elements like paragraphs and lists, and **cannot span multiple lines**.

If you want to have support for a different table syntax, such as one of the other types supported by Pandoc, then that should be implemented as a separate third-party extension. We will not be adding multiline support to the existing extension. 

[1]: https://stackoverflow.com/a/48754707/866026
[2]: https://michelf.ca/projects/php-markdown/dingus/
[3]: https://stackoverflow.com/a/57166923/866026
[4]: https://pandoc.org/MANUAL.html#extension-pipe_tables

**Comment by timvink** [comment]
Thanks @waylan for the detailed analysis and the clarification. Closing this issue.
