### ISSUE TITLE
Support for pygments’ lineanchors option.

### ISSUE THREAD

**Issue by phryk** [Python-Markdown/markdown#980]
pygments’ `linenos='table'` functionality is suboptimal because tables are still horrible to properly style in 2020.

Elements will overflow by default, potentially breaking site layouts.
When trying to limit the width of the code, you either end up
* Hiding part of the code (`overflow-x: hidden`)
* Have a vertical scrollbar *sometimes* (`overflow-x: auto`), breaking vertical alignment to the line numbers
* Have a vertical scrollbar *always* (`overflow-x: scroll`) and can manage with a `padding-bottom` on `td.linenos`, but the scrollbar will be there, even if not needed

Also, when doing something like `whitespace: pre-wrap` on the `<code>` element, vertical alignment breaks completely.

If the generated `<code>` element would have every single line
wrapped in another element, it would be possible to use a CSS
counter to automatically generate line numbers that
* Play nice with wrapped lines in the code.
* Aren't selectable and thus won't show up when copy-pasting code.
* Could also just get an id attribute assigned, thus making lines
`:target`able.

This seems to be more or less exactly what pygments’ [`lineanchors`](https://pygments.org/docs/formatters/) option does.

Now, `lineanchors` isn't just a `bool`, but a `str` which is used as a prefix for anchor targets.
I would propose adding it as boolean option to Python-Markdown and using a SHA2 hash of the code being highlighted for the prefix value.

**Comment by waylan** [comment]
In #816 we are refactoring so that any and all pigments options can be accepted and passed on to Pygments. I expect this will address your needs.

Looking at what you want to accomplish, I believe the `linenos=inline` option is what you want. This was discussed in some detail in #652. The option, like others, will be available to you with the changes in #816.

I'm closing this as a duplicate.

**Comment by phryk** [comment]
Thanks for the information. Nice to see that I'm seemingly so lucky with the timing. :)
