### ISSUE TITLE
Markdown converts embed HTML into non-usable HTML

### ISSUE THREAD

**Issue by Smudger1** [Python-Markdown/markdown#982]
This:
```
<embed type="text/html" src="https://example.com/" width="100%" height="100%">
```
gets converted into this (when rendered on the page):
```
<p> &lt;embed type="text/html" src="https://example.com/" width="100%" height="100%"&gt; </p>
```
making the embed tag unusable. Is there are any way to stop this from happening?

**Comment by waylan** [comment]
I can't seem to replicate this:

```py
>>> markdown.markdown('<embed type="text/html" src="https://example.com/" width="100%" height="100%">')
'<p><embed type="text/html" src="https://example.com/" width="100%" height="100%"></p>'
```

Which version are you using?

**Comment by Smudger1** [comment]
@waylan I'm using version 3.2. 
I'm django for the project and have the following displaying the markdown:
`{{ page.text | escape | markdown | safe }}`
with page.text being the variable holding the text.

**Comment by Smudger1** [comment]
Never

**Comment by waylan** [comment]
@Smudger1 I assume you closed this because you worked out that either the `escape` or `safe` Django filters were the cause of the problem.
