### ISSUE TITLE
Markdown function hangs when deregistering 'paragraph' blockprocessor

### ISSUE THREAD

**Issue by andredelft** [Python-Markdown/markdown#985]
Hi!

I'm writing a markdown extension for which I would like to deregister the default paragraph blockprocessor `ParagraphProcessor`:

```python
class MyExtension(Extension)
    def extendMarkdown(self, md):
        md.parser.blockprocessors.deregister('paragraph', strict = True)
```
But when I use it, e.g.:
```pycon
>>> from markdown import markdown
>>> markdown('test', extensions = [MyExtension()])
```
the function keeps running indefininetly. I'm not sure why this is the case, deregistering other blockpocessors seems to work fine (tried with 'olist' and 'code').

Any idea what's going wrong here?

**Comment by waylan** [comment]
The `paragraph` blockprocessor is the fallback. If nothing else matches, then the 'block' is assumed to be a paragraph. Therefore, it is the only *required* blockprocessor.  At a minimum, you would need to provide your own replacement 'paragraph' blockprocessor.

By removing the `paragraph` blockprocessor you are creating an infinite loop. A simlified explanation is that a while loop is used which tests the length of `blocks`. The loop only ends when `blocks` is length 0. When called, the `paragraph`  blockprocessor always accepts the top block as a paragraph if it hasn't been consumed by another blockprocessor. Therefore, each run though the loop consumes another block until none are left, ending the loop. By removing the `paragraph` blockprocessor, once a block is encountered which is not consumed by any other blockprocessors, the parser would enter into an infinite loop as the length of `blocks` would never be reduced.

**Comment by andredelft** [comment]
Right, that makes a lot of sense. I've been able to solve it by writing an alternative fallback. Thanks for the answer!
