### ISSUE TITLE
Markdown in AWS Lambda

### ISSUE THREAD

**Issue by markotitel** [Python-Markdown/markdown#986]
Hi, just would like to report one issue occured to me.
Last two versions `3.2.2` and `3.2.1` throws error when trying to use module.

```
import markdown

def lambda_handler(event,context):
    markdown.markdown(event['entry']['messagetext'])
```
Error message is `"module 'markdown' has no attribute 'markdown'`

If I use version `3.2` the code works fine.

**Comment by waylan** [comment]
I'm not able to replicate this. Could you provide more details?

**Comment by waylan** [comment]
As this cannot be replicated and insufficient information has been provided to act on, this is being closed.
