### ISSUE TITLE
Prevent converting '\n' between lines into space (for Eastern characters)

### ISSUE THREAD

**Issue by flyaway1217** [Python-Markdown/markdown#992]
The problem is described here:
https://stackoverflow.com/questions/8550112/prevent-browser-converting-n-between-lines-into-space-for-chinese-characters

I can not find a good solution to this problem. Is it possible to create a new extension for solving this problem?

Thanks for the help!

**Comment by facelessuser** [comment]
> The problem is described here

Unfortunately, this is what Markdown should be doing. We can see here that all Markdown parsers do basically the same thing: https://johnmacfarlane.net/babelmark2/?text=%E8%BF%99%E6%98%AF%0A%E4%B8%80%E5%8F%A5%E8%AF%9D%E3%80%82. The one exception is the parser that converts newlines to `<br>` like GitHub used to do.

> I can not find a good solution to this problem. Is it possible to create a new extension for solving this problem?

Probably? I haven't looked into the code to see how plausible it would be. I imagine if you look at the `nl2br` extension (which duplicates the newline to `<br>` logic that GitHub used to use) that you can probably override it to do what you want. With that said, it may mess up parsing of some things that require word boundaries when parsing, but that is something you'd have to debug/workaround.

**Comment by waylan** [comment]
This is clearly an issue for browsers and/or the HTML spec to address. Markdown is simply a subset of HTML.

That said, if you wanted to remove newlines via a Markdown extension, I would suggest a [Treeprocessor][1] which removed the unwanted newlines from the text and tail of each element. If you can effectively identify which newlines need to be removed (not sure how as I don't understand the context of the language), it should be a really simple extension. Actually, if you run right before the `PrettifyTreeprocessor` (at perhaps priority 11) you could perhaps remove all newlines. Then the `PrettifyTreeprocessor` will restore any structural newlines and leave out any within the body of text.

I'm closing this as there is no actionable item here. If you need any help with your extension, feel free to ask on this issue.

[1]: https://python-markdown.github.io/extensions/api/#treeprocessors
