### ISSUE TITLE
Blackline casued wrong rendering display-mod LaTex result.

### ISSUE THREAD

**Issue by minghu6** [Python-Markdown/markdown#993]
Just look at the exp:
```python
import markdown


md_doc = """
$$
A = B + C

$$
"""
print(markdown.markdown(md_doc))
```
Expected output:
```html
<p>$$
A = B + C$$</p>
```

Actual output:
```html
<p>$$
A = B + C</p>
<p>$$</p>
```
Which cause the formula can't be rendered.

**Comment by waylan** [comment]
Markdown has no knowledge of Math. If you would like to give Markdown knowledge of Math syntax so that it ignores it, then you need to use an extension. A few math related extensions are listed in the [wiki](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#math--latex)

**Comment by minghu6** [comment]
@waylan Oh, please wait a minute, 
you mean that the math extension should write another `Treeprocessor` class to check if adjective `<p>` elements contains ```$$``` to solve the question ? Since `inlinePatterns` of `Markdown` can't handle this case.

**Comment by facelessuser** [comment]
@minghu6 the syntax is LaTeX, not Markdown, so Markdown doesn't recognize it. The content inside can conflict with actual Markdown and cause issues, so an extension must be provided to recognize it and preserve it through the Markdown parsing processes. There are several extensions that parse math. I will only speak to mine at this point: https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/. It allows for block `$$` and inline style `$`, but blank lines are not allowed in its block format. Maybe there is another version that allows this 🤷.

With that said, SuperFences allows for custom fence content, and you can configure it to parse Math in a block using fences: https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#alternative-math-blocks

````
```math
3 + 3
```
````

> you mean that the math extension should write another Treeprocessor class to check if adjective <p> elements contains $$ to solve the question ? Since inlinePatterns of Markdown can't handle this case.

Treeprocessors will not handle LaTeX properly, you'd honestly want to capture the content before Treeprocessors get run as the content can be malformed by Treeprocessor time.

---

Anyways, I would try out one of the extensions listed in the wiki and post questions on their repo if you have issues. Here is not really the correct place.

**Comment by minghu6** [comment]
@facelessuser Thank your answer very much! and I'm using your `pymdown-extensions` now !

I don't asked for the `markdown` libarary process the Latex，but hope that either the origin Latex content put in the same one `<p>` (so, I can render it using a `JaveScript` Latex lib) or expose a method for Latex extension to process Latex content. (There is no proper way for extension to deal with it,  I can only find using Treeprocessor to solve it from source code. I afraid that most of LeTax extension just deal with `inlinePatterns`)

**Comment by facelessuser** [comment]
Mine handles block and inline, and I know there are others. It doesn't use treprocessors. Assuming you use the correct mode and configure the JavaScript options correctly, it should work in MathJax or even KaTeX as I've tested it on both.

**Comment by minghu6** [comment]
@facelessuser excuse me, which repo,  `pymdown-extensions` ? I can't find Latex releated doc from it.

**Comment by facelessuser** [comment]
Yes today is the one. I looked to it earlier: Arithmatex.

**Comment by minghu6** [comment]
@facelessuser But the Arithmatex also need no emptyline, for it recieves lines breakon emptyline as input https://github.com/Python-Markdown/markdown/blob/2164c4b4752b9061c742326ea0413719333058fc/markdown/core.py#L263

`A block also must contain no empty lines and should be both preceded and followed by an empty line.` From Arithmatex  doc

And blockprocessor has no much difference bettwen onlineprocessor, since both of them receive `lines` breakon emptyline:
`self.lines = source.split("\n")`

**Comment by facelessuser** [comment]
> @facelessuser But the Arithmatex also need no emptyline, for it recieves lines breakon emptyline as input

Yes, I already stated that and said if you want blank lines, you'd have to use the alternate format which uses a special formatter: facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#alternative-math-blocks.

I use both in my docs and show real working examples. Again, this discussion should happen over at that repo.

**Comment by waylan** [comment]
As @facelessuser stated, please take this discuss to the repo for the extension.
