### ISSUE TITLE
Can't Follow wiki - Tutorial Altering Markdown Rendering

### ISSUE THREAD

**Issue by flywire** [Python-Markdown/markdown#996]
It's hard to find a relevant tutorial for markdown extensions so this one is a really important. Unfortunately it seems to be written upside down.

I'd expect to be able to execute the code as it is written and this doesn't seem possible starting with `def run(self, root):` which requires an ElementTree object. I understand a  registered Treeprocessor is at least required before that object is accessible.

```
>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>>
>>> input = """
... ![a local image](/path/to/image.jpg "A title.")
...
... ![a remote image](http://example.com/image.jpg  "A title.")
... """
>>>
>>> html = markdown.markdown(input, extensions=[ImageExtension()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ImageExtension' is not defined
>>>
```

```
>>> html = markdown.markdown(input, extensions=[ImageExtension.py:ImageExtension()])
  File "<stdin>", line 1
    html = markdown.markdown(input, extensions=[ImageExtension.py:ImageExtension()])
                                                                 ^
SyntaxError: invalid syntax
```

**Comment by flywire** [comment]
To be clear, I'm suggesting a more realistic development process would be using "Hello World" in the run method until the extension has been run once, then add the run method code.

**Comment by facelessuser** [comment]
The wiki is actually written by the community. You are free to update it if you feel it needs help. To be honest the first example is pretty basic. "Hello World" I don't think is as helpful, but I'm sure that is subjective. The problem with the wiki tutorial seems to be that it leaves out that the example is incomplete. The extension needs a `makeExtensions` function to return the extension.

```py
def makeExtension(*args, **kwargs):
    """Return extension."""

    return MyExtension(*args, **kwargs)
```

So the extension examples should all have *that* at the bottom:

```py
from markdown.extensions import Extension

class MyExtension(Extension):
   def extendMarkdown(self, md):
       # Insert code here to change markdown's behavior.
       pass


def makeExtension(*args, **kwargs):
    """Return extension."""

    return MyExtension(*args, **kwargs)
```

etc.

**Comment by facelessuser** [comment]
Our docs do mention `makeExtension`, but I'm sure they could be improved as well as it is not immediately clear until you get quite a ways into the documentation of the API.

I think this is the only place we actually mention it: https://python-markdown.github.io/extensions/api/#dot_notation.

**Comment by flywire** [comment]
I'm happy to edit the tute. Is the following notation correct for Win10?
~~~
>>> html = markdown.markdown(input, extensions=[ImageExtension.py:ImageExtension()])
~~~

**Comment by facelessuser** [comment]
> `>>> html = markdown.markdown(input, extensions=[ImageExtension.py:ImageExtension()])`

No, this is probably not right. I've honestly never used the colon extension format before. That must be new. I guess maybe that makes it so you don't need `makeExtension`?  Maybe I'm not fully up to date on everything...I should look into adopting that moving forward in my extensions...

Anyways, that format is only if you are pointing to the extension via a string I guess. In that case, you'd need to specify it in a string, not mention the `.py` extension as you are supposed to use the same dot notation you would to import a module, and not call the function because you are in a string.

So, if I had to guess, I'd say you use:

```
>>> html = markdown.markdown(input, extensions=["ImageExtension:ImageExtension"])
```

This is assuming `ImageExtension` is found locally.

**Comment by facelessuser** [comment]
I would always include `makeExtension` anyways as users often may use the old way (like me) which does not use the colon:

```
>>> html = markdown.markdown(input, extensions=["ImageExtension"])
```

**Comment by waylan** [comment]
> ```python
> >>> html = markdown.markdown(input, extensions=[ImageExtension.py:ImageExtension()])
>   File "<stdin>", line 1
>     html = markdown.markdown(input, extensions=[ImageExtension.py:ImageExtension()])
>                                                                  ^
> SyntaxError: invalid syntax
> ```


You have multiple problems here. The colon syntax only works for strings and is should be the import path. Python Import paths do not include the file extension. Finally, when using the string, there would be no `()`. So, assuming the file `ImageExtension.py` is on your PYTHONPATH, then it would be the string (notice the quotes) `'ImageExtension:ImageExtension'`.

However, if you want to use the actual Python object, well then you need to import the object in your code:

```python
from ImageExtension import ImageExtension

html = markdown.markdown(input, extensions=[ImageExtension()])
```

Either way, this is all basic Python stuff. Nothing unique to the Markdown library here. The tutorial is not meant to teach Python, but assumes a basic understanding of Python.

@facelessuser, yes the colon is a newer addition. It is a basic Python convention, albeit not very commonly used. Personally, if I could go back in time, we would have never had the `makeExtension` function, but used the this instead. The documentation discourages using strings altogether (import objects instead), but if you are using strings, the preferred method is entry_point names, then strings which point to the class (with a colon) and last is a string which points to a module with a `makeExtension` function.

**Comment by flywire** [comment]
Thank you for your help. Would you mind tweaking the tutorial so it runs because this seems like a minor change and I don't understand the semantics?

I have limited python experience so I'm trying to follow the tutorial. I don't expect it to teach me python but I hope it will work if I follow it.

Maybe I've misunderstood the process. The tutorial seems to offer a process for developing the extension without a `pip install extension` at every change. (I have a fork of an extension that I run in Mkdocs which has the same base code as this tutorial but this tutorial explains the code in detail. I only want to examine the ElementTree by printing to console during development.)

>So, assuming the file ImageExtension.py is on your PYTHONPATH

I assume not required if Python is run from folder code is in.

As it stands:

---
```

D:\source\repos\tutorial>type ImageExtension.py
from markdown.treeprocessors import Treeprocessor       # let's create a new Treeprocessor
from markdown.extensions import Extension               # inform Markdown of our new Treeprocessor


    def run(self, root):
        for element in root.iter('img'):                # Iterate over img elements only
            attrib = element.attrib                     # copy the element's attributes for later use
            if self.is_unknown_host(attrib['src']):     # Check for links to external images
                tail = element.tail                     # Save the tail
                element.clear()                         # Reset the element
                element.tag = 'a'                       # Change the element to a link
                element.set('href', attrib.pop('src'))  # Copy src to href
                element.text = attrib.pop('alt')        # Copy alt to label
                element.tail = tail                     # Reassign tail
                for k, v in attrib.items():             # Copy all remaining attributes to element
                    element.set(k, v)


class ImageExtension(Extension):
    def extendMarkdown(self, md):
        # Register the new treeprocessor
        md.treeprocessors.register(InlineImageProcessor(md, hosts=self.getConfig('hosts')), 'inlineimageprocessor', 15)


def makeExtension(*args, **kwargs):
    return ImageExtension(*args, **kwargs)


D:\source\repos\tutorial>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>>
>>> input = """
... ![a local image](/path/to/image.jpg "A title.")
...
... ![a remote image](http://example.com/image.jpg  "A title.")
... """
>>>
>>> from ImageExtension import ImageExtension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\source\repos\tutorial\ImageExtension.py", line 5
    def run(self, root):
    ^
IndentationError: unexpected indent
>>>
>>> html = markdown.markdown(input, extensions=[ImageExtension()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ImageExtension' is not defined
>>>
```

**Comment by waylan** [comment]
The line `from ImageExtension import ImageExtension` does not go in the file where `ImageExtension` is defined, but it goes where you use the object. In fact, I clearly demonstrated that in my comment above. I don't know that there are any changes we can make to help you with that. These are the sorts of things we assume you already know. I would suggest finding a few beginner Python tutorials and learn these basics first.

**Comment by flywire** [comment]
Tutorial updated. Everythng explained in detail at: https://python-markdown.github.io/

**Comment by flywire** [comment]
Can the [Tree processor](https://python-markdown.github.io/extensions/api/#working_with_et) `__init__` be clarified?

[Configuration Settings](https://python-markdown.github.io/extensions/api/#configsettings) uses `**kwargs`, and `getConfigs()` returns a dict of all key/value pairs. 

I'm not clear why the arguments are explicitly passed to the tree processor which inherits from `markdown.treeprocessors.Treeprocessor` rather than using something like `*args, **kwargs` to pass the `config` list or dictionary without explicitly listing every item? (btw, I can't see how to access config from within the class which inherits from `markdown.treeprocessors.Treeprocessor` shown below.)

The tutorial uses:

```python
class InlineImageProcessor(Treeprocessor):
    def __init__(self, md, hosts):
        self.md = md
        self.hosts = hosts
```
Apologies to @facelessuser if it is implied in the previous response which I note was different to the docs.

**Comment by flywire** [comment]
https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/toc.py#L146-L151 has:
```python
class TocTreeprocessor(Treeprocessor):
    def __init__(self, md, config):
        super().__init__(md)

        self.marker = config["marker"]
        self.title = config["title"]
...
```

How can `**kwargs` (dict of all key/value pairs) be accessed in https://github.com/Python-Markdown/markdown/wiki/Tutorial-2---Altering-Markdown-Rendering#test-2?
```python
class InlineImageProcessor(Treeprocessor):
    def __init__(self, md, config):
        super().__init__(md)
        self.hosts = config["hosts"]
...
```
