### ISSUE TITLE
Option to only do TOC processing if the marker is found

### ISSUE THREAD

**Issue by daturkel** [Python-Markdown/markdown#997]
I love the table of contents extension. My one issue is that, on pages where all I've got is, say, an H2 tag, I don't want to enable behavior like turning all headers into anchor links.

Ideally, there would be an option along the lines of `marked_only: bool = False`. If `marked_only` is `False`, we get the current behavior: all TOC options run on every page, regardless of whether or not the `[TOC]` marker is found.

If `marked_only` is `True`, the TOC options would _only_ run on pages where the `[TOC]` marker is found. That way thinks like permalinks/anchor tags wouldn't be generated on that page.

Is this something doable? I'd be happy to try to contribute if you could point me in the right direction.

**Comment by waylan** [comment]
I see not point or value in this. In fact, a very common use case is to use the extension without the marker. And if an ID is added to a few headers that don't need them, what harm is there?

**Comment by daturkel** [comment]
I should clarify that in my use case, I've got `anchorlink = True`, so it's not just a matter of adding `id`s on the headers (which I agree is harmless) but whether or not they're links (and all the styling that comes with that).

**Comment by waylan** [comment]
Personally, I would think that one would want consistent styling across an entire website. If, on the other hand, you are rendering an individual page, then you can pass options appropriate for that page.

**Comment by daturkel** [comment]
That's fair. If I'm trying to reuse a single `Markdown` instance, can I change still change extension settings post-initialization? Or do I need to build a new `Markdown` instance each time?

**Comment by waylan** [comment]
You would need a new instance.

**Comment by daturkel** [comment]
Ok thanks. Closing the issue.
