### ISSUE TITLE
Importing docstrings

### ISSUE THREAD

**Issue by matthewatabet** [Python-Markdown/markdown#999]
Hi there!

I'm considering using `Python-Markdown` as an alternative to `Sphinx` to reduce the complexity of my documentation process.

But, to do this, I need to be able to import docstrings. Is there a way to do this in `Pyhton-Markdown`? I Googled around a bit but didn't find anything. I thought I'd check here before writing my own extension.

Thanks!

**Comment by mitya57** [comment]
Python-Markdown is just a Markdown parser, importing docstrings is out of scope for this project.

However, there are third-party projects that use Python-Markdown and allow you to import docstrings. I just searched and found these two plugins for [MkDocs] (which is using Python-Markdown):

- https://github.com/pawamoy/mkdocstrings
- https://github.com/NiklasRosenstein/pydoc-markdown

In theory it is possible to write an extension that will do this in pure Python-Markdown, without MkDocs. But I am not aware of any such extensions. If you find one or write it yourself, please add it to the [wiki]. See also the [tutorial] how to write extensions for Python-Markdown.

In any case, I am closing this as out of scope.

[MkDocs]: https://www.mkdocs.org/
[wiki]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
[tutorial]: https://github.com/Python-Markdown/markdown/wiki/Tutorial-1---Writing-Extensions-for-Python-Markdown

**Comment by matthewatabet** [comment]
@mitya57 Great, thanks for the advice! Much appreciated.

**Comment by waylan** [comment]
There is a [longer list][1] of MkDocs plugins on the MKDocs wiki. However, of note is [mkautodoc][2] which uses a Markdown extension. It also happens to provide some additional MkDocs specific stuff as a MkDocs plugin, but if you are looking for a Markdown extension, that is where I would start. It is possible other of the MkDoc plugins also use a Markdown extension, but I know not all do and I have't looked at all of them too closely.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building
[2]: https://github.com/tomchristie/mkautodoc
